### PR TITLE
Issue/4661 disconnect button does not work

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Parent issue: #4661 (Disconnect button doesn't work from the first time #4718)

### Description
Clicking on the Disconnect button was broken in the `Card reader detail screen`. This PR fixes that.

### Why was it broken?
```   
cardReaderManager.readerStatus.collect { status ->
                when (status) {
                    is Connected -> cardReaderManager.softwareUpdateAvailability.collect(
                        ::handleSoftwareUpdateAvailability
                    )
               }
}
```

In the above code snippet, There are 2 `collect` functions. We know that `collect` is a suspended function. Here is what is happening in the above code.

We start the first suspend `collect` function as soon as the `CardReaderDetailViewModel` starts. Since it is a suspend function, it starts and suspends until the flow terminates. Here's the catch, `readerStatus` is a `StateFlow` and since `StateFlow` is a hot flow. It never terminates. As a result, the second `Collect` suspend function never executes.

Here are the steps to understand it better

1. Go into the `CardDetailFragment` screen --- (First `collect` starts)`readerStatus` will be `Not Connected`
2. You will see `Not connected` state initially
3. Connect to the reader successfully --- `readerStatus` will be `Connected` (We start our second `Collect` suspend function at this point)
4. Now, you will see the option to Disconnect the reader
5. Click on the `Disconnect reader` button. 
6. Nothing happens 💥 

This is because as I said earlier, our first `collect` suspend function has not terminated yet. `readerStatus` is `StateFlow` and since `StateFlow` is a hot flow, it never terminates. As a result, the second `collect` never executes, and hence the `Not Connected` state which gets fired by clicking the Disconnect button has no effect and nothing happens.

### What is the Fix?
Launching the second `collect` suspend function in a separate `Coroutine` fixes this.

### Testing instructions
1. Go into the `CardDetailFragment` screen
2. Click on `Connect card reader`
3. Once connection happens successfully, you should see the option to Disconnect the reader
4. Tap on the `Disconnect reader` button and see that the disconnection actually happens and you get redirected to the `Not Connected` state.

### Images/gif

https://user-images.githubusercontent.com/1331230/131961920-52ec5a79-4064-4802-be70-8a936afe1d54.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by malinajirka** [comment]
Non-blocking comment, feel free to continue with review of this PR @kidinov  - I just wanted to share my observations.

@AnirudhBhat I think you are on the right path but I'm not sure if the explanation is 100% precise. Let me share my thoughts.

The fact that `readerStatus is a StateFlow and since StateFlow is a hot flow. It never terminates.` is imho not related to this issue. However, what is related is that `cardReaderManager.softwareUpdateAvailability is a StateFlow and since StateFlow is a hot flow it never terminates`.



_1. Go into the CardDetailFragment screen --- (First collect starts)readerStatus will be Not Connected
2. You will see Not connected state initially
3. Connect to the reader successfully --- readerStatus will be Connected (We start our second Collect suspend function at this point) **------>>> This is the issue imho, we suspend the coroutine which is collecting "readerStatus" events and never release it**
4. Now, you will see the option to Disconnect the reader
5. Click on the Disconnect reader button.
6. Nothing happens 💥 **-------> Because the coroutine which is collecting the "readerStatus" events is still suspended from step 3, so it can't process the new event**_



The solution you provided will work fine. However, I'm not sure if we ever cancel the coroutine started here `is Connected -> launch { ... }`. I mean we cancel it when we leave the VM, but if you keep connecting/disconnecting, I think we'll be subscribed multiple times (in other words we'll start a new coroutine on each "onConnected" but we don't cancel the previously started coroutine which is doing exactly the same job - `::handleSoftwareUpdateAvailability`) , wdyt? (tbh I'm not sure it's worth fixing - but better to discuss it and make a decision).

**Comment by AnirudhBhat** [comment]
@malinajirka You are absolutely correct! That's what I meant to write but somehow in the process of writing a tale about two suspend functions, I think my mind ran into some synchronization issue ;) Thanks for correcting it 🙇 And yeah, I believe coroutine is not getting canceled started here is `Connected -> launch { ... }`. I was thinking to cancel this coroutine every time we move to Disconnected state. WDYT?

**Comment by malinajirka** [comment]
>  I think my mind ran into some synchronization issue ;) 

:D yeah, this issue was quite tricky to explain.

> I was thinking to cancel this coroutine every time we move to Disconnected state. WDYT?

That sounds good to me ;).

Really great job on investigating this issue 👏

**Review by kidinov — COMMENTED** [review]
Great job, thanks! 

Looking into that, I started to think that we might not need any flows here at all. What we need is just to know what is the current state of the optional firmware update. This state can be changed only in 2 circumstances:
* After connection to a reader
* After the optional update has happened

Having said that I think we might just have a simple property 

```
var updateAvailabilityEvents: SoftwareUpdateAvailability = SoftwareUpdateAvailability.NotAvailable
``` 

inside `BluetoothReaderListenerImpl` 

Then inside  `CardReaderDetailViewModel` it can be

```
    init {
        launch {
            cardReaderManager.readerStatus.collect { status ->
                when (status) {
                    is Connected -> handleSoftwareUpdateAvailability(cardReaderManager.softwareUpdateAvailability)
                    else -> showNotConnectedState()
                }
            }.exhaustive
        }
    }
```

@malinajirka @AnirudhBhat wdyt?

**Comment by AnirudhBhat** [comment]
@kidinov My only concern here is that if we go by this approach, `SoftwareUpdateAvailability` becomes screen-specific. What I mean is that in this example `CardReaderDetailViewModel` knows what is the status of the latest software update is. But, If some other screen wants to know the software availability status, then it always returns `Not available`. Though, right now we might not have this requirement to know software update availability on different screens. I am not sure this will be the case in the future as well. WDYT?

**Comment by kidinov** [comment]
@AnirudhBhat 

Not sure that I got you. The only change I proposed is to change the type of

```
val softwareUpdateAvailability: Flow<SoftwareUpdateAvailability>
```

to 

```
val softwareUpdateAvailability: SoftwareUpdateAvailability
```
inside: `CardReaderManager`

Because we don't actually need to subscribe to changes of SoftwareUpdateAvailability, we just need the current state - if it's available or not.

But maybe I'm missing something though, especially I didn't get why this might happen:

```
But, If some other screen wants to know the software availability status, then it always returns Not available. 
```
?

**Comment by AnirudhBhat** [comment]
@kidinov 
Thanks for the clarification! Here is what I was saying. Now that we are not subscribing to the software update availability. I assume that `_updateAvailabilityEvents` will become a regular variable instead of `StateFlow` in `BluetoothListenerImpl`. I was thinking if we want to show the software availability status on some other screen (in the future?). Then, this would become a problem? Going by the approach wherein we make `_updateAvailabilityEvents` a regular variable. Here are the steps to visualize the problem. 

1. User connected to the reader. (reader status will be `Not Available`)
2. There is an update available. The user decided to update the reader.
3. Update finishes successfully.  We locally change the update status from `Not Available` to `Available` in `CardReaderDetailViewModel` screen by using the below logic
```
is Connected -> handleSoftwareUpdateAvailability(cardReaderManager.softwareUpdateAvailability)
```
4. `BluetoothListenerImpl` never knows about this change. 
5. Now, let's assume in the future. If we want to show the `Software update availability` status banner on another screen as well (like in the settings screen as per this vaw3DvewbUwuQnPXpdNGGH-fi-2030%3A165540). I believe this will become a problem since the latest `Software update availability` state as per `BluetoothListenerImpl` is `Not Available`.

Does this make sense or am I missing something here?

**Comment by AnirudhBhat** [comment]
@kidinov Thanks for the clarification!
I just tested the approach and it seems like once the card reader gets connected successfully, status changes into a `connected` state before the SDK triggers `onReportAvailableUpdate` callback. Hence, by the time readerStatus is `connected` and when it tries to query the `software update availability` status from `CardReaderManager`. It will still be `Not available`. WDYT?

```
launch {
            cardReaderManager.readerStatus.collect { status ->
                when (status) {
                    is Connected -> handleSoftwareUpdateAvailability(cardReaderManager.softwareUpdateAvailability)
                    else -> showNotConnectedState()
                }
            }.exhaustive
        }
```

**Comment by kidinov** [comment]
@AnirudhBhat  then my idea doesn't make sense =). Good job!

**Pull request merged**
