### PR TITLE
Hackweek project - Optional leakcanary installation

### PR DESCRIPTION
**Pull request by kidinov**
### Description

The PR does 2 things:
* Makes it possible to remove from installation leakcanary which should improve development speed a bit in cases when it's not needed
* Removes:
```
        // TODO remove this after we update AGP, it's a bug that has been fixed in 4.1.1 and later
        // see: https://issuetracker.google.com/issues/168794947
        disable "ParcelCreator"
```

It seems to be have been fixed

### Testing instructions

Set in the `gradle.properties`:
* `enableLeakCanary = true` or nothing (should behave the same way. Leakcaray is ON)
* `enableLeakCanary = false` (disables leak canary and does not install it)
(passing `-PenableLeakCanary=false/true` to gradle in command line should behave the same way)

Notice that when `enableLeakCanary = false` then the library is not installed at all 
When it's `true` or you use default then it is installed and it collects leaks

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hichamboushaba** [comment]
Thanks @kidinov for working on this, this would be a nice improvement for when trying to record demos too 👍.

Just a question before approving the PR, wouldn't it be simpler to pass the new gradle property as a `buildConfig` one, then just do a small update to our custom `LeakCanaryInstaller` to make sure it's not installed when it's false? I mean something like this:
```kotlin
 if (BuildConfig.ENABLE_LEAK_CANARY && !PackageUtils.isTesting()) {
            WooLog.v(WooLog.T.DEVICE, "Installing LeakCanary")
            val application = context!!.applicationContext as Application
            AppWatcher.manualInstall(application)
        }
```
To reword the question a bit, is excluding the leakCanary binaries in debug builds beneficial for this case? Because this would be the only difference.
Let me know what you think 🙂.

**Comment by kidinov** [comment]
@hichamboushaba thank you for taking a look

> To reword the question a bit, is excluding the leakCanary binaries in debug builds beneficial for this case? Because this would be the only difference.

I have considered this approach, but after checking that leak canary brings some dependencies, decided that it is worth excluding for sake of packaging and installation speed. For instance, the `core` lib is 600kb

image

**Comment by hichamboushaba** [comment]
> I have considered this approach, but after checking that leak canary brings some dependencies, decided that it is worth excluding for sake of packaging and installation speed. For instance, the core lib is 600kb

Since this impacting only debug builds, is it worth optimizing considering the complexity it brings to the solution? IMHO the APK size is not something worth considering for debug builds, especially for a small size like 600kb 🙂.

**Comment by kidinov** [comment]
@hichamboushaba 

> especially for a small size like 600kb

I mentioned one of the AAR files. I briefly checked the others and in total it is more than 1MB.

> APK size is not something worth considering for debug builds

I don't agree here. 
* Resolving extra dependencies
* Time to pack bigger apk
* Upload a bigger APK to a device
* Unpack bigger apk

And all of this dozens/hundreds of times per day per every dev. Even if it takes one extra second, to me it sounds like it is totally worth the extra 4-5 lines of the code to avoid that

**Comment by hichamboushaba** [comment]
Thanks for keeping up with me on this discussion.

Just to understand the goal of the PR here, is the goal to allow devs to keep LeakCanary disabled for long time? don't you think this would lead to ignoring leaks more often? 

I was under the impression this PR's goal is to disable LeakCanary only in some exceptional cases, and there those optimizations (even though I still think they are very minimal and won't have any noticeable impact 🙂) won't be a significant factor.

**Comment by kidinov** [comment]
@hichamboushaba 

The goal is to give the opportunity to disable it. During developing a feature you don't have to focus on the leaks during every run, but during the final testing, people must have this enabled. I was planning to emphasize this in the P2 that introduces this option

**Review by hichamboushaba — APPROVED** [review]
Looks good.

For the record, I still think the solution could be a lot simpler with a simple BuildConfig variable, but let's agree to disagree 🙂, and it's not a blocker point.
I also worry that this may lead to ignoring leaks more often, since catching them is done basically when working on features, but this may be a subjective point.

**Pull request merged**
