### PR TITLE
GitIgnore some IDEA files

### PR DESCRIPTION
**Pull request by kidinov**
We don't have some idea files related to the code formatting so it makes sense to gitignore them. 

Also, I added `vcs.xml` file to be ignored:

https://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project/18454251#18454251

When I use "local builds" IDEA modifies `vcs.xml`. If we need this file under git, please let me know

### CODE REVIEW

**Comment by hichamboushaba** [comment]
pinging @woocommerce/platform-9 for their opinion too.

**Comment by oguzkocer** [comment]
This comes up infrequently in different projects, for example we have removed `.idea/compiler.xml` in https://github.com/woocommerce/woocommerce-android/pull/3452. I think the best course of action (and my suggestion) for this would be to open up a p2 discussion and decide on a common set of rules across projects so we can fix it once and for all.

I'd personally ignore as much as possible from the IDE because I don't think there is a reason to force anyone to work in a certain way or with certain settings. The only case I can think of where it'd make sense to check in these types of files is if it'll help developers avoid unnecessary configuration.

Having said that, I don't actively work on the Android projects and I don't use Android Studio, so it's difficult for me to say which file would fit that bill. I hope by opening up a p2 discussion we can collectively figure that out.

**Comment by hichamboushaba** [comment]
The files that were removed during the `detekt` migration are `Project.xml` and `codeStyleConfig.xml` (https://github.com/woocommerce/woocommerce-android/pull/4228), I think the initial goal of this PR is to ignore them, and unless I'm missing something, they are not there 🙂.

**Review by hichamboushaba — APPROVED** [review]
LGTM, but I prefer to wait for someone else to review it too.
cc @woocommerce/android-developers

**Comment by hichamboushaba** [comment]
Thanks @oguzkocer for the insight, just to give more context, the motive behind this PR is ignoring the files that were removed after the migration to `detekt` https://github.com/woocommerce/woocommerce-android/pull/4152

**Comment by oguzkocer** [comment]
Thanks @hichamboushaba - I think the changeset includes a lot more than that motive, so we have to take that into account while reviewing the PR. Even still, if WCAndroid developers are onboard with this I don't see any reason not to merge this in. It's also something we can revert very easily and since it shouldn't break anyone's flow, your review should be enough in my opinion.

From `#platform9` perspective, the most important thing with `.gitignore` changes is that we don't accidentally expose any secrets. The only related change I see in this PR is `sentry.properties` and that seems to just move to another line, so we should be all good 👍

**Comment by hichamboushaba** [comment]
You are right @oguzkocer, I missed some changes 🤦, thanks for the heads up, I was under the impression it's just `/.idea/vcs.xml` and `/.idea/codeStyles/`.
@kidinov can you please revert the changes to other files and limit it to these two, or start a P2 discussion before we move forward.

> The only related change I see in this PR is sentry.properties and that seems to just move to another line, so we should be all good

I think it was just moved inside the same file.

**Review by hichamboushaba — CHANGES_REQUESTED** [review]
This is just to delete my approval 🙂, see https://github.com/woocommerce/woocommerce-android/pull/4228#issuecomment-864176245 for context.

**Comment by kidinov** [comment]
@oguzkocer 

> The only related change I see in this PR is sentry.properties and that seems to just move to another line, so we should be all good 👍

It was a duplicate of the same. One was just removed


@hichamboushaba 
> You are right @oguzkocer, I missed some changes 🤦, thanks for the heads up, I was under the impression it's just /.idea/vcs.xml and /.idea/codeStyles/.
@kidinov can you please revert the changes to other files and limit it to these two, or start a P2 discussion before we move forward.

> /.idea/externalDependencies.xml

We don't have this file anymore and it's used to enforce checkstyle plugin installation

> /.idea/checkstyle-idea.xml

We don't have to enforce checkstyle plugin anymore so keep it in the git doesn't really make sense

> /.idea/codeStyleSettings.xml

It's an old way how idea was storing code style settings. Not in use since 2017. I deleted the file - https://github.com/woocommerce/woocommerce-android/pull/4228/commits/e7683a862fd22d765aba26ce0f5c2fbfc9b42f44
```
Intellij IDEA 2017.3 has got new project code style settings format. Now all code style settings are located under <PROJECT_ROOT>/.idea/codeStyles
```

**Comment by hichamboushaba** [comment]
Thanks for the clarifications @kidinov.
But still I think with the changes, our .gitignore is a bit aggressive, I don't know if we should ignore the whole `codeStyles` directory or not.
By googling a bit, I see that adding `.idea/codeStyles/codeStyleConfig.xml` to the repo is quite common, I know I'm the one who suggested ignoring it, but it was based on the fact that it was removed already 🙂.

I saw the recent PR about re-adding some `editorConfig` changes #4229, and I think we are drifting from the original goal which was to keep everything similar to the default kotlin style conventions. I think we should keep `.idea/codeStyles/codeStyleConfig.xml`, and use it to share code formatting matching the default kotlin codestyle, without any `editorConfig` configuration, and ignore only `.idea/codeStyles/Project.xml` as it was giving us issues recently.

If we decide to ignore `codeStyleConfig.xml`, then we should document how code formatting should be done automatically, either using the `detekt` plugin as discussed before, or some other way. If we keep it to each developer to do it their way, we will have a lot of inconsistencies, as `detekt` doesn't enforce some formatting rules by default, for example the [indentation](https://detekt.github.io/detekt/formatting.html#indentation).

I think the whole team has to discuss which is the better approach 🙂, WDYT about moving the discussion to P2 or Slack?

**Comment by kidinov** [comment]
> I saw the recent PR about re-adding some editorConfig changes #4229, and I think we are drifting from the original goal which was to keep everything similar to the default kotlin style conventions

It's not exactly that, because from my knowledge lines length is not specified in kotlin code convention, but detekt by default has 120, so we just set it to match. Not sure about intent size though.

 >  I think we should keep .idea/codeStyles/codeStyleConfig.xml, and use it to share code formatting matching the default kotlin codestyle, 

Is this possible? I see that it just contains `<option name="USE_PER_PROJECT_SETTINGS" value="true" />` which means use project-specific config from `project.xml` file.

> If we decide to ignore codeStyleConfig.xml, then we should document how code formatting should be done automatically, either using the detekt plugin as discussed before, or some other way. If we keep it to each developer to do it their way, we will have a lot of inconsistencies, as detekt doesn't enforce some formatting rules by default, for example the indentation.

I would just turn on indentation check in detekt then. In readme we have how to setup detekt plugin for those who want it.

> I think the whole team has to discuss which is the better approach 🙂, WDYT about moving the discussion to P2 or Slack?

I totally don't mind if you restart this discussion again

**Comment by hichamboushaba** [comment]
> It's not exactly that, because from my knowledge lines length is not specified in kotlin code convention, but detekt by default has 120, so we just set it to match. Not sure about intent size though.

Still, I think having two sources of truth here is not optimal, personally, I would remove those, and keep the `codeStyles` files from the IDE, but it's not a blocker.
The indent size is 4 spaces in kotlin conventions, so it matches what we had in `editorConfig` as well.

> Is this possible? I see that it just contains <option name="USE_PER_PROJECT_SETTINGS" value="true" /> which means use project-specific config from project.xml file.

Sorry I didn't check this, in this case, if we want to follow what I suggested, we'd have to keep both files.

> I would just turn on indentation check in detekt then. In readme we have how to setup detekt plugin for those who want it.

We should turn it on, but I think it should be done in a separate PR, because I think it'll raise many issues in the repo.

**Review by hichamboushaba — APPROVED** [review]
LGTM after @kidinov's clarifications, if there is any concern in the future, we can always revert the changes 🙂

**Comment by kidinov** [comment]
> Still, I think having two sources of truth here is not optimal, personally, I would remove those, and keep the codeStyles files from the IDE, but it's not a blocker.

I see it in opposite way. Detekt uses ktlint, and ktlint uses `.editorconfig` to take configuration from. Idea uses `.editorconfig` as well, so it is the single source of truth. Idea config files are not used by detekt/ktlint so it's another (second) source of truth.

> We should turn it on, but I think it should be done in a separate PR, because I think it'll raise many issues in the repo.

Agree. Mind to put into in p2 posts with our ongoing detekt configuration talks? I hope to collect feedback from there and make a PR this week

**Comment by hichamboushaba** [comment]
> ktlint uses .editorconfig to take configuration from

Nice, I didn't know this, TIL

> Mind to put into in p2 posts with our ongoing detekt configuration talks? 

I'll add it 👍

**Pull request merged**
