### PR TITLE
Issue/5387 Remove order identifier

### PR DESCRIPTION
**Pull request by kidinov**
@wzieba To keep PR smaller I split the change in several of them

Part of: #5387 

Merge after https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2225 is merged and fluxc hash is adjusted ✅

### Description

This PR is part in a chain of PRs which removed order identifier from the app

### Testing instructions

* Use included build with [the fluxc branch](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2225)
* Try to collect payment
* Try to edit shipping labels

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by kidinov** [comment]
@wzieba @malinajirka Please correct me if I'm addressing my questions to the wrong people. 

I'm working on the change and because I'm not entirely sure that I truly understand some things regarding the task I decided to quickly align with you 

I was reading [some discussions](p91TBi-6dF-p2) regarding the decision-making process but still have some questions:

* The accepted answer states: `use tuple of (remote order id x local site id) to identify orders.`. Does it mean that we just want to pass 2 parameters or do we really want to use a tuple or even a string as it used to be with `OrderIdentifier`?
* What's the point of using `LocalOrRemoteId`? This is not parcelable or serializable so we can not pass them between screens. Passing long/int and then cover it again in the wrapper lossing compile time check doesn't make much sense to me. Also, why is this a sealed class if we as I can see never use `when` on it?

If the idea is to make a compile-time check that we don't pass `remoteId` into `localId` method may be better to use value classes?
* What I've done so far for the payments (check the PR) is this what we expect?

**Comment by wzieba** [comment]
👋 Thanks for those questions, it's good indeed to sync with small piece before all changes.

> The accepted answer states: `use tuple of (remote order id x local site id) to identify orders.` . Does it mean that we just want to pass 2 parameters or do we really want to use a tuple or even a string as it used to be with OrderIdentifier?

It was more about logical database model. How we'll consume that in Woo, it depends only on us. What you did in this PR looks good to me.

> What's the point of using `LocalOrRemoteId`? This is not parcelable or serializable so we can not pass them between screens. Passing long/int and then cover it again in the wrapper lossing compile time check doesn't make much sense to me. 

I think that making `LocalOrRemoteId` not parcelable or serializable is a very good decision. This is domain class representing id - adding platform-specific details for such would break seperation of concerns and generally layering. If we need to move it around between fragments, I believe wrapping/unwrapping it in primitives is a little cost. But if we could avoid that (I think it's possible with mentioned by you `value classes`, as they're inlined into primitives in compile-time right?) it would be even better.

> Also, why is this a sealed class if we as I can see never use when on it?

I believe it's `sealed` to make sure that no more types are added by consumers of the FluxC.

> If the idea is to make a compile-time check that we don't pass remoteId into localId method may be better to use value classes?

Yes, that'd be another good idea but it's already a huge effort to scope in Order->Room migration. It'd also require changes in almost every aspect of the apps - both Woo and WordPress.

Also, if we'll now use `LocalOrRemoteId`, we can change it later to value class easier than from primitive types.

I'd also be against introducing `value class` next to `LocalOrRemoteId` without having a strong commitment and time to do whole migration everywhere. Ambiguity in those types would make more problems than benefits I think.

> What I've done so far for the payments (check the PR) is this what we expect?

Yes, I think that looks good.

My only little concern is method naming: `fetchOrderByRemoteId` has a signature that accepts only `RemoteId` as argument so adding `ByRemoteId` feels redundant to me. But that's a minor one.

WDYT about all of this @kidinov ?

**Comment by kidinov** [comment]
@wzieba Thank you for helping me here!

It's way more clear now!

What I still don't understand though is `LocalOrRemoteId` in general. It looks like an attempt to bring something similar to kotlin's result but not for results and it doesn't really work from what I see, because we don't use the type hierarchy is actually "sealed" and known during compilation time 

More what I still don't follow is the reason why we brought the usage of `LocalOrRemoteId` on the Woo side. E.g. in `Order` 

```
    val localId
        get() = LocalOrRemoteId.LocalId(this.rawLocalOrderId)

    val remoteId
        get() = LocalOrRemoteId.RemoteId(this.rawRemoteOrderId)
```

Aside from that, we create a new instance every time we access the property, I am still not following what is the goal to expose this here instead of just a `Long` (or value class to have compile-time check). In many places, we still have to extract `value` (long) from this anyway, because as I mentioned above we can not pass it between activities/fragments, and probably in many places we expect long, not `LocalId` or `RemoteId` at the moment. Even if the plan to refactor it and use `LocalOrRemoteId` everywhere, then we still have to wrap/unwrap it if we want to pass between android's components and then we lose compile-time check which kind of defeats the purpose of having a wrapper

Furthermore, I think it breaks things in some places, for instance:

* `CardReaderPaymentViewModel::449`, the name will be something like `receipt-order-RemoteId(value=5)` instead of 
`receipt-order-5`
* `OrderDetailViewModel::353`. I think we want to track remote id (long) not `RemoteId(value=12313)`

How do you look into
* We replace `localId` and `remoteId` in `Order` class with value classes (we probably need to override to string so the issues I mentioned above will be fixed). It will at least stop us pushing in the direction to build APIs in the domain layer which accepts `LocalOrRemoteId` 

OR

* We make `LocalOrRemoteId` serialazable. It's not platform (android) specific so it's totally fine by me. For sake of example [Result](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) is Serializable. It will make this type fully usable and we will have compile-time check even when we pass it in android components. I still don't see the value to have it as a sealed class though, if class is not `open` you can not extend it anyway. We still need to fix the issues I mentioned above though

What's your opinion?

**Comment by wzieba** [comment]
Thanks @kidinov ! This is a good discussion, I have read your arguments and have following thoughts:

> I still don't understand what is `LocalOrRemoteId` for in general. It looks like an attempt to bring something similar to kotlin's result but not for results and it doesn't work =)

I believe it was introduced exactly for helping to understand context when working with ids, and prevent confusions between them in compile time. I understand that `value class` would be a better option but back in 2019, when `LocalOrRemoteId` was introduced, it was a good solution to me. I think it does fulfil its purpose.

> Aside from that, we create a new instance every time we access the property, I am still not following what is the goal to expose this here instead of just a Long (or value class to have compile-time check).

I think that the new instance is really not a problem here, it's quite low level performance thing. The goal of exposing it to Woo was the same as the one in FluxC - to determine exactly type of the id in compile time. I'll reference to `value class` argument in next paragraph.

>  In many places, we still have to extract value (long) from this anyway, because as I mentioned above we can not pass it between activities/fragments, and probably in many places we expect long, not LocalId or RemoteId at the moment.

Yes we do and I think changing those signatures is beneficial. Also I don't believe there's a lot of places where we share id of the order between Android components. If you did some research, could you share some of the places? I think it might be for opening order details and maybe something around notifications.

❓ Do you know if when passing `value class` between Android components, do we have to do some mappings, or does it work out of the box? Because if it doesn't, we'll have to have `LocalOrRemoteId`, `Long` and `value class` and map between them back and forth. This feels to me like big overhead.

> CardReaderPaymentViewModel::449

Just to be sure: I assume you meant 447, on current develop. Yeah, this is a bug you found, thanks! 😄 During the conversion I should've check any references to it. It should be `private fun Order.getReceiptDocumentName() = "receipt-order-${remoteId.value}"` - thanks!

> OrderDetailViewModel::353

Yup, this is another bug of the same nature as above. I haven't checked any string injections. It makes me think that we maybe should change the way how we create tracking events to method with signature, so when type of anything will change - we'll break it in compile time.

About proposed solutions:

> We replace `localId` and `remoteId` in Order class with value classes (we probably need to override to string so the issues I mentioned above will be fixed). It will at least stop us pushing in the direction to build APIs in the domain layer which accepts LocalOrRemoteId

I like this more than making `LocalOrRemoteId` serialisable but I'm still worried about including yet another wrapper around `id`.

To sum up - I don't really see issue with using `LocalOrRemoteId` and challenges you've described sounds like easy to work on and maintain in the future. The biggest one to me is passing id between Android components, which to my knowledge doesn't happen that often.

Edit: 

> I still don't see the value to have it as a sealed class though, if class is not open you can not extend it anyway. We still need to fix the issues I mentioned above though

Good point. I'm thinking now about serialisable approach 🤔 . I understand it's not framework-specific but still JVM-specific which I don't like (and I don't like `Result` being serialisable as well). But I wonder if does it make any difference to us?

---

Maybe I've been working on this matter for so long that I have tunnel vision on it, but I'm just trying to find best solution as this decision might influence how we'll model app not only in scope of `Order`, but every other model. That's why I believe it's so important to have consensus here.

@woocommerce/android-developers as this matter might affect all of us, do you mind to chime in if you want? Thank you in advance!

**Comment by hichamboushaba** [comment]
We had a discussion in our Order Creation weekly call about this subject, and as I explained in the call, these are my thoughts:
1. `LocalOrRemoteId` is useful in its context, especially when an order had two types of ids previously, and I think we can keep it for the other classes if it's used on them.
2. With the new way of identifying an `Order` in the database, there is only a single `id`, which is the `remoteId`, the other part `localSiteId` is not something we want to expose through the Woo app, our Repositories should hide it, since the app is targeting a single site represented by the `SelectedSite` class, which means they can get the site id before making any calls to the FluxC's Stores, or they can even pass the `Site` object instead of the `id` if it makes the code easier to understand.
The exception for this is just push notifications, but even for those, we switch the site before showing the order.
3. Due to the point 2, I don't see an added value for neither `LocalOrRemoteId` nor a value class for the context of Orders, all the app components will use just the `remoteId`, and so it can stay as a simple Long type, without any confusion.

**Comment by kidinov** [comment]
@wzieba @hichamboushaba thank you for your answers! 

> To sum up - I don't really see issue with using LocalOrRemoteId and challenges you've described sounds like easy to work on and maintain in the future. The biggest one to me is passing id between Android components, which to my knowledge doesn't happen that often.

I'm not saying that having a wrapper of a primitive type in order to have compile-time verification that you don't pass wrong id or long or int there is a bad thing. Quite the opposite. It's just I don't like the implementation. In short my opinion on this:

* Having a hierarchy in `LocalOrRemoteId` doesn't bring anything except confusion. We always expect and pass concrete types `RemoteId` and `LocalId`. Just 2 simple wrappers `RemoteId` and `LocalId` will work in the same way
* Being an identifier and not serializable/parcelable makes it not usable in the Android context. I don't think that we should design a system based on how often our current solution doesn't work. Better if it always works =)
* In general passing domain layer types around (including in the presentation layer) doesn't sound like a good idea. Especially that theoretically Fluxc is not even our code, at least not 100% ours

Having said that, I'm not saying that we should rewrite all the usages of `LocalOrRemoteId` in the app, but I agree with @hichamboushaba that we should at least remove it from "Order" related code just because it's not needed and I make changes anyway. The only thing I would argue about is that I see a lot of value in passing a value type, instead of primitive. The reason is exactly the same why `LocalOrRemoteId` was created - to be sure already in compile time that we don't pass the wrong id (site id or whatever) or just a random number instead of `OrderRemoteId`

Thoughts?

**Comment by hichamboushaba** [comment]
> to be sure already in compile time that we don't pass the wrong id (site id or whatever) or just a random number instead of OrderRemoteId

Can you explain what compile safety a value type would bring in our case? 🙂
From what I see, even if we introduce another type, we can instantiate it with whatever value, so it won't have any guarantees that it's the right one.

I think `LocalOrRemoteId` was created to avoid confusion between local and remote ids, which we don't have now, since `localId` will be removed from the Order completely, and there is a single `id` for identifying the order, and it's the one that Android components need to exchange.

I'm just discussing, if there is any value-added by the value class, then go for it, we just need to be sure the navigation component will be able to handle it.

**Comment by kidinov** [comment]
@hichamboushaba 

> Can you explain what compile safety a value type would bring in our case? 🙂

Definitely! A couple of examples from our codebase:

```
    override fun showOrderDetailWithSharedTransition(
        localSiteId: Int,
        localOrderId: Int,
        remoteOrderId: Long,
        remoteNoteId: Long,
        sharedView: View
    )
```

It's pretty simple to make a mistake and call it like that:

```
showOrderDetailWithSharedTransition(localOrderId, localSiteId, remoteNoteId, remoteOrderId, sharedView)
```

And it will be compilable and it might even work (incorrectly) but there is a chance that it will be missed and released

Another benefit would be is avoiding the code similar to this:

```
        <argument
            android:name="orderId"
            ** android:defaultValue="0L" **
            app:argType="long" />
```

Which is not really error-prone 

@wzieba  @hichamboushaba  I've created [a draft PR](https://github.com/woocommerce/woocommerce-android/pull/5503) with the usage of a value class instead of `RemoteId`. The ides is the following:

* We always pass a value class internally
* If external API requires either long or `RemoteId` or whatever we convert it to the closest to the API place

Please let me know if you are ok with that approach so I can proceed

**Comment by hichamboushaba** [comment]
> Definitely! A couple of examples from our codebase:

> override fun showOrderDetailWithSharedTransition(
        localSiteId: Int,
        localOrderId: Int,
        remoteOrderId: Long,
        remoteNoteId: Long,
        sharedView: View
    )

Normally this function should be refactored to this:

```kotlin
override fun showOrderDetailWithSharedTransition(
        remoteOrderId: Long,
        remoteNoteId: Long,
        sharedView: View
)
```

I don't know what's the use of the `remoteNoteId` here, but it must be something specific to this usecase, but for the other ids, the app shouldn't bother with them, the `localSiteId` will be always calculated from the current `SelectedSite`, and `localOrderId` will be removed after the refactoring.

> Another benefit would be is avoiding the code similar to this:
>        <argument
>            android:name="orderId"
>           **android:defaultValue="0L"**
>            app:argType="long" />

What do you mean here? the `defaultValue`?

**Comment by kidinov** [comment]
@hichamboushaba

This was just an example, so you get the idea. There are many places in the code like that, that's why value classes (or wrappers before) are used

> What do you mean here? the defaultValue?

Yep. If you don't pass order id in the fragment then it "works" with an order with `id = 0`. The order might be in DB or might not be, in any case, it's a clear road to the incorrect state

**Comment by hichamboushaba** [comment]
> This was just an example, so you get the idea. There are many places in the code like that, that's why value classes (or wrappers before) are used

Thanks for the examples @kidinov, but I still don't get the idea, sorry 🙂, I know the code is like that in many places, but the code needs to be fixed, and not finding other ways to make it less confusion. Actually this was the goal of refactoring to using a `composite primary key` instead of having both a `localId` and `remoteId` in our Orders, remove the confusion around which id we need to pass.

This is just my opinion, but I feel like adding another class for this case will just create some confusion (`OrderId` vs `LocalOrRemoteId`), where there is no confusion at all, an Order is identified just by its `remoteId`.

> Yep. If you don't pass order id in the fragment then it "works" with an order with id = 0.

But a value class doesn't prevent this, you can still instantiate it like this `OrderId(0L)` 😕 

Anyway, if I'm the only one who thinks we don't need an additional class for this, ignore my comments, and go ahead with the implementation 🙂

**Comment by wzieba** [comment]
Thanks for continuing discussion @kidinov and @hichamboushaba - I took a wider look at this matter and re-evaluated my previous opinions.

I still stand on the opinion that adding a new class (`value class`) is not the best approach as it introduces yet another way to wrap id. I second to

> (...) I feel like adding another class for this case will just create some confusion (OrderId vs LocalOrRemoteId, where there is no confusion at all, an Order is identified just by its remoteId.

Just to emphasise: I see pros of using `value class` and thank you @kidinov for your sample PR but I'm not sure if they're big enough to sacrifice simplicity (aka having just `Long` as id).

After seeing this discussion and different arguments I see that `LocalOrRemoteId` is very helpful in scope of `FluxC` library but indeed it's not especially on client side. So what I would opt for now is removing `LocalOrRemoteId` from `Order` model and change it to simple `Long` as @hichamboushaba proposed in his first comment.

**Comment by kidinov** [comment]
@hichamboushaba @wzieba Thank you for the discussion! I probably failed to explain properly the value of "value" classes 😃. You should look into value classes, not like a wrapper, but more like `a primitive of a specified type`. In any case, I've just created [an issue](https://github.com/woocommerce/woocommerce-android/issues/5505) and will pick up it first. 🙏

**Comment by hichamboushaba** [comment]
> You should look into value classes, not like a wrapper, but more like a primitive of a specified type

Yes, the compiler will make sure to convert it to the primitive type, but still, on some occasions, it will cause some wrapping/unwrapping, since you had to make it `Parcelable` to be able to use it with the Navigation component, which means whenever we pass it to an `action`, or we read it from the `NavArgs`, it will be written/read like a `Parcelable`, and not like a primitive `Long` 🙂.

Thank you both for the enriching discussion ❤️

**Review by wzieba — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
