### PR TITLE
[Product Subscriptions] Edit sign up fee + Details formatting in the price row

### LINKED ISSUE #10151: Add Sign-up fee field to the price screen

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #10151 

### Description
This PR has three main changes:
1. Add the sign-up fee to the pricing screen.
2. Updates the price row to show details about the subscription schedule.
3. Updates the format of the subscription's period and interval to match what iOS did p1699952473205259/1699889235.104879-slack-C03L1NF1EA3

##### Subscription
1. Make sure that the Woo Subscriptions plugin is installed in your store.
4. Create a Subscription product.
5. Open the app, then navigate to this product.
6. Click on the price button, and confirm it shows the correct sign-up fee.
7. Change the sign-up fee value.
8. Go back to the product, and confirm the change was reflected.

##### Variable Subscription
1. Make sure that the Woo Subscriptions plugin is installed in your store.
4. Create a Variable Subscription product, then create a variation (or more).
5. Open the app, then navigate to this product, then open one of the variations.
6. Click on the price button, and confirm it shows the correct sign-up fee.
7. Change the sign-up fee value.
7. Go back to the variation , and confirm the change was reflected.

**Note**: For both the above cases, clicking on save or update would reset the data, as we don't send it to the backend yet.

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by 0nko — COMMENTED** [review]
Everything looks good, there's just one thing -- when you have the signup fee, the title in the product property description says "No sign up fee: $X}".

**Comment by hichamboushaba** [comment]
Thanks @0nko for the review, this should be fixed in 64f83fb

**Review by 0nko — COMMENTED** [review]
Thanks for the fix, Hicham. After some more testing, I noticed that underneath the sale price there is a string:



Was that supposed to display the interval (Every 4 weeks)?

Another thing, when you delete the sign up fee and go back to the product/variation detail, the previous value is displayed.

**Comment by hichamboushaba** [comment]
Thanks again @0nko for catching these, and sorry for missing them.

> Was that supposed to display the interval (Every 4 weeks)?

Yes, fixed in a818600dd6fd7c3e02414fa4c2c3bd946e97d42b

> Another thing, when you delete the sign up fee and go back to the product/variation detail, the previous value is displayed.

We weren't even saving the value in this case, fixed in 0cb4fb5

Ready for another round 🤞

**Review by 0nko — APPROVED** [review]
Thanks for the fixes! 

I have one more nit-pick but I'll leave it up to you if you want to change it: When you set the sign up fee to 0, it's displayed in the price description. Should we just hide it? The read-only subscription hides it.

Nice work! 👍

**Comment by hichamboushaba** [comment]
> I have one more nit-pick but I'll leave it up to you if you want to change it: When you set the sign up fee to 0, it's displayed in the price description. Should we just hide it? The read-only subscription hides it.

Another great catch, thanks @0nko, fixed in fb1f6f7

**Pull request merged**
