### PR TITLE
Bump Tracks (Sentry). Improve Sentry Gradle Plugin configuration

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR bumps Tracks (transitively: Sentry SDK) and Sentry Gradle Plugin to the newest stable versions.

By sending code sources and thanks to the CodeCov integration, now report at Sentry will show source code which caused the issue, as well as information if this part is covered by unit tests.

The PR also improves build setup: it disables Sentry tasks in `debug` builds and disables sending list of dependencies, as we don't need it (we can identify dependencies by releases).

### Testing instructions

Not needed. I verified that issues are still sent when bumping the library, and I tested if uploading sources and mapping files is also correct.

### Images/gif

| Before | Screenshot 2024-03-15 at 14 08 57 |
|--------|--------|
| After | Screenshot 2024-03-15 at 14 02 42 |

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wzieba** [comment]
hi @samiuelson 👋 ! If it's not to late to merge for 17.8 release, I think it'd be nice to do, so we'll benefit from better reports on Sentry in this release already.

**Review by samiuelson — APPROVED** [review]
Looks like a nice improvement. Thanks @wzieba! 🚢

**Comment by wzieba** [comment]
Thanks! I'll merge trunk as soon as #11094 will land there.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/199">17.8</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
