### PR TITLE
CardPayments Payments Flow UI

### PR DESCRIPTION
**Pull request by malinajirka**
Parent issue #3726 

This PR updates layout of CardReaderPaymentsDialog and connects it to its VM ViewState.

Few notes
- ~The imported vector drawables have some artefacts - I didn't want to delay the progress on this right now, but if you know how to fix them, please let me know~
- I'm using hardcoded colors in vector xmls - afaict that's what we do in other vector drawables
- Please review even the layout carefully, since I'm new to the codebase I might be overlooking some best practices

To Test - Make sure to test these changes with a site with WCPay in devmode (or live mode, but only hw reader is supported in live mode)
1. Open app settings
2. Tap on "Manage card reader"
3. (optional) Check "use simulated reader"
4. Tap on "Connect card reader"
5. Go back - open a detail of an order in **USD currency**
6. Tap on "Collect payment"
7. Check that the flow works and the payment succeeds

| Light | Dark |
|---|---|
|  |  |
|  |  |
|  |  |
|  |  |

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
I tested this with my live site on an emulator, and as expected saw `NETWORK_ERROR.STRIPE_API_ERROR: Expired API Key provided` in the log. However, I saw an empty progress dialog for a few seconds, then this empty view appeared:

empty

I knew it was going to fail, but it looks like we need to handle failure better (perhaps this is already planned for a later PR?). Note that the same empty view appeared when I used a real device and real reader and just left the payment dialog showing without ever tapping the card. The log showed  `E/StripeTerminal: USER_ERROR.CARD_READ_TIMED_OUT: Timeout during card read`.

And the same empty view appeared when Stripe rejected my test card (`PAYMENT_ERROR.PAYMENT_DECLINED_BY_STRIPE_API: Your card was declined. Your request was in live mode, but used a known test card.`).

**Comment by nbradbury** [comment]
I used a real card then rotated the device when the "Payment successful" screen appeared, and it restarted the whole collect payment flow.

dialog

**Comment by nbradbury** [comment]
> I'm using hardcoded colors in vector xmls - afaict that's what we do in other vector drawables

We're actually using a hodge-podge of hardcoded colors and color resources in our vectors. You'll note most of the `ic_` drawables use color resources since their colors will likely change for dark mode. I'd recommend using color resources when possible, but it's not a requirement we've talked about as a team.

> Please review even the layout carefully, since I'm new to the codebase I might be overlooking some best practices

Layout looks good to me!

**Comment by malinajirka** [comment]
Thanks for the review @nbradbury ! I'm planning to handle all the errors in separate PRs since there'll be quite a lot of them. 

The empty view is empty since I haven't implemented the ViewState.Failure yet - it just hides all the views.

I'll fix the rotation issue in this PR. I noticed it yesterday but I forgot to fix it :(.

**Comment by malinajirka** [comment]
@nbradbury It's ready for another round ;). I've fixed the configuration change issue and added a test for it so it doesn't happen again. I'll handle all error states in a separate PR(s). Thanks!

**Comment by nbradbury** [comment]
@malinajirka Fix looks good and I'll merge shortly, but I have a suggestion for a future PR. If you tap the screen outside of the collect payment dialog, the dialog disappears - even if the payment is being processed. I'm not a fan of modals, but in this case I think we want to prevent accidental taps from interfering with the payment.

**Review by nbradbury — APPROVED** [review]
:shipit:

**Comment by malinajirka** [comment]
> If you tap the screen outside of the collect payment dialog, the dialog disappears - even if the payment is being processed. I'm not a fan of modals, but in this case I think we want to prevent accidental taps from interfering with the payment.

Good point! I'm not sure what would be the best way to handle this since we don't want to prevent the user from leaving the flow. Perhaps we should introduce a cancel button on all the steps. I'll discuss it with a designer. Thanks!

**Pull request merged**
