### PR TITLE
Issue/3176 shipping label refund changes

### LINKED ISSUE #3176: [Shipping Labels M1]: display products card if shipping labels are refunded
Once a shipping label is refunded, it “resets” the Order details screen, meaning all the products are listed independently from a package, with the 2 CTAs “Create shipping label” and “Mark as fullfill”.  The “shipping label refund requested” should leave in a separate area (similarly to core).

Screen Shot 2020-11-18 at 13 48 54
Screen Shot 2020-11-18 at 13 50 49

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3176 by modifying designs if shipping labels are refunded.

**This PR is in draft till [this PR](https://github.com/woocommerce/woocommerce-android/pull/3283) can be reviewed and merged.**

#### Changes
- The Products card should be displayed with products that are NOT associated with any shipping labels.
- The product section in the Shipping Labels card should be hidden if the shipping label is refunded.
- Changed the order of the products and refunds card in the Order detail screen. Previously, it was displayed below the shipping labels section but it should actually be displayed above the shipping labels section.

#### Screenshots
. 

#### To test
- Create atleast 2 shipping labels for an order by following the instructions from `p91TBi-3xD`.
- Refund one of the shipping label within 2 minutes of creating the shipping label.
- Open the app and click on the order. 
  - Notice that the products card is displayed with products not associated with any shipping labels. 
  - Notice that the refunded shipping label does not display the products section.
  - Notice that the shipping label that was not refunded displays the products section.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — COMMENTED** [review]
Hi @anitaa1990 , when all shipping labels have been refunded, users need to be able to see their products and be able to fulfill their orders again. So you should see the Products card with the fulfillment CTA and the packages card with the "refund requested" notices. 

https://d.pr/i/JR5rIQ

Currently on the screenshot you shared, I don't see the Products card

**Comment by anitaa1990** [comment]
Hey @Garance91540, these two screenshots are actually from the same screen 😅 

 I just split them into two since I couldn't take a screenshot of the whole screen. This is the current implementation:



Let me know if this is fine!

**Review by AmandaRiu — CHANGES_REQUESTED** [review]
@anitaa1990 Code looks good, but I found some issues during testing: 

**Item count incorrect in packages.** I created this really large order containing 6 items and spread them between 3 packages. It seems like if the customer orders multiples of a single item and they are spread across different packages - each package will report the same total items. 

This first package shows 2 Long Sleeve T-shirts are in this package, but in actuality there was only 1. 

Mobile | Web 
-- | -- 
1_package-1|1_package-1-web


The second package contains only 2 items but the app shows a total of 4 items (2 of each item)

Mobile | Web
-- | --
1_package-2|1_package-2-web


**Refunded package still shows products**




**Products card does not get displayed for items in a refunded package**

3_refunded-items


All these tests were run on a Pixel 2 running Android 10.

**Review by Garance91540 — DISMISSED** [review]
ah gotcha! in that case all good!

**Comment by anitaa1990** [comment]
Thanks so much for the review @AmandaRiu!

> Item count incorrect in packages.  

Yup, this is a known issue. We don't get the quantity of the products when fetching shipping labels. We only get the `product_names` and `product_ids` associated with the shipping label. The quantity displayed is the quantity fetched from the order. This is one of the things that needs to be fixed on the API side. Until then, I wonder if we should perhaps hide the quantity field? cc @Garance91540 WDYT?

> Refunded package still shows products

I had access to the order you mentioned here and I believe it is related to the same issue mentioned above 😨. It looks like the quantity of `Ninja Hoodie` in this order is 2.  And there are 2 shipping labels and both of them have 1 Ninja hoodie associated with it. And the API is returning only the product name here. So in the app, there is no way for us to know which product was refunded since both shipping labels have the same product and only one of them is refunded. So I think both products are displayed here even though one package is refunded. This issue should not occur if the shipping label was purchased/created after WCS 1.24.1 since we introduced the `product_ids` fix in this release just to fix this issue. But unfortunately, this issue would persist in shipping labels purchased before 1.24.1 😞 

> Products card does not get displayed for items in a refunded package

I'm not actually able to reproduce this. I was able to view this order from your test site on the app and it was working as expected 😕 Maybe it could be related to internet issue and the order not being updated correctly?


Ready for another round 👍

**Review by AmandaRiu — APPROVED** [review]
@anitaa1990 Thank you for all the detailed answers. It looks like merging the changes from develop helped to fix the issue you weren't able to reproduce. It sounds like the rest of the items are known and there's not much to do about it at this point :shipit:

**Comment by Garance91540** [comment]
> Until then, I wonder if we should perhaps hide the quantity field? cc @Garance91540 WDYT?

I wasn't aware of this issue. Yes in that case it's better to temporarily hide data vs show corrupt data. But can we make sure to update this as soon as we get that fix in the API? It's still a pretty important information to display

**Pull request merged**
