### PR TITLE
Issue/11059 order deletion

### LINKED ISSUE #11059: [Orders] Support order deletion
Add support for deleting orders from the app.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #11059 

⚠️ Depends on https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2972

### Description
This PR adds support for deleting orders from the Order Details screen, it uses the changes of the FluxC PR above to handle the deletion with cancellation.
In order to support the tablet mode, I mirrored what was done for products deletion by adding a shared ViewModel `OrdersCommunicationViewModel` that's used to pass the action from the order details screen to the list screen.

### Testing instructions
1. Open order details screen.
2. Notice the trash button.
3. Click on it and notice the alert.
4. Confirm the trash.
5. Notice the Undo snackbar on the order list screen.
6. Repeat 2-5 and use the Undo button of the Snackbar.
7. Confirm the item deletion was reverted.

Repeat the above steps on a tablet.

### Images/gif
[Screen_recording_20240313_101635.webm](https://github.com/woocommerce/woocommerce-android/assets/1657201/279cd2e2-8a7a-4606-8d7a-be343e221d5d)

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>OrdersCommunicationViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>CommunicationEvent</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/199">17.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hichamboushaba** [comment]
@JorgeMucientes @0nko please don't review this PR yet, as I'm still working on the issue mentioned above, and I think I'm on a track for a simpler solution that solves the issue.

**Comment by hichamboushaba** [comment]
> @JorgeMucientes @0nko please don't review this PR yet, as I'm still working on the issue mentioned above, and I think I'm on a track for a simpler solution that solves the issue.

This is ready for review now.

**Review by 0nko — APPROVED** [review]
Works great! 👍

**Pull request merged**
