### PR TITLE
Issue/1057 add dates to order list

### LINKED ISSUE #1057: Order List: Add individual dates
**Is your feature request related to a problem? Please describe.**

When trying to find an order from a specific date it can be difficult to scan through right now, as we group things into an "older than a month" category.

**Describe the solution you'd like**

Add the date to the top of each order cell:

Android-order-cell

Corresponding [iOS issue
](https://github.com/woocommerce/woocommerce-ios/issues/956)

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #1057 by adding dates to the order list. 

Screenshot_1557856435

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by nbradbury** [comment]
cc @kyleaparker for design review

**Comment by AmandaRiu** [comment]
@nbradbury Code looks good, but just as I was about to merge I noticed there is a funkiness with the spacing inside the order list cell. I'm wondering if there should be less space between the date and the order number? Looking at the design, the vertical spacing between the 3 elements is identical, but in this implementation the date is floating farther from the rest of the text:

Screen Shot 2019-05-14 at 6 21 04 PM

**Comment by kyleaparker** [comment]
Agree with @AmandaRiu, the spacing of the date is a little off. The design is using 4pt between those two elements

**Comment by nbradbury** [comment]
@AmandaRiu @kyleaparker I decreased the padding to 4dp in 4777e12.

Screenshot_1557922456

**Comment by AmandaRiu** [comment]
Verified changes, all looks good 👍

**Pull request merged**
