### PR TITLE
Enable setting negative values for product regular price

### LINKED ISSUE #4665: Add Support for Entering Negative-priced Product
WooCommerce core supports adding negative-priced product, as [per this conversation](https://github.com/woocommerce/woocommerce/issues/25037#issuecomment-554072804) (h/t to @iamgabrielma for the find).

Currently, the app does not support this yet.

Interestingly, the app is already able to display negative-priced products in product details, and in order details.

See p91TBi-5NR-p2 for more details.

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #4665

### Description
Enable input for negative prices on edit products. The main reason for this is explained [here](p91TBi-5NR-p2) in detail. Basically, Woo core already supports negative prices and the apps already support displaying these negative prices. The missing piece was enabling the user to input these negative pricing from the apps. 

If wondering why we need to support negative prices these are a couple of use cases why the user may need this: 

Screenshot 2021-09-24 at 15 54 24

### Testing instructions
Just edit any product and try to set a negative number for the regular price. 

https://user-images.githubusercontent.com/2663464/134686346-3016a51a-4e55-4fe4-88ff-08a23b3e633a.mp4

### Bonus points

- Avoid displaying `salePriceErrorMessage` when setting negative pricing which leads to the pricing not being saved. 

https://user-images.githubusercontent.com/2663464/134687557-9c87032a-2fc1-4082-8ee6-3118024ab77c.mp4

- Enable adding negative numbers to sale price too. Not sure this will be useful for the user, but this is possible to do in core/web WooCommerce. Plus, for consistency, if we enable negative values for regular prices IMHO it makes sense to enable it as well for sale prices.

### CODE REVIEW

**Review by 0nko — CHANGES_REQUESTED** [review]
The change looks good, I just noticed one issue -- when you set a negative sale price and then adjust the regular price so that sale price > regular price, you won't get the validation error. This doesn't happen for positive values because and it's caused by the new `salePrice > BigDecimal.ZERO` condition.

**Comment by JorgeMucientes** [comment]
You're absolutely right. When I first added that check `salePrice > BigDecimal.ZERO` I did not intend to allow negative sale prices. But then I change my mind and forgot to remove that check. Good catch thanks! 

Removed the check: 

https://user-images.githubusercontent.com/2663464/134863195-21b3986a-d6d5-4c15-a155-d012c4a338b8.mp4

**Comment by 0nko** [comment]
Unfortunately, you now can't set a price without also specifying a sale price. I think you'll need remove the default 0 value for sale price and make it nullable.

**Comment by JorgeMucientes** [comment]
Ouch! 🤦🏼  😅 

I think the current code updates covers now all the scenarios. I used another approach different than making `salePrice` nullable, as this had other side effects. For example, in `ProductDetailFragment` if salePrice is null the code fallbacks to the [previous value](https://github.com/woocommerce/woocommerce-android/blob/ff49737efb6edb54f724809b6a0e75c4705a19b5/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/ProductDetailViewModel.kt#L864). Also added a couple tests.

Btw while testing the changes, I found a bug. Though it was some kind of race condition as the bug is intermittent, but can't really see where it is. I was able to reproduce the bug in develop branch too.

The bug: 

The video shows how after several attempts changing any of the product price values, in the third change when going back to the product detail view the sale price is not refreshed accordingly to 2. Now, if we open any other screen, or simply rotate the app, causing the views to repaint, then the sale price value will have the right value. 

https://user-images.githubusercontent.com/2663464/134966573-c38f505d-f35b-4c16-9d07-3ed4a4e53abc.mp4


I added a log to `LiveDataDelegate.observe` to check the price values used to update the ViewState from ProductDetailViewModel and it all looks good, even when the bug happens

```kotlin
    fun observe(owner: LifecycleOwner, observer: (T?, T) -> Unit) {
        if (_liveData.hasActiveObservers()) {
            throw(IllegalStateException("Multiple observers registered but only one is supported."))
        }

        previousValue = null
        _liveData.observe(
            owner,
            Observer {
                if (it is ProductDetailViewModel.ProductDetailViewState) {
                    Log.i(
                        "RACE CONDITION",
                        "OnBack -> regular price:${it.productDraft?.regularPrice}  sale price: ${it.productDraft?.salePrice} "
                    )
                }
                onChange(previousValue, it)
                observer(previousValue, it)
                previousValue = it
            }
        )
    }
```

and the logs:

```logs 
2021-09-27 20:35:51.001 18788-18788/com.woocommerce.android.prealpha I/RACE CONDITION: OnBack -> regular price:10  sale price: 3 
2021-09-27 20:35:51.003 18788-18788/com.woocommerce.android.prealpha I/RACE CONDITION: OnBack -> regular price:10  sale price: 2 
2021-09-27 20:35:51.003 18788-18788/com.woocommerce.android.prealpha I/RACE CONDITION: OnBack -> regular price:10  sale price: 2 
2021-09-27 20:35:51.053 18788-18788/com.woocommerce.android.prealpha I/RACE CONDITION: OnBack -> regular price:10  sale price: 2 
2021-09-27 20:35:51.054 18788-18788/com.woocommerce.android.prealpha I/RACE CONDITION: OnBack -> regular price:10  sale price: 2 
2021-09-27 20:35:55.394 18788-18788/com.woocommerce.android.prealpha I/RACE CONDITION: OnBack -> regular price:10  sale price: 2 
2021-09-27 20:35:55.446 18788-18788/com.woocommerce.android.prealpha I/RACE CONDITION: OnBack -> regular price:10  sale price: 2 
```

There is actually no race condition by looking at the code and the logs, as these updates are always run sequentially. In this case, I believe it's better to open a new issue to take a closer look into this right? It's not a major thing as it is not easy to reproduce but I guess we should keep track of it.

**Comment by 0nko** [comment]
> There is actually no race condition by looking at the code and the logs, as these updates are always run sequentially. In this case, I believe it's better to open a new issue to take a closer look into this right? It's not a major thing as it is not easy to reproduce but I guess we should keep track of it.

Sounds good 👍

**Review by 0nko — APPROVED** [review]
:shipit:

**Pull request merged**
