### PR TITLE
Feature: Show all product reviews

### LINKED ISSUE #1324: Show all Product Reviews
Now that the last tab in the app now only contains product review notifications, it seems confusing that we don't show all product reviews. #1300 explored how we would go about implementing this feature change with the following specs:

- Show all product reviews in the "Reviews" tab
- Show unread product review notifications
- Support review moderation
- Support notification seen/read functionality

To accomplish the above, we'll need to do the following:

- [x] FluxC: Add the product review endpoints for fetching and storing product reviews list, product review single, and update product review. ([#](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1343), [#](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1374))
- [x] Update `NotificationHandler` to fetch the `ProductReview` and `ProductModel` when a new review notification is received. (Maybe use the `ProductImageMap` singleton to handle fetching the product for each of the review)
- [x] Display a simple list of product reviews (#1388)
- [x] Implement mark all as read functionality (#1389)
- [x] Open and view review detail (#1390, PR #1412)
- [x] Review moderation (#1391, PR #1419 )
- [x] Add tracks events (#1421, PR #1431 )
- [x] Add tests (#1392, PR #1439 )

### PR DESCRIPTION
**Pull request by AmandaRiu**
Closes #1324 and implements the new designs to convert the content of the "Reviews" tab from just showing product review notifications to showing all product reviews. 

all-product-reviews

This required moving from using the `/notifications` endpoint for populating the screen, to implementing support for the `/product/reviews` endpoint. This feature is a bit of a mixed bag however as we still use the `/notifications` endpoint for:

Reviews List:
- showing the "unread" indicator for items in the reviews list if that product review has a matching `Notification` and the status of said notification is "unread"
- enabling the "mark all as read" menu option if any unread product reviews are present
- sending a request to the API to mark all product reviews as read if the user clicks on the "mark all as read" menu option

Review Detail:
- sending a request to the API to mark the active product review as read if there is a matching unread notification

A list of all the tickets and related PRs for this feature can be found in #1324. All PRs have been approved and merged so this PR just needs a final run-through of the finished product to make sure all is well.

### CODE REVIEW

**Comment by nbradbury** [comment]
Just noticed the star rating seems to be missing from review detail. Was this intentional?

It shows in the list:
Screenshot_1570198912

But not in the detail:
Screenshot_1570198958

**Comment by AmandaRiu** [comment]
> Just noticed the star rating seems to be missing from review detail. Was this intentional?

Oh wow! How did that slip through? I'll take a look at it now. Thanks!

**Comment by AmandaRiu** [comment]
@nbradbury Fixed the ratings bar in Product Review Detail. Ready for another round!

**Comment by nbradbury** [comment]
@AmandaRiu Looks like the order list has the opposite problem - it shows the rating bar even when there's no rating.

Screenshot_1570202274

In `develop` the rating bar is hidden:

develop

**Comment by AmandaRiu** [comment]
Removed ratings bar in the review list item if rating is 0. :)

**Comment by nbradbury** [comment]
Great work - really glad to have this feature! :shipit:

**Pull request merged**
