### PR TITLE
UL: Modified password and passwordless flow

### LINKED ISSUE #3120: [Unified Login - Continue with WP.com] - Pwd step
I'm sorry to check this so late in the game, but I just realized this part of the flow needs updating. 

In the WP flow, once users enter their email:
1 . if the email matches a WP.com account, but doesn't have a pwd set, we show them this screen https://d.pr/i/YVWIJc

2. If the email matches a WP.com account and the pwd already has been set, we show this screen: https://d.pr/i/SPE1AM

Screen Shot 2020-11-03 at 14 34 15

In all cases, there should only be a one-step magic link (no longer 2 different screens)

Thank you!

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #3120 by implementing the new password and passwordless designs for unified login. 
- The extra step for magic link has been removed
- Login via a passwordless WordPress.com account now supported (account created via SIWA)
- New password layout screen now used.

Password Login | Magic Link Login
-- | -- 
password|magic-link

### To Test

The following tests all use the "Log In with WordPress.com" option. 

**Login with Password**
1. Click **Log in with WordPress.com**
2. Enter WordPress.com account email, click **Continue**
3. Enter password, click **Continue**, login successful

**Login with Magic Link**
1. Click **Log in with WordPress.com**
2. Enter WordPress.com account email, click **Continue**
3. Click **Get a login link by email** option. The magic link request screen will briefly be displayed before auto-routing to the Magic Link sent screen. 
4. Finish logging in via magic link

**Passwordless login** 
1. Click **Log in with WordPress.com**
2. Enter WordPress.com account email (Use an account that was created via SIWA)
3. Click **Continue**. The magic link request screen will briefly be displayed before auto-routing to the Magic Link sent screen. 
4. Finish logging in via magic link

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — DISMISSED** [review]
👏👏

**Comment by AmandaRiu** [comment]
This one is ready for review 👍

**Comment by Garance91540** [comment]
@AmandaRiu one quick note: on the screencast you shared, when you select "get a login link by email", I'm seeing the first magic link screen flashing and then the second magic link screen. Is it possible to remove completely the first "flashing" screen?

**Comment by AmandaRiu** [comment]
> @AmandaRiu one quick note: on the screencast you shared, when you select "get a login link by email", I'm seeing the first magic link screen flashing and then the second magic link screen. Is it possible to remove completely the first "flashing" screen?

@Garance91540 That screen you see flashing is just the "requesting magic link" screen which you'll want to show if someone has a slow connection (otherwise it will feel like the app has frozen). We could and should change the designs around this but I think in that case it'd make sense to coordinate with WPAndroid as well since these screens are part of the shared flow the two apps use. If the designs could join the "Requesting magic link" and "magic link sent" into a single view where maybe there's a progress animation then the flow wouldn't feel so jarring.

**Review by nbradbury — DISMISSED** [review]
Looks good! :shipit:

**Comment by nbradbury** [comment]
@AmandaRiu I was just about to merge this but saw there are now conflicts in the release notes.

**Comment by AmandaRiu** [comment]
@nbradbury resolved the conflict. Ready for merge!

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
