### PR TITLE
[Tablet support M3] Part 3 – Product selection state sync in two-pane layout

### PR DESCRIPTION
**Pull request by samiuelson**
Closes: #10616, #10617, #10619, #10620, #10973

### Description

1. This PR introduces a new `LIVE` selection mode in the product selector screen. The Live mode is designed for the product selector working in the two-pane mode, next to the order creation screen and includes the following specifics:
  -  Removed selection confirmation button. Results are passed live using `ProductSelectorSharedViewModel`.
  - Variation selector screen is shown using dialog in the tablet mode. This makes the navigation more straightforward and contextual in tablet mode.
2. Updated toolbars implementation to match designs

Designs: 6kkCwI9VOEYcidp6UT5bln-fi-192%3A25891

### Testing instructions

Test the order creation screen:
* Verify that the toolbars match the designs
* Verify that products selected in the product selector are added to the order
* Verify that products removed in the Order Summary pane are automatically removed in product selector
* Verify that the product selector and variation selector work as before

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4527432/3dac84fd-489a-44cc-8c6e-bd5d5c434cc4

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          3 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>DeviceType</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add tests for class <code>ProductSelectorSharedViewModel</code> (or add <code>unit-tests-exemption</code> label to ignore this).</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>status: do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AnirudhBhat** [comment]
@samiuelson Thanks for working on this! While I couldn't review the code, I tested the functionality and found few things that can be fixed.

1. Variation selector dialog disappears on screen rotation


https://github.com/woocommerce/woocommerce-android/assets/1331230/d899bfc7-1782-4742-a2dd-2d80957350ac

2. There's still an option to add products from the order summary pane that takes us to product selector screen on a separate full screen

https://github.com/woocommerce/woocommerce-android/assets/1331230/443b3e06-5e61-4ec2-9914-d16a9506c75e

3. Product selector doesn't behave as expected when trying to add/remove products in a quick manner. Also, the selection/de-selection of products takes some time which could make the user believe the selection isn't working.


https://github.com/woocommerce/woocommerce-android/assets/1331230/622cf737-11c4-4879-9e4f-daeeec3b4951

4. Order summary screen's contents overlap in a split view 
Screenshot 2024-02-19 at 12 36 13 PM

**Comment by jd-alexander** [comment]
I did a first pass on the PR. I will have another review tomorrow.

**Review by jd-alexander — APPROVED** [review]
Code looks good and it works as expected per the testing instructions. The only minor comment I have is the divider, if we can do something here to be in alignment with the designs or if the thicker border was more in alignment with iOS design specifications. Let me know your thoughts. 
border

**Comment by samiuelson** [comment]
> Code looks good and it works as expected per the testing instructions. The only minor comment I have is the divider, if we can do something here to be in alignment with the designs or if the thicker border was more in alignment with iOS design specifications. Let me know your thoughts. !

Good point! I've added an [issue](https://github.com/orgs/woocommerce/projects/205/views/2?pane=issue&itemId=56083959&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status) to the project board and will add the divider in a separate PR.

**Pull request merged**
