### PR TITLE
Anitaa/navigation tests order detail info card

### LINKED ISSUE #179: Add Order Detail Tests: Customer Info Card
Tests for #137 

## Populating the Form
* [ ] Populating customer name
* [ ] Populating shipping details
* [ ] Populating billing details
* [ ] if `hasSeparateShippingDetails()` use shipping info, if not, use billing info.
* [ ] Address formatting for different locales
* [ ] Billing phone formatting
* [ ] Billing phone formatting for different locales
* [ ] Empty billing phone number

## Expand/Minimize View
* [ ] onLoad - view is condensed and `VIEW MORE` button is visible
* [ ] click `VIEW MORE`:
  * Expand to full view
  * Label change to `VIEW LESS`
* [ ] click `VIEW LESS`:
  * Condense view
  * Label changes to `VIEW MORE`

## Action Buttons
* [ ] email customer
  * test w/ no email
  * test w/ failure
* [ ] call customer
  * valid phone number
  * invalid phone number
  * missing phone number
  * error handling
* [ ] text customer
  * valid phone number
  * invalid phone number
  * missing phone number
  * error handling

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #179. This is PR number 3 for UI test and focuses on:

### Populating the Form
- [x] verify that customer info card labels are displayed correctly
- [x] Populating customer name, shipping address, shipping country
- [x] if `hasSeparateShippingDetails()` then billing address should be different from shipping address
- [x] Address formatting for different locales
- [x] Verify that billing email address is displayed correctly
- [x] Verify that billing phone is displayed correctly, if available. 
- [x] Handle empty billing phone number
- [x] Billing phone formatting for different locales

### Expand/Minimize View
- [x] `onLoad` - view is condensed and VIEW MORE button is visible
- [x] When VIEW MORE is clicked: expand to full view and label change to VIEW LESS
- [x] When VIEW LESS is clicked: condense view and label changes to VIEW MORE

### Action Buttons
- [x] email customer when intent is present
- [x] email customer when no activity is available to handle intent
- [x] Verify that popup is displayed with Call/Message items displayed
- [x] Verify that when `Call` item is clicked in popup menu, an intent to dial the number is called.
- [x] Verify that when `Message` item is clicked in popup menu, an intent to sms is called.

### To Test:
- [x] Run `OrderDetailCustomerInfoCardTest`

### CODE REVIEW

**Comment by anitaa1990** [comment]
For some reason, when running the tests individually they all pass but when running them in a suite the last two tests i.e. intent to email/call/message fails. Still debugging on why this is happening

**Comment by anitaa1990** [comment]
> For some reason, when running the tests individually they all pass but when running them in a suite the last two tests i.e. intent to email/call/message fails. Still debugging on why this is happening

This was found to be because Snackbar was being displayed (`Error fetching data` - because stats were no found for the mock site) and this meant Espresso could not identify the Popup menu. So the Popup menu was not opened. Fixed this by adding a mock presenter for `DashboardPresenter`, which meant we could mock the stats data and the Snackbar was no longer displayed.

**Comment by AmandaRiu** [comment]
@anitaa1990 Let me know when this PR is ready to review (or remove the "not ready for merge" label) and I'll pick it up. It looks like it currently has some merge conflicts.

**Comment by anitaa1990** [comment]
Merged all the UI test PRs into a single [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing this

**Pull request closed without merging**
