### PR TITLE
ExPlat integration

### PR DESCRIPTION
**Pull request by RenanLukas**
### ExPlat integration

Closes: 164-gh-woocommerce/woomobile-private

### Description

Integration with ExPlat will allow us to create experiments (e.g. A/B tests) in the project.

### Testing instructions

It's not possible to test the integration by itself since we don't have any experiments yet. 
To test if `ExPlat` instance is being provided properly:

1 - In the `ExperimentationModule`, inside the `provideExPlat` method, inject a mock `Experiment` in `experiments = setOf()`. e.g.:
```
experiments = setOf(object: Experiment {
            override val identifier: String = "test_experiment"
        })
```
2 - Inject `ExPlat` anywhere to test if the instance provided by `ExperimentationModule` is working. I've injected in `MainActivity` for testing. e.g.:
```
@Inject lateinit var exPlat: ExPlat
```

3 - Call `getVariation` using the same test `Experiment` identifier you've used in step `1`. e.g.
```
       val variation = exPlat.getVariation(
            object : Experiment {
                override val identifier = "test_experiment"
            }
        )
```
`variation` property `name` should be `control`:
image

4 - Call `getVariation` using a different identifier. e.g.
```
       val variation = exPlat.getVariation(
            object : Experiment {
                override val identifier = "test_experiment_2"
            }
        )
```

An exception should be thrown:
```
Caused by: java.lang.IllegalArgumentException: ExPlat: experiment not found: "test_experiment_2"! Make sure to include it in the set provided via constructor.
```

When we have real experiments, [here's an example](https://github.com/wordpress-mobile/WordPress-Android/pull/14286) by @renanferrari on how to test them using Charles proxy.

### Images/gif
N/A

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Depends on https://github.com/Automattic/Automattic-Tracks-Android/pull/121

### CODE REVIEW

**Comment by shiki** [comment]
@ThomazFB You don't need to review this if you don't want to. 

I'm gonna spend some time reading about ExPlat and checking if we can test this in the real world.

**Comment by ThomazFB** [comment]
Changes here looks good and following the steps described here everything works as expected. I'm now setting up a test experiment in Abacus and setting it up in the WCAndroid so we can verify everything end to end. After that, if everything goes well, I believe we can merge this PR 😄

**Review by ThomazFB — APPROVED** [review]
Tested using the `wcandroid_explat_config_test` experiment created to integrate with the work done here, had to do some quick adaptations but nothing too complicated, I think we can move forward with the solution introduced here. LGTM :shipit: 

Thank you @RenanLukas for your work to adjust the ExPlat to the WCAndroid! 🙇

**Comment by shiki** [comment]
Thank you, @RenanLukas and @ThomazFB for getting this merged!

**Comment by pmusolino** [comment]
@RenanLukas as far as you know, is it possible to use it also with non-logged users right now?

**Pull request merged**
