### PR TITLE
Merge 10.8 code freeze into trunk

### PR DESCRIPTION
**Pull request by spencertransier**
This contains the changes from completing the 10.8 code freeze:

- [X] Version bump
- [X] Release notes
- [X] Strings to be translated

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
- [x] New version header in `RELEASE-NOTE.txt` 
- [x] Version updates in `build.gradle`
- [x] `release_notes.txt` updated with notes from `RELEASE-NOTE.txt` for current version 
- [x] `strings.xml` updates via automation merging values from libraries
- [ ] Switched `ext` versions to stable releases

I noticed that [MediaPicker](https://github.com/wordpress-mobile/WordPress-MediaPicker-Android) is [pointing to its latest `trunk` commit](https://github.com/woocommerce/woocommerce-android/blob/624e1760a0443af62eb061500c253756a685b641/build.gradle#L117).

That's the version we had for a few release cycles now. Since 10.6 according to the GitHub information in [the commit](https://github.com/woocommerce/woocommerce-android/commit/0dc4d5e8fcb8e00aa16f6be274f0f1edc32b53f2).

image

I see there's now new stable release for MediaPicker. I wonder whether pointing to `trunk` without a new release is intentional. cc @hichamboushaba as the author of the version change commit.

I don't think the version usage is a blocker, as we've been using it for a couple of weeks already. Still, it would be good to address it if it was not an intentional change. As such, I disabled auto-merge before approving this.

**Comment by hichamboushaba** [comment]
> I see there's now new stable release for MediaPicker. I wonder whether pointing to trunk without a new release is intentional. cc @hichamboushaba as the author of the version change commit.

The trunk commit's goal is to bring the changes of this [PR](https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/pull/59).
I assumed the release manager would create a new MediaPicker release and update the version similar to what happens with FluxC, if I'm wrong in my assumption, please let me know, and I'll create a new release and update the version myself.

**Comment by spencertransier** [comment]
@mokagio Ah, sorry about that! As you can see in the Release Scenario, p8Qyks-3VC-p2, only `fluxCVersion`, `wordPressLoginVersion`, and `aboutAutomatticVersion` are mentioned. I didn't realize the other dependencies needed to be updated as well if they were pointing to a trunk commit (I made a note to update the RS template). 

I'm going to merge this for now to ensure the translations get into the weekly kit, then create another PR to update MediaPicker to a stable release.

**Comment by mokagio** [comment]
@hichamboushaba 

> I assumed the release manager would create a new MediaPicker release

That is correct.

---

@spencertransier 

> I didn't realize the other dependencies needed to be updated as well if they were pointing to a trunk commit.

To be honest, I _think_ that's the expected behavior, as it would be consistent with what we do in iOS, but I don't have a hard rule for it to link to. My guess is that not having the library in the release scenario was an oversight, but I could be missing something.

We'll discuss that with Android folks in the PR to update the template.

**Comment by spencertransier** [comment]
The PR for updating MediaPicker to the new `0.1.1` version is now up: https://github.com/woocommerce/woocommerce-android/pull/7585

**Pull request merged**
