### PR TITLE
issue/1695-add-product-list-loading-indicator

### LINKED ISSUE #1695: Products: Shows single entry in some cases
**Describe the bug**
Following a specific set of actions I'm able to get the product list to only show the first product. Force refresh reloads everything as expected.

**To Reproduce**
1. Click on Products. Verify the contents.
2. Click on Reviews.
3. Hit the Back button to pop back to the main screen.
4. Go back into the app. (My Store shows incorrectly, filing a separate issue for that).
5. Tap Reviews.
6. Tap Products.

**Screenshots**
Video: https://d.pr/v/BM7gsZ

**Expected behavior**
Products should show entire list on device.

**Mobile Environment**
Please include:
- Device: Pixel 2 XL
- Android version: 10
- WooCommerce Android version: 3.2-rc3

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #1695. 

#### Changes
- This tiny PR adds logic to display the PTR refresh indicator when the product list loaded for the first time.  
- Another change added to the PR was to stop the product list from loading more products when the product list is refreshing. This was because I noticed that when there is only one product in the list (which is loaded from the db), there is another `loadMore` products API call being initiated while the product list is still being fetched.

#### Screenshots
LEFT: before the fix . RIGHT: after the fix
 . 

#### Testing
- Click on any order with a product OR click on any product in the Top Earners tab. The product detail screen is displayed. 
- Click on Products tab now.
- Notice there is one product in the list and there is no loading indicator.
- Wait a while and the product list is loaded with the fetched data. 
- Pull changes from this PR and notice the refresh indicator displayed when the product is being fetched in the previous step.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
This works, but it also causes the progress spinner to appear every time the user returns to the product list from another child fragment or activity. I don't think we want that behavior.

**Comment by anitaa1990** [comment]
> This works, but it also causes the progress spinner to appear every time the user returns to the product list from another child fragment or activity. I don't think we want that behavior.

Yeah I should have mentioned that in the PR that this would work the same way orders and reviews do at the moment which is display the loading indicator each time the list is refreshed. I figured it's not a blocking behaviour and it might be less confusing that perhaps having the products refreshed but not knowing that it's getting refreshed. I'll try to brainstorm some ideas on how to workaround this 😄I can't think of any at the moment

**Comment by nbradbury** [comment]
> I should have mentioned that in the PR that this would work the same way orders and reviews do at the moment which is display the loading indicator each time the list is refreshed.

This doesn't appear to be the case. If I tap a product to view product detail, in this PR I see the loading indicator when I return to the product list. But if I tap an order to view order detail, I don't see the loading indicator when I return to the order list. Same goes for reviews.

**Comment by anitaa1990** [comment]
> This doesn't appear to be the case. If I tap a product to view product detail, in this PR I see the loading indicator when I return to the product list. But if I tap an order to view order detail, I don't see the loading indicator when I return to the order list. Same goes for reviews.

Bah! I had `do not keep activities` enabled so every time I clicked on `Settings` and came back in all tabs, the screen was refreshed. This same issue happens for reviews and orders as well. If there are one or two orders/reviews stored locally they are displayed first and then once the refreshed list is fetched, then the UI is updated. It's fine if there is a good internet connection but if network is slow, the gap between the updates is noticeable 🤔 

In any case, I've reverted the logic to display the refresh indicator each time but kept the logic to not load more products to the list while it is still refreshing to keep from calling the API twice.

**Pull request merged**
