### PR TITLE
[Mobile Payments] Use another pattern to determine installed plugin

### LINKED ISSUE #9458: [Mobile Payments] Use other pattern to determine installed plugin
Currently, we use both the folder and the name to identify if the plugin is installed, but this may not always be correct, sometimes, the plugin can be installed in another folder. We need to match only by the plugin name

pdfdoF-3pF-p2#comment-4637

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #9458

### Description

As discussed, the way we determine WCPay and Stripe plugins is not optimal and may not work on some sites. This PR make use only of the name part of the plugin, not the folder (which can be different)

The change may be risky so I'd like to ask 2 people to review/test that

pdfdoF-3pF-p2#comment-4619

### Testing instructions

Try IPP for both WCPay and Stripe plugins

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rossanafmenezes** [comment]
Hi @kidinov and @AnirudhBhat 

I have tested it and the app works after the changes with both Stripe and WCPay. To me, the changes look fine. That said, there are other places in the app that still use the old `WOO_PAYMENTS` and `WOO_STRIPE_GATEWAY` slugs, like the `HelpViewModel`.  Wouldn't that break with the plugin-related tags generated when a user creates a ticket from the app? 🤔

**Comment by kidinov** [comment]
> That said, there are other places in the app that still use the old WOO_PAYMENTS and WOO_STRIPE_GATEWAY slugs, like the HelpViewModel. 

@rossanafmenezes, that's a good catch! I implemented the same in `HelpViewModel`.  Do you see more places like that? I mean related to the IPP plugins?

9032b6bc186ac9d2581c770bd4d1a71c0d34b97d

**Comment by rossanafmenezes** [comment]
> > That said, there are other places in the app that still use the old WOO_PAYMENTS and WOO_STRIPE_GATEWAY slugs, like the HelpViewModel.
> 
> @rossanafmenezes, that's a good catch! I implemented the same in `HelpViewModel`. Do you see more places like that? I mean related to the IPP plugins?
> 
> [9032b6b](https://github.com/woocommerce/woocommerce-android/commit/9032b6bc186ac9d2581c770bd4d1a71c0d34b97d)

Hi @kidinov 

Not related to IPP. The only other mention I could find was on the `GetPaidViewModel` (related to store creation)

**Review by rossanafmenezes — APPROVED** [review]
LGTM but as you said, it would be probably good to have a second pair of eyes.

cc: @AnirudhBhat

**Comment by AnirudhBhat** [comment]
Quick update so that it doesn't look like there's no activity on this PR. There's a conversation going on around this PR in our internal Slack thread.  p1690217153057089-slack-C025A8VV728

**Comment by kidinov** [comment]
@AnirudhBhat is the convo about this PR? I thought that the issue happens on the trunk as well

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @kidinov LGTM :shipit:

**Comment by AnirudhBhat** [comment]
@kidinov 
> is the convo about this PR? I thought that the issue happens on the trunk as well

Yes. Approved the PR. We can fix the issue on a separate PR

**Pull request merged**
