### PR TITLE
issue/715-illegal-state-noordersview

### LINKED ISSUE #715: IllegalStateException: noOrdersView must not be null
```
Fatal Exception: java.lang.IllegalStateException: noOrdersView must not be null
       at com.woocommerce.android.ui.orders.OrderListFragment.showNoOrdersView(OrderListFragment.kt:386)
       at com.woocommerce.android.ui.orders.OrderListFragment.onQueryTextChange(OrderListFragment.kt:524)
       at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1180)
       at android.support.v7.widget.SearchView$10.onTextChanged(SearchView.java:1714)
       at android.widget.TextView.sendOnTextChanged(TextView.java:10611)
       at android.widget.TextView.setText(TextView.java:6024)
       at android.widget.TextView.setText(TextView.java:5847)
       at android.widget.EditText.setText(EditText.java:138)
       at android.widget.TextView.setText(TextView.java:5804)
       at android.support.v7.widget.SearchView.setQuery(SearchView.java:569)
       at android.support.v7.widget.SearchView.onActionViewCollapsed(SearchView.java:1277)
       at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.collapseItemActionView(Toolbar.java:2407)
       at android.support.v7.view.menu.MenuBuilder.collapseItemActionView(MenuBuilder.java:1370)
       at android.support.v7.view.menu.MenuBuilder.clear(MenuBuilder.java:594)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:453)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:55)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:655)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

[Crashlytics](https://fabric.io/automattic/android/apps/com.woocommerce.android/issues/5c3cd31af8b88c296343da8a)

### PR DESCRIPTION
**Pull request by nbradbury**
Resolves #715 by disabling the order search listeners when the order fragment's view is destroyed.

To test:
* Run `develop`
* Perform a search on the orders list
* Switch to the notifs tab
* BOOM!
* Run this branch, observe no boom :)

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by aforcier** [comment]
@nbradbury this is good to go, but there's a conflict in the release notes that needs to be addressed

**Comment by aforcier** [comment]
@nbradbury of course, my merging https://github.com/woocommerce/woocommerce-android/pull/714 just now created another conflict 🤦‍♂️

**Comment by nbradbury** [comment]
> my merging #714 just now created another conflict

I predict this is going to annoy us a lot with future PRs 🔮 

Anyway, conflict resolved and ready to go.

**Comment by aforcier** [comment]
:shipit:

**Pull request merged**
