### PR TITLE
Issue/6132 order creation long customer note

### LINKED ISSUE #6132: [Order Creation] Huge texts added as Customer notes doesn't collapse when displayed inside the Order Creation view
Summary
==========
Inside the Order Creation view, when a very long customer note is added, it shows the entire contents instead of collapsing the text to a maximum size to achieve a better navigation inside the creation form:

https://user-images.githubusercontent.com/3903757/161082448-0a5a7a10-1cb7-4662-a12a-ca2b254f7a68.mp4

Steps to Reproduce
==========
1. Go to the Order Creation view
2. Select to add a customer note and insert a huge text e.g. a Lorem ipsum.
3. Go back to the Order Creation view and verify that the view is displaying the full text instead of collapsing everything

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #6132 - this PR adds `WCReadMoreTextView` which automatically shows a "Read more" button after a specified number of lines, and this new component is used for the customer note during order creation.

To test:

- Add a large customer note during order creation
- Verify that a "Read more" button appears to display the entire note
- Replace the long note with a short one
- Verify the button no longer appears

long

short

### CODE REVIEW

**Review by rossanafmenezes — APPROVED** [review]
Hi @nbradbury !

It looks good to me. 

Screen Shot 2022-04-05 at 4 56 59 PM

Screen Shot 2022-04-05 at 4 57 11 PM

Screen Shot 2022-04-05 at 5 17 53 PM

It also works on older APIs like 24 (I have an M1 MBP so can't test on anything older than API 24)

Screen Shot 2022-04-06 at 5 59 05 AM

Screen Shot 2022-04-06 at 6 08 25 AM

Thank you @malinajirka for the second pair of eyes.

**Comment by nbradbury** [comment]
Thanks for the review, @rossanafmenezes! I'll update order detail to match and ping you when it's ready/

**Comment by rossanafmenezes** [comment]
Sounds like a plan

**Comment by nbradbury** [comment]
@rossanafmenezes This is ready for review now. I ended up not using the same "Read more" treatment for order detail because that screen's design is somewhat different. Instead I simply set `maxLines` for the order note and made it show an ellipses if it was cut off.

note

**Comment by rossanafmenezes** [comment]
Looks good to me. Merging!

unrelated to the PR, I noticed this on the order Detail screen:

Screen Shot 2022-04-06 at 14 46 03

It's extremely nitpicky, so not sure if it's even worth creating an issue for this, but regardless of the text, the number of lines, etc, the closing double quote is always added to the next line.

**Pull request merged**
