### PR TITLE
Jetpack CP: fetch site's metadata from the remote site directly

### LINKED ISSUE #5137: Jetpack CP: fetch site's metadata from the remote site
As discussed in p91TBi-6lK-p2, we need to implement a short term solution to fetch the site's metadata directly from the remote site, instead of relying on WPCom Cache site, this will happen only to sites that use Jetpack CP.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #5137

### Description
This PR updates FluxC to bring the changes that were discussed in p91TBi-6lK-p2 

### Testing instructions
1. You need a Jetpack CP site for the test.
2. Open the app.
3. Login to your Jetpack CP site.
4. Open the site, and then update the site's title.
5. Re-open the app (you may need to force-close the app before opening it to force trigger the site fetch call)
6. Confirm that the site's title has been updated.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hafizrahman** [comment]
Adding link to the relevant FluxC PR just to make searching easier: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2169

**Comment by hafizrahman** [comment]
I saw something a bit different after this step:

> Re-open the app (you may need to force-close the app before opening it to force trigger the site fetch call)

In my test, after I rename site in wp-admin:
1. Force close app, then start app again
2. At this point, the app still showing the old site name at the top under "My store",
3. If I move to a different tab (say, Orders), then go back to My Store, only then the new site name is shown.

Is that expected?

**Comment by hichamboushaba** [comment]
> In my test, after I rename site in wp-admin:
> 
> 1. Force close app, then start app again
> 2. At this point, the app still showing the old site name at the top under "My store",
> 3. If I move to a different tab (say, Orders), then go back to My Store, only then the new site name is shown.
> 
> Is that expected?

Yes, this is expected, and happens for sites that uses jetpack-the-plugin too, it happens because we launch the fetching on background, but we don't interact to it in the MyStore tab, we can fix it, but not part of this PR, and it's a minor issue IMO.

**Review by hafizrahman — APPROVED** [review]
Thanks for your reply @hichamboushaba , I agree that it's a minor issue and doesn't have to be part of this PR.

I'm pre-approving this PR, there's just a conflict to resolve. 👍🏼

**Pull request merged**
