### PR TITLE
Migrate to `ksp`

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR migrates build from `kapt` to `ksp`.

### How to test

Please smoke test the app (although CI checks should be just fine).

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>status: do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wzieba** [comment]
hi @atorresveiga ! 👋 😄 Are you okay with reviewing this PR?

**Comment by atorresveiga** [comment]
> hi @atorresveiga ! 👋 😄 Are you okay with reviewing this PR?

Sure @wzieba !

**Comment by atorresveiga** [comment]
@wzieba Is this ready for a review?

**Comment by wzieba** [comment]
Yes it is @atorresveiga ! Sorry for not marking it as such, thanks for asking 🙂

**Review by atorresveiga — APPROVED** [review]
Thanks for working on this @wzieba. I smoke tested the app and everything is working as expected.

LGTM! :shipit:

**Pull request merged**
