### PR TITLE
Dark Mode: Dashboard Stats card (old version)

### LINKED ISSUE #1578: Dark Mode: My Store - Stats Card
Implement dark/light mode for the Store Stats section of the My Store tab.

Screen Shot 2019-12-27 at 2 01 05 AM

Screen Shot 2019-12-27 at 2 01 24 AM

### PR DESCRIPTION
**Pull request by AmandaRiu**
Partially fixes #1578 by implementing new dark/light mode styling for the v1 Dashboard stats card.

* Amazingly `MPAndroidChart` doesn’t define any custom style attributes so styling this view at the theme level isn't possible yet. We can add these in the future however (recommended). 
* Due to the way MPAndroidChart sets `textSize`, I had to manually assign the text size for the x and y axis on the graphs instead of using a dimension resource.
* The `MPAndroidChart` component already adds alpha to whatever color you define as the highlight color. Because of this, I had to tweak the bar highlight color to something other than what was assigned in the designs so I could get to something relatively close.
* There is no current design for the old dashboard stats card so the tabs don’t follow the designs outlined in Figma (since the colors used in those tabs reflect the colors of the app bar.

The screenshots below show light and dark examples with first the "days" tab when the app loads (notice the "days" tab is now indented to reflect designs), as well as the "months" tab with a month bar selected.

### Light Mode

With a single bar selected:

### Dark Mode

With a single bar selected:

### CODE REVIEW

**Comment by AmandaRiu** [comment]
pinging @Garance91540 for a design review

**Comment by Garance91540** [comment]
@AmandaRiu , a few notes on my side:

- I think it's live in prod but normally the y axis is on the left (currently showing on the right side of the chart)
- the tab indicator should be purple in light mode
- I don't think there were designs for it so I just added them, but when there are refunds, we'll need to update the chart to add the zero x axis and negative value on the y axis: https://d.pr/i/oRIvYX
I'm assuming this will be a separate issue so I created a new item on Monday https://woocommerce.monday.com/boards/241066873/pulses/413942771

**Comment by AmandaRiu** [comment]
@Garance91540 Thanks for the design review!

> I think it's live in prod but normally the y axis is on the left (currently showing on the right side of the chart)

Ah, I can update that while Im at it. I couldn't find any designs for this card so I wasn't sure. 

> the tab indicator should be purple in light mode

Good catch! I'll get that updated. 



> I don't think there were designs for it so I just added them, but when there are refunds, we'll need to update the chart to add the zero x axis and negative value on the y axis: https://d.pr/i/oRIvYX
I'm assuming this will be a separate issue so I created a new item on Monday https://woocommerce.monday.com/boards/241066873/pulses/413942771

Yeah that wouldn't be relevant to this project to convert over to dark mode so I'd leave that as a separate issue altogether.

**Comment by AmandaRiu** [comment]
@Garance91540 Here's what it looks like now. Note that changing the `tabIndicatorColor` to use `colorPrimary` effects both dark and light modes. 

Screen Shot 2020-01-02 at 4 45 32 PM

**Comment by Garance91540** [comment]
looking 🔥

**Comment by AmandaRiu** [comment]
Design inspection has passed and now this PR is ready to be reviewed 👍

**Comment by nbradbury** [comment]
Some of the labels look very pale to me, making them hard to read.

colors

Plus, in the above screenshot notice how the Top Performer tabs are being cut off.

The colors for the new stats cards are also very pale:

device-2020-01-07-084830

**Comment by AmandaRiu** [comment]
@nbradbury Thanks for the review: 

> In dark mode some of the labels look very pale to me, making them hard to read.

All those labels are for cards that haven't been addressed by this PR. 

> The colors for the new stats cards are also very pale:

Same as above.

**Pull request merged**
