### PR TITLE
Merge "illustration and design updates" feature branch.

### PR DESCRIPTION
**Pull request by hafizrahman**
This feature branch contains the following updates, all of which have been tested and approved:

| # | Update | PR | What it does |
|- |- |- |- |
| 1. | Illustration updates| #3678 | Replaces various illustrations in the app (listed below) |
| 2. | Empty states design updates | #3879 | Various tweaks in empty state screen (listed below) |
| 3. | Empty Products screen FAB update | #3882 | Empty product screen now uses regular button instead of FAB to add new product (more details below) |

As functionalities have been tested in the PRs above, the review steps below only focus on the design element changes. cc @woocommerce/mobile-designers 

# To be reviewed:
## 1. Illustration updates:

| # | Case 	| Before 	| After: Light 	| After: Dark 	|
|- |-	|-	|-	|-	|
|1. | Empty Orders list: no order. Requires a test site with no order yet. Please note the string change as well. 	|  no-order-original | no-order-light | no-order-dark |
|2. | Empty Orders list: all fulfilled. Make sure the site has all orders with the "Completed" status. Probably easiest to create a new site, make one order, then set its status as "Completed". | all-order-fulfilled-original	|  all-order-fulfilled-light	|  all-order-fulfilled-dark	|
|3. | Order loading. This shows up when opening the "Orders" tab and the app is loading new Orders. | order-loading-original |  order-loading-light	|  order-loading-dark 	|
|4. | Empty search result. Use the search icon on top right of Orders screen, and enter a keyword that will have no result. |  no-result-original | no-result-light 	|  no-result-dark  	|
|5. | Empty reviews 	| empty-reviews-original  	|   empty-reviews-light |  empty-reviews-dark	|
|6. | Empty products 	|  no-products-original |  no-products-light 	| no-products-dark  	|
|7. | Jetpack required. For this, try logging in to a site with no Jetpack plugin. 	|  no-jetpack-original |  no-jetpack-light	| no-jetpack-dark |
|8. | Empty dashboard view	|image|image|image|
|9. | Missing analytics view	|image|image	|image|
|10. | "What is Jetpack?" login fragment	|image!| image | image|
|11. | "Sign in - Need WordPress" login fragment	|image	|image | image|
|12. | "Print Shipping label Info" view	|image |image |image	|

### Empty State Screen in Light Mode
|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Screen&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Changes&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|Before|After|
|-|-|-|-|
| Empty State Screen in Light Mode | Background color, headline styling, body text styling, button width. |image| image |
| "Not a WordPress site" screen | Spacing between image and text, body text styling |image |image|
| "Site needs Jetpack" screen | Content now vertically centered. |image|image|
|  "Print with your device" screen | Background color now white |image|image|

## Empty products screen:

| Before | After |
|-|-|
| image | image |

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@hafizrahman I assigned myself to review this and wanted to check if it needed design approval before I merge it. It looks like the previous PRs all passed design review so I'm guessing we're fine without one here?

**Comment by nbradbury** [comment]
This can be a separate PR, but it looks like we should audit how these screens appear in landscape. For example, the "No products" empty view gets cut off.

product-land

**Comment by Garance91540** [comment]
Hi @hafizrahman !

One note: all the CTAs that are not full width have the same width (197px) : https://d.pr/i/s92eJd

Thanks!

**Review by Garance91540 — APPROVED** [review]

**Comment by hafizrahman** [comment]
@nbradbury Thank you for the review! I made a separate issue for landscape mode empty screens: #4100 

Also I read your previous message but couldn't find it anymore. The three PRs mentioned at the beginning already involved functionality and design review. I just wasn't sure what's still needed when merging a feature branch like this, and thought it might be good to at least have a quick design review again in this PR. What do you usually do for merging feature branches?

**Comment by hafizrahman** [comment]
@Garance91540 

> One note: all the CTAs that are not full width have the same width (197px) : https://d.pr/i/s92eJd

Thank you for your note!  In the original PR, I had initially set the button with to be a fixed `197dp` value which will be the equivalent of `197px`, but then @anitaa1990 suggested [in her review here](https://github.com/woocommerce/woocommerce-android/pull/3879#discussion_r621987117) a modification because the way we implemented widths in the app is different and it's not recommended to set a fixed value like I initially did.

If I understand correctly, the modification helps ensure the app can adapt to multiple screen sizes, while at the same time the result (in portrait mode) is can still be close to the original `197px` value in the design.

**Comment by nbradbury** [comment]
> I just wasn't sure what's still needed when merging a feature branch like this, and thought it might be good to at least have a quick design review again in this PR. What do you usually do for merging feature branches?

Usually when a feature branch is submitted and all its PRs have been reviewed, we simply merge the feature branch with minimal testing. A final design review isn't usually necessary if all PRs have already been approved by a designer.

In this case, I took it for a simple test run and noticed the landscape issue and wanted to make sure it was tracked, but I'm good to merge this PR as-is if you give me a thumbs up.

**Comment by nbradbury** [comment]
> I had initially set the button with to be a fixed `197dp` value which will be the equivalent of `197px`, but...it's not recommended to set a fixed value like I initially did.

I agree with that. Given the number of screen sizes for Android devices, setting a fixed size isn't the best practice. Nothing needs to change in this PR, but if this comes up again I recommend using `app:layout_constraintWidth_percent` in constraint layouts to limit the width to a percentage of the screen.

**Comment by Garance91540** [comment]
> Thank you for your note! In the original PR, I had initially set the button with to be a fixed 197dp value which will be the equivalent of 197px, but then @anitaa1990 suggested in her review here a modification because the way we implemented widths in the app is different and it's not recommended to set a fixed value like I initially did.

If I understand correclty, the modification helps ensure the app can adapt to multiple screen sizes, while at the same time the result (in portrait mode) is can still be close to the original 197px value in the design.

Thanks for the context @hafizrahman !
I'm ok not setting a fixed width, but I think we should have at least a set minimum width of 160px) to avoid [screens like this](https://d.pr/i/VrDXiq)

**Comment by Garance91540** [comment]
It also seems like for some screens the background color is still too dark:

Screen Shot 2021-05-28 at 2 32 30 PM

(the 3 first screens seem to have the right colors but the screens after seem of a different color)

Here are the designs:

**Comment by AliSoftware** [comment]
Code freeze for 6.8 happening today, so I'm moving the milestone to 6.9.

**Comment by anitaa1990** [comment]
Since Nick is aafk I took over the review for the PR. Given that this PR has been hanging around for a while @Garance91540 what do you think about fixing the button width issue in another PR?

@hafizrahman, there are a bunch of merge conflicts in this PR and once that is fixed, we can :shipit:

**Comment by hafizrahman** [comment]
@Garance91540 
> It also seems like for some screens the background color is still too dark:

Ah, I apologize for the confusion! I copied the images with too dark bg color from the first PR for "[1. Illustration updates](https://github.com/woocommerce/woocommerce-android/pull/3678)", and when they were created, the dark bg color issue hadn't been tackled yet. My intention for those screenshots was to ask to focus on the illustration change only, but I failed to mention that other elements might be inaccurate in those screenshots.

The bg color issue has since been resolved on the second PR "[2. Empty States Design Updates](https://github.com/woocommerce/woocommerce-android/pull/3879)", where the bg is set to Gray 0 (`@color/woo_gray_0` which translates to #F6F7F7 in light mode), so I think we're good to go here.

**Comment by hafizrahman** [comment]
@anitaa1990 Have fixed conflicts, and updated release note as well.

**Review by anitaa1990 — APPROVED** [review]

**Pull request merged**
