### PR TITLE
Release 21.1 update changelog

### PR DESCRIPTION
**Pull request by atorresveiga**
Following the steps of the code freeze process. Update release notes to a more readable format.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR has the <code>Releases</code> label: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by irfano — CHANGES_REQUESTED** [review]
> We've disabled order editing for transactions with currencies different from your store's

This sounds like a downgrade. I know we fixed an issue by disabling it, but we could phrase it differently.
Also, `3/4` sounds too technical. I updated some part of the note. WDYT?


> Our latest update brings key enhancements to streamline your WooCommerce experience! We’ve fixed editing permissions for orders in different currencies, optimized the payments hub view, enabled easy receipt sharing via Google SMS, and fixed date range selection to correctly use your timezone. Enjoy smoother operations!

**Comment by atorresveiga** [comment]
> We've disabled order editing for transactions with currencies different from your store's
> 
> This sounds like a downgrade. I know we fixed an issue by disabling it, but we could phrase it differently. Also, `3/4` sounds too technical. I updated some part of the note. WDYT?
> 
> Our latest update brings key enhancements to streamline your WooCommerce experience! We’ve fixed editing permissions for orders in different currencies, optimized the payments hub view, enabled easy receipt sharing via Google SMS, and fixed date range selection to correctly use your timezone. Enjoy smoother operations!

Thanks for the review @irfano. Fixed [here](https://github.com/woocommerce/woocommerce-android/pull/12900/commits/567133862be0903babac91c89aa5e14e6095b032)!

**Review by irfano — APPROVED** [review]
Thanks for updating it. LGTM! 👍🏻

**Pull request merged**
