### PR TITLE
Issue/6928 order metadata UI

### LINKED ISSUE #6928: [Order Meta Data] Add UI to display a list of order metadata in Order Details screen
Related [iOS issue](https://github.com/woocommerce/woocommerce-ios/issues/7241) and [PR](https://github.com/woocommerce/woocommerce-ios/issues/7241)

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #6928 

This PR implements the "custom fields" UI which displays an order's viewable metadata. To test:

* Open order detail for an order that has viewable metadata and ensure the "View custom fields" button appears and that clicking it correctly shows the metadata
* Open order detail for an order that does **not** have viewable metadata and ensure the above button doesn't appear

Note that at this point individual items in the custom field list aren't actionable - that is, clicking on them does nothing, hyperlinks aren't enabled, HTML is shown raw, etc. These may be considered for future PRs.

https://user-images.githubusercontent.com/3903757/178741705-38dfef9e-1017-4312-aefb-458ba87a085a.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@ThomazFB There's currently an issue with this PR that I'd prefer to handle separately. I had thought order detail always fetches the order, but it turns out this isn't the case. This means that there may be no stored metadata for the order even though the actual order has some.

I can think of a few solutions:

1. Always fetch the order. This would work, but I'm not wild about fetching unnecessarily since we don't do that currently.
2. In [this FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2467), I can update the migration to clear the order table. This would also work, but it wouldn't help us if order metadata changes and the order isn't re-fetched in order detail.
3. Go back to our original idea of a separate request to fetch the metadata.

Regardless of the solution, I think this PR is ready for review.

**Comment by ThomazFB** [comment]
@nbradbury the feature is looking good! I've tested it by integrating it with my current draft [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2469), and everything worked smoothly! Nice work with this view!

I've just one question regarding big texts. On the iOS side, we're displaying everything inside the key and value, so for the lorem ipsum metadata, everything is displayed there:

| Android  | iOS |
| ------------- | ------------- |
| Screenshot_20220714_010211 | Simulator Screen Shot - iPhone 13 Pro Max - 2022-07-14 at 00 59 23 |

Do you think we should do the same here? Since it's a dedicated view, we may have room to display everything regardless of the size. Also, pinging @rachelmcr since this would be a design decision for us.

Order details data fetching
==========

> There's currently an issue with this PR that I'd prefer to handle separately. I had thought order detail always fetches the Order, but it turns out this isn't the case. This means there may be no stored metadata for the Order even though the actual Order has some.

Regarding this point you mentioned on fetching the Order, my perspective here is: Maybe the Order Details should be the view responsible for controlling when to update the Order or not, metadata included, since the Custom Fields view is a "child" list of the details itself. 

This fetching limitation would also be true for everything else displayed inside the Order Details, right? I mean, the Order Details sometimes requires the user to do a swipe down to force a refresh to get the most recent data, and I wonder if there's a specific reason why that view doesn't do that because it feels like this is the root of the issue. 

I'm also wondering if the metadata shouldn't be bound to the Order it belongs to. So I'm asking myself: if we do a side load of the metadata and leave the Order outdated, could it cause a scenario where the metadata reflects stuff that's still not displayed in the Order Details?

But in case we can't work with a proper solution for the Order Details, I believe the third point you listed could be a simple solution. Maybe with that we could do a metadata side load when entering the Custom Fields view, WDYT?

**Comment by nbradbury** [comment]
> On the iOS side, we're displaying everything inside the key and value, so for the lorem ipsum metadata, everything is displayed there:

I've never liked showing lengthy text in lists as it requires extra scrolling. On Android we could use a [WCReadMoreTextView](https://github.com/woocommerce/woocommerce-android/blob/72f6192517cd45eefa8d618cd7490c476a3f5418/WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCReadMoreTextView.kt) for the value, which shows a "Read more" button when the text goes beyond a set number of lines.

**Update:** in [58e7262](https://github.com/woocommerce/woocommerce-android/pull/6937/commits/58e726244a52d40c3efedee076cfb916fd87d578) I removed the `maxLines` to be consistent with iOS. We can revisit this later.

> if we do a side load of the metadata and leave the Order outdated, could it cause a scenario where the metadata reflects stuff that's still not displayed in the Order Details?

Very good point! Given this - plus the fact the order may show outdated information in the detail screen - perhaps we should always fetch the order?

**Review by ThomazFB — APPROVED** [review]
>I've never liked showing lengthy text in lists as it requires extra scrolling. On Android we could use a [WCReadMoreTextView](https://github.com/woocommerce/woocommerce-android/blob/72f6192517cd45eefa8d618cd7490c476a3f5418/WooCommerce/src/main/kotlin/com/woocommerce/android/widgets/WCReadMoreTextView.kt) for the value, which shows a "Read more" button when the text goes beyond a set number of lines.

> Update: in [58e7262](https://github.com/woocommerce/woocommerce-android/pull/6937/commits/58e726244a52d40c3efedee076cfb916fd87d578) I removed the maxLines to be consistent with iOS. We can revisit this later.

Oh, thanks for adjusting this! I've no strong preference on this one, and not sure if we should support bigger texts or not, I don't even know if they exist 😅, but I guess we can stick with the consistency as you mentioned. Thanks!

 >Very good point! Given this - plus the fact the order may show outdated information in the detail screen - perhaps we should always fetch the order?

I agree! But maybe we could do it in an optimistic way? The Order Details have this great advantage of opening immediately after being selected in the Order List. We could make a side fetch request, and when it returns, we compare if the fetched one is different from the current one. I believe this is already the case for some sections of the details view 🤔 

Anyway, I'm approving this PR.

**Comment by rachelmcr** [comment]
I also don't have a strong preference about the longer text. I have a slight preference toward showing more information rather than less for this iteration, but it makes sense to me to revisit if we make tweaks to the UI in a future iteration. Thanks!

**Pull request merged**
