### PR TITLE
Update FluxC version to contain `_fields` in fetch orders by ids

### PR DESCRIPTION
**Pull request by wzieba**
Please check: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1990 for details.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by wzieba** [comment]
@nbradbury I've merged `develop`, it's ready for review. Thanks!

**Comment by nbradbury** [comment]
@wzieba There's a strange "dependabot" problem that's causing a failing check.

**Comment by wzieba** [comment]
True @nbradbury , it's addressed here: https://github.com/woocommerce/woocommerce-android/pull/3960#issuecomment-833359297 and soon we should expect fix for that.

This PR won't change anything about Dependabot, that's just false positive.

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
