### PR TITLE
chore: delete shared library

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR removes all configuration needed to run React Native shared library. It reverts all changes introduced in https://github.com/woocommerce/woocommerce-android/pull/9386.

### Testing instructions

No need.

### Images/gif

Because React Native setup was introducing many native libraries, we can observe a big decrease in .apk size:

| Before | After | 
| --- | --- |
| image | Screenshot 2023-09-29 at 12 41 38 |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by wzieba** [comment]
@ThomazFB , as you reviewed the PR that introduced React Native, do you mind reviewing this PR as well? 🙂

**Review by ThomazFB — APPROVED** [review]
Looks good! Thanks for looping back with this, @wzieba!

**Comment by Ecarrion** [comment]
@wzieba Should we also delete de `SHIPPING_ZONES` feature flag I disabled [here](https://github.com/woocommerce/woocommerce-android/pull/9805/files)?

**Comment by wzieba** [comment]
Thanks @Ecarrion ! https://github.com/woocommerce/woocommerce-android/pull/9885

**Pull request merged**
