### PR TITLE
Issue/1801 empty states search

### PR DESCRIPTION
**Pull request by nbradbury**
This is the first PR for #1801, which changes the empty views for order list search and product list search. A few things to note:

* These changes affect the other empty views in the app, but those will be changed in separate PRs
* The vector image for search lost some detail after being imported into Android Studio, and this will likely happen to other vector images added later in this project. I'll address those all at once, when I have a better idea of how to retain the detail.

@AmandaRiu Hope you don't mind, but I've assigned this to you since you're most familiar with the order list.

Screenshot_1578583904

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
> all looks good, the only thing I found was that the background colors for the container holding these images is wrong.

@AmandaRiu Thanks, not sure why I didn't see that! Fixed in c6e2b42.

**Comment by AmandaRiu** [comment]
@nbradbury that fixed products empty search, but the orders version is still white.

**Comment by nbradbury** [comment]
> that fixed products empty search, but the orders version is still white.

Drat. Fixed in bf17ce1.

**Comment by nbradbury** [comment]
> orders looks good, but products is now missing it's text alignment 🤷‍♀

I made only a background color change in that last commit, so that is...bizarre. And I can't repro that at all, even on an API 29 device. Any chance something got accidentally changed on your end?

Screenshot_1578603762

**Pull request merged**
