### PR TITLE
Merge 8.9 code freeze to trunk

### PR DESCRIPTION
**Pull request by oguzkocer**
Besides the usual commits by `fastlane` lanes, I've updated `fastlane` to `2.205.1` in 7e2be57c40ad5659ed68516022e16d8e5f9f0f70.

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
- [x] New version header in `RELEASE-NOTE.txt` 
- [x] Version updates in `build.gradle`
- [x] `release_notes.txt` updated with notes from `RELEASE-NOTE.txt` for current version 
- [x] `strings.xml` updates via automation merging values from libraries

As part of my release cycle PRs review checklist, I have an item about updating the internal libraries. That does not appear in this diff, because it happened already in a dedicated PR: https://github.com/woocommerce/woocommerce-android/pull/6161

Out of curiosity: Looking at our internal release scenario checklists, I don't understand whether the dedicated PR is the default approach or was it a one-off process variation?

Regardless, _ship it_ :shipit:

**Comment by oguzkocer** [comment]
@mokagio The dedicated PR was necessary in this case, because our tooling is not able to download strings from a commit hash and requires a tagged version instead. Since the `code_freeze` lane is handling that download, the login library version update needed to happen before the code freeze. (the FluxC update was combined out of convenience)

We had a discussion about this on Slack and will move the string download to `complete_code_freeze` lane to remove this requirement.

Hope that clarifies it for you!

**Comment by AliSoftware** [comment]
> We had a discussion about this on Slack

@mokagio for refs: p1649098672473969/1649098139.783629-slack-C02KLTL3MKM

**Comment by mokagio** [comment]
Thanks @oguzkocer @AliSoftware 👍

**Pull request merged**
