### PR TITLE
[Woo POS] Hide cart when payment succeed

### LINKED ISSUE #11867: [Woo POS] Hide cart when payment succeed
Now we show cart on the left

Image

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #11867

### Description

Adds animation and small code improvements to the home screen

### Testing information

* Collect payment -> notice that payment success screen is full screen and has 1 card in it (not 2 as before)
* Test other cases -> going back from there, new transactions and so on

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/ff9542df-b3f9-4a1b-996a-e2815bcc064e

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          3 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>Checkout</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/224">19.4</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by backwardstruck — APPROVED** [review]
Tested and code changes look good. I'll have it rebuild since it's not currently passing CI.

Screenshot_20240702_122042

**Comment by kidinov** [comment]
@backwardstruck Thanks for the review!

>  I'll have it rebuild since it's not currently passing CI

It doesn't pass the CI because of the "do not merge" tag - to prevent from merging. You can click on the "details" next to the failed job to see why it didn't pass

**Comment by backwardstruck** [comment]
> @backwardstruck Thanks for the review!
> 
> > I'll have it rebuild since it's not currently passing CI
> 
> It doesn't pass the CI because of the "do not merge" tag - to prevent from merging. You can click on the "details" next to the failed job to see why it didn't pass

Indeed, thanks!

**Pull request merged**
