### PR TITLE
Dark Mode v2: What is jetpack dialog tweaks

### LINKED ISSUE #2329: Dark Mode v2: What is jetpack dialog
Minor design tweaks needed for this dialog

#### Design 

Screen Shot 2020-04-27 at 6 27 42 PM

### Needs updating:
* Image background color:
	* light: #F7F7F7
	* dark: Gray 80 (#2c3338)
	* paddingTop = `30dp`
* Body = OnSurfaceHigh

### PR DESCRIPTION
**Pull request by AmandaRiu**
Closes #2329 by implementing the following minor UI tweaks:

- updated body text color
- updated image background color

**NOTE:** Requires design review before merge

### Designs

Screen Shot 2020-04-27 at 6 27 42 PM

### Implementation

Before | After
-- | --
Screenshot_1588045430|Screenshot_1588118104
Screenshot_1588045436|Screenshot_1588045499

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — CHANGES_REQUESTED** [review]
Hi Amanda! These illustrations look great. I have one quick comment about the text padding, could we adjust it as follows: https://d.pr/i/EmtVI2 ? Thank you!

**Comment by AmandaRiu** [comment]
@Garance91540 Updated the padding in the dialog. It's tricky because these are buttons, not just text, so I had to tweak it to figure out a _relative_ padding around the buttons. The "OK" may look off, but that's just because there is a minimum width of the button, but if the language were changed and the text longer, you'd see that the button padding there would also be 24dp. For example:

Screen Shot 2020-04-28 at 10 54 45 AM


Here are the updated screenshots:

Light | Dark 
-- | --
Screen Shot 2020-04-28 at 10 51 31 AM|Screen Shot 2020-04-28 at 10 51 17 AM

**Review by Garance91540 — DISMISSED** [review]
Looking good! 👏

**Comment by AmandaRiu** [comment]
Ready for review + merge! 🥳

**Review by anitaa1990 — APPROVED** [review]
Changes look good! Tested in API 21, 23, 28 and 29. There are some merge conflicts in the code. Once it's fixed, we can :shipit:

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
