### PR TITLE
[Dashboard] Add corruption handlers to Data Stores using Protocol Buffer schemas.

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
This is a follow-up to https://github.com/woocommerce/woocommerce-android/pull/12891, where reverting the Data Store library upgrade didn't clear the corrupted files to some users. We verified that the corruption exception we're getting is very likely to be connected with a parsing failure of the Protocol Buffer schemas we have in the app, affecting two Data Stores: `Dashboard` and `CustomDateRange`. 

This PR adds a corruption handler to the DataStore creation, which simply restarts the DataStore with the default instance of each schema.

How to Test
==========
There's no defined step to reproduce this crash; it's caused by a DataStore library bug that's not clear when and how it occurs. Also, we reverted the version causing this problem. Testing here should focus on making sure that the Dashboard and Custom date range of the My Store are both working as expected and didn't introduce any regression.

The solution ability to fix the problem will be tested by monitoring crashes from Sentry.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Review by malinajirka — CHANGES_REQUESTED** [review]
Thanks for working on this @ThomazFB!

I have been able to reproduce the exception by modifying the file manually. I can confirm this PR fixes the issue. 🥳 

If you want to give that a try, copy [this file](https://cloudup.com/c6YYEbOIyyj) to the device `/data/data/com.woocommerce.android.dev/files/datastore`.
1. Open Dashboard
2. Edit the custom range for `Most active coupons` card
3. Tap on Save 💥 

However, I would like to suggest a couple changes for consideration:
1. I think we might want to consider targeting the beta branch to ensure the fix is available to the users ASAP.
2. The most important one: I believe we need to manually track the crash to Sentry in the cases in which we recover with a non-fatal error => otherwise, if we break the app (eg. when we update the library) and the preferences will be recreated on each startup, we won't know about this issue.
3. I'd personally consider adding this corruption handler to all DataStore instances. Unless there is a specific reason why we want to target only the ones which have been crashing.

Let me know what you think.

**Comment by ThomazFB** [comment]
Amazing idea for testing the crash @malinajirka! 👏 Much better to move forward knowing that this will truly fix the problem 😄 Thank you so much for that! 🙇 

>I think we might want to consider targeting the beta branch to ensure the fix is available to the users ASAP.

Agreed! Now that we're even more confident that this will solve the issue, we should aim to deliver this as a hotfix.

>The most important one: I believe we need to manually track the crash to Sentry in the cases in which we recover with a non-fatal error => otherwise, if we break the app (eg. when we update the library) and the preferences will be recreated on each startup, we won't know about this issue.

Yes, I'll adjust this PR to contain a track to Sentry for every single DataStore using the Protocol Buffer 🫡 

>I'd personally consider adding this corruption handler to all DataStore instances. Unless there is a specific reason why we want to target only the ones which have been crashing.

Personally, I believe we can only target DataStores using the Protocol Buffer with the handler. The Corruption Handler requires us to provide a replacement data when the problem happens, but the other DataStores use the `Preferences` class as the access the data, which is the default schema-less structure offered by the library. Unfortunately, this DataStore internal version of the Preferences is adjusted to be only provided by the Library and we can't access the implementation constructor. 

Also, since the Corruption Handler must return the replacement data when it's called, we can't leave it there just as a listener to report issues to Sentry and suppress the crash.

**Comment by malinajirka** [comment]
> Personally, I believe we can only target DataStores using the Protocol Buffer with the handler. The Corruption Handler requires us to provide a replacement data when the problem happens, but the other DataStores use the Preferences class as the access the data, which is the default schema-less structure offered by the library. Unfortunately, this DataStore internal version of the Preferences is adjusted to be only provided by the Library and we can't access the implementation constructor.
> Also, since the Corruption Handler must return the replacement data when it's called, we can't leave it there just as a listener to report issues to Sentry and suppress the crash.

I saw this piece of code on one of the blogposts. Do you think it could work?
```
corruptionHandler = ReplaceFileCorruptionHandler(
            produceNewData = { emptyPreferences() }
        )
```

**Comment by ThomazFB** [comment]
I initially dropped the idea of using the `emptyPreferences` call after I noticed that the DataStore implementation `readData` was already resorting to using the `serializer.defaultValue` (which is a call for a new emptyPreferences in the `PreferencesSerializer` instance), but after your mention over using it on the Corruption Handler I double-checked and noticed this is exclusive to the `FileNotFoundException`, and only when the file doesn't exist, so it doesn't serve for Corruptions 😅 

image


So yes, I think your example should be our default handling here, let me adjust it. Thanks, @malinajirka 🙇

**Comment by ThomazFB** [comment]
@malinajirka I added your suggestions following our discussion, but I had to open a separate PR cherry-picked from this branch since this one here started from trunk after the `21.2` code freeze.

This is the new PR: https://github.com/woocommerce/woocommerce-android/pull/13058

**Pull request closed without merging**
