### PR TITLE
Dark Mode: Dialogs

### LINKED ISSUE #1995: Dark Mode: Apply dialog theme to dialogs across the app
List of dialogs can be found here: https://github.com/woocommerce/woocommerce-android/issues/1869

### PR DESCRIPTION
**Pull request by AmandaRiu**
Closes #1995 by implementing material components and dark/light theming to all the dialogs in the app **except** for the following:
- `WCProductPropertyReadMoreView.kt` since @0nko is working on those views
- Login > What is Jetpack? - both login dialogs will be converted during the login project
- Login > Email help

## Screenshots
Click image to view full size

Before | After (light) | After (dark)
--- | --- | ---
Upload Method Selector
upload-method-before|upload-method-light|upload-method-dark
Updating Product dialog
updating-product-before|updating-product-light|updating-product-dark
Support Email dialog
support-email-dialog_before|support-email-dialog_light|support-email-dialog_dark
Support Email dialog (text input focused)
support-email-dialog_beforeFocused|support-email-dialog_lightFocused|support-email-dialog_darkFocused
Stock status selector
stock-status-before|stock-status-light|stock-status-dark
Refunds - select quantity
select-quanitity-before|select-quantity-light|select-quantity-dark
Rate Woo
--- |rate-woo-light|rate-woo-dark
Confirm remove product image
confirm-remove-image-before|confirm-remove-image-light|confirm-remove-image-dark
Confirm Refund
confirm-refund-before|confirm-refund-light|confirm-refund-dark
Confirm logout
confirm-logout-before|confirm-logout-light|confirm-logout-dark
Confirm discard note
confirm-discard-note-before|confirm-discard-note-light|confirm-discard-note-dark

## To Test
Verify views on API 21, 28, and 29

### CODE REVIEW

**Comment by Garance91540** [comment]
Hi @AmandaRiu ! Everything looks good, but I have a question regarding the quantity picker. Curious to know why you chose a different one than [what we currently have](https://d.pr/i/ru9IL0)?
I find it lighter than the new ones which display thick horizontal separators.

**Comment by AmandaRiu** [comment]
@Garance91540 

> Curious to know why you chose a different one than what we currently have?
I find it lighter than the new ones which display thick horizontal separators.

I just went with the default material style for the component since I couldn't find a style for it in Figma - not even in the component or sticker sheets for dark/light themes. Very odd....you'd think it'd be in the template. Anyway, I'm happy to update it and remove the horizontal bars 👍 Thanks for the review!

**Comment by AmandaRiu** [comment]
@Garance91540 

Updated! Here's how it looks now:

**Comment by Garance91540** [comment]
> I just went with the default material style for the component since I couldn't find a style for it in Figma - not even in the component or sticker sheets for dark/light themes. Very odd....you'd think it'd be in the template. Anyway, I'm happy to update it and remove the horizontal bars 👍 Thanks for the review!

Yes I also looked for it, but when looking at other Android apps what I realized is that this is quantity picker is actually more a iOS than a Material pattern. From what I've seen in Material, it's more a minus and plus icon around the number. https://d.pr/i/GEiHM5 But since it's not an "official" pattern, I think we are good using what you implemented!

**Comment by AmandaRiu** [comment]
@0nko I think that should be fine. It's a very old version of Android and hopefully we'll drop support for it sometime in near future.

**Pull request merged**
