### PR TITLE
Search in cache first on ProductSelection screen

### PR DESCRIPTION
**Pull request by malinajirka**
`Do not merge label` - remove after [the FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2662) is merged and the reference is updated in build.gradle. 

This is still a draft but I'd like to know your opinion about the approach. I'll turn it into a proper PR when this approach is agreed on or close the PR if we opt for a different approach.

### Description

This PR adds support for local search to the ProductSelectorScreen. This screen is currently being used only in the Coupons flow, however, we plan to start using it in the Order Creation flow - the main aim of this PR is to reduce the time it takes to create an order.

The solution isn't perfect, but imo it gives us 90% of the functionality with minimal effort. 

`Caveat #1`
Imagine the following scenario:
1. User opens the search and enters a query
2. The app shows 25 products from the cache
3. The app initiates a request to fetch 25 search results from the server
4. The user scrolls to the bottom of the list
5. The app WILL NOT load more data from cache until request from step 3 completes successfully. 

This is a limitation of this solution, but I personally believe it's safe to assume that in most cases users who use search will enter enough letters so there are less than 25 results shown. Moreover, if the request completes, more data are loaded from the database. So the impact of this caveat is imo minimal. (implementing a proper solution isn't trivial)

`Caveat 2`
Products which are fetched after the products from cache are already shown are always appended to the bottom of the list - the products don't have any specific order. However, this feels better than changing the order of the products "under users' hands". Wdyt?

`Caveat 3`
Page 1 from the cache might not correspond to Page 1 from the server, but similar as in Caveat 1, I think even without it, it's an improvement and I assume most users will enter enough characters anyway. 

This PR also improves the current implementation of the search screen as it cancels previous requests when the user updates the search query -> previously, the app would wait for the previous request to complete before it initiated a new request.

This PR doesn't add any unit tests since the whole feature unfortunately isn't tested. I think it'd be nice to add tests for it, but that's out of the scope of this PR.

### Testing instructions

(You might need to hardcode `isCouponsEnabled=true` in `MoreMenuViewModel` in order to enable the feature)
1. Open More Menu
2. Tap on Coupons
3. Select a coupon
4. Tap on the overflow menu
5. Select Edit coupon
8. Tap on "Edit Products"
9. Test the search - you might want to try adding `delay(5000)` or changing the size of the page or generating a bunch of products on your site using [a plugin](https://wordpress.org/plugins/woocommerce-product-generator/). Make sure loading indicator is shown whenever a request is in progress - either during loadMore or when the search query changes.

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by kidinov** [comment]
@malinajirka 

Overall it works fine! Some improvements may be done though

Many points from here are not related to the PR
* It looks like that search in the cache is only by NAME (**no SKU** which is important I think), while remote search matches also by the description that's why combining those result don't really work. I can perform the same search 2 times, and the results will be different. We won't find in the local cache the products found in the remote search
* It looks like that we don't show descriptions anywhere, but the remote search matches on it. It's confusing to see some products that visually have nothing to do with the entered query
* It's very hard to unselect one specific product if it's somewhere at the bottom of the list. And if you don't remember its name you can not search for it as well. Maybe the button "show selected" would be useful
* User can put a new line symbol in the search field
* In the dark mode carriage in the search field is black, which looks wrong

**Comment by malinajirka** [comment]
Awesome, thanks so much for the review @kidinov !

> It looks like that search in the cache is only by NAME (no SKU which is important I think)

I looked into this yesterday and the remote endpoint doesn't currently support searching by SKU and Title/Description within one request. We'd have to send two requests which would complicate other things. So I intentionally omitted SKU search. Having said that, I think we should implement it at some point. 

One solution would be to use the same approach we use on Product List - have a separate tab for SKU search. That's easy to implement, but the UX isn't optimal. Probably a better approach is to modify the endpoint so it support searching by title+desc+sku within one request - something @toupper and I discussed yesterday.

> while remote search matches also by the description

I forgot about this, I'll update fluxc to match by description as well.

> It looks like that we don't show descriptions anywhere, but the remote search matches on it. It's confusing to see some products that visually have nothing to do with the entered query

I feel like this is a pretty common behavior that search matches by things that are not directly visible and might not make sense at first sight. I think we can stay consistent with the web for now and possibly change it if we receive negative feedback on the search results, wdyt?


> It's very hard to unselect one specific product if it's somewhere at the bottom of the list. And if you don't remember its name you can not search for it as well. Maybe the button "show selected" would be useful

Yeah, I see what you mean. However, I'm wondering how common is unselecting a product in order creation use case. Also worth noting is that the user can change quantity to `0` on the order creation detail screen. I'd personally not optimize for this scenario right now, wdyt?

> User can put a new line symbol in the search field
> In the dark mode carriage in the search field is black, which looks wrong

Nice catches, I'll submit issues and we can fix them in a separate PR to keep this PR focused.

**Comment by kidinov** [comment]
@malinajirka 

> I looked into this yesterday and the remote endpoint doesn't currently support searching by SKU and Title/Description within one request. We'd have to send two requests which would complicate other things. So I intentionally omitted SKU search. Having said that, I think we should implement it at some point.

Can we add SKU matching in the local search part? It will make things confusing though, so not sure if it's a good temporary workaround

> I feel like this is a pretty common behavior that search matches by things that are not directly visible and might not make sense at first sight. I think we can stay consistent with the web for now and possibly change it if we receive negative feedback on the search results, wdyt?

Probably. I was confused because I didn't add these descriptions, if a merchant did then probably it will be fine for them

> Yeah, I see what you mean. However, I'm wondering how common is unselecting a product in order creation use case. Also worth noting is that the user can change quantity to 0 on the order creation detail screen. I'd personally not optimize for this scenario right now, wdyt?

Agree, for order creation it's probably fine, but for coupons maybe not ideal

**Comment by malinajirka** [comment]
> Can we add SKU matching in the local search part? It will make things confusing though, so not sure if it's a good temporary workaround

Yes, we could, but that would imo not work great. Imagine you have a product in the local db and you search for SKU -> it finds it. Then you search for a product which is not in the local db using SKU -> it doesn't find it at all. The current solution currently always finds the same or more products in the remote - which I think is a safer approach. Does it make sense, wdyt?

> Agree, for order creation it's probably fine, but for coupons maybe not ideal

That's a good point! Having said that, I'd not tackle it as part of this project.

**Comment by malinajirka** [comment]
> while remote search matches also by the description

Fixed in the FluxC PR. The local search checks Title, Description and Short Description fields now.

> User can put a new line symbol in the search field
In the dark mode carriage in the search field is black, which looks wrong

I decided to fix these after all in https://github.com/woocommerce/woocommerce-android/pull/8391/commits/e5edfbd924ca60cc75f09ccb9b76c20b3016e690. This bug was affecting all WCSearchFields in the codebase.


It is ready for full review and can be merged after the FluxC PR is merged. Thanks @kidinov!

**Review by kidinov — APPROVED** [review]
@malinajirka 
> Yes, we could, but that would imo not work great. Imagine you have a product in the local db and you search for SKU -> it finds it. Then you search for a product which is not in the local db using SKU -> it doesn't find it at all. The current solution currently always finds the same or more products in the remote - which I think is a safer approach. Does it make sense, wdyt?

Yeah, that is what I was calling confusing. Let's omit that then 👌


LGTM!

**Comment by atifnimran** [comment]
Right choice

**Pull request merged**
