### PR TITLE
Dark Mode: Beta Features Settings Page

### PR DESCRIPTION
**Pull request by AmandaRiu**
The final step in closing #1584. This PR applies light/dark mode styling by swapping out widgets with the new custom settings widgets and tweaking styles. 

beta-features

## Recommended Testing
Since the changes in this component use custom widgets already previously tested, a simple review of the code and design should suffice. The changes in this PR are minimal.

cc: @Garance91540 and @kyleaparker design review

### CODE REVIEW

**Comment by Garance91540** [comment]
Looking good on my end!

**Comment by nbradbury** [comment]
@AmandaRiu Is this ready for review? It looks good to go but it's a still a draft.

**Comment by AmandaRiu** [comment]
This one is ready for code review

**Comment by nbradbury** [comment]
:shipit:

**Pull request merged**
