### PR TITLE
Update reader illustrations

### PR DESCRIPTION
**Pull request by irfano**
Closes: woocommerce/woomobile-private#378

### Description

This updates the illustrations appearing in the reader connection and payment flow.
Additionally, a layout issue has been fixed (f001f14cfd3a4a43688edb9c4430ed6b17d15c69). You can see the issue in the "before" column of the third row.

### Steps to reproduce

1. Login with a site eligible to use Payments. (Internal guide: PdfdoF-D-p2)
2. Enable Simulated Card Reader from "Menu → Settings → Developer Options"
3. To test the reader connection flow, go to "Menu → Payments → Manage Card Reader".
4. To test the payment flow, go to "Menu → Payments → Collect Payment", enter an amount, and select "Card reader" on the payment method screen.

Apply this patch to show a single reader in the reader connection flow: [Always_show_single_reader.patch](https://github.com/user-attachments/files/18246588/Always_show_single_reader.patch)

### Testing information

Please test in both light and dark modes.

### Images/gif

|before|after|after dark|
|-|-|-|
||||
||||
||||
||||
||||
||||
||||
||||
||||
||||

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by hafizrahman — APPROVED** [review]
Looks good and I don't see any issues with the new illustrations. I tested the screens using the site from the smoke testing guide, in Dark and Light mode on a Pixel 4 Simulator.

I noticed some readability issue on bigger font sizes but I don't think it's related to this PR, even though I see you fixed a layout issue here also.

I've reported that to peaMlT-14Y-p2

**Comment by wagveloso** [comment]
Hi there! Thanks for requesting to review the screens. They look great! There's only one screen that needs an update. The [Here's the link to the screen in Figma](https://www.figma.com/design/Ntkk0ER4hHt5y9KjEGIiGk/Woo-Mobile-App-Rebrand-Audit?node-id=3193-5508&t=PCLd5dsEBIZA4CfQ-1).

The reasons behind the changes are:

- The reader could be coloured, as it is connected and ready to collect the payment
- And the purple in the pagination dots is inconsistent, it should be Woo 40 on light version

If it's not a considerable amount of work 😅, is it possible to update the white outlined reader to purple if it's connected?

Thanks!

**Comment by irfano** [comment]
Thanks for the review, @wagveloso! I'll update the illustration and indicator color on the linked screen. I’ll also change the selected indicator color to purple, as we did on the login carousel.
> If it's not a considerable amount of work 😅, is it possible to update the white outlined reader to purple if it's connected?

If you mean this white-outlined reader,
image
this popup is already displayed only when the reader is connected.

**Pull request merged**
