### PR TITLE
issue/3651-product-price-update-bug-fix

### LINKED ISSUE #3651: Unable to edit product price in some cases
/hat tip @mdrockwell for the original report at https://github.com/wordpress-mobile/WordPress-Android/issues/14167 which I have copied below. 👍

### Expected behavior
After tapping on the price field, you're able to update it to a new value.

### Actual behavior
After tapping on the price field and tapping on the backspace key, the existing price will clear, but you aren't able to enter a new price.

### Steps to reproduce the behavior
1. Navigate to Products tab
2. Select product
3. Enter the price change view
4. Tap on backspace key
5. Attempt to enter new price

##### Tested on Honor 8A, Android 9, WooCommerce Android 6.1-rc-2, using Microsoft SwiftKey keyboard.

Video of this found here: 3783405-zen

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3651. This PR updates the product regular price and sale price to use `WCMaterialOutlinedEditTextView` instead of using `CurrencyEditText`. 

### Changes
- Added the currency symbol and currency position as part of the `SiteParameters`.
- Updates `ProductDetailViewModel` to fetch the store currency and displays that as a prefix or suffix of the currency value, based on the store settings.
- Removed rounding up of the sale and regular price.

### Testing
- Click on a product from the Products TAB.
- Click on the Pricing section.
- Notice that the currency symbol is displayed correctly and the position of the currency is displayed correctly.
- Try updating the regular price and the sale price and verify that the update is successful.

**This PR cannot be merged till this [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1975) can be merged.**

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by hichamboushaba — COMMENTED** [review]
Nice improvement @anitaa1990 👏 , but I have just three questions/suggestions before approving merging this:
1. With this change, we won't have any rounding, wdyt about our last discussion regarding the number of decimals configured in the backend?
2. Do you think it's worth modifying the `CurrencyEditText` to handle this by itself? if we do this, we'll have a consistent experience across the app, and it will fix whatever bug there is in other places as well.
3. We are not respecting the space parameter in the currency position anymore, I don't think it's a blocker, but we should be aware of it, do you think this requires a design review?

These are not blockers, and can be done in a separate PR if you think so 🙂

**Comment by anitaa1990** [comment]
Thanks for the review @hichamboushaba! 

> With this change, we won't have any rounding, wdyt about our last discussion regarding the number of decimals configured in the backend?

🤔 I see Core allows you to enter any number of decimal values in `wp-admin`. But the actual price displayed in the product page is according to the store settings, which makes sense, since that's the point of having a decimal count in store settings. 

Screenshot 2021-04-29 at 10 33 45 AM
Screenshot 2021-04-29 at 10 33 55 AM

iOS also rounds up based on the decimal numbers configured. So it makes sense to follow iOS here since that is the amount that will be displayed in the product page. 

Android, before this PR seems to round off everything, so that the incorrect price is updated in Core and displayed in the product page. But after the fix in this PR, it should follow Core's behaviour and display the correct value in both Product detail and pricing page.

WDYT?

> Do you think it's worth modifying the CurrencyEditText to handle this by itself? if we do this, we'll have a consistent experience across the app, and it will fix whatever bug there is in other places as well.

The only place `CurrencyEditText` is being used is when refunding by amount. We're currently not supporting this feature in the app right now (we only support refund by items). So we can leave this as is I think. WDYT?

> We are not respecting the space parameter in the currency position anymore, I don't think it's a blocker, but we should be aware of it, do you think this requires a design review?

Good point! I did notice that during implementation and actually had that change in FluxC in the beginning. But when I did have that change, the `prefix` or `suffix` ignores the space and I actually didn't see any UI difference when adding the space parameter in the UI. So I left it as is.

**Comment by anitaa1990** [comment]
FluxC hash has been updated in this PR and it's ready for another round @hichamboushaba!

**Review by hichamboushaba — APPROVED** [review]
Thanks @anitaa1990 for the clarifications, I'm approving the PR as all the discussions are not blockers and we can always have another PR that implements any change we agree on 🙂.

> iOS also rounds up based on the decimal numbers configured. So it makes sense to follow iOS here since that is the amount that will be displayed in the product page.
> 
> Android, before this PR seems to round off everything, so that the incorrect price is updated in Core and displayed in the product page. But after the fix in this PR, it should follow Core's behaviour and display the correct value in both Product detail and pricing page.

I don't understand the above two sentences, or I'm missing something, they seem contradictory to me 😄, should we follow iOS in rounding, or follow core in not rounding?

**Comment by anitaa1990** [comment]
> I don't understand the above two sentences, or I'm missing something, they seem contradictory to me 😄, should we follow iOS in rounding, or follow core in not rounding?

Lol! So we are currently following Core in not rounding when editing the product but we are displaying rounded values in product detail screen, which is the actual value displayed in the product page. This is similar to what iOS is doing 😄

**Comment by anitaa1990** [comment]
I'm merging this PR since I think this might be a good thing to include in the next release. Thanks @hichamboushaba!

**Comment by hichamboushaba** [comment]
Sorry @anitaa1990, I didn't notice the other review request, as I approved the PR before 🙂, LGTM :shipit:

**Pull request merged**
