### PR TITLE
Added option to display existing images in Aztec

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes Step 2 of #1594. This PR adds the ability to display existing images Aztec editor.

### Testing
- Click on the product description in the product detail page for a product with an image in the description. Verify that the image is displayed.
- Click on the product description in the product detail page for a product without an image in the description. Verify that the existing functionality remains the same.

### Screenshots

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
Thanks @0nko! I actually didn't notice that we had a separate module :)  I don't think we need a custom functionality at the moment so we can use the existing one. 

I tried importing the `glide-loader` module to our app and it looks like Aztec is using an older version of Glide so when using Aztec's version, I keep getting this crash:
```
java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager'
```
I think it's because it's trying to utilise an older method that is no longer available in the v4 version of the library. Should I open a new PR in the Aztec side to update the version for this and then use the updated version in our app?

**Comment by 0nko** [comment]
> Should I open a new PR in the Aztec side to update the version for this and then use the updated version in our app?

If you don't mind. Someone else might benefit from this too :).

**Comment by anitaa1990** [comment]
> If you don't mind. Someone else might benefit from this too :).

Surely! Will do that and update this PR 👍

**Comment by anitaa1990** [comment]
Added the `Glide-loader` module to the app @0nko! PR ready for another round 👍

**Pull request merged**
