### PR TITLE
[Better Tablet Products] Reviews in settings have double toolbar

### LINKED ISSUE #11071: [Better Tablet Products] Settings -> Reviews have double toolbar
Image

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #11071

### Description

I noticed that reviews in the settings have double toolbar. The reason was that 2 different framgnets reused the same layout. I extracted the common part to solve this

### Testing instructions

On a tablet and a phone
* Products -> Product -> Reviews -> Notice that toolbar is single there
* Settings -> Reviews -> Notice that the toolbar is single there (it was double)

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/4d020c91-7a5a-43b5-a842-4865ac9d65b8

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/199">17.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
Tablet:

Screenshot_20240314_151933

Screenshot_20240314_151842

Phone:

Screenshot_20240314_152829

Screenshot_20240314_152513

**Review by backwardstruck — APPROVED** [review]
Code changes make sense 👍

**Comment by kidinov** [comment]
@backwardstruck 👋

JFYI, the procedure is that the reviewer merges the PR, if the milestone matches and there is "do not merge" tag. Not a bug deal in this case, but this PR missed the release as I was AFK

**Pull request merged**
