### PR TITLE
Issue/3472 fix first day of week

### LINKED ISSUE #3472: Display Weekly Stats Mon thru Sun (instead of Sun thru Sat)
**Describe the bug**
When viewing stats in the Woo Android app, the week is shown as Sun through Saturday (unlike the browser or iOS app) 
Report here: 3677458-zen

**To Reproduce**
1. Go to WP-Admin
2. Click on Stats
3. Select the "Store" tab and the "Weeks" view
4. Notice that the week is displayed Monday through Sunday (this is not the case in the mobile Android app, it's Sunday through Saturday instead, dividing the weekend.)

**Screenshots**
image

**Expected behavior**
The Android version of the app would display the weekly stats in the same way that the browser and iOS versions do (Monday through Sunday) 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: multiple
- Android version: 11
- WooCommerce Android version: 5.7

</details>

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #3472 

***Ready for review, but not ready for merge***
~1. Wait until https://github.com/woocommerce/woocommerce-android/pull/3694 gets merged into develop~
2. Wait until https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1926 gets merged into develop
3. Update FluxC hash with a tag
4. Remove "Not ready for merge" label
5. Merge this PR

Graph for "This week" on the dashboard always display "Sunday" as the first day of week. Ideal solution would use "Week starts on" settings from WPAdmin as suggested [here](https://github.com/woocommerce/woocommerce-android/issues/3472#issuecomment-799788963). However, AFAICT this solution is not straighforward. We decided to let the OS choose the first day of week based on user's locale.

To test:
1. Set your device to English (US)
2. Restart the Woo app
3. Open dashboard
4. Click on "This week" tab
5. Notice the week starts with Sunday
6. Set your device for example to French
2. Restart the Woo app
3. Open dashboard
4. Click on "This week" tab
5. Notice the week starts with Monday 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hey @malinajirka, just a quick ping to tell you that #3694 is merged! 😄

**Review by anitaa1990 — DISMISSED** [review]
The changes look good and tested the scenarios in English, French and Tamil and works as expected :shipit:  

There is a merge conflict that needs to be addressed and the FluxC hash has to be updated. will merge once that's done!  Nice work @malinajirka

**Comment by malinajirka** [comment]
Thanks @anitaa1990 for the reviews! I've fixed the merge conflict and update FluxC tag.

**Review by anitaa1990 — APPROVED** [review]
:shipit:

**Pull request merged**
