### PR TITLE
[Tooling] Use Linter agent for Gradle wrapper validation

### PR DESCRIPTION
**Pull request by iangmaia**
This PR updates the pipeline config to move the Gradle Wrapper Validation from the `android` queue to the `linter` queue.

### Testing
CI should be 🟢

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iangmaia** [comment]
@ParaskP7 @wzieba 
I've implemented the Linter command to Validate the Gradle Wrapper and this is a test PR using it. Basically the wait time for the job is very little as expected:
Screenshot 2024-11-22 at 15 11 49

What do you think, shall we experiment with it in a few projects? Do you perhaps can think of potential issues?

**Review by wzieba — APPROVED** [review]
This is cool @iangmaia ! Thanks for working on it. I see that on other PRs this step takes 22s-28s so it's a nice improvement. I don't see any potential issues 👍

**Comment by ParaskP7** [comment]
Same to what Wojtek said @iangmaia , cool stuff and thanks for working on that! 🥇 

> What do you think, shall we experiment with it in a few projects?

Yes! 💯 

> Do you perhaps can think of potential issues?

Not off the top of my head, no. 😊

**Review by ParaskP7 — APPROVED** [review]

**Pull request merged**
