### PR TITLE
[REST API] Finalize Jetpack activation for application password case and logs user in

### LINKED ISSUE #8697: [REST API] Update the Jetpack installation flow for application passwords support
This should be as simple as replacing the `selectedSite.set(site)` in this [line ](https://github.com/woocommerce/woocommerce-android/blob/c6e2c27f83adf67895d5136dc141f50a7d83ec4e/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/jetpack/main/JetpackActivationMainViewModel.kt#L150) with `jetpackActivationRepository.setSelectedSiteAndCleanOldSites(site)`.

But we need to double-check the behavior after doing this change to confirm that everything works as expected.

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes #8697 

After Jetpack activation (installation and/or connection) is completed, previously the app refresh the state of the app. This PR completes the activation process by setting the site properly, and removing all previous sites in the DB that doesn't use WPCom REST API.

In effect, after activation is completed, this returns the merchant back to the "My Store" screen, but it's now in the Jetpack-connected state where every features are now available.

### To test:
1. Prepare a test self-hosted site with no Jetpack plugin (or Jetpack plugin active, but the account disconnected),
2. Start app, login and complete the site credentials flow, this logs in the user in the Application Password flow,
3. on "My Store" screen, tap the Jetpack banner at the bottom,
4. on the Jetpack Benefit screen that appears, click the "Log In to Continue" button,
5. Go through the Jetpack installation / connection flow, until everything is completed and the "Continue" button is shown,
6. Tap "Continue", make sure you're now logged in to "My Store" in the WordPress.com login flow,
7. Test around the app especially for features that's only available on WordPress.com flow:*
   1. Visitor stats,
   2. Switching store if you have more than one in the same WordPress.com account,
   3. Notifications

### CODE REVIEW

**Comment by hafizrahman** [comment]
Added do not merge, waiting for #8701 and #8702 before this is ready for launch.

**Comment by JorgeMucientes** [comment]
Hey @hafizrahman 👋🏼 I've just tested the install Jetpack flow and noticed a couple things:

- At the end of the flow I land on the site picker screen rather than on my store. Is that expected when you have multiple sites? Is it something related to my account? Sharing screen recording: 

https://user-images.githubusercontent.com/2663464/229471294-c8d6fd87-fb20-4c14-af16-2dff3c3305ed.mp4


- When clicking on the install Jetpack banner I noticed there's a weird transition where it seem as if the screen was being opened in landscape mode by default: 


https://user-images.githubusercontent.com/2663464/229471277-5fdcc1e3-8147-4272-a8d5-f30bb9646aa0.mp4

Kindly let me know what you think about those behaviors, if we may want to tackle them elsewhere or you want to address them in this PR 🙂

**Comment by hafizrahman** [comment]
@JorgeMucientes Thanks for testing! I've discussed this with @0nko and we decided to move the site picker one into a separate issue: https://github.com/woocommerce/woocommerce-android/issues/8735

I'll work on the odd transition effect in this PR.

**Comment by hafizrahman** [comment]
@JorgeMucientes I wonder why I couldn't replicate that effect:

1. This on a simulator, Pixel 5 with API 29:

https://user-images.githubusercontent.com/266376/229743066-85c1df4e-3074-46fd-b601-aca661c2f4db.mov


2. This on a real device, Samsung S21:

https://user-images.githubusercontent.com/266376/229744144-f9e78ec4-3b38-4983-b5ac-bacd386544f7.mp4

They both show regular transition to me 🤔 Any idea how to replicate this?

**Comment by JorgeMucientes** [comment]
Hey @hafizrahman. Thanks for looking into the concerns I shared. 

> I've discussed this with @0nko and we decided to move the site picker one into a separate issue: https://github.com/woocommerce/woocommerce-android/issues/8735

Sounds good!

> I wonder why I couldn't replicate that effect:

I can't replicate the effect now either. I double check different dev settings configurations to check if that could be related (like "Don't keep activities" or set automatic device rotation) but nothing. Could not reproduce it again. So, all good!!

Nice job! Feel free to merge when ready 👍🏼

**Review by JorgeMucientes — APPROVED** [review]

**Comment by ParaskP7** [comment]
FYI: @hafizrahman @JorgeMucientes @0nko I moved the `13.1` milestone to `13.2` in order to proceed with the code freezing process. Do let me know if you still need this PR to be part of the `13.1` release.

**Comment by 0nko** [comment]
@ParaskP7 Yes, please change it back to 13.1. We're currently working on getting it merged to `trunk`.

**Comment by ParaskP7** [comment]
Great, thanks for the notice @0nko ! 🙇 

Kindly let me know when this get merged to `trunk` so I can start with the `13.1` code-freeze process, I'll hold-on until then. 🙏

**Comment by hafizrahman** [comment]
@ParaskP7 this is now finished, thank you for your patience!

**Comment by ParaskP7** [comment]
Great, thank you @hafizrahman and @0nko ! 🙇 🎉 ❤️ 

FYI: I'll now proceed with the `13.1` code-freeze process if there is nothing else pending from your side. 🙏

**Pull request merged**
