### PR TITLE
Issue/6343 adjust to compose guidelines

### LINKED ISSUE #6343: Update Compose code for Inbox and MoreMenu to comply with Compose guidelines
More Menu and Inbox screen have some code parts not following Compose guidelines: 

- Remove the use of hardcoded numbers for dimens and use existing dimens from resources
- Add missing suffix "screen" to compose kotlin files and root composable funtion for that file.

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #6343 

### Description
Adjust More Menu and Inbox screen to comply with compose guidelines: 
- Remove hard-coded dimens
- Add proper naming to files and root composable functions
- Remove unnecessary xml files

EXTRA: The clickable background/effect on More Menu header to open site switch screen was kind of weird. It did not match parent width. I've updated this to use a `Box` layout and extend the clickable area to the full width of the row.

### Testing instructions
Just navigate to More Menu and Inbox screen and double check there is nothing wrong with paddings/margins and sizes. 
Click on More Menu header and check the new clickable effect. 

### Images/gif

https://user-images.githubusercontent.com/2663464/165460703-c4a6a28b-f010-49e8-94ad-df05c90ac68c.mp4

### CODE REVIEW

**Comment by JorgeMucientes** [comment]
Going to add a couple more changes to remove the unnecessary xml files. So converting this into draft

**Comment by JorgeMucientes** [comment]
FYI. Decided to run the UI test to check a couple things related to this p91TBi-8mI, but UI test are broken and its not related to this changes. They've been broken for some time and we already have an issue created to address that.  So that should not prevent this PR from being merged

**Review by malinajirka — CHANGES_REQUESTED** [review]
Thanks @JorgeMucientes! The PR looks good overall, however, I found one issue and one potential issue.

1. The site address seems to not have any right margin/padding.



2. I don't see the `Inbox` at all 😕  (I do see it for the same site on another build of the app)

Wdyt?

**Comment by JorgeMucientes** [comment]
Thanks for looking into this @malinajirka. 

- Good catch about the missing margins on the site name and url. Fixed it! Added a fair amount of margin to ensure that content never overlaps settings button
- Regarding Inbox not visible. 2 possible things going on:
    - Are you testing a debug version of the app? Inbox is featured flagged. 
    - Could you check that your site has an updated version of WooCommerce. We recently merged a use case for disabling Inbox for older WC versions. In this case, the value (which is not definitive yet) is set to 
`INBOX_MINIMUM_SUPPORTED_VERSION = "6.4.0"` So any version older than that would disable Inbox option. 

If none of the following applies please tell me and I'll review. I've just tested it and I can see Inbox button if those conditions are met.

**Review by malinajirka — APPROVED** [review]
> Are you testing a debug version of the app? Inbox is featured flagged.

I thought I was but I forgot that CI builds are still set to be non-debuggable.

Thanks for the changes, it LGTM :shipit: !

**Pull request merged**
