### PR TITLE
Add track event to see analytic report

### LINKED ISSUE #10668: [Analytics Hub] Add Tracks event for tapping the link to a full analytics report
Add new Tracks event:

- `analytics_hub_view_full_report_tapped`
   - Custom prop `report` with value `revenue|orders|products` (the report that is opened)
   - Custom prop `period` with value set to the currently selected date range (e.g. `today|yesterday|custom`)
   - Custom prop `compare` with value `previous_period` (in the future this can be expanded to include `previous_year` when the app supports a previous year comparison)

The event should be triggered when the user taps on a card’s link to view the full analytics report, with the custom props reflecting the selected report and the currently selected date range and comparison period.

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #10668

### Why
We plan to add full analytics reports to the Analytics Hub, by opening the web report in a webview.  This PR tracks user interactions with the new See Report button on the Analytics Hub cards.

### Description
This PR triggers the new `analytics_hub_view_full_report_tapped` event when the user taps on a card’s link to view the full analytics report, with the custom props reflecting the selected report and the currently selected date range and comparison period.

Registered here: https://github.com/Automattic/tracks-events-registration/pull/2221.

#### Custom properties:
- Custom prop `report` with value `revenue`|`orders`|`products` (the report that is opened)
- Custom prop `period` with value set to the currently selected date range (e.g. `today`|`yesterday`|`custom`)
- Custom prop `compare` with value `previous_period` (in the future this can be expanded to include previous_year when the app supports a previous year comparison)

### Testing instructions
1. Open the My Store screen
2. Tap on See more
3. Tap on the See Report link of the different cards and check that the `analytics_hub_view_full_report_tapped` event is sent and the custom props reflect the selected report, the selected date range, and the comparison period.

### Images/gif

```
🔵 Tracked: analytics_hub_view_full_report_tapped, Properties: {"period":"today","report":"products","compare":"previous_period","blog_id":222408976,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-small-bundle-yearly","store_id":"b6468f83-4986-44f1-b4ce-6021649dbf29","is_debug":true,"site_url":"https:\/\/woo-practically-automatic-witch.wpcomstaging.com"}
```

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by rachelmcr** [comment]
@atorresveiga Quick thing I just discovered: On iOS, we're already tracking the selected date range in the Analytics Hub with the event `analytics_hub_date_range_option_selected`, and in the custom prop recording the selected period we use these strings:

https://github.com/woocommerce/woocommerce-ios/blob/748b5d7a1c5fa189b8cbf7f46c2dcd605f850435/WooCommerce/Classes/ViewRelated/Dashboard/Analytics%20Hub/Time%20Range/AnalyticsHubTimeRageAdapter.swift#L198-L209

For consistency, could we use the same strings for the `period` property in this new `analytics_hub_view_full_report_tapped` event on both platforms? (The values for the other custom props don't need any changes.)

**Comment by atorresveiga** [comment]
> For consistency, could we use the same strings for the period property in this new analytics_hub_view_full_report_tapped event on both platforms?

Sure @rachelmcr! I updated the period property here: https://github.com/woocommerce/woocommerce-android/pull/10687/commits/699c4208f582ad4bfad0edef6655c137732af706

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/191">17.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ThomazFB — APPROVED** [review]
Looks good! :shipit:

**Pull request merged**
