### PR TITLE
Dark Mode: Order Details Customer Info Card

### LINKED ISSUE #1587: Dark Mode: style order detail screens
Implement light/dark mode on the order detail screen. 

## Todo
- [x] Order Status card (#1919)
- [x] Products card (#1922)
- [x] Payment Card (#1932)
- [x] Customer Information Card (#1933)
- [x] Notes card (#1934)
- [x] Shipping Method notice card (#1964)
- [x] Change order status dialog (#1965)
- [x] Refunded Products card (#1963)
- [x] Shipment Tracking card (#1963)

### PR DESCRIPTION
**Pull request by AmandaRiu**
Partially fixes #1587 by implementing light/dark theming to the Order Details Customer Info Card.

### Collapsed
customer-card-collapsed

### Expanded
customer-card-expanded

### No Billing info
customer-info-card-no-billing

### Layout bounds
customer-card-bounds

## To Test
Verify various states of the customer info card on API 23 and API 29:
- Collapsed
- Expanded
- With email/without email
- With phone number/without phone number
- With billing address/without billing address

### CODE REVIEW

**Comment by AmandaRiu** [comment]
Updated the design implementation to include a divider:

## Collapsed
cust-info-collapsed

## Expanded
custom-info-expanded

## Layout borders
cust-info-borders

Ready for review!

**Comment by AmandaRiu** [comment]
@0nko can you give me access to your store? I can't replicate any of these issues. 

When I remove the billing address I get:



and when I remove the Shipping address I get:



Also note the padding below **Order Total** in above screenshots. It's odd because in your screenshots the **Paid by customer** row is missing and I can't get it to disappear like in your screenshot even with orders where no payment has been made.

**Comment by 0nko** [comment]
@AmandaRiu I've added you to my site. The affected orders are **#3316** and **3326**.

> Paid by customer row is missing and I can't get it to disappear like in your screenshot even with orders where no payment has been made.

It's hidden for orders with the `Awaiting payment` status.

**Comment by AmandaRiu** [comment]
@0nko Thanks for adding me to your site. 
- Padding issue on payment card - fixed in 51520969162772c1db3faab9c780a8cb5e6e5e5d
- empty address view - this is a pre-existing issue. I've opened a [bug ticket to track it](https://github.com/woocommerce/woocommerce-android/issues/1960)
- missing ripple background - fixed in 0ab684acebe4e695739b7d972db160ddbade6d89

Thank you for the thorough review. Ready for another round!

**Pull request merged**
