### PR TITLE
IPP: Use auto size with max line restriction for the labels

### LINKED ISSUE #8248: TTP description text gets cut off in smaller devices in landscape mode
landscame_mode_bug

This happens in the card reader type selection screen.

### LINKED ISSUE #8328: [Mobile Payments] Error message cut off when payment failed
**Describe the bug**
In PR 8317, we introduced a cancel button for error messages in the TTP workflow.
Depending on the length of the error message, it now can get cut off. For the NFC chip being disabled error message, this even occurred with the phone's default font size and in portrait orientation. (This would only get worse as the font size gets larger, languages with longer words, and in landscape orientation.) I saw this issue with the NFC chip error message, but it likely affects other error messages as well.

**To Reproduce**
1. Disable the "Use NFC" setting for your phone
2. Start payment collection
3. Choose Tap to Pay 
4. See error and note how message is cut off

**Screenshots**

**Expected behavior**
The full error message should be shown so the user knows how to resolve it.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Google Pixel 7
- Android version: 13
- WooCommerce Android version: built from trunk on Feb 14, 2023

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #8328
Closes: #8248

### Description

The PR adds autoscaling on the labels which are cut off in certain circumstances

### Testing instructions

* Run the payment flow on the store and device with TPP enabled
* Rotate the device
* Notice that the text is fully visible
---

* Run the payment flow on the store and device with TPP enabled with NFC disabled
* Notice that on the error screen the error text is fully visible even when the device font size set to a bigger size

### Images/gif

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by lmischner** [comment]
It looks like we've introduced a similar issue to 8328 to the select reader type screen and a similar issue to 8248 to the error screen. 

If I change the font size on my device, the error text goes beneath the try again / cancel buttons (like 8248 did on the select reader type screen). This occurs in both portrait and landscape mode.


On the select reader type screen, changing font size caused the explanatory message to get cut off:

**Comment by kidinov** [comment]
@lmischner thank you for looking into that!

I don't know that the change caused any of that you mentioned - I assume that something that we had for a while

And there is no magic pill here - we have fixed-size dialogs here and we need to fit changeable font somehow in it. There are 2 ways to do so:
* We can make the content scrollable. It's not really practical, because many people will miss it anyway and it will take a lot of effort for the improvement that won't have much impact
* We can limit how much the font scales

I've spent some time on the implementation of the second one. It still doesn't work well when font scaling is too big, but keeping in mind that impact is very limited it should be good enough. Please take a look
d74e31a94a2265d2b7ef351ded985438faa7164b

**Comment by lmischner** [comment]
Thanks for taking a look!

I confirmed that the reader selection window now always shows the full message, regardless of font size. The NFC chip error still goes under the button, but only at the Pixel's largest font setting (and it's still more legible than it was prior to your fix).

Looks good to me from a user experience POV. I'll leave code review to @AnirudhBhat !

**Review by AnirudhBhat — APPROVED** [review]
Thanks for taking care of this @kidinov. LGTM! :shipit:

**Pull request merged**
