### PR TITLE
Build instrumentation tests in CI

### PR DESCRIPTION
**Pull request by mokagio**
### Suggestion

Build the instrumentation tests in CI to learn when they break faster.

Screen Shot 2020-05-21 at 8 18 53 pm

### Context

While working on the screenshots automation, the test script for which lives in `androidTest`, I've bumped a few times into broken builds due to changes that made it into the base branch while my PRs were waiting for review.

I'd like to add a step in CI to build the instrumentation tests, so that if something in a PR breaks them, we can discover it earlier and either fix the test or make the call to remove it because it's obsolete.

I think the person whose change break the tests is the one in the best position to fix them, because they'll have context on the change ready at hand.

### Possible alternative

If the team feels this is too much of a burden, or that those tests are a lost cause I could take care of:

- Moving the screenshots test in a dedicated module (is module the right term?), so that they don't need `androidTest` to build; or
- Leave the screenshots tests where they are, but remove all the tests we don't care about anymore.

### Feedback please 🙏 

There are two things I don't like:

- It's by far the slowest step in the build, which is no good, builds should be as fast as possible. _Suggestion:_ maybe this step should only run on `develop`? Slower feedback loop to learn if the tests are broken, but overall faster feedback loop while working on the PR
- The output doesn't show the failure reason clearly. _Can you point me towards how to make this better?_

---

Note that CI is failing right now. Once #2465 will be merged into the base branch and picked here, the build will pass. I've done this intentionally to show how a real world failure would look like.

---

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mokagio** [comment]
Thanks @jkmassel and @0nko. I'll start with removing the `--stacktrace` option. I had the wrong expectation of what info it would show, and you are totally right, it only adds noise.

I'll then see what can be done to split and/or parallelize.

Thanks, and stay tuned 😉

**Comment by mokagio** [comment]
> One thing we _could_ do to make this faster is to run it as its own task in parallel with unit tests

@jkmassel was this what you were thinking of?

abc-screenshot-2020-05-24-214018

**Comment by mokagio** [comment]
Thanks @0nko 

Unfortunately, it looks like I need to do a bit more work on how the new job is configured 😞 . It's missing decryption of some values. It did look odd that the build was failing after my `develop` rebase post merging #2465. 😕

Screen Shot 2020-05-26 at 10 55 33 pm

Stay tuned 👍

**Comment by jkmassel** [comment]
Ah sorry!! Missed the previous ping. Yes, this looks great. 

The next step (IMHO) will be getting the instrumentation tests (ie – non-screenshot) running on CI soon, but that's probably another PR!

:shipit:

**Comment by mokagio** [comment]
Oh hey! Thanks @0nko 🙏. Not sure why I didn't merge it myself 🤔 

And thanks @jkmassel, too 😄 .

**Pull request merged**
