### PR TITLE
issue/3083-product-firstimage-url-crash-fix

### LINKED ISSUE #3083: NullPointerException: images field in WCProductModel must not be null
Sentry Issue: [WOOCOMMERCE-ANDROID-ZW](https://sentry.io/organizations/a8c/issues/1976910550/?referrer=github_integration)

```
NullPointerException: Gson().fromJson(images, JsonElement::class.java) must not be null
    at com.woocommerce.android.model.ProductKt.toAppModel(Product.kt:404)
    at com.woocommerce.android.ui.products.ProductListRepository.getProductList(ProductListRepository.kt:152)
    at com.woocommerce.android.ui.products.ProductListRepository.fetchProductList(ProductListRepository.kt:98)
    at com.woocommerce.android.ui.products.ProductListRepository$fetchProductList$1.invokeSuspend
...
(15 additional frame(s) were not displayed)

Gson().fromJson(images, JsonElement::class.java) must not be null
```

### PR DESCRIPTION
**Pull request by anitaa1990**
This tiny PR fixes #3083 by updating the fluxC hash which contains the actual fix for the crash.

### To test
- I was able to reproduce this issue by SSP'ing into a user' site from the [list of affected users from Sentry](https://sentry.io/organizations/a8c/issues/1940414806/events/?project=1459556&referrer=github_integration).
- It happens just when clicking on the Products tab. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by nbradbury — DISMISSED** [review]
:shipit:

**Comment by nbradbury** [comment]
@anitaa1990 Looks like I approved this too soon, because there are conflicts that need to be addressed.

**Comment by nbradbury** [comment]
Sorry @anitaa1990, but it looks like there's still a conflict due to a PR that was just merged.

**Comment by anitaa1990** [comment]
Thanks @nbradbury! I've fixed the merge conflict and it's ready for review 👍

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
