### PR TITLE
[HACK] Research if CallThrottler can be implemented without assumption on 200ms

### LINKED ISSUE #12458: Research if `CallThrottler` can be implemented without assumption on 200ms
Currently, there is an assumption that a navigation starts without 200ms, which may be correct all the time or maybe not, e.g. we assume that this flow is not possible:
* Click
* 200ms passed
* Click again
* Double navigation

We also recently had an issue related to this time based approach too

p1724752391339309-slack-C025A8VV728

Check if:
* https://github.com/woocommerce/woocommerce-android/issues/12458#issuecomment-2321259503
* There is an actually generic solution here, e.g. we can simply check if navigation has started already and then ignore new navigation request
* Or may what we actually want is to ignore duplicated events within 200ms instead of ignoring all events

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12458 

### Description

We have had a couple of issues recently with CallThrottler, which is used for navigation. After some research, @samiuelson   [found out](https://github.com/woocommerce/woocommerce-android/issues/12458#issuecomment-2321259503) that apparently, the reason why that approach was introduce was already fixed in the navigation library itself, that's why the PR removes `CallThrottler`

### Testing information

* Try initiate multiple navigations in different parts of the app
* Notice that it works properly and only one instance of a fragment is getting open

### The tests that have been performed

The one from the testing information

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hichamboushaba** [comment]
Thanks @kidinov for the PR.

My understanding of the issue and why we needed the `CallThrotter` that Ondrej added back then is this: the `NavController` actions are synchronous, while the FragmentTransactions are not, so when we call `navigate`, it will update the `currentDestination`, while the `FragmentManager` will handle the navigation asynchronously, so if another call to `navigate` happens immediately after, it would result in the crash.

To experiment with the above, I added two `navigate` consecutive calls on one of the app listeners, and the app still crashes with the `IllegalArgumentException`, so I'm not really certain our assumption that the Navigation library had some updates to avoid this are accurate, @samiuelson can you please share the source of the [findings](https://github.com/woocommerce/woocommerce-android/issues/12458#issuecomment-2321259503)? I took a quick look at the release notes of the Navigation library, and I couldn't see exactly what changes could have helped avoiding the issue.

-----

If the throttler is causing some issues, I'm fine with removing it, we already catch the exception on production builds, so it should be safe, we just need to extend the catching logic to the other [`navigateSafely`](https://github.com/woocommerce/woocommerce-android/blob/7094daa37e297b084d058b82ce806d58823fe66b/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt#L36-L44) version.
Reporting the errors to Sentry on production builds instead of silently ignoring them would be great too to keep an eye on any increase, but we'll need to find a way how to retrieve the `CrashLogging` class from the extension 🤔, we can experiment with something like this (which should be fine since CrashLogging is a Singleton):
```Patch
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt	(revision 7094daa37e297b084d058b82ce806d58823fe66b)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt	(date 1727178007716)
@@ -6,9 +6,16 @@
 import androidx.navigation.NavDirections
 import androidx.navigation.NavOptions
 import androidx.navigation.fragment.FragmentNavigator
+import com.automattic.android.tracks.crashlogging.CrashLogging
 import com.woocommerce.android.util.WooLog
 import org.wordpress.android.util.BuildConfig
 
+private var crashLogging: CrashLogging? = null
+
+fun NavController.Companion.installCrashLogging(_crashLogging: CrashLogging) {
+    crashLogging = _crashLogging
+}
+
 fun NavController.navigateSafely(
     directions: NavDirections,
     extras: FragmentNavigator.Extras? = null,
@@ -26,6 +33,7 @@
                 throw e
             } else {
                 WooLog.w(WooLog.T.UTILS, e.toString())
+                crashLogging?.recordException(e)
             }
         }
     }
Index: WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt	(revision 7094daa37e297b084d058b82ce806d58823fe66b)
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/AppInitializer.kt	(date 1727177992035)
@@ -7,6 +7,7 @@
 import android.net.ConnectivityManager
 import androidx.lifecycle.Lifecycle.State.STARTED
 import androidx.lifecycle.ProcessLifecycleOwner
+import androidx.navigation.NavController
 import androidx.work.Constraints
 import androidx.work.ExistingPeriodicWorkPolicy
 import androidx.work.NetworkType
@@ -22,6 +23,7 @@
 import com.woocommerce.android.background.UpdateDataOnBackgroundWorker
 import com.woocommerce.android.config.WPComRemoteFeatureFlagRepository
 import com.woocommerce.android.di.AppCoroutineScope
+import com.woocommerce.android.extensions.installCrashLogging
 import com.woocommerce.android.extensions.lesserThan
 import com.woocommerce.android.extensions.pastTimeDeltaFromNowInDays
 import com.woocommerce.android.network.ConnectionChangeReceiver
@@ -195,6 +197,7 @@
         this.application = application
 
         crashLogging.initialize()
+        NavController.installCrashLogging(crashLogging)
         Thread.setDefaultUncaughtExceptionHandler(
             UncaughtErrorsHandler(
                 context = application,
```

**Comment by kidinov** [comment]
@hichamboushaba 👋

> To experiment with the above, I added two navigate consecutive calls on one of the app listeners, and the app still crashes with the IllegalArgumentException, so I'm not really certain our assumption that the Navigation library had some updates to avoid this are accurate, @samiuelson can you please share the source of the https://github.com/woocommerce/woocommerce-android/issues/12458#issuecomment-2321259503? I took a quick look at the release notes of the Navigation library, and I couldn't see exactly what changes could have helped avoiding the issue.

I think that Sam used LLM to construct this statement. Chatgpt may used to commit messages, change itself, or just hallucinate =)

In any case, I can confirm that I can not reproduce the crash manually. I am guessing that they do something with the UI event queue to avoid the crash, but when you just set a double navigation call, it rightfully crashes. Not sure about though

> If the throttler is causing some issues, I'm fine with removing it, we already catch the exception on production builds, so it should be safe, we just need to extend the catching logic to the other [navigateSafely](https://github.com/woocommerce/woocommerce-android/blob/7094daa37e297b084d058b82ce806d58823fe66b/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/NavController.kt#L36-L44) version.
Reporting the errors to Sentry on production builds instead of silently ignoring them would be great too to keep an eye on any increase, but we'll need to find a way how to retrieve the CrashLogging class from the extension 🤔, we can experiment with something like this (which should be fine since CrashLogging is a Singleton):

Good call!

I've implemented it slightly differently, which is not ideal too, but I looks a bit better in sense of lack of mutable static shared state. Wdyt?

eca873345193a0f2f19af9b0313d8622a1d7ac40

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/238">20.6</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hichamboushaba** [comment]
> In any case, I can confirm that I can not reproduce the crash manually. I am guessing that they do something with the UI event queue to avoid the crash, but when you just set a double navigation call, it rightfully crashes. Not sure about though

I believe we never were able to reproduce the crash manually, it happens only in some cases (maybe slow devices where the Fragment transactions take longer), but the underlining issue is still there IMO, and I don't think Google team is planning to do anything about it, it's working as [expected](https://issuetracker.google.com/issues/118975714) for them (and kinda it makes sense).

> Good call!

> I've implemented it slightly differently, which is not ideal too, but I looks a bit better in sense of lack of mutable static shared state. Wdyt?

Nice work, this looks cleaner, I'll do a proper review later today before approving it.

**Review by hichamboushaba — APPROVED** [review]
Nice work @kidinov, I like the solution to get the crashlogging dependency 👍 

Feel free to merge this when the CI is green.

**Pull request merged**
