### PR TITLE
[Support Requests] Create Form UI

### LINKED ISSUE #8331: [Support Requests] Build New Contact Support UI
We need to build a new UI that looks more like a Contact support form rather than a chat.

We are still waiting for the final designs but here is a quick iOS mock-up that we can use as a guide.

1 | 2
--- | ---
Image | Image

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #8331 by introducing our own Support Request form view that will replace the current usage of the Zendesk Activities. Since the Settings and Help section of the app still doesn't have proper support for navigation graphs, the form was implemented through a new Activity instead of a Fragment.

The original designs were made with only the iOS version in mind, so I took the liberty of adapting the form to fit our view style around WCAndroid app. Please feel free to suggest any adjustments.

<details>
  <summary>iOS UI implementation</summary>

| Top  | Bottom |
| ------------- | ------------- |
| Simulator Screen Shot - iPhone 14 Pro - 2023-02-21 at 20 09 26 | Simulator Screen Shot - iPhone 14 Pro - 2023-02-21 at 20 09 28 |

</details>

⚠️⚠️⚠️ Disclaimer
==========
This PR only introduces the form UI, no ticket creation event should be triggered, and the submit support request button is disabled to avoid misclicks while the feature is under development. The button is connected with the Zendesk creation event, but please bear in mind that overriding the button state and creating a ticket may create unwanted results in our Zendesk woo mobile queue. 

Captures
==========
https://user-images.githubusercontent.com/5920403/220478309-e51fd4e7-1d15-4b45-b059-10b8b48dc234.mp4

How to Test
==========
1. Open the app and hit the Menu section in the bottom bar
2. Once inside the menu, hit the `gear` icon to go to the app settings
3. Select the `Help & support` option of the app settings list, it's the very first option
4. Inside the Help options, select the `Contact support` option
5. Verify that the new form opens and all expected UI interactions work as expected through all view elements, and only the `submit` button is disabled. Validation constraints will be added later.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by wzieba — APPROVED** [review]
Looks good! As this PR is UI-only, I focused on UI suggestions. **They are all non-blocking**.

If you don't agree with some of them or they will take time - please feel free to ignore them. Those are only suggestions!

1. Make the whole radio button "selectable background". 

I think it's always nicer when the selectable row on a list. Here's a sample from e.g. "Android Now" app. I'd set the selectable background for the whole width in our case.

image

2. Make rows have more space

I think we could add more height to each item to make it easier to click and remove the "bold" and increased font size (to match guidelines).

| Woo | Sample from Material Design | 
| --- | --- |
| Screenshot 2023-02-23 at 11 30 25 | Screenshot 2023-02-23 at 11 30 48 |

3. Consistency with titles

I see that two sections have different ideas for titles. I'd match the "I need help with" caption to "Let's get this sorted" - I think the second one looks better.

Screenshot 2023-02-23 at 11 36 49

**Comment by ThomazFB** [comment]
Hey @wzieba, thank you for your review and so many relevant inputs! I guess I added too much "iOS-looking" stuff from the designs. I adjusted all your suggestions besides the Radio Button ripple effect affecting the entire row area. 

I tried some approaches, and I think they will require a large rework since the RadioButton component itself doesn't allow a ripple effect area override, so we would have to abandon the `RadioGroup` and do things manually. But since the entire row is already clickable, I decided to remove the ripple effect affecting only the radio circle, so it looks at least consistent with the clickable area.

Anyway, here's the final result of the form with your suggestions:


Let me know what you think!

**Review by atorresveiga — APPROVED** [review]
Great work, @ThomazFB! The UI is looking great. I didn't know about the radio group limitation, so I also tried some approaches to make the whole item selectable as per @wzieba's suggestion, but unfortunately, without success. While testing the different approaches, I noted that I needed to change the style of each radio button component separately, so I went ahead and created a style for the radio buttons in this section. I named the style `Woo.RadioButton.Support `.  Here is the Patch with the changes in case you decide it is worth having a style for all the radio buttons in this section. I will let the decision up to you. 

The code looks good! :shipit: 

<details>
  <summary>Patch</summary>

```
Index: WooCommerce/src/main/res/layout/activity_support_request_form.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/res/layout/activity_support_request_form.xml b/WooCommerce/src/main/res/layout/activity_support_request_form.xml
--- a/WooCommerce/src/main/res/layout/activity_support_request_form.xml	(revision 32cf4277b1a10c0dd4896fa552f9da46510b7bf3)
+++ b/WooCommerce/src/main/res/layout/activity_support_request_form.xml	(date 1677263202280)
@@ -1,6 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:app="http://schemas.android.com/apk/res-auto"
+    xmlns:tools="http://schemas.android.com/tools"
     android:layout_width="match_parent"
     android:layout_height="match_parent"
     android:background="@color/woo_gray_6"
@@ -47,30 +48,24 @@
                         android:id="@+id/help_options_group"
                         android:layout_width="match_parent"
                         android:layout_height="wrap_content"
-                        android:layout_marginStart="@dimen/minor_100"
-                        android:orientation="vertical">
+                        android:paddingStart="@dimen/minor_100"
+                        android:orientation="vertical"
+                        tools:ignore="RtlSymmetry">
 
                         <RadioButton
                             android:id="@+id/mobile_app_option"
-                            style="@style/Woo.RadioButton"
-                            android:layout_width="match_parent"
-                            android:layout_height="@dimen/major_325"
-                            android:background="@android:color/transparent"
-                            android:text="@string/support_request_help_app"
-                            android:textAppearance="?attr/textAppearanceListItem" />
+                            style="@style/Woo.RadioButton.Support"
+                            android:text="@string/support_request_help_app" />
 
+                        <!---->
                         <View
                             style="@style/Woo.Divider"
                             android:layout_marginStart="@dimen/minor_50" />
 
                         <RadioButton
                             android:id="@+id/ipp_option"
-                            style="@style/Woo.RadioButton"
-                            android:layout_width="match_parent"
-                            android:layout_height="@dimen/major_325"
-                            android:background="@android:color/transparent"
-                            android:text="@string/support_request_help_ipp"
-                            android:textAppearance="?attr/textAppearanceListItem" />
+                            style="@style/Woo.RadioButton.Support"
+                            android:text="@string/support_request_help_ipp"/>
 
                         <View
                             style="@style/Woo.Divider"
@@ -78,12 +73,8 @@
 
                         <RadioButton
                             android:id="@+id/payments_option"
-                            style="@style/Woo.RadioButton"
-                            android:layout_width="match_parent"
-                            android:layout_height="@dimen/major_325"
-                            android:background="@android:color/transparent"
-                            android:text="@string/support_request_help_payments"
-                            android:textAppearance="?attr/textAppearanceListItem" />
+                            style="@style/Woo.RadioButton.Support"
+                            android:text="@string/support_request_help_payments"/>
 
                         <View
                             style="@style/Woo.Divider"
@@ -91,12 +82,8 @@
 
                         <RadioButton
                             android:id="@+id/woo_plugin_option"
-                            style="@style/Woo.RadioButton"
-                            android:layout_width="match_parent"
-                            android:layout_height="@dimen/major_325"
-                            android:background="@android:color/transparent"
-                            android:text="@string/support_request_help_plugins"
-                            android:textAppearance="?attr/textAppearanceListItem" />
+                            style="@style/Woo.RadioButton.Support"
+                            android:text="@string/support_request_help_plugins"/>
 
                         <View
                             style="@style/Woo.Divider"
@@ -104,12 +91,8 @@
 
                         <RadioButton
                             android:id="@+id/other_option"
-                            style="@style/Woo.RadioButton"
-                            android:layout_width="match_parent"
-                            android:layout_height="@dimen/major_325"
-                            android:background="@android:color/transparent"
-                            android:text="@string/support_request_help_other"
-                            android:textAppearance="?attr/textAppearanceListItem" />
+                            style="@style/Woo.RadioButton.Support"
+                            android:text="@string/support_request_help_other" />
 
                     </RadioGroup>
 
Index: WooCommerce/src/main/res/values/styles_base.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/WooCommerce/src/main/res/values/styles_base.xml b/WooCommerce/src/main/res/values/styles_base.xml
--- a/WooCommerce/src/main/res/values/styles_base.xml	(revision 32cf4277b1a10c0dd4896fa552f9da46510b7bf3)
+++ b/WooCommerce/src/main/res/values/styles_base.xml	(date 1677263610484)
@@ -575,6 +575,15 @@
         <item name="android:textAppearance">?attr/textAppearanceSubtitle1</item>
     </style>
 
+    <style name="Woo.RadioButton.Support" parent="Widget.MaterialComponents.CompoundButton.RadioButton">
+        <item name="paddingStart">@dimen/major_100</item>
+        <item name="android:paddingLeft">@dimen/major_100</item>
+        <item name="android:textAppearance">?attr/textAppearanceListItem</item>
+        <item name="android:layout_width">match_parent</item>
+        <item name="android:layout_height">@dimen/major_325</item>
+        <item name="android:background">@android:color/transparent</item>
+    </style>
+
     <style name="Woo.CheckBox" parent="Widget.MaterialComponents.CompoundButton.CheckBox">
         <item name="paddingStart">@dimen/major_75</item>
         <item name="android:paddingLeft">@dimen/major_75</item>

```
</details>

**Comment by ThomazFB** [comment]
Oooh, nice refactoring, @atorresveiga! I submitted your patch in the PR. And thanks for trying to find an alternate way to the Radio button ripple effect! I was afraid that maybe I wasn't finding an obvious solution in front of me 😅 

I guess with that, we can go ahead and merge this one. WDYT?

**Comment by atorresveiga** [comment]
LGTM! :shipit:

**Comment by wzieba** [comment]
Thank you @ThomazFB for applying changes and @atorresveiga for the support!

**Pull request merged**
