### PR TITLE
Feature/add release tooling

### PR DESCRIPTION
**Pull request by loremattei**
This PR adds some Fastlane lanes that help the release of the app.
In order to share the same code, all the actions in the WordPress Android repository have been extracted and added to the release-toolkit.

# To Test
Testing is not trivial and should be done paying great attention, especially for the code_freeze lane because the test is done on the main repository.

In order to make the steps clearer, I'm referring to defined release numbers, instead of saying this version or next version. Note that these numbers works as of today, when 1.4 is the version in beta testing. If you test this PR later, you have to change the number consequently.

### code_freeze lane
This lanes executes the steps to code freeze a new version of the app.
Please, be super careful with this and make sure to revert all the changes that the script does.

1. Tag a fake version 1.4 in your local repository: `git checkout develop` && `git tag 1.4`. You don't need push it to origin.
2. Checkout this branch and run `bundle exec fastlane code_freeze codefreeze_version:1.5`.
3. Verify that a new 1.5 branch has been created.
4. Verify that the version has been updated in build.gradle.
5. Verify that the 1.5 milestone has marked with the snowflake icon.
6. Verify that the branch protection has been set for the release/1.5 branch.
7. Verify that the change log file has been created in your home.

Clean up
1. Remove the branch protection for the release/1.5 branch on GitHub.
2. Delete the release/1.5 branch on GitHub.
3. Remove the snowflake icon from the 1.5 milestone.
4. Remove the 1.4 tag from your local repository.
5. Remove the release/1.5 branch from your local repository.

### finalize_release lane
This lane downloads the translations and runs some final checks.
The simpler way to test this lane is to use a fake release branch.

1. Checkout a fake release/1.4.1 branch from the one in this PR, push it to origin and set it as upstream.
2. Run `bundle exec fastlane finalize_release`.
3. Verify that the app translations have been downloaded.
4. Verify that the test build and checks pass.
5. Verify that all the files have been committed and pushed.

Clean up
1. Remove the fake release/1.4.1 branch from GitHub.
2. Remove the fake release/1.4.1 branch from your local repository.

### CODE REVIEW

**Comment by jkmassel** [comment]
@loremattei – I'm thinking I'll test this Monday for the `1.5` RC side-by-side with the release scenario – that'll give a good indication that everything is working the same.

**Comment by jkmassel** [comment]
I attempted testing this with the release today, but the script crashed. I think this may have been because branch protection already existed on the branch. 

```
BlackBook:woocommerce-android jeremymassel$ bundle exec fastlane code_freeze
[✔] 🚀 
+-----------------------------------+---------+-----------------------------------------+
|                                     Used plugins                                      |
+-----------------------------------+---------+-----------------------------------------+
| Plugin                            | Version | Action                                  |
+-----------------------------------+---------+-----------------------------------------+
| fastlane-plugin-wpmreleasetoolkit | 0.1.9   | gp_downloadmetadata setfrozentag        |
|                                   |         | an_localize_libs promo_screenshots      |
|                                   |         | gp_update_metadata_source get_prs_list  |
|                                   |         | an_validate_lib_strings                 |
|                                   |         | an_update_metadata_source               |
|                                   |         | setbranchprotection                     |
+-----------------------------------+---------+-----------------------------------------+

[14:34:42]: ------------------------------
[14:34:42]: --- Step: default_platform ---
[14:34:42]: ------------------------------
[14:34:42]: Driving the lane 'android code_freeze' 🚀
[14:34:42]: --------------------------------
[14:34:42]: --- Step: android_codefreeze ---
[14:34:42]: --------------------------------
[14:34:42]: Skip confirm on code freeze: false
[14:34:42]: To not be asked about this value, you can specify it using 'codefreeze_version'
[14:34:42]: The version to freeze: 1.5
[14:34:49]: Code freezing release: 1.5
[14:34:49]: Update release branch version: false
[14:34:49]: $ git checkout develop
[14:34:49]: ▸ Already on 'develop'
[14:34:49]: ▸ Your branch is ahead of 'origin/develop' by 4 commits.
[14:34:49]: ▸ (use "git push" to publish your local commits)
[14:34:49]: $ git pull
[14:34:50]: ▸ Current branch develop is up to date.
[14:34:50]: $ cat ./WooCommerce/build.gradle | grep versionName
[14:34:50]: ▸ versionName "1.4"
[14:34:50]: $ cat ./WooCommerce/build.gradle | grep versionCode
[14:34:50]: ▸ versionCode 44
[14:34:50]: Building a new release branch starting from develop.
Version in develop is 1.4 (code: 44).
After code freeze:
New 1.5 on branch release/1.5: version name: 1.5-rc-1 - version code: 45.
Do you want to continue?
 (y/n)
y
[14:34:55]: $ git status --porcelain
[14:34:55]: Git status is clean, all good! 💪
[14:34:55]: $ git checkout develop
[14:34:55]: ▸ Already on 'develop'
[14:34:55]: ▸ Your branch is ahead of 'origin/develop' by 4 commits.
[14:34:55]: ▸ (use "git push" to publish your local commits)
[14:34:55]: $ git pull
[14:34:56]: ▸ Current branch develop is up to date.
[14:34:56]: $ git checkout -b release/1.5
[14:34:56]: ▸ Switched to a new branch 'release/1.5'
[14:34:56]: $ cp ./RELEASE-NOTES.txt ./WooCommerce/metadata/release_notes.txt
[14:34:56]: $ echo "1.6
-----
 " > ./RELEASE-NOTES.txt
[14:34:56]: $ cat ./WooCommerce/metadata/release_notes.txt >> ./RELEASE-NOTES.txt
[14:34:56]: $ git add RELEASE-NOTES.txt ./WooCommerce/metadata/release_notes.txt
[14:34:56]: $ git commit -m "Update release notes for code freeze"
[14:34:56]: ▸ [release/1.5 7ef067a8] Update release notes for code freeze
[14:34:56]: ▸ 2 files changed, 12 insertions(+), 2 deletions(-)
[14:34:56]: $ git push --set-upstream origin release/1.5
[14:35:00]: ▸ remote:
[14:35:00]: ▸ remote: Create a pull request for 'release/1.5' on GitHub by visiting:
[14:35:00]: ▸ remote:      https://github.com/woocommerce/woocommerce-android/pull/new/release/1.5
[14:35:00]: ▸ remote:
[14:35:00]: ▸ To github.com:woocommerce/woocommerce-android.git
[14:35:00]: ▸ * [new branch]        release/1.5 -> release/1.5
[14:35:00]: ▸ Branch 'release/1.5' set up to track remote branch 'release/1.5' from 'origin'.
[14:35:00]: $ ./tools/update-release-names.sh 45 1.5-rc-1
[14:35:00]: ▸ Done.
[14:35:00]: ▸ Switching and pulling: release/1.5
[14:35:01]: ▸ Editing WooCommerce/build.gradle - name: 1.5-rc-1 code: 45
[14:35:01]: ▸ Adding to git
[14:35:01]: $ git push
[14:35:08]: ▸ To github.com:woocommerce/woocommerce-android.git
[14:35:08]: ▸ 7ef067a8..1079d536  release/1.5 -> release/1.5
[14:35:08]: --------------------------------------------------
[14:35:08]: --- Step: Switch to android localize_libs lane ---
[14:35:08]: --------------------------------------------------
[14:35:08]: Cruising over to lane 'android localize_libs' 🚖
[14:35:08]: ------------------------------
[14:35:08]: --- Step: an_localize_libs ---
[14:35:08]: ------------------------------
[14:35:08]: Merging Login Library strings into ./WooCommerce/src/main/res/values/strings.xml
 - Skipping username string
 - Skipping enter_email_wordpress_com string
 - Skipping enter_site_address string
 - Skipping default_web_client_id string
 - Skipping login_notification_channel_id string
[14:35:08]: Done (0 added, 0 updated, 109 untouched, 5 skipped).
[14:35:08]: Cruising back to lane 'android code_freeze' 🚘
[14:35:08]: ---------------------------------
[14:35:08]: --- Step: setbranchprotection ---
[14:35:08]: ---------------------------------
[14:35:08]: Logged in as: Jeremy Massel
WARNING: The preview version of the Branch_protection API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.
+-----------------------------+---------------------+
|                   Lane Context                    |
+-----------------------------+---------------------+
| DEFAULT_PLATFORM            | android             |
| PLATFORM_NAME               | android             |
| LANE_NAME                   | android code_freeze |
| GIT_REPO_WAS_CLEAN_ON_START | true                |
+-----------------------------+---------------------+
[14:35:09]: PUT https://api.github.com/repos/woocommerce/woocommerce-android/branches/release/protection: 404 - Branch not found // See: https://developer.github.com/v3/repos/branches/#update-branch-protection

+------+--------------------------------------+-------------+
|                     fastlane summary                      |
+------+--------------------------------------+-------------+
| Step | Action                               | Time (in s) |
+------+--------------------------------------+-------------+
| 1    | default_platform                     | 0           |
| 2    | android_codefreeze                   | 25          |
| 3    | Switch to android localize_libs lane | 0           |
| 4    | an_localize_libs                     | 0           |
| 💥   | setbranchprotection                  | 0           |
+------+--------------------------------------+-------------+

[14:35:09]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Change facebook id dynamically
    https://github.com/fastlane/fastlane/issues/404 [closed] 3 💬
    22 Sep 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/bin/fastlane)
Octokit::NotFound: [!] PUT https://api.github.com/repos/woocommerce/woocommerce-android/branches/release/protection: 404 - Branch not found // See: https://developer.github.com/v3/repos/branches/#update-branch-protection
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/request/retry.rb:128:in `call'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `put'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/connection.rb:156:in `request'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/connection.rb:37:in `put'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/client/repositories.rb:583:in `protect_branch'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/bundler/gems/release-toolkit-bdaaef3307fa/lib/fastlane/plugin/wpmreleasetoolkit/actions/setbranchprotection_action.rb:16:in `run'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:35:in `block (2 levels) in parsing_binding'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/gems/fastlane-2.117.1/bin/fastlane:23:in `<top (required)>'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  /Users/jeremymassel/Projects/woocommerce-android/vendor/bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'
```

Will investigate further later on.

**Comment by loremattei** [comment]
It's pretty weird. The errors says "branch not found", which is not possible because the log shows that the branch was created. 
I just tried to run the lane after having commented out the `old_version = android_codefreeze(options)` line in order to avoid issues with the code freeze branch, and it worked perfectly.

**Comment by AmandaRiu** [comment]
@loremattei  @jkmassel  what's the status on this PR? Do you need any additional assistance with testing?

**Comment by jkmassel** [comment]
I'm not 100% sure – I can try to tackle it, but it _may_ need to wait until Lore is back?

**Comment by AmandaRiu** [comment]
@jkmassel ah ok, I didn't realize Lore was away. That's fine. I just wanted to see what was going on with it. Thanks for the update.

**Comment by loremattei** [comment]
Hey @jkmassel! I've tried again this today while doing WCAndroid 1.7 code freeze and worked with no errors. Could you please check again if it fails for you or it was just a temp hiccup? 
The logs you provided clearly show that the branch was pushed and tracked when you did the test, so the error doesn't make any sense to me.

**Pull request merged**
