### PR TITLE
Dark Mode: Order Status TagView

### LINKED ISSUE #1794: Dark Mode: Style Order status TagView
Apply Dark/Light mode stylings to the Order Status tags:
- Convert from using the custom `TagView` class to the Material `Chip` class 
- Apply light and dark styles/themes

## Text Style
textAppearance: Caption
textColor: surface - high emphasis

## Background Style
Corner Radius: 4dp
paddingTop: 4dp
paddingBottom: 4dp
paddingLeft: 12dp
paddingRight: 12dp

Screen Shot 2020-01-03 at 11 01 13 PM

### Designs
Screen Shot 2020-01-03 at 10 58 20 PM
Screen Shot 2020-01-03 at 10 58 13 PM

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #1794  by applying dark/light mode styling to the custom `TagView` class. 
- I did not convert to a material ChipView because it seemed like overkill for our uses. 
- I did not mess around with border or fill coloring since the design shows colors for future changes to the order list when multiple statuses start getting used.
- All other parts have been styled. 

This PR only covers the order status tag.

### API 21
tagview-api-21

### API 29
tagview-api-29

### Updated Screenshot
To show the updates to the order status tag colors after design review

Screen Shot 2020-01-08 at 4 29 56 PM

### CODE REVIEW

**Comment by AmandaRiu** [comment]
@Garance91540 This one is ready for a design review! 👍

**Comment by Garance91540** [comment]
Hi @AmandaRiu! This looks good to me!

**Comment by Garance91540** [comment]
Hi @AmandaRiu ! I have one comment about the status tag colors, I think @kyleaparker had updated the colors for the current status as well, as indicated here:

Screen Shot 2020-01-07 at 3 07 25 PM

Is it be possible to update those on dark mode? So the contrast is a bit harder to see (for example between "processing" and "completed")

**Comment by AmandaRiu** [comment]
@Garance91540 

> Is it be possible to update those on light mode and dark mode?

Surely, I'll get that updated today and submit new screenshots.

**Comment by AmandaRiu** [comment]
@Garance91540 I've updated the tag colors and corner radius to match the new style. Ready for another review. 

Screen Shot 2020-01-08 at 4 29 56 PM

**Comment by AmandaRiu** [comment]
This one is ready for review 🍾

**Comment by AmandaRiu** [comment]
@anitaa1990 Yup, both those issues are known issues and not related to this PR.

**Pull request merged**
