### PR TITLE
Add jalapeno build flavor

### PR DESCRIPTION
**Pull request by AmandaRiu**
Similar to [this WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/11640), this PR adds a new build flavor called “jalapeño”. The eventual goal is to use this flavor for PR builds so testers can install this version along side the current production version and the changes required to update the tooling will come in a later PR since this one is already hefty. The following changes are included in this PR:

- New `jalapeño` build flavor
- Custom launch and woo bubble icons for the `jalapeño` build type
- Splash screens for `wasabi` and `jalapeno`
- New `splash_background` color definition so the jalapeño build could easily override it and for a green splash background. 

### API 23 Screenshots

Icons
--|
|

Screen | Wasabi | Jalapeño | Release
-- | -- | -- |--
**Splash** |23-splash-wasabi|23-splash-jalapeno|23-splash-release
**Login Toolbar** | Screenshot_1589443083|23-login-jalapeno|23-login-release

### API 28 Screenshots

Icons
--|
|

Screen | Wasabi | Jalapeño | Release
-- | -- | -- |--
**Splash**|28-splash-wasabi|28-splash-jalapeno|28-splash-release
**Login Toolbar**|28-login-wasabi|28-login-jalapeno|28-login-release

## To Test
- update `google-services.json` from `.mobile-secrets`
- Verify the following on release, wasabi and jalapeño builds on a device running API 21 or 22, then again on a device running API 23+:
  - Log in with Google
  - Log in with email address

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by oguzkocer** [comment]
Hi there! `4.3` is being frozen, so this PR is being bumped to `4.4`. If these changes _have to_ be shipped with `4.3`, please target `release/4.3` and cc me in the PR so I can cut a new beta release. Also if you can keep the release dates in mind and bump the PRs & issues you are working on before the code freeze date, we'd really appreciate it.

**Comment by loremattei** [comment]
Hey @AmandaRiu 👋 Since I was tinkering in the Firebase console yesterday for the shared debug key and I saw this PR, I also created the `com.woocommerce.android.prealpha` app ID, so it's now available for use.

**Comment by AmandaRiu** [comment]
@loremattei 

> Hey @AmandaRiu 👋 Since I was tinkering in the Firebase console yesterday for the shared debug key and I saw this PR, I also created the com.woocommerce.android.prealpha app ID, so it's now available for use.

Thank you so much! I'm not familiar on how to set that all up and was going to be reaching out next week to talk about it so you've saved me some time 👍

**Comment by ThomazFB** [comment]
Hey @AmandaRiu, sorry for the long time to finish the review, I've tested all the scenarios you described and it's working just fine for me, code looking good, the flavor is selectable from the build variants menu and the colors for the app icon and splash screen are changing just fine. Really nice work, LGTM :shipit:

**Review by ThomazFB — APPROVED** [review]

**Pull request merged**
