### PR TITLE
Removed redundant stats v4 availability check when app is opened

### LINKED ISSUE #3667: API optimisations: Remove the Stats v4 availability check from the app
We seem to calling a separate API to check the availability of `wc-admin` for the store each time the app is opened. That seems to be a costly call taking almost ~900ms on average. We could maybe consider removing this call and using the response of the Today TAB API to check the availability and display the empty view.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3667. This PR removes the redundant API call when the app is first opened, to check if the stats `v4-analytics` API is available for a store. 

### To test
**There should be no behavioural changes to the UI.**
- Login to a test store that has the latest version of WooCommerce and verify that the stats tab is loaded successfully.
- Login to a test store that has WooCommerce plugin version < 4.2. You can install the [WooCommerce Beta Tester](https://wordpress.org/plugins/woocommerce-beta-tester/) plugin to switch the Woo version of a store. You should be able to see an empty Stats screen asking you to update to the latest version of Woo.

One thing I noticed is that when the empty screen is displayed, there is no way to refresh the screen, other than to click on one of the bottom tabs and coming back to this screen again. I think we can introduce a pull to refresh in that screen though. But out of scope for this PR, will open a new PR for that.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hafizrahman** [comment]
## Testing notes:

I'm not sure if I should log out of my account or not between testing the first site and second site, so just to be extra safe, I deleted and re-built the app to test the second site.

> Login to a test store that has the latest version of WooCommerce and verify that the stats tab is loaded successfully.

This works perfectly.

> Login to a test store that has WooCommerce plugin version < 4.2. You can install the WooCommerce Beta Tester plugin to switch the Woo version of a store. You should be able to see an empty Stats screen asking you to update to the latest version of Woo.

This is what I see on the app, testing on an Atomic site with WooCommerce 4.0 using the beta tester plugin:



I couldn't see the update request message. Have double-checked via WP CLI to confirm that the site is on WooCommerce 4.0.0 🤔 

> One thing I noticed is that when the empty screen is displayed, there is no way to refresh the screen, other than to click on one of the bottom tabs and coming back to this screen again.

Related to that, I was able to pull down on this screen and it's doing a refresh animation (that doesn't result in anything as far as I can check):


https://user-images.githubusercontent.com/266376/113560240-dfa82c00-962c-11eb-9279-8c9c3d73f205.mp4

**Comment by anitaa1990** [comment]
Thanks for testing @hafizrahman!

> I'm not sure if I should log out of my account or not between testing the first site and second site, so just to be extra safe, I deleted and re-built the app to test the second site.

I don't think you need to logout and login back into the app between testing the first site and second site. You can switch your store between the first and the second and verify that the stats screen is loaded successfully. 

> I couldn't see the update request message. Have double-checked via WP CLI to confirm that the site is on WooCommerce 4.0.0 🤔

So this is the screen we are supposed to display if the store does not have WC-admin or Woo < 4.2. 

Would you be able to test with Woo version less than 3.9?

> Related to that, I was able to pull down on this screen and it's doing a refresh animation (that doesn't result in anything as far as I can check):

So the screen you mentioned is displayed when Woo > 4.2 is available for the store but there is just no data to display. But the screen I had mentioned is when Woo latest version is not available. And in that screen there is no way to pull to refresh.

**Comment by hafizrahman** [comment]
> Would you be able to test with Woo version less than 3.9?

Created a new, non-WordPress.com site at version 3.8.0 and now it's displaying the expected message 🎉 



Went back to my WordPress.com site, modified it to 3.8.0, and now it's displaying the same as above. 🎉 

Then I went back and upgraded both non-WordPress.com site and WordPress.com site to 4.0.0, and the "no data to display" screen was shown on both.

**Review by hafizrahman — APPROVED** [review]
Changes LGTM!

**Pull request merged**
