### PR TITLE
Revert DataStore library version

### LINKED ISSUE #12867: CorruptionException: Unable to parse preferences proto.
Sentry Issue: [WOOCOMMERCE-ANDROID-G1K](https://a8c.sentry.io/issues/6036044657/?referrer=github_integration)

```
InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
    at androidx.datastore.preferences.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2107)
    at androidx.datastore.preferences.protobuf.CodedInputStreamReader.getFieldNumber(CodedInputStreamReader.java:82)
    at androidx.datastore.preferences.protobuf.MessageSchema.mergeFromHelper(MessageSchema.java:3913)
    at androidx.datastore.preferences.protobuf.MessageSchema.mergeFrom(MessageSchema.java:3895)
    at androidx.datastore.preferences.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1648)
...
(37 additional frame(s) were not displayed)

CorruptionException: Unable to parse preferences proto.
    at androidx.datastore.preferences.PreferencesMapCompat$Companion.readFrom(PreferencesMapCompat.kt:34)
    at androidx.datastore.preferences.core.PreferencesSerializer.readFrom(PreferencesSerializer.jvm.kt:46)
    at androidx.datastore.core.okio.OkioReadScope.readData$suspendImpl(OkioStorage.kt:180)
    at androidx.datastore.core.okio.OkioReadScope.readData(OkioStorage.kt:0)
    at androidx.datastore.core.StorageConnectionKt$readData$2.invokeSuspend(StorageConnection.kt:74)
...
(30 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue https://github.com/woocommerce/woocommerce-android/issues/12867 by reverting the DataStore library version back to `1.0.0`.

During the project migration to the Version Catalog, we ended up migrating the DataStore from `1.0.0` to `1.1.0`. Unfortunately, this upgrade introduced [a current known bug from the library](https://href.li/?https://issuetracker.google.com/issues/256784635) to our app. 

To fix it, this PR reverts the app back to the version prior to the Version Catalog migration one month ago.

How to Test
==========
Currently, 90% of the app's reliance on DataStore is related to Analytics and Stats. To properly test this downgrade, I recommend verifying if the Analytics Hub, My Store Stats, and Top Performers are all working as expected.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/243">21.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by atorresveiga — APPROVED** [review]
LGTM!
:shipit:

**Comment by ParaskP7** [comment]
👋 @ThomazFB , thanks for the fix and apologies for the inconvenience! 🙏 🙇 

FYI: As part of the [Version Catalogs](https://github.com/woocommerce/woocommerce-android/pull/12765) migration I did warn (⚠️) about such changes (see description), and also wrote a descriptive [commit](https://github.com/woocommerce/woocommerce-android/commit/7f69b0c4c5eb37a934724aa87ae158ab68097b57) on it too, mentioning that `WooCommerce` and `WooCommerce-Wear` were using a different version of `datastore`, point to `1.0.0` and `1.1.0` correspondingly. I hope that with Version Catalogs we will avoid such inconsistencies going forward, along with all the potential problems this could create. 😞

**Comment by ThomazFB** [comment]
Hey @ParaskP7, don't worry about that, and there is no need for apologies; this is not on you in any way; we can't predict that a small version bump of a library could introduce a shady crash like that one; this is a quality fault from the library itself. The Version Catalog was an amazing introduction to our app and thanks for all your work on that!

**Pull request merged**
