### PR TITLE
Fix "No Stores" view to reflect design changes

### LINKED ISSUE #3124: [Unified Login - Continue with WP.com] - Jetpack required screen style updates
When the WP.com account doesn't have any stores connected, this is the current screen we display. 

Screenshot_20201103-145423

Could we display this screen instead?

Screen Shot 2020-11-03 at 5 36 54 PM

Thank you!

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #3124 by applying the following updates to the "No Woo Stores Found" screen:
- Updated message and added "What is Jetpack" button
- Display the "Learn more about connecting Jetpack" button and make it primary
- Make the "Log in with another account" a secondary button
- Also fixed the margins and centering around the User Info section of the view as it was off-center

Before | After
-- | --
no-stores-before|Screenshot_1606957989

**Landscape version:**

### To Test
1. Click "Continue with WordPress.com" on the first login screen.
2. Log in with a user who has no WooCommerce stores connected to the account. 
3. Click "What is Jetpack" -- verify info dialog appears
4. Click "Learn more about connecting Jetpack" -- verify it loads the Jetpack instructions in a webview
5. Click "Log in with another account" -- verify routed back to the welcome screen. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — APPROVED** [review]
👏👏👏

Small formatting notes (that can totally be addressed in a different PR)
- Can we make sure the "What is Jetpack" as well as the buttons text are Body 2 Medium?
- Can we remove the dropshadow under the Primary button?

Thank you!

**Comment by nbradbury** [comment]
@AmandaRiu I'm good to merge this but decided to wait to see if you want to include Garance's formatting change in this PR.

**Comment by AmandaRiu** [comment]
@Garance91540 I have verified the "What is jetpack" button is Body2, and the drop shadow was removed in a different PR that fixed the button styles so that's good to go 👍 

@nbradbury Ready for merge 👍

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
