### PR TITLE
Issue/2844 order detail refactor fulfill order

### PR DESCRIPTION
**Pull request by anitaa1990**
This PR takes care of the 13/13 step of the Order Detail refactoring #2844 .

#### Changes
- Adds the option to Fullfill an order. This PR changes the way the Order fulfill takes place by bypassing the Order Fulfill screen and updating the status of the order to `Complete`. This was because the Order fulfill screen was just duplicating the same data displayed in the Order Detail and seemed redundant. (Pending discussion with the rest of the team. P2 post to follow).
- Adds unit tests to `OrderDetailViewModel`.
- Removes all unused resources.

#### Notes
- I have split this massive change into multiple small PRs in order to make reviews easier. 
- This PR is to be merged into a feature branch.
- **This PR is in draft till this [Step 12 PR](https://github.com/woocommerce/woocommerce-android/pull/2877) can be merged.**

#### Testing
- Run `OrderDetailViewModelTest`.
- Test that new order notification opens the Order Detail screen correctly.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
@woocommerce/android-developers, this one is ready for review 👍

**Review by AmandaRiu — CHANGES_REQUESTED** [review]
@anitaa1990 Nice work on all these changes - it's a lot! Tested new order notification and that worked great. AFA functionality I noticed the following:

1. Per Garance's comment on this p2 post [p91TBi-3mT-p2#comment-1870] - the button label should be changed from **Begin Fulfillment** to **Mark order complete**. 



2. If you leave the order detail view after marking the order complete before the snackbar goes away the process appears to get canceled even though the snackbar stays active and appears to run through the process successfully.

**Comment by anitaa1990** [comment]
Thanks for the review @AmandaRiu! 

> Per Garance's comment on this p2 post [p91TBi-3mT-p2#comment-1870] - the button label should be changed from Begin Fulfillment to Mark order complete.

Done in  2a42204

> If you leave the order detail view after marking the order complete before the snackbar goes away the process appears to get canceled even though the snackbar stays active and appears to run through the process successfully.

I just added logic in 2a42204 to dismiss the snackbar when back is clicked, similar to the behaviour we have in `develop` right now.

LEFT: behaviour in this branch.  RIGHT: behaviour in develop right now.
. 


Ready for another round 👍

**Review by AmandaRiu — CHANGES_REQUESTED** [review]
@anitaa1990 The changes you made look good, but while testing I ran into another issue. I have a couple orders where the "Mark order complete" button won't appear, even though the orders are in processing. It seems to be specific to these orders since I _can_ get the button to appear on other orders. Any idea? I checked in the current production version and both these orders have the ability to mark complete in the old version. Here's a gif:

ezgif com-resize

**Comment by anitaa1990** [comment]
> The changes you made look good, but while testing I ran into another issue. I have a couple orders where the "Mark order complete" button won't appear, even though the orders are in processing. It seems to be specific to these orders since I can get the button to appear on other orders. Any idea?

Ah, I failed to mention that! So if there are shipping labels for the order, the assumption is that the order is already fulfilled (since there is an option to mark the order as complete, when purchasing shipping labels). But in cases when the order is not fulfilled when purchasing shipping labels, the user can just click on the `Edit` icon to change the order status as complete. This is because if there are multiple shipping labels for an order, we weren't sure where to display the `Mark order as complete` button so @Garance91540 mentioned that users can just change the order status by clicking on the edit icon. Sorry I failed to mention that earlier! The relevant discussion can be found in `p91TBi-3pf#comment-1881`

**Review by AmandaRiu — APPROVED** [review]
Thanks for the clarification @anitaa1990 LGTM! :shipit:

**Pull request merged**
