### PR TITLE
Issue/1108 fragmentize product detail

### LINKED ISSUE #1108: Fragmentize Product Detail
Prior to converting to the the navigation component, we should fragment-ize some of activities. First up was the "Add Order Note" activity in #1104, now we need to do the same for Product Detail.

### PR DESCRIPTION
**Pull request by nbradbury**
**Important:** #1104 should be merged before this one.

Closes #1108 - This PR converts the product detail activity to a fragment, in preparation for our AndroidX & nav component migration. 

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by nbradbury** [comment]
> The toolbar title of product detail is generally the name of the product

Good catch! Fixed in cb47bb5

> The back button is not displayed when fragment is resumed after enabling Do not keep activities

I'm not able to repro this, and I tried on three emulators and a real device. Is this consistent, and does it happen only on a certain SDK level?

**Comment by nbradbury** [comment]
> I was finally able to reproduce this a specific steps.

Thanks @anitaa1990 - I was also able to reproduce following those steps. Rather than fix this here, I think what we need is a consistent, centralized way for fragments to set/reset the activity title and the toolbar close icon.  The way we do it now, where each child fragment is responsible for setting the title and icon, isn't scalable. Are you okay with merging this now and we tackle that in a separate PR?

**Comment by anitaa1990** [comment]
> Thanks @anitaa1990 - I was also able to reproduce following those steps. Rather than fix this here, I think what we need is a consistent, centralized way for fragments to set/reset the activity title and the toolbar close icon. The way we do it now, where each child fragment is responsible for setting the title and icon, isn't scalable. Are you okay with merging this now and we tackle that in a separate PR?

Sure, that sounds good 👍.  I'm good to merge. Were you able to reproduce this issue as well? 
> One more brain twister I found:
Enable Do not keep activities
Click on a product from the list in My Store tab.
Click on Home button and close the app. Open it again.
Click on the close icon.
Notice that the stats page is blank

I'm not sure if we can tackle this here or in a separate PR?

**Comment by nbradbury** [comment]
That seems like an entirely separate problem, so we should file a separate
issue for it.

**Comment by anitaa1990** [comment]
Sounds good. Created a separate issue for it [here](https://github.com/woocommerce/woocommerce-android/issues/1123). 

LGTM :shipit:

**Pull request merged**
