### PR TITLE
Return to default detekt, ktlint settings regarding wild card imports

### LINKED ISSUE #6371: Return to default detekt/ktlint settings regarding wild card imports
Following the discussion it looks like after some time with this disabled we found out that it doesn't bring much

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #6371

### Description

The PR reverts to default (aka no wildcards) ktlint and detekt settings. Also, baseline is regenerated that includes all the wildcards we added since then.

### Testing instructions

No user facing changes. Take a look into the code changes

### CODE REVIEW

**Comment by JorgeMucientes** [comment]
Thank you for opening the discussion and looking into this @kidinov 🥇 

I just have a couple questions regarding this changes: 

- I've checked out this branch, enabled wildcard imports from AS settings and then applied some auto import on the fly. It added wildcard imports to my file. My understanding was that with the current `.editorconfig` this shouldn't happen as it should override the IDE code style settings right? Btw I have EditorConfig plugin installed and applied.
- I get this warning in `.editorConfig` file, which I don't know if it may be related to the previously described issue:

Screenshot 2022-04-27 at 10 10 35

- As for Detekt checks. Just curious, is there any difference between `NoWildCardImports` from formatting section and `WildCardImports` from style section? Seems like they both do the same which means will have duplicated errors for the same thing and if for any reason we want to suppress some specific wildcard we will have to do it twice. The [docs](https://detekt.dev/docs/rules/style/#wildcardimport) from `Detekt` state the following: 
> NOTE: This rule has a twin implementation NoWildcardImports in the formatting rule set (a wrapped KtLint rule). When suppressing an issue of WildcardImport in the baseline file, make sure to suppress the corresponding NoWildcardImports issue.

Imo we can enable just one of the 2 rules. Wdyt?

**Comment by kidinov** [comment]
@JorgeMucientes  Thank you for the review!

> I've checked out this branch, enabled wildcard imports from AS settings, and then applied some auto import on the fly. It added wildcard imports to my file. My understanding was that with the current .editorconfig this shouldn't happen as it should override the IDE code style settings right? Btw I have EditorConfig plugin installed and applied.

Discussed offline, looks like AS bug

> I get this warning in .editorConfig file, which I don't know if it may be related to the previously described issue:
IDEA doesn't support this option, but other code editors that's probably it makes sense to keep it here too

This option should work for other editors who support it. IDEA doesn't that's we use specific options here

> As for Detekt checks. Just curious, is there any difference between NoWildCardImports from formatting section and WildCardImports from style section? Seems like they both do the same which means will have duplicated errors for the same thing and if for any reason we want to suppress some specific wildcard we will have to do it twice. The [docs](https://detekt.dev/docs/rules/style/#wildcardimport) from Detekt state the following:

The first is ktlint the second is Detekt setting. They look to be essentially the same rule

> Imo we can enable just one of the 2 rules. Wdyt?

I see your point, but I would keep as fewer changes in the default settings of detekt as possible, just for sake of reducing the potential for debates. I'm a big fan of `go fmt` approach where you have no debates at all because you can not change the behavior of the tool. I wish detekt would be the same too haha

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Thanks for the reply @kidinov 

> Discussed offline, looks like AS bug

I'll keep an eye on that.

> I see your point, but I would keep as fewer changes in the default settings of detekt as possible, just for sake of reducing the potential for debates. I'm a big fan of go fmt approach where you have no debates at all because you can not change the behavior of the tool. I wish detekt would be the same too haha

I disagree with that. I think debates are usually fruitful, and I think that tooling customization is great to be able to adjust the tools to the needs of each team or project. That said, I don't have a strong opinion on this and I don't think is critical at all, so I'm good with keeping both checks enabled even if they check for the same thing. If it becomes annoying, we can deactivate one in the future easily.

I approved the PR but not merged as I remember you saying something about not merging it yet, so I was unsure. Feel free to merge when you consider. 

Nice work 👍🏼 !

**Comment by kidinov** [comment]
@JorgeMucientes 

> I disagree with that. I think debates are usually fruitful, and I think that tooling customization is great to be able to adjust the tools to the needs of each team or project. 

Well, I agree, but there are borders. Debates regarding if we want to use spaces VS tabs, or if we want to have braces on a new line or not, don't bring much, but people can fight for this very hard 😀

When tooling just says "ok there is the only way to do so", then life is getting way simpler for everyone. It's the same as nobody debates on a team level about the syntax of a language. And it is like that because you can not configure it

**Pull request merged**
