### PR TITLE
Nick/app widget selected site

### PR DESCRIPTION
**Pull request by nbradbury**
As part of #7288, this PR changes the stats today widget to use the selected site instead of storing the siteId in preferences. No revenue or order stats are shown yet, but the title of the selected site should be showing in the widget.

This PR also ensure that when the selected site changes in the app, the widget is updated to show the newly selected site.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@JorgeMucientes I'm not sure if you've started your review yet, but I wanted to let you know that I pushed a change to this PR that makes sure the widget is updated when the selected site is changed in the app.

**Comment by JorgeMucientes** [comment]
Code looks good and works as expected, nice job @nbradbury 👍🏼 

The only thing I noticed is that if you log out from the app the widget still displays the title for the last store I was logged in with. Is that expected? It should display a non logged in error right? Since I'm uncertain if you intend to tackle that on another PR I'll approve the PR and leave it up to you to merge this now and fix that elsewhere.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by nbradbury** [comment]
@JorgeMucientes Thanks for the review! That's a good catch, but I"ll add it to [my checklist](https://github.com/woocommerce/woocommerce-android/issues/7288) rather than tackle it here.

**Review by atorresveiga — APPROVED** [review]
Looks good to me! :shipit:

**Comment by atorresveiga** [comment]
I will merge this PR as the log-out issue will be tackled in another task

**Pull request merged**
