### PR TITLE
The payment link option in the menu on order details should be removed

### LINKED ISSUE #6668: The Payment Link option in the  `...` menu on Order Details should be removed.

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #6668

### Description

Removes redundant "share payment link" action from the order details screen, because now "collect button" opens payment method selection screen which includes this action 

### Testing instructions

* Create an order in the "ducks-in-row" branch
* Notice that "share payment" action in the order details screen is available
* Create an order in the current branch
* Notice that "share payment" action in the order details screen is not available

### Images/gif

https://user-images.githubusercontent.com/4923871/174961634-dc6271d8-498b-4fdf-a0be-353e073c6b27.mp4

### CODE REVIEW

**Review by rossanafmenezes — APPROVED** [review]
LGTM 👍 @kidinov 

Unrelated to this PR tho, I just noticed the behaviour when you click on the share payment link option and click out of the sharing sheet. It goes all the way back to the Order list. Is this expected? 

Screen Capture on 2022-06-22 at 09-58-00

**Comment by kidinov** [comment]
@rossanafmenezes 

> Unrelated to this PR tho, I just noticed the behaviour when you click on the share payment link option and click out of the sharing sheet. It goes all the way back to the Order list. Is this expected?

Yeah, it doesn't look good to either, My guess is that we don't know if a user actually shared anything that's why we always go back. I think @nbradbury might know more

**Comment by nbradbury** [comment]
> I just noticed the behaviour when you click on the share payment link option and click out of the sharing sheet. It goes all the way back to the Order list. Is this expected?

The assumption is that once the order link has been shared/copied, then the user is done with the order and returned to the list. I'm open to alternative ideas, of course.

Unrelated to that, I didn't seen an issue filed for this on iOS. Currently order detail on iOS has a share menu item, which is now different from WCAndroid.

**Comment by rossanafmenezes** [comment]
> The assumption is that once the order link has been shared/copied, then the user is done with the order and returned to the list. I'm open to alternative ideas, of course.

🤔  It makes sense. In my head I was thinking about an edge situation, you have the sharing modal on and you click outside of it by mistake or because you forgot to add info to the order. I would expect it go back to the screen showing in the background or the order details, but what you said makes sense.

**Pull request merged**
