### PR TITLE
Issue/3726 Fixed buttons styles on order details screen

### PR DESCRIPTION
**Pull request by kidinov**
Parent issue #3726 

Fixes styles of buttons as per design - vaw3DvewbUwuQnPXpdNGGH-fi-178%3A69756

image

image

### How to test
Just open order details (USD cash on delivery order)

### CODE REVIEW

**Review by nbradbury — APPROVED** [review]
Looks good! :shipit:

**Comment by malinajirka** [comment]
@kidinov It seems this change is not behind a feature flag - Could you please double check it all looks good even on stores without card reader support, if you haven't already. Thanks!

**Comment by kidinov** [comment]
@malinajirka  Sorry, I forgot to post a screenshot for this case. 

I think it does look good. Issue refund button was not in line with other buttons on the screen, so I believe that this is an improvement

image

**Comment by malinajirka** [comment]
Awesome, I completely agree that it looks better than the previous button ;)! Thanks for double-checking!

**Pull request merged**
