### PR TITLE
Issue/database ondowgrade

### PR DESCRIPTION
**Pull request by nbradbury**
Right now we handle database downgrades only in `DEBUG` builds, and it's pretty clunky. At startup the user gets taken to a site picker that tells them there are no stores in the current account until the store list is fetched a few seconds later.

In this PR we do two things:

1. Also handle downgrades in beta releases. This is a draft PR because I'd like feedback on whether we should do this. We've had a couple of beta releases go badly due to a database downgrade, so it would be good to have this. However, this means release builds would _not_ handle downgrades - they would simply crash (as they do now).

2.  When a downgrade is detected, the site picker no longer appears. Instead, the main activity fetches the site list and updates when the fetch is completed.

To test, I recommend adding this to WooWellSqlConfig:

```
override fun getDbVersion() = 999
```

Run that once, then each time afterwards reduce the version by one. That will trigger the downgrade.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by nbradbury** [comment]
> In low internet situations, the site picker is displayed when no stores but a button to login again.

I'm not able to reproduce this. That _was_ the situation prior to this PR but this PR _should_ correct that. Is there any chance you switched branches?

**Comment by anitaa1990** [comment]
> I'm not able to reproduce this. That was the situation prior to this PR but this PR should correct that. Is there any chance you switched branches?

I'm not able to reproduce this either anymore :) I _did_ switch branches from the stats UI changes, so it could be because of that.

**Comment by nbradbury** [comment]
> sorry, I was able to reproduce this

Ah! Okay, I see what's happening. My code incorrectly assumes the store list was fetched successfully. When it can't be fetched - which is easy to reproduce by enabling airplane mode - it returns the user to the site picker, which says the app can't find any stores.

Technically that's correct in that it did fail to find any stores, but it's not very friendly. The problem is without any stores in the database the app is useless (in fact, it will crash if you try to change tabs). Because of this we do need to close the main activity.

I _think_ this will be such a rare situation that I'm fine with leaving it alone (how often are we going to have a database downgrade coupled with no connection?), but if you or @kyleaparker think otherwise I'm fine to change it.

**Comment by anitaa1990** [comment]
> I think this will be such a rare situation that I'm fine with leaving it alone (how often are we going to have a database downgrade coupled with no connection?)

😄 Yup, I agree this is a rare corner case that happens only when there is no internet connection. I feel that it’s probably fine to wait on this and if we get a lot of confused users, we could address it then?

**Comment by nbradbury** [comment]
> I feel that it’s probably fine to wait on this and if we get a lot of confused users, we could address it then?

👍

**Comment by nbradbury** [comment]
> I'm good to merge these changes! I'm not sure if @AmandaRiu would like to take a look before we merge?

I think she's off the rest of the week, so I'd say it's okay to go ahead and merge.

**Pull request merged**
