### PR TITLE
Refund by items

### PR DESCRIPTION
**Pull request by 0nko**
This PR brings the refund by items feature. All code has already been reviewed and tested in sub-PRs so this can be merged after a quick smoke test.

image

image

image

image

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@0nko Has a design review been requested and approved for this feature branch?

**Comment by 0nko** [comment]
@nbradbury No. I'll do that now.

**Comment by AmandaRiu** [comment]
@nbradbury I'm doing a code freeze for 3.3 now. Please target the `release/3.3` branch when this is ready for merging. We can do another beta release at that time.

**Comment by AmandaRiu** [comment]
After speaking with Nick we've agreed to move this one to release 3.4.

**Pull request merged**
