### PR TITLE
Fix incorrect image upload error message

### PR DESCRIPTION
**Pull request by 0nko**
This PR fixes the wrong private site status message for self-hosted sites, which prevents the app from uploading images.

**To test:**
1. Create a self-hosted site with WooCommerce but without installing Jetpack or connecting a WP.com user using JCP
2. Log in to the app
3. Start creating a product
4. Verify the image uploading is available

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207315305241121

### CODE REVIEW

**Review by hichamboushaba — APPROVED** [review]
Thanks for taking care of this @0nko, it works well.

Before merging this, it seems to me this is a serious bug, shouldn't we include it in the current beta version?

**Comment by 0nko** [comment]
Thanks @hichamboushaba. I've rebased the branch onto `release/18.6`

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/211">18.6 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hichamboushaba** [comment]
> Thanks @hichamboushaba. I've rebased the branch onto release/18.6

Thanks @0nko, there is a failing unit test that's preventing the merge.

**Pull request merged**
