### PR TITLE
Update Woo with latest changes to the login library

### PR DESCRIPTION
**Pull request by anitaa1990**
The login library went [through a refactor recently](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/52) and this PR just updates the Woo app with those changes. 

### Changes
- Most of the color resources have been removed from `WordPressLoginFlow/colors.xml`. There were a couple of places in the app that were using those colors and commit 2de1224 updates those to use different set of colors.
- The `WordPressLoginFlow/build.gradle` file was updated to use the latest version of material design and constraintLayout.
- There were a couple of drawable files that were deleted from the login lib and commit 5688b24 updates some files to use a different drawable.
- Some methods in the `LoginListener` and `LoginAnalyticsListener` were updated and commit bea19bc removed those methods from the `LoginActivity`.

### Testing
There should be no behavioural changes in the Login flow as such and no designs have been changed. I've written down a few scenarios I think are worth testing before this PR can be merged.

**It would be good to test screen in the login flow in dark mode and light mode to verify that there have been no design changes.**

###### Scenario 1: Login by entering password
- Click on `Enter your store address`.
- Enter a valid store address with Woo + Jetpack installed.
- Enter a valid email address and click on `Continue`.
- Enter the password and click on `Continue`.
- Verify that you are logged into the site you entered in step 1.

###### Scenario 2: Login by magic link 
- Click on `Enter your store address`.
- Enter a valid store address with Woo + Jetpack installed.
- Enter a valid email address and click on `Continue`.
- Click on `Get a login link by email`.
- Check your email and click on the link.
- Verify that you are logged into the site you entered in step 1.

###### Scenario 3: Login by site credentials   
- Click on `Enter your store address`.
- Enter a valid store address with Woo + Jetpack installed.
- Click on `Continue with Store Credentials` button.
- Enter a valid username + password and click on `Continue`.
- Try to test both magic link scenario and type password scenario.
- Verify that you are logged into the site you entered in step 1.

###### Scenario 4: Login by site credentials   
- Click on `Enter your store address`.
- Enter a valid store address with Woo + Jetpack installed.
- Click on `Continue with Store Credentials` button.
- Enter a valid username + password and click on `Continue`.
- Try to test both magic link scenario and type password scenario.
- Verify that you are logged into the site you entered in step 1.

###### Scenario 5: Enter invalid site address   
- Click on `Enter your store address`.
- Enter a valid url (google.com) that does not have WordPress.
- Notice you are redirected to an error screen that states WordPress is not installed on the site.
- Click the back button and now enter an invalid site url.
- Notice that an error message is displayed below the site url field.
- Verify that the `finds your site address` link is clickable.

###### Scenario 6: Enter a site with no Woo or Jetpack
- Click on `Enter your store address`.
- Enter a valid url for a store that does not have Woo or Jetpack installed.
- Notice you are redirected to an error screen that states Jetpack is required.
- Click the back button and enter a valid url to a store that has Jetpack but not Woo.
- Enter a valid email address and click on `Continue`.
- Enter a valid password and click on `Continue`.
- Notice that you are redirected to an error screen that states you the site is not a WooCommerce site.

###### Scenario 1: Login by entering email
- Click on `Continue with WordPress.com`.
- Enter a valid email address and click on `Continue`.
- Enter the password and click on `Continue`.
- Verify that you are redirected to the Site picker screen after successful login.

###### Scenario 2: Login by Google
- Click on `Continue with WordPress.com`.
- Click on `Continue with Google`.
- Enter the password and click on `Continue`.
- Verify that you are redirected to the Site picker screen after successful login.

Please do smoke test the app to verify if everything is working correctly.

### CODE REVIEW

**Comment by nbradbury** [comment]
This makes me happy :)
Screen Shot 2021-04-01 at 12 48 00 PM

**Comment by nbradbury** [comment]
I see @0nko has been assigned to review this, but given the importance of login I figured more eyes on this couldn't hurt. 

I wasn't able to test magic link (that has never worked for me), but the other scenarios tested fine. FWIW, I ran into some issues that turned out to be problems in `develop` as well (ie: they're not the fault of this PR). I filed #3789 and #3790 for these.

So this gets a :shipit: from me, but we'll want @0nko to look at it beforehand.

**Comment by anitaa1990** [comment]
Thank you for testing @nbradbury! I think Ondrej got assigned because of the automated PR assignment we have :)

> I ran into some issues that turned out to be problems in develop as well (ie: they're not the fault of this PR). I filed #3789 and #3790 for these.

I failed to mention Known issues in the PR description. I ran into those two as well and had filed issues in #3445  and #3776 for it :) 

> So this gets a :shipit: from me, but we'll want @0nko to look at it beforehand. 

Since Ondrej is AFK till Tuesday I'm good to merge this PR if it's got a 👍 from you

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
