### PR TITLE
Add/Edit Products Release 1 - Update Product Inventory - Step 2

### PR DESCRIPTION
**Pull request by anitaa1990**
This PR addresses step 2 of #1614 by adding the new product inventory Editing screen. Note that this PR only adds the new UI screen for the product inventory screen. The logic to actually update the product inventory will take place in another PR.

#### Notes
- Added the `Not ready for merge` label since this [step 1 PR](https://github.com/woocommerce/woocommerce-android/pull/1810) needs to be reviewed and merged before merging this PR.
- Targeting `develop` branch since this change affects only debug users.
- Note that this PR has some TODO's in the code that will be addressed in the next PR.

#### Screenshots
(LEFT: when manage stock is enabled . RIGHT: when manage stock is disabled)
 . 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by jkmassel** [comment]
Bumping this PR to `3.5` as part of the `3.4` code freeze.

**Comment by nbradbury** [comment]
I've removed the "not ready for merge" label since #1810 has been merged, and I'll review this shortly.

**Comment by nbradbury** [comment]
@anitaa1990 This looks great! I did notice that if the stock status dialog or backorder dialog is showing it disappears when the device is rotated, but this can be addressed in another PR. :shipit:

**Comment by anitaa1990** [comment]
Thanks for the review @nbradbury!! 

> I did notice that if the stock status dialog or backorder dialog is showing it disappears when the device is rotated

I noticed this was the behaviour when we try to change order status in the order detail screen so I retained the same logic here to keep the behaviour consistent. I've opened a separate issue [here](https://github.com/woocommerce/woocommerce-android/issues/1869) so we can discuss and implement a consistent behaviour for this across the app.

**Pull request merged**
