### PR TITLE
Add Coupon selector files for order creation

### LINKED ISSUE #9463: Add Order Create Coupon Selector files
Add Order Create Coupon Selector files (VM, Fragment and Screen)

### PR DESCRIPTION
**Pull request by rossanafmenezes**
Closes: #9463 

### Description

Add initial files for the order creation coupon selector

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by samiuelson — APPROVED** [review]
Good start!

I'd personally put these classes in `com.woocommerce.android.ui.coupons.selector` package similar to ProductSelector. But this is not crucial, so I'll leave it for you to decide.

**Comment by rossanafmenezes** [comment]
Thanks @samiuelson It makes more sense. I have created the /Selector package and moved the files there.

**Comment by samiuelson** [comment]
@rossanafmenezes Sorry, I forgot to mention, we could also rename these classes, e.g. `OrderCreateCouponSelectorFragment` to `CouponSelectorFragment`, and the same for view model and screen files. Maybe they will be used in other places than order creation in the future, so it would make sense to make them loosely connected to order creation.

**Comment by rossanafmenezes** [comment]
> @rossanafmenezes Sorry, I forgot to mention, we could also rename these classes, e.g. `OrderCreateCouponSelectorFragment` to `CouponSelectorFragment`, and the same for view model and screen files. Maybe they will be used in other places than order creation in the future, so it would make sense to make them loosely connected to order creation.

Thanks, @samiuelson . I have renamed the files (and classes) here [7e75bea](https://github.com/woocommerce/woocommerce-android/pull/9466/commits/7e75beabd4129d93ce372012a20f94e21f426655)

**Pull request merged**
