### PR TITLE
Coupons: Make Empty Product Selector Screen be Scrollable

### LINKED ISSUE #6854: [Coupons] - Landscape mode - can't clear filter when there are no results for products/categories
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Turn on Coupon Management beta feature
2. Use landscape mode > Go to Menu > Coupon > Select a coupon > Edit coupon
3. Scroll down to All Products / Select Product Categories 
4. Filter by something that will not return any results
5. No results screen returned, see that screen is not scrollable on landscape mode and merchant can't see/click the Clear Filters button

**Screenshots**
no search results android

**Expected behavior**
Screen should be scrollable so that button can be clicked

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: OPPO Reno6 Z 5G
- Android version: 12
- WooCommerce Android version: Alpha build woocommerce-installable-build-pr6825-eb80fd5.apk

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #6854

### Testing instructions

1. Turn on Coupon Management beta feature
2. Use landscape mode > Go to Menu > Coupon > Select a coupon > Edit coupon
3. Scroll down to All Products / Select Product Categories
4. Filter by something that will not return any results
5. This will show the empty product screen. Make sure the screen is scrollable and the "Clear Filters" button can be seen and tapped.

### Video

https://user-images.githubusercontent.com/266376/177297957-5ea42087-2e74-4923-9668-bff4441d59ec.mov

### CODE REVIEW

**Comment by hafizrahman** [comment]
I wonder if it's better to just move the "Clear Filters" button to the top instead of making customers scroll, when in landscape mode 🤔

**Review by hichamboushaba — APPROVED** [review]
LGTM 👍  

> I wonder if it's better to just move the "Clear Filters" button to the top instead of making customers scroll, when in landscape mode

I'd say it's fine as is, I don't think people use the app in landscape mode often.
But I'll leave the decision to you 🙂, I'll leave the PR unmerged for now.

**Comment by JorgeMucientes** [comment]
Sorry for chiming in! To me, it looks good as it is. 

I just wanted to ask if we have tracked somewhere else the fact that you have to click twice in "Show Products" button after selecting your filters. I notice this while testing this PR but this happens in other places of the app where product filters are used. 

https://user-images.githubusercontent.com/2663464/177730488-1fb09634-97a3-4521-9a5f-a70894fefbf3.mp4

**Comment by hafizrahman** [comment]
@JorgeMucientes Thanks for that feedback! I've added it in my to-do list to double-check that and make an issue for it if needed.

**Pull request merged**
