### PR TITLE
Feature/8260 sync onboarding task list

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Part of: #8260 

### Description
Fetches onboarding tasks from API and updates the UI accordingly. This works for both WP.com sites and self-hosted sites

### Testing instructions

**Atomic site**
1. Create a new site (doesn't have to be through the app store creation flow)
2. Check the onboarding list is displayed
3. Complete at least one of the visible tasks on the list and check that it is marked as compelted. The easiest one to complete is usually add a new product. 

**Selfhosted site**
1. Create a self hosted site 
2. Check that 3 tasks are displayed: Tell us more about your store, Add your first product and Get paid. Launch store and customise domain are not available for self hosted sites.

### CODE REVIEW

**Review by 0nko — COMMENTED** [review]
The UI looks great, but when I tested a task completion (adding a product) with an atomic site, the UI was never updated even after I used PTR to refresh the site. Only after I killed the app and started it it would show the task as complete. Is that expected?

Also, the items are not clickable, but I suppose that's still WIP, right?

**Comment by JorgeMucientes** [comment]
Hey @0nko thanks for reviewing this! 

> Also, the items are not clickable, but I suppose that's still WIP, right?

Yes, I'll add the clickable handler once I start working on the specific task

> but when I tested a task completion (adding a product) with an atomic site, the UI was never updated even after I used PTR to refresh the site. Only after I killed the app and started it it would show the task as complete. Is that expected?

That is actually a good point. So far that behavior is expected as I'm only refreshing the list from the API once every time the app has a fresh start. I have mixed feelings about fetching data from the API for every "onResume" of my store tab. I'll bring this debate to Slack as I how often we refresh the status of the list is more of a product decision that it also involves iOS devs.

**Review by 0nko — APPROVED** [review]
The code looks good. 👍 I'll leave it up to you what to do about the fetching. From the user point of view, however, I found it confusing that the task status didn't update (especially after deliberately refreshing using pull-to-refresh).

Nice work!

**Comment by JorgeMucientes** [comment]
Thanks for the feedback @0nko. I agree with you points regarding the refreshing of the list. I'll address the new refresh policy in a different PR and merge this one to avoid blocking the other PRs that are dependent on this PR being merged.

**Pull request merged**
