### PR TITLE
Filtering out the current product from the product selection list

### LINKED ISSUE #4521: Linked Products: consider filtering out the current product from the list when linking products
Should Android match with iOS regarding filtering out the current product from the list when adding linked products?

Steps to reproduce:

1. Open any product for editing.
1. Go to the Linked products detail.
1. Attempt to add the product you are currently editing as an Upsell.
1. Attempt to add the product you are currently editing as a Cross-sell.

**Result:** it's possible to add a linked product to itself on Android ([1m7s](https://user-images.githubusercontent.com/1119271/127563097-418d2d74-ec28-4d3d-90a1-181a761e77e6.mp4)) but on iOS the current product is filtered out of the "Add product" screen so you cannot link a product to itself ([52s](https://user-images.githubusercontent.com/1119271/127563136-1fa736db-4c9e-481d-8c47-ed6609a466fb.mp4)).

image Screen Shot 2021-07-29 at Jul 29 2 50 15 PM
<sup>Tested with WCiOS 7.2.0.0 TestFlight beta on iPhone 11 iOS 14.7.1.</sup>

<sup>(internal reference: p5T066-2wI-p2#comment-9355 /hat tip @pmusolino)</sup>

### PR DESCRIPTION
**Pull request by SowmiaS**
Fixes #4521
### Description
Currently the user can add a product under upsell/cross-sell products of itself.
It is not meaningful to have the product listed under upsell/cross-sell products of itself.
So the current product should be excluded from product selection list screen.
### Demo

https://user-images.githubusercontent.com/4975407/137851965-3c856f39-49b4-4e1c-8547-1f4cb2d04168.mp4

https://user-images.githubusercontent.com/4975407/137851929-e8f976de-c44a-42f9-b147-e96285bb1cd3.mp4

#### Test Case 1:
Given that I have products “A”, “B”, “C”, “D”
And Then I click the product “A”
When I navigate to add products selection Page for Upsells/Cross-sells
Then I should be able to see products “B”, “C”, “”D
And  I should not see product “A”
#### Test Case 2:
Given that I have products “A”, “B”, “C”, “D”
And Then I click the product “A” which has upsell/cross-sell product - “B”
When I navigate to edit products selection Page for Upsells/Cross-sells
Then I should be able to see product “B”
And  Then I click “AddProducts” button
Then I should be able to see products “C”, “D”
And I should not see product “A” ( which is the product itself )
And I should not see product “B” ( which is already added product )

### CODE REVIEW

**Comment by shiki** [comment]
I just realized that Ondrej is AFK. 🤦 @AnirudhBhat or @ThomazFB, would one of you be able to review this? 🙂

**Comment by anitaa1990** [comment]
I assigned the PR to myself since it's from an outside contributor 😊 Thanks for staying on top of this @shiki!

**Review by anitaa1990 — APPROVED** [review]
The changes look good 👏 Thank you for working on this @SowmiaS!

**Comment by anitaa1990** [comment]
@SowmiaS there is one lint issue in the PR. I've updated the PR to fix the lint issue but just wanted to give you a heads up that you can run `./gradlew detektAll` from the project root in the terminal and this will identify any lint issues in the PR, that you can fix 😄

**Comment by 0nko** [comment]
Thanks for taking care of this, @anitaa1990!

**Pull request merged**
