### PR TITLE
[Woo POS] Simulate overlay for the connect reader button

### LINKED ISSUE #12587: [Woo POS] More Products Screen changes
Related to this issue:
https://github.com/woocommerce/woocommerce-android/issues/12556

https://wp.me/pdfdoF-5iv

❓ Design. Products Screen bottom Move reader connection behind screen:

[Image](https://private-user-images.githubusercontent.com/947561/365290193-e3ae2476-2c56-46f9-a14c-d4c0074717ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MTkyMTMsIm5iZiI6MTcyNjUxODkxMywicGF0aCI6Ii85NDc1NjEvMzY1MjkwMTkzLWUzYWUyNDc2LTJjNTYtNDZmOS1hMTRjLWQ0YzAwNzQ3MTdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQyMDM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWNjNGJlMzQyZWY3OTY0OThiZmMwMmZlMWRlZDIxYjAzNjkwMzI2NDIwNzNhYzUxNjAzMzkwYmExMjBkYmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TdqpIYCGw2DKA3En9_LotAA25u3gVqzu_i55Hbrp_EU)

and

❓ Design. Products Screen bottom Shadow appears after card. This one will probably be addressed in this PR:
https://github.com/woocommerce/woocommerce-android/pull/12557

### LINKED ISSUE #12629: [Woo POS] Move reader connection button behind the overlay when a menu shown

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12587

### Description

The PR adds a simulation of the overlay on top of the "connect reader" button when the menu is shown

### Steps to reproduce

Open pos -> click on the menu button

### Testing information

Try both dark and light modes

### The tests that have been performed

What;s in the steps to reproduce

### Images/gif

https://github.com/user-attachments/assets/bec27f09-44ed-4622-b16f-5ca872eb2cd1

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
Nice. I understand what was meant by `Move reader connection behind screen` now.

**Comment by backwardstruck** [comment]
> ## [Codecov](https://app.codecov.io/gh/woocommerce/woocommerce-android/pull/12631?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce) Report
> Attention: Patch coverage is `0%` with `23 lines` in your changes missing coverage. Please review.
> 
> > Project coverage is 40.63%. Comparing base [(`2c07c11`)](https://app.codecov.io/gh/woocommerce/woocommerce-android/commit/2c07c116a12a937b910fbb4d95098d98674e3e8d?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce) to head [(`7aed80b`)](https://app.codecov.io/gh/woocommerce/woocommerce-android/commit/7aed80b23d80b490bf42b8c20f555a1d006454a5?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce).
> 
> [Files with missing lines](https://app.codecov.io/gh/woocommerce/woocommerce-android/pull/12631?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce)	Patch %	Lines
> [...ce/android/ui/woopos/home/toolbar/WooPosToolbar.kt](https://app.codecov.io/gh/woocommerce/woocommerce-android/pull/12631?src=pr&el=tree&filepath=WooCommerce%2Fsrc%2Fmain%2Fkotlin%2Fcom%2Fwoocommerce%2Fandroid%2Fui%2Fwoopos%2Fhome%2Ftoolbar%2FWooPosToolbar.kt&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce#diff-V29vQ29tbWVyY2Uvc3JjL21haW4va290bGluL2NvbS93b29jb21tZXJjZS9hbmRyb2lkL3VpL3dvb3Bvcy9ob21lL3Rvb2xiYXIvV29vUG9zVG9vbGJhci5rdA==)	0.00%	[23 Missing ⚠️ ](https://app.codecov.io/gh/woocommerce/woocommerce-android/pull/12631?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce)
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/woocommerce/woocommerce-android/pull/12631?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=woocommerce).

I don't think we need a unit test for this.

**Review by backwardstruck — APPROVED** [review]
Tested in light and dark mode. Code change is good.

**Pull request merged**
