### PR TITLE
[Issue 3885] product variation delete confirmation dialog to a dialog fragment

### LINKED ISSUE #3885: [Variations] Delete confirmation dialog dismissed when the device orientation changes
Inside `VariationDetailFragment` when selecting the delete variation option, if the device rotates, the confirmation dialog is dismissed, we should be able to make the dialog visible for any orientation change.

| Select the Delete | Rotate the device when the confirmation dialog shows up |
| ------------- | ------------- |
| image | image |

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes: #3885

### Description
This PR was created to address the issue where the confirmation dialog is dismissed upon device rotation in the `VariationDetailFragment`, some notable changes:

1. Reattaching the Listener: A method named `reattachDialogInteractionListener` was added to the VariationDetailFragment. This method is called within `onViewCreated` to re-establish the connection between the `VariationDetailFragment` and the `WooDialogFragment`. It checks if the dialog is currently displayed and, if so, sets the current instance of `VariationDetailFragment` as the listener to the dialog. This ensures that the dialog can continue to communicate with the active instance of the fragment after a configuration change.

3. Event Handling: The ViewModel was updated to handle the delete action through a `ShowDialogFragment` event. This event encapsulates all necessary information to display the dialog, including message IDs and button texts. When the event is triggered, the dialog is shown with the current context, and any actions taken in the dialog are communicated back to the ViewModel through the established listener interface.

4. Observing Lifecycle Events: The `VariationDetailFragment `observes the `ShowDialogFragment` event. If the fragment is recreated due to an orientation change, the observer ensures that the dialog is shown again with the correct listener attached.

### Testing instructions

1. Click a production with multiple variations. 
2. Click Variations. 
3. Open a variation. 
4. Click the menu option. 
5. Press Delete. 
6. See the dialog visible. 
7. Rotate the device and realize that the dialog is still open. 
8. Verify that the actions on the dialog work as expected.

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/1509205/b8135256-c6e0-4c42-807d-b9887b17b202

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ShowDialogFragment</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/191">17.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jd-alexander** [comment]
Hi @AnirudhBhat I've reviewed the PR requirements regarding Tracks-related updates. I want to clarify that my changes only involved moving existing Tracks logic to a new function, without altering its behavior or the events it triggers. Given this, I'm unsure if the full validation process in the Tracks system and updating the internal spreadsheet is necessary. Could you advise if these steps are still needed for such changes? Thanks for your guidance!

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @jd-alexander. Works as expected! :shipit:

**Comment by AnirudhBhat** [comment]
> Given this, I'm unsure if the full validation process in the Tracks system and updating the internal spreadsheet is necessary. Could you advise if these steps are still needed for such changes?

Sorry, I missed your comment. This PR does not require any modifications to the spreadsheet since it only involves reorganizing existing events, without adding or removing any.

**Comment by jd-alexander** [comment]
> > Given this, I'm unsure if the full validation process in the Tracks system and updating the internal spreadsheet is necessary. Could you advise if these steps are still needed for such changes?
> 
> Sorry, I missed your comment. This PR does not require any modifications to the spreadsheet since it only involves reorganizing existing events, without adding or removing any.

No problem! Thanks for chiming in. I appreciate it @AnirudhBhat

**Pull request merged**
