### PR TITLE
Fix timezone issue when running UI tests for Order list

### LINKED ISSUE #1105: Order Detail: UI tests failing for order detail screen
When testing this [PR](https://github.com/woocommerce/woocommerce-android/pull/1094), @AmandaRiu noticed some of the UI tests failing in `OrderListItemTest`.

### Screenshot
Screen Shot 2019-05-29 at 2 06 51 PM

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #1105 by adding logic for a fixed timezone when running UI tests in `OrderListItemTest`.

### Testing
I was able to reproduce this issue by changing the timezone in the emulator to `Midway` which was **GMT-11:00**. I think we could also change the timezone to plus or minus 11 hours. 
Checkout the `develop` branch and run `OrderListItemTest`. 4 of the tests will fail.

Pull the changes from this branch and try again. All tests should pass.

### CODE REVIEW

**Comment by loremattei** [comment]
Hey! I'm moving this to 2.1 because 2.0 has been cut. If you want it to land 2.0, please feel free to move it back, target the release branch and ping me to build a new beta :-)

**Comment by anitaa1990** [comment]
> I changed my timezone to Midway and all tests passed, but those four tests failed when I changed it to Hawaii-Aleutian Standard Time (GMT-10).

Oh, that's weird! I tested multiple timezones in different devices and I am not able to reproduce this. Could this be a specific device issue? Could you let me know which api you were using to test? I will try to reproduce this?

**Comment by nbradbury** [comment]
> Could you let me know which api you were using to test?

This was on a Pixel 2 emulator running API 27 (Oreo).

**Comment by anitaa1990** [comment]
Update: tried running multiple timezones in emulator 27 and 28. Still not able to reproduce the failure scenario

**Comment by anitaa1990** [comment]
@nbradbury I wasn't able to reproduce this issue but I thought it might be timezone related. So modified the logic a bit to fetch current UTC time instead of the current time based on the locale. This meant regardless of the timezone, the UI tests should be able to pass successfully. The tests are working for me in multiple timezones but given that I wasn't able to reproduce this successfully, could I trouble you to run this again and see if it is working for you?

**Comment by nbradbury** [comment]
@anitaa1990 I'm sorry to say that those four tests are still failing. In each case, the exception is something like this:

```
android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: RecyclerView with id: com.woocommerce.android:id/ordersList at position: 5
```

**Comment by anitaa1990** [comment]
@nbradbury Thanks for the quick review! I merged the latest androidx changes from `develop`. It went really smoothly 😄.  
> In each case, the exception is something like this: `android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: RecyclerView with id: com.woocommerce.android:id/ordersList at position: 5`

Yup, this is related to timezone. The tests are expecting the order list to be grouped in a particular segment based on the time and it seems it is getting messed up when running into multiple timezones. I tried to replicate the timezone issue by modifying my device time and was able to replicate it. I've tried to modify the logic a little bit in 387b4c9. Could I trouble you to check one more time? Thanks!

**Comment by nbradbury** [comment]
Good news - all tests pass now! :shipit: 

Screen Shot 2019-06-06 at 7 45 04 AM

**Pull request merged**
