### PR TITLE
Add navigation tests for Order list to Order detail screen

### LINKED ISSUE #168: Create Navigation Tests for Order List to Order Detail
Write the following tests for PR #155 

**While on the Order List View:**
* [ ] Clicking on an order item in the orders list ("Orders") opens the OrderDetailFragment.

**While inside the Order Detail View:**
* [ ] Toolbar title displays "Orders #" + order number.
* [ ] "UP" navigation button is displayed in the toolbar 
* [ ] Clicking the device "back" button returns the user to the orders list screen. The Toolbar title changes to "Orders" and the "UP" button is no longer shown.
* [ ] Clicking the "Dashboard" bottom bar option loads the DashboardFragment, then clicking the "Orders" bottom bar option loads the OrderListFragment (so the detail view should no longer be visible)
* [ ] Clicking the "Orders" bottom bar option loads the OrderListFragment and changes the Toolbar title to "Orders".

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #168. This is the first PR in a series that adds basic UI navigation tests for `OrderListFragment`. This includes:

-  [x] Clicking on an order item in the orders list ("Orders") opens the OrderDetailFragment. 

While in the `OrderDetailFragment`:
-  [x] Toolbar title displays "Orders #" + order number.
-  [x]  "UP" navigation button is displayed in the toolbar
-  [x]  Clicking the device "back" button returns the user to the orders list screen. The Toolbar title changes to "Orders" and the "UP" button is no longer shown.
-  [x] Clicking the "Dashboard" bottom bar option loads the DashboardFragment, then clicking the "Orders" bottom bar option loads the OrderListFragment (so the detail view should no longer be visible)
-  [x] Clicking the "Orders" bottom bar option loads the OrderListFragment and changes the Toolbar title to "Orders".

## To Test:
- [x]  Run `OrderListNavigationTest`

### CODE REVIEW

**Comment by anitaa1990** [comment]
@AmandaRiu @aforcier, @nbradbury , could I trouble you all for a review on this PR please?

**Comment by AmandaRiu** [comment]
@anitaa1990 seeing some merge conflicts on this and the label "not ready for merge". Please fix the conflcts and remove that label when ready for review. Thanks!

**Comment by anitaa1990** [comment]
@AmandaRiu resolved merge conflicts. This is definitely ready for a review. Sorry for the confusion! I remembered during the trial that the tag `Not ready for merge` was added till review was completed so added it here.

**Comment by anitaa1990** [comment]
Merged all the UI test PRs into a single [PR](https://github.com/woocommerce/woocommerce-android/pull/1041) so closing this

**Pull request closed without merging**
