### PR TITLE
Issue [5973] Calculate percentage fee

### LINKED ISSUE #5973: [Order Creation] Retain state of "Percentage fee" checkbox when editing a fee
Discussed in p1646250815730879-slack-C02KUCFCSFP. 

https://user-images.githubusercontent.com/198826/156442515-95c94ae1-1509-44b3-ac2f-32f45a9b53f0.mov

## Steps

1. Tapped on Fee to add a fee.
2. Checked Percentage fee.
3. Entered 10 (percentage)
4. Pressed Done.
5. Tapped on Fee to edit that fee.
6. The Percentage fee checkbox is not checked. It's showing me the Amount instead of the percentage that I entered.

## Discussion

This seems like a limitation since we save the fixed amount even if they entered a percentage. There's no easy way to tell if they previously entered a percentage. Core also behaves similarly. 

We could probably use `meta` to keep the state.

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #5973

### Description
Please don't merge this PR until it is approved by design

This PR aims to fix the loss of the percentage state by adding some clarification to what the app is doing (calculate the fee as a percentage but save as an amount). Now when the user switches to calculating the fee as a percentage, the user can also see the fee amount result. Also, it removes the fee tax total from the fee percentage calculation for a more accurate result.

#### Test 1
1. Orders -> New Order (+) -> Create Order
2. Add fee -> Check that **calculate percentage** is hided
----
#### Test 2
1. Orders -> New Order (+) -> Create Order
2. Add product -> Select product
4. Add fee -> Check calculate percentage is shown
5. Press **calculate percentage** -> Enter a percentage -> Check the calculated amount is shown and updates accordingly
6. Switch calculate percentage several times
----
#### Test 3
1. Orders -> New Order (+) -> Create Order
2. Add product -> Select product
3. Add fee -> Check calculate percentage is shown
4. Press calculate percentage -> Enter a percentage -> Press Done
5. Remove the product (-) -> Press remove order from product
6. Add fee -> Check that **calculate percentage** is hided
----
#### Test 4
Run OrderCreationViewModelTest
Run OrderCreationFeeViewModelTest

#### Final result

https://user-images.githubusercontent.com/18119390/165353286-1fd4e521-45a5-4052-8320-675edd290883.mp4

#### First iteration
https://user-images.githubusercontent.com/18119390/161331467-263b0c26-b299-45e9-bf01-36a0971a210e.mp4

#### Evidence
When calculating user fees, fees' taxes should be removed from the order's total.

In this example, I started by adding a product that cost 25.00, and with taxes, the order total became 25,50
Applying a fee of 10% turns into a fee of the 10% of 25,50 -> 2,55
Now, if I tried to modify that fee to the same amount (remove the 10% and set 10% again). As the percentage calculation includes the fee tax the new result is 2,74 and not the initial 2,55

https://user-images.githubusercontent.com/18119390/165530939-4108472f-5a5a-4aa0-a135-fa72116f40d0.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by joe-keenan — APPROVED** [review]
Overall, this is looking great!
I’ve been sitting here for half an hour trying to understand how the tax calculation interacts with the percentage calculation, and it’s breaking my brain. So I’m going to trust that you know what you’re doing on that front. 
From my testing, the calculated percentage is based on order total – tax inclusive. 
So [$10 product + $5 tax] shows a 50% fee as $7.50. Once selected, the tax and order total are then recalculated to include the fee. Unlike your third video, I could still see the percentage calculation option. I hope this is right because even though it’s a little confusing, I think it’s still useful.
I think we might be able to make it clearer by stating that the calculation is tax inclusive (if tax > 0, anyway), but it may not be necessary.
I’m very curious to hear user feedback about this interface, from people that have taxes set up, and use the percentage fee.

**Comment by atorresveiga** [comment]
@joe-keenan I updated the video with a more detailed explanation of what I mean for a more accurate percentage calculation.  I hope it helps.
> From my testing, the calculated percentage is based on order total – tax inclusive.

That's right. In the previous version, we used the order total to calculate the percentage fee (products + shipping + taxes). I have only updated the function to remove the tax related to the fee in the calculation to be more accurate.

**Comment by nbradbury** [comment]
@atorresveiga I'm afraid I'm also a bit confused by the UI. In the video below I added a 10% fee, but when I edit that fee it shows as 10.09%. 

https://user-images.githubusercontent.com/3903757/165566694-88c6ab22-9f83-4e9b-8d35-21b0ac65d3aa.mp4

**Comment by atorresveiga** [comment]
>  In the video below, I added a 10% fee, but when I edit that fee, it shows as 10.09%.

@nbradbury Hi Nick! The video shows that the order total (products + taxes) is 3.27. When you apply a 10% fee, the fee value should be 0.327, and it gets rounded to 0.33. Then if you try to edit the fee when you calculate back 0.33 (the rounded value) from 3.27 (your original order total product + taxes), the result is rounded to 10.09 (10.0917431193) from this calculation (0.33 * 100 / 3.27).

Steps

- Original order total (product + taxes) = 3.27
- Calculate a 10% fee, 10% from 3.27 = 0.327 ~ 0.33 (Now the fee is higher than 10% )
- Edit the fee of 0.33
- Calculate from %  (0.33 * 100 / 3.27) 0.33 represents ~ 10.09% of 3.27

Please let me know if this helps.
I'm thinking that (as pointed out by @joe-keenan) including the taxes and shipping in the percentage calculation could be a bit confusing 🤔.
Should we use only the product total? WDYT @joe-keenan @shiki @nbradbury?

**Comment by nbradbury** [comment]
> When you apply a 10% fee, the fee value should be 0.327, and it gets rounded to 0.33

@atorresveiga Do we have to do the rounding? I ask because to me this is a confusing experience.

**Comment by atorresveiga** [comment]
@nbradbury IMO rounding was the more accurate way to represent the real value. In this example, 0.327 could be represented either as 0.32 or 0.33. Note that 0.32 will have an error of 0.07 (0.327 - 0.07 = **0.320**) while 0.33 an error of 0.03 (0.327 + 0.03 = **0.330**). Maybe I'm missing something here. Is there anything we could do on our end without involving the rounding to represent a value like the one mentioned before **0.327**? WDYT?

**Comment by joe-keenan** [comment]
Math is not my strong suit, so feel free to ignore me, but could we store the full, pre-rounded values, and use those for calculations, while displaying rounded values in the interface?

**Comment by nbradbury** [comment]
@hichamboushaba @shiki Could I get your opinion on [this](https://github.com/woocommerce/woocommerce-android/pull/6151#issuecomment-1111207362)? I really like the solution, but the user experience feels broken to me in that the percentage changes when you edit the fee.

**Comment by shiki** [comment]
Relaying what Joe mentioned in https://github.com/woocommerce/woocommerce-android/issues/5973#issuecomment-1081351873:

> Until we can overcome the technical issue, the only thing I can think of is adding some clarification.
>
> - Change “Percentage fee” to “Calculate as a percentage”
> - Add a caption to the field: “Calculated amount: $23.99”
>
> You’ll enter the percentage, see the dollar value, and confirm your decision. Then on the order details screen, you’ll recognise the dollar value when you see it again.

And it looks like that's what @atorresveiga has done here. However, as expected, we still end up with the same original problem: when editing a fee, the percentage is not retained. 

The user will have more information about what's happening. They will _see_ a different percentage, and they (theoretically) have an idea about where the percentage came from because we're now displaying the amount. On the other hand, given that @nbradbury was confused, we can guess that our merchants would be confused too. So maybe this isn't the way to go.

The percentage change during editing is expected because taxes are added on top of the fees. And we calculate the percentage based on the order total. I don't think we should change this since this is how Core works.

So, looking at this widely, maybe the answer is to follow what Core is doing: only allow “Calculate as percentage“ when they're **adding a new fee**. In that way, we can hide the problematic percentage recalculation. And hopefully, keep this simpler for our merchants. Here's a sample UI for illustration:

image

The other option is to set the percentage to zero when editing. But given that we've spent a long time on this already, I'm more inclined to prefer the first option: hiding the percentage. We could change this decision when we have more data that many merchants actually use this part of the feature. 

What do you think? 

---

This is how Core allows editing of fees. 

image

**Comment by atorresveiga** [comment]
@shiki, I agree that we could move forward with the first option and iterate from here once we have more feedback from the merchants and the use of the feature.

With this in mind, I updated the code to hide the percentage calculation when editing the fee value. The only problem I found was that we were allowing the user to add a fee value of 0, leading to a scenario where the percentage calculation could be hidden on a 0 value fee. To fix it, I updated the code to remove the fee if the value is 0 (we were hiding the fee on the UI if the value was 0 anyway). 

I would love to hear your thoughts on removing the fee if the value is 0 @shiki @nbradbury @joe-keenan @hichamboushaba (not sure if I'm missing something here 🤔) and what do you think of the new version.
Thanks for your collaboration with this issue 👏.

Here is a video with the new behavior.


https://user-images.githubusercontent.com/18119390/166253905-9720a896-5daa-4ea6-80bc-a74dec35d341.mp4

**Comment by hichamboushaba** [comment]
> To fix it, I updated the code to remove the fee if the value is 0 (we were hiding the fee on the UI if the value was 0 anyway).

Core allows adding fees with value `0`, so to stay consistent with I'd vote to update the logic to display fees with `0` value, instead of disallowing `0` as value.

**Comment by atorresveiga** [comment]
> Core allows adding fees with value `0`, so to stay consistent with I'd vote to update the logic to display fees with `0` value, instead of disallowing `0` as value.

I'm reverting the changes @hichamboushaba to favor consistency with core.

**Comment by joe-keenan** [comment]
> With this in mind, I updated the code to hide the percentage calculation when editing the fee value.

Following what @shiki suggested, I think it would be less confusing to – when editing – remove the ability to enter a percentage completely. 
When you’re first adding a fee, I think you should still be able to choose to enter a percentage. We should still show the calculated value because it will still be output in the Fee field as a calculated value, not a percentage.
Overall it’s not an ideal solution since it’s not friendly to give people something and then take it away. But, the perfect solution would be to allow having an actual percentage as a fee, and I think it would be better to spend any further effort working towards that.

**Comment by shiki** [comment]
I tested this (somewhat terribly p1651527785924309-slack-C02KUCFCSFP). It looks like this is in a state that will solve our problems. Thank you for all the work, @atorresveiga! 

Hopefully, someday the API allow us to store the percentage value so we can provide a better experience.

I'm leaving it to @nbradbury to review the code.

**Review by nbradbury — APPROVED** [review]
I agree with @joe-keenan that it's a shame to remove a feature, but the end result is much better. Thanks for your work on this @atorresveiga! :shipit:

**Pull request merged**
