### PR TITLE
Order detail: Incorrect handling of empty shipping & billing

### LINKED ISSUE #298: Order detail: Incorrect handling of empty shipping & billing
If an order has empty shipping & billing, we end up with an order detail like this:

screenshot_1533841508

You can repro this using order 896 in our test site.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #298 by adding logic to handle missing shipping and billing addresses.

### Scenarios
- Only display shipping address if available.
- Only display billing address if available. Otherwise the view should be hidden.
- Only display billing phone/email, if available. Otherwise the view should be hidden.
- If shipping and billing details are not available, empty text should be displayed. 

### Testing
- [x] Run `OrderDetailCustomerInfoCardTest`
- [x] Run `OrderFulfillmentCustomerInfoCardTest`
- [x] Verify that when an order shipping/billing address is changed in a test site, the details are changed in Order detail and Order fulfillment screen accordingly.

### Screenshots
  

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by anitaa1990** [comment]
@kyleaparker could you review this for me ☝️☝️☝️ ? :-) Thank you!!

**Comment by kyleaparker** [comment]
Thanks for the detail @anitaa1990!

>Only display the shipping address, hide billing address section

What happens to the phone and email in this scenario?

>Insert "No address specified." into the shipping address, populate the billing address cell and include the "Show billing" icon

Is it possible to hide the shipping address section here and show the billing details by default?

I notice there are a few spacing issues in the address section
- The line spacing looks tight, is it using 14 font size / 20 line height?
- The margin below each address needs to be increased to match the other cards

**Comment by anitaa1990** [comment]
@kyleaparker thanks for the quick review! 

> Only display the shipping address, hide billing address section
What happens to the phone and email in this scenario?

This would be hidden as well. Like this:


Or we would follow what the web UI does and display the phone number/email if it is available, even if the address is not available.
 

> Insert "No address specified." into the shipping address, populate the billing address cell and include the "Show billing" icon
Is it possible to hide the shipping address section here and show the billing details by default?

Yup, this is definitely possible. Something like this?


> I notice there are a few spacing issues in the address section
The line spacing looks tight, is it using 14 font size / 20 line height?
The margin below each address needs to be increased to match the other cards

Yup, the specs are correct. I increased the margin below each address. This one looks much better 😄


Should we just hide the address section for both shipping and billing, if it is not available? So if no billing address is available but phone number and email is available, this would be displayed:


### No billing address, phone or email


### No shipping address

**Comment by nbradbury** [comment]
Hey @anitaa1990, just let me know when this has passed design review and I'll tackle the code review.

**Comment by kyleaparker** [comment]
>Or we would follow what the web UI does and display the phone number/email if it is available, even if the address is not available.

We should definitely show the phone number/email if available but I don't think we need to show the billing address if it's not provided. 

>Yup, this is definitely possible. Something like this?

Yes exactly, we would just need to remove the divider under "Customer Information" 

>Yup, the specs are correct. I increased the margin below each address. This one looks much better 😄

Nice!

>Should we just hide the address section for both shipping and billing, if it is not available? So if no billing address is available but phone number and email is available, this would be displayed:

In this scenario I don't think we need the billing address, just the phone and email

**Comment by anitaa1990** [comment]
Hey @kyleaparker could you please take a look at the below scenarios and let me know if this is ok to merge? Thank you!!

**Comment by kyleaparker** [comment]
Looks good! Only thing I see is there are a couple of screenshots where there is a double border above the email address:
- Billing/shipping address and email available but no phone
- No address but phone and email available
- No address or phone but email available

**Comment by anitaa1990** [comment]
Thanks for the quick review @kyleaparker! I've modified the view to remove the double border:
#### Billing/shipping address and email available but no phone:
 

#### No address but phone and email available
 

#### No address or phone but email available:

**Comment by anitaa1990** [comment]
@nbradbury PR is ready for review 👍

**Pull request merged**
