### PR TITLE
Issue/1867 edit products events

### LINKED ISSUE #1867: Edit Products Release 1: Add analytics to click events when editing simple products
Similar to what iOS has implemented [here](https://github.com/woocommerce/woocommerce-ios/issues/1675#issuecomment-575187699), we would need to include events to track user button clicks when editing products.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #1867. This PR adds all the tracking events associated with updating product inventory, shipping and pricing settings.

#### Events
event name | trigger | properties
-- | -- | --
product_detail_view_price_settings_tapped | User tapped on the price settings row in the Product Detail screen | n/a
product_detail_view_shipping_settings_tapped | User tapped on the shipping settings row in the Product Detail screen | n/a
product_detail_view_inventory_settings_tapped | User tapped on the inventory settings row in the Product Detail screen | n/a
product_price_settings_done_button_tapped | User tapped on the Done menu button in the product price settings screen | `has_changed_data`: a boolean that indicates whether the user has changed any fields on the screen
product_shipping_settings_done_button_tapped | User tapped on the Done menu button in the product shipping settings screen | `has_changed_data`: a boolean that indicates whether the user has changed any fields on the screen
product_inventory_settings_done_button_tapped | User tapped on the Done menu button in the product inventory settings screen | `has_changed_data`: a boolean that indicates whether the user has changed any fields on the screen

#### TO DO
- These events need to be updated to the Events spreadsheet and are currently copied from this [iOS PR](https://github.com/woocommerce/woocommerce-ios/issues/1675).
- Events need to be validated/registered.

~@jaclync @pmusolino, thanks for adding these events in iOS!! Since you both worked on the Edit Products M1 release features, I added you both as reviewers to verify if these are all the events that are currently being used in the iOS app. I couldn't find this in the Events spreadsheet and copied these events from this [PR](https://github.com/woocommerce/woocommerce-ios/issues/1675). There are some events missing from here that are present in the [iOS PR](https://github.com/woocommerce/woocommerce-ios/issues/1675) but these have already been added on the android side so I haven't included them here.~

~Do let me know if I missed some events here. I took the liberty to add the above events to the spreadsheet.~

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
Added the `Not Read for Merge` to this PR since this [PR](https://github.com/woocommerce/woocommerce-android/pull/2025) needs to be merged first and the base branch of this PR should be updated before merging!

**Comment by jkmassel** [comment]
I'm freezing `3.8`, so this is being bumped to `3.9`. If you need it to be part of the `3.8` release, please re-target `release/3.8` and merge there. Once you have, please ping me that it's been merged and I'll be happy to cut a new release candidate!

**Comment by anitaa1990** [comment]
Thanks so much for the review @jaclync! 🙏

**Comment by anitaa1990** [comment]
PR ready for review 👍

**Pull request merged**
