### PR TITLE
Feature: Unified Login M1

### PR DESCRIPTION
**Pull request by AmandaRiu**
Unified Login M1 Feature PR. All the code (except for release notes of course) in this branch has already been reviewed and approved. This PR just merges the feature into `develop` for the 5.1 release. This PR includes the following PRs:

**Description** | PR
:------------------------------- | :--
Step 1 - Fix merge conflicts and get a working build | #2722 
Site Address Flow | #2773 
WPcom Flow | #2803 
Jetpack not connected error screens | #2833 
Store picker and error screens | #2833 
Add tracks for login w/ site address - flow and interaction events | #2836 
Find connected email help - tracks events | #2841 
Track events for wpcom login flow | #2843 
Hide TOS buttons if not signup mode during login | #2845

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@AmandaRiu One thing I didn't notice before is there's no shadow above the buttons in the site picker. There previously was a shadow above the Continue button.

Screenshot_1600189151

**Comment by nbradbury** [comment]
When the site picker is accessed from Settings, it shows the same two buttons as login. Do we want to show "Log in with another account" here?

If we do, then it looks like there's a bug. When I tap that button it takes me to the login screen, and if I try to back out of it the login screen reappears a couple times.

ezgif-7-2e894fcec56a

**Comment by AmandaRiu** [comment]
> @AmandaRiu One thing I didn't notice before is there's no shadow above the buttons in the site picker. There previously was a shadow above the Continue button.

This is per the design for that view: 
Screen Shot 2020-09-09 at 4 01 11 PM

**Comment by AmandaRiu** [comment]
> When the site picker is accessed from Settings, it shows the same two buttons as login. Do we want to show "Log in with another account" here?
> 
> If we do, then it looks like there's a bug. When I tap that button it takes me to the login screen, and if I try to back out of it the login screen reappears a couple times.

Oh good catch, no that other button shouldn't be visible. I'll get it fixed.

**Comment by AmandaRiu** [comment]
@nbradbury I've added some logic to hide that "try another account" button if the store picker is opened from settings. Great catch, thank you 😄 As noted in code comments the missing shadow on the button bar is an intentional change per the designs. Ready for another review!

**Review by nbradbury — APPROVED** [review]
Looks good, great work on this! :shipit:

**Pull request merged**
