### PR TITLE
build: bump Glide to `4.16.0`

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR bumps Glide. It's a next step in `ksp` migration.

It required some further adjustments to not rely on generated code:

> The generated API is deprecated as of Glide 4.14.0. Glide’s annotation processors will continue to be used for [configuration](https://bumptech.github.io/glide/doc/configuration.html).

See details [in the documentation](https://bumptech.github.io/glide/doc/generatedapi.html#this-page-and-the-generated-api-are-deprecated).

### To test

Please some test the app focusing on images: verify that e.g., product images are displayed correctly.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/191">17.3</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wzieba** [comment]
hi @AnirudhBhat 👋 are you fine with reviewing this PR? 🙂

**Comment by AnirudhBhat** [comment]
> are you fine with reviewing this PR?

Yes, @wzieba

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @wzieba. I've tested the flow which involves images and they all seem to work as expected. :shipit:

**Pull request merged**
