### PR TITLE
Add UI tests for Order detail screen

### LINKED ISSUE #168: Create Navigation Tests for Order List to Order Detail
Write the following tests for PR #155 

**While on the Order List View:**
* [ ] Clicking on an order item in the orders list ("Orders") opens the OrderDetailFragment.

**While inside the Order Detail View:**
* [ ] Toolbar title displays "Orders #" + order number.
* [ ] "UP" navigation button is displayed in the toolbar 
* [ ] Clicking the device "back" button returns the user to the orders list screen. The Toolbar title changes to "Orders" and the "UP" button is no longer shown.
* [ ] Clicking the "Dashboard" bottom bar option loads the DashboardFragment, then clicking the "Orders" bottom bar option loads the OrderListFragment (so the detail view should no longer be visible)
* [ ] Clicking the "Orders" bottom bar option loads the OrderListFragment and changes the Toolbar title to "Orders".

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #168, #174 , #178, #179 , #180 , #181 , #195  

This PR adds UI tests to the Order Detail page. 

### 1. Navigation from Order list page to Order detail page
- [x] Clicking on an order item in the orders list ("Orders") opens the OrderDetailFragment.

### 2. Order Detail Page Navigation:
-  [x] Toolbar title displays "Orders #" + order number.
-  [x]  "UP" navigation button is displayed in the toolbar
-  [x]  Clicking the device "back" button returns the user to the orders list screen. The Toolbar title changes to "Orders" and the "UP" button is no longer shown.
-  [x] Clicking the "Dashboard" bottom bar option loads the DashboardFragment, then clicking the "Orders" bottom bar option loads the OrderListFragment (so the detail view should no longer be visible)
-  [x] Clicking the "Orders" bottom bar option loads the OrderListFragment and changes the Toolbar title to "Orders".

#### To Test:
- [x]  Run `OrderListNavigationTest`

### 3. Order Info Card
* [x] Populate card
* [x] Parsing `dateCreated` into one of the following friendly time-based labels to generate the `Created <friendly date category> at <time>` message:
  * Today
  * Yesterday
  * Older than 2 days
  * Older than a week
  * Older than a month
* [x] Order status label: 
  * Check if the order status (Pending, Processing, On Hold, Completed, Cancelled, Refunded, Failed) matches the corresponding text, text color and background color as written in `OrderStatusTag` class.

### 4. Customer Provided Note Card
* [x] customer note populated successfully
* [x] `customerNote` is empty - Hide Customer Note card
* [x] `customerNote` is NOT empty - show the customer note card

#### To Test:
- [x]  Run `OrderDetailNavigationTest`

#### Populating the Form
- [x] verify that customer info card labels are displayed correctly
- [x] Populating customer name, shipping address, shipping country
- [x] if `hasSeparateShippingDetails()` then billing address should be different from shipping address
- [x] Address formatting for different locales
- [x] Verify that billing email address is displayed correctly
- [x] Verify that billing phone is displayed correctly, if available. 
- [x] Handle empty billing phone number
- [x] Billing phone formatting for different locales

#### Expand/Minimize View
- [x] `onLoad` - view is condensed and VIEW MORE button is visible
- [x] When VIEW MORE is clicked: expand to full view and label change to VIEW LESS
- [x] When VIEW LESS is clicked: condense view and label changes to VIEW MORE

#### Action Buttons
- [x] email customer when intent is present
- [x] email customer when no activity is available to handle intent
- [x] Verify that popup is displayed with Call/Message items displayed
- [x] Verify that when `Call` item is clicked in popup menu, an intent to dial the number is called.
- [x] Verify that when `Message` item is clicked in popup menu, an intent to sms is called.

#### To Test:
- [x] Run `OrderDetailCustomerInfoCardTest`

### 6. Product List Card
- [x] populate with one product
- [x] populate with at least multiple products
- [x] verify that product label is displayed correctly
- [x] if order status is processing: fulfill button to be displayed
- [x] if order status is other than processing: details button to be displayed
- [x] verify that product name, image & quantity is displayed
- [ ] testing currency formatter for multiple currencies (dollar, pound, inr)
- [ ] if sku not empty, verify it is displayed
- [ ] if sku is empty, verify it is not displayed

The last 3 items on the list are not relevant to the order detail screen product card view since we are only displaying a condensed version of the product list in this screen. Product list/product details UI tests is segregated into another [PR](https://github.com/woocommerce/woocommerce-android/issues/1043).

#### To Test:
- [x] Run `OrderDetailProductCardTest`

### 7. Payments Card
- [x] verify that payments labels and payment message is displayed correctly
- [x] verify that if payment method title is empty, it should be hidden
- [x] verify that for different currencies the subtotal, shipping, taxes and total are displayed correctly.
- [x] verify that payment discount details are displayed correctly for multiple discounts
- [x] verify that payment discount details are displayed correctly for single discount
- [x] verify that payment discount details are not displayed when there are no discounts
- [x] no refunds - hide refunds section
  - update card title to `Payment`
- [x] has refund:
  - show and populate refund section
  - update card title to `Payment - Refunded`

#### To Test:
- [x] Run `OrderDetailPaymentCardTest`

### 8. Order Notes List Card
- [x] verify that order notes label is displayed
- [x]  Verify proper note date/time stamp is displayed
- [x]  Verify appropriate note type and icon is populated for customer notes
- [x]  Verify appropriate note type and icon is populated for system notes
- [x] Verify appropriate note type and icon is populated for private notes
- [x] Verify populate note message
- [x] Verify notes are displayed in reverse-chronological order

#### To Test:
- [x] Run `OrderDetailNotesCardTest`

### 8. Order List
Verify that:
- [x] Pull to refresh is working
- [x] the `order number` is displayed correctly
- [x] there are 5 sections in total displayed in the list  
- [x] the section title is displayed correctly  
- [x] there is only 1 list item in "Today" section
- [x]  there is 1 list item in "yesterday" section
- [x]  there is 1 list item in "Older than 2 days" section
- [x] there is 1 list item in "older than a Week" section
- [x] there are 3 list items in "older than a month" section
- [x] the order item order name matches the format: "Jane Eyre"
- [x] the order item order name is empty & is handled correctly
- [x] the order item order name is really long & is handled correctly
- [x] the first order item order total is displayed in the format: {currency}{orderTotal} for multiple currencies
- [x] the order status label name, label text color, label background color is displayed correctly for different order statuses: `Pending`, `Processing`, `On Hold`, `Completed`, `Cancelled`, `Refunded`, `Failed`

Created separate issue for testing RTL support [here](https://github.com/woocommerce/woocommerce-android/issues/1042)

### CODE REVIEW

**Comment by anitaa1990** [comment]
Would like to fix issue #195 as well before asking for review for this PR

**Comment by loremattei** [comment]
I'm moving this PR to 1.9, since 1.8 has been cut. If this has to land 1.8, please feel free to target the release branch and ping me to build a new beta.

**Comment by nbradbury** [comment]
@anitaa1990 When I run the tests on an API 28 emulator I get this message at startup:

pie

**Comment by nbradbury** [comment]
On a different emulator (API 27), the test `verifyPaymentCardViewWithSingleDiscountPopulatedSuccessfully` consistently fails for me.

```
android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: is "$10.00"' doesn't match the selected view.
Expected: with text: is "$10.00"
Got: "AppCompatTextView{id=2131362195, res-name=paymentInfo_discountTotal, visibility=VISIBLE, width=63, height=51, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@caccb8b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=933.0, y=21.0, text=$10, input-type=0, ime-target=false, has-links=false}"

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:1538)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:90)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:52)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:314)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:291)
at com.woocommerce.android.ui.orders.OrderDetailPaymentCardTest.verifyPaymentCardViewWithSingleDiscountPopulatedSuccessfully(OrderDetailPaymentCardTest.kt:263)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
Caused by: junit.framework.AssertionFailedError: 'with text: is "$10.00"' doesn't match the selected view.
Expected: with text: is "$10.00"
Got: "AppCompatTextView{id=2131362195, res-name=paymentInfo_discountTotal, visibility=VISIBLE, width=63, height=51, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@caccb8b, tag=null, root-is-layout-requested=false, has-input-connection=false, x=933.0, y=21.0, text=$10, input-type=0, ime-target=false, has-links=false}"
```

**Comment by nbradbury** [comment]
I see a similar problem with `verifyPaymentCardViewPopulatedSuccessfullyForEuro`:

```
android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: is "euro22.00"' doesn't match the selected view.
Expected: with text: is "euro22.00"
Got: "AppCompatTextView{id=2131362210, res-name=paymentInfo_subTotal, visibility=VISIBLE, width=147, height=72, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@c901bab, tag=null, root-is-layout-requested=false, has-input-connection=false, x=849.0, y=0.0, text=euro22.0, input-type=0, ime-target=false, has-links=false}"
```

**Comment by anitaa1990** [comment]
> @anitaa1990 When I run the tests on an API 28 emulator I get this message at startup:

Hey @nbradbury, I noticed this issue as well. When running the entire test suite in a class, only the first tests in all UI tests is failing in android 9 devices. This is because of the dialog you mentioned, being displayed. And because this dialog is displayed, it is blocking the UI so this error is displayed:
`android.support.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: com.woocommerce.android:id/orders`. 

I am still exploring options on how to fix this from some references [here](https://stackoverflow.com/questions/49957255/espresso-test-on-android-p-preview-detected-problems-with-api-compatibility-err) and [here](https://stackoverflow.com/a/49229911/9862062).  

> On a different emulator (API 27), the test verifyPaymentCardViewWithSingleDiscountPopulatedSuccessfully consistently fails for me.

Ohh, that's weird! When I run the tests together and individually it is passing 😕. Will try to reproduce this and fix!

Thanks for the quick review 🙇‍♀

**Comment by anitaa1990** [comment]
@nbradbury @AmandaRiu , while searching for a fix on UI tests failing in emulator 28 devices, I came across this [SO answer](https://stackoverflow.com/questions/49957255/espresso-test-on-android-p-preview-detected-problems-with-api-compatibility-err) which deals with the same problem. 

It seems to be related to non-SDK api violations in the app. This has already been noted in this issue #287 by @AmandaRiu.

Based on the suggesstion from the SO answer, I changed the `targetSdkVersion` to 28 to see if it would help. Now running all the UI tests is working and it’s passing.

But targeting sdk 28 would come with it’s own set of [problems](https://developer.android.com/about/versions/pie/android-9.0-changes-28) and not sure we would not be fixing the `greylist` issues by just upgrading to version 28. 

So wanted to know your thoughts on this before starting any implementation.

**Comment by nbradbury** [comment]
@anitaa1990 The only behavioral change in targeting SDK 28 that catches my eye is the warning about foreground services, but if that's an issue for us it appears to be easily solved. I'm not sure I like bumping the target level just for tests, but we'd probably do that eventually anyway.

@AmandaRiu This is really your call, though. WDYT?

**Comment by anitaa1990** [comment]
> On a different emulator (API 27), the test verifyPaymentCardViewWithSingleDiscountPopulatedSuccessfully consistently fails for me.

> I see a similar problem with verifyPaymentCardViewPopulatedSuccessfullyForEuro:

Update: Debugged on why UI tests related to currency formatting are failing intermittently because site settings is `null` [here](https://github.com/woocommerce/woocommerce-android/blob/develop/WooCommerce/src/main/kotlin/com/woocommerce/android/util/CurrencyFormatter.kt#L46). This means when the app is actually expecting €30.00, in the UI tests, the value displayed is €30 or €30.0. Need to find a way to mock site settings to so that currency formatting can be tested.

**Comment by AmandaRiu** [comment]
Nice work on this project @anitaa1990! Wow, so much testing...awesome!

> The only behavioral change in targeting SDK 28 that catches my eye is the warning about foreground services, but if that's an issue for us it appears to be easily solved. I'm not sure I like bumping the target level just for tests, but we'd probably do that eventually anyway.

@nbradbury  @anitaa1990  We'd definitely need to address the permissions change for foreground services, and with Android Q right around the corner I think it makes sense to do that as soon as we can. I recommend opening another PR that updates the `targetApiVersion` to 28 and the associated changes to support these changes. Then once that is merged we can circle back to this PR so we don't have a bunch of tests failing.

**Comment by nbradbury** [comment]
Update: I've been working on moving to SDK 28, and the foreground service change doesn't apply to us. The one about Apache HTTP deprecation **does** apply, but there is a workaround.

**Comment by anitaa1990** [comment]
I merged with `develop` and all tests are working in api 28 🎉.

Still need to work on the below issue:
```
On a different emulator (API 27), the test verifyPaymentCardViewWithSingleDiscountPopulatedSuccessfully consistently fails for me.
I see a similar problem with verifyPaymentCardViewPopulatedSuccessfullyForEuro:

Update: Debugged on why UI tests related to currency formatting are failing intermittently because site settings is null here. This means when the app is actually expecting €30.00, in the UI tests, the value displayed is €30 or €30.0. Need to find a way to mock site settings to so that currency formatting can be tested.
```

Will work on this tomorrow and submit for review 👍

**Comment by anitaa1990** [comment]
Run all the UI tests in the following devices/emulators before submitting for review:  
- [ ] Emulator API 21
- [ ] Emulator API 22
- [x] Emulator API 26
- [x] Emulator API 27
- [x] Emulator API 28

**Comment by anitaa1990** [comment]
@AmandaRiu @nbradbury  PR is ready for review 👍 

Heads up, there are a couple of issues with testing in devices below 23. 
1. `getColor()` for[ GradientDrawable](https://developer.android.com/reference/android/graphics/drawable/GradientDrawable.html) is only available after API 24. So in previous devices there is no way to check if the TextView background color in TagView matches the color we have passed for devices below API 24. So added a minimum API required check for these tests in f78956d

Currency symbols for India is returning as Rs rather than ₹ in devices below API 24.
This line in FluxC Currency.getInstance(currencyCode).getSymbol(locale) from WCCurrencyUtils.getLocalizedCurrencySymbolForCode returns the currencyCode rather than ₹. Based on the unit tests run in FluxC here, this seems to be a known issue. So again added the same check as above here in f78956d.

**Comment by anitaa1990** [comment]
@AmandaRiu @nbradbury PR merged with latest dagger changes and ready for review 👍

**Comment by nbradbury** [comment]
All tests pass 🎉 :shipit:

**Pull request merged**
