### PR TITLE
Order creation: Customer fetching

### PR DESCRIPTION
**Pull request by 0nko**
This PR adds a new FAB to the order list for order creation and it loads a list of existing customers for the store. 

Since these changes have been developed during a trial and due to the scope of the order creation, it is still WIP.

https://user-images.githubusercontent.com/4923871/110446956-cb761b00-80d0-11eb-8ba0-9b93a54a9907.mp4

This is a feature branch, all code has already been reviewed.

### CODE REVIEW

**Comment by anitaa1990** [comment]
Hey @0nko, I'm taking a look at the code but wondering do we want to merge this into `develop`? Since the order creation feature is still in the design phase, maybe we could mark the PR as `Not ready for merge` and close it once it's been reviewed?

**Comment by 0nko** [comment]
@anitaa1990 Even though the branch is called `order-creation`, it's really about Customers due to the limited scope of a trial. There's hardly any UI and it's behind a feature flag so we could simply disable it until we're ready to continue the work. I just thought it might be useful to merge it so it doesn't fall behind `develop` too much as it can be a pain to resolve conflicts after a while. But I'm fine with shelving it as well :).

**Comment by jkmassel** [comment]
This PR is being bumped to `6.6` because `6.5` is being frozen today.

**Comment by AliSoftware** [comment]
Bumped again, to 6.7

**Comment by AliSoftware** [comment]
Bumping milestone again since code freeze of 6.7 is happening today
\cc @0nko

**Pull request closed without merging**
