### PR TITLE
Merge release/5.9 into develop (Release Notes)

### PR DESCRIPTION
**Pull request by AliSoftware**
- Editorial Release Notes for 5.9
- Update metadata strings

Editorial post reference: p2JRYi-5bH-p2#comment-19860

### CODE REVIEW

**Review by loremattei — APPROVED** [review]
It looks like there's also a fix being merged. It looks good to me, anyway. 
(Approving,  but leaving merging to you so that you can double check this is what you wanted to do as you're not mentioning it in the description).

**Comment by AliSoftware** [comment]
@loremattei Well spotted 👍 

The fix was only  merged a couple of minutes ago, and after I created the PR (ref: p1611913751154900-slack-C6H8C3G23), so it wasn't part of the diff when I created the PR 😉 

We decided to not yet make a beta for those 2 fixes yet as they are only edge cases not worth spamming our beta testers (especially since I already did an rc-2 yesterday) so we'll wait a bit before issuing a new beta.

Do you think it's ok to still merge those fixes to `develop` even if they haven't shipped into a new beta just yet? Or do you think it makes more sense to move this PR to draft and wait for when I'll do rc-3 to undraft it again?

**Comment by AliSoftware** [comment]
I'm actually gonna go ahead and merge it anyway (it's no big deal to merge a fix early) because we need this PR to land before this weekend so that the Weekly Kit sent to translators on Monday morning has the Editorial notes in time.

**Comment by mokagio** [comment]
@AliSoftware FWIF, I did the same – merging to `develop` even though there was no new beta deployment associated with the changes in the PR – some weeks ago [for WordPress iOS 16.4 beta 2](https://github.com/wordpress-mobile/WordPress-iOS/pull/15552).

I spoke online about it with @loremattei at the time and he confirmed (Lore, correct me if I'm wrong) that it's okay to do this.

We value merging fixes that land into the release branch into `develop` ASAP to avoid divergence more that keeping a neat "1 merge from release brach = 1 new deployment" relationship.

**Comment by oguzkocer** [comment]
> Do you think it's ok to still merge those fixes to develop even if they haven't shipped into a new beta just yet? Or do you think it makes more sense to move this PR to draft and wait for when I'll do rc-3 to undraft it again?

Exactly what @mokagio said. I think the idea with these merges is to keep `develop` up to date with all the changes in the release branch. Most of the time we release a new beta, so they go in together, but it can be merged earlier/later too.

I think when to merge to `develop` is mostly release manager's call with the default being as early as possible.

**Comment by AliSoftware** [comment]
Yeah agreed, that's what I figured too in the end. Just had a brain fart at the time.

The idea after all is to sync develop with release ASAP; we do it after each beta to be sure to have _at least_ that synchronization point (and to ensure the version numbers/name/code are bumped in develop when they were bumped in release) at minimum, but after all that doesn't mean we can't merge on other occasions and more often too in addition to those. 👍

**Pull request merged**
