### PR TITLE
Remove addons feature flag

### LINKED ISSUE #4424: [Product Add-ons] Remove Add-ons feature flag
Remove the Product Add-ons feature flag once the project is ready to be delivered.

## Action Items

- [ ] Test the flows before opening the feature flag. See #4439. 
- [ ] Compare with iOS to make sure we're delivering the same things. Whatever comes up may or may not be done after the feature flag is opened. 
- [ ] Place the Experimental toggle switch to control the Add-ons feature instead of the code Feature flag at #4686

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #4424 by delivering the Product Add-ons feature to general availability.

## Action Items before merging

- [x] Test the flows before opening the feature flag. See #4439. 
- [x] Compare with iOS to make sure we're delivering the same things. Whatever comes up may or may not be done after the feature flag is opened. 
- [x] Place the Experimental toggle switch to control the Add-ons feature instead of the code Feature flag at #4686

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by shiki** [comment]
@ThomazFB @wzieba  I'm testing this branch. I configured global add-ons to be applied to a specific category only. 



The add-ons are visible on the web for products that belong to that specific category:



But not on Android or iOS:

Android | iOS
--------|-------
    |       


I can confirm that the experimental feature toggles are on because I can see add-ons on other products.

Am I missing something? Is this expected? 

cc @Ecarrion

**Comment by shiki** [comment]
☝️ When ordering that product, iOS is able to display the View Add-ons button. Android is not. 

iOS | Android
--------|-------
        |       image

**Comment by ThomazFB** [comment]
Hey @shiki, thanks for doing some tests with the Add-ons feature ❤️. For your first comment, I would say that the result is expected, we don't present Global Add-ons data at the `Product Details view`, what should be expected to appear there are only the Add-ons configured inside the Product Edit section of Woo core. Example:
image

But we could discuss if we should present Global Add-ons attached to a specific Product category at the Product Details anyway. I guess I would just have to investigate if a Global Add-on has the necessary data to infer this relationship in the app.

Now for your second comment, we definitely have a bug here! Would be possible for you to send me the JSON file of this Order and the JSON of this Product without the Add-ons button? This way I can do all kinds of tests and detect from the ground up what could be going wrong 😬

**Comment by Ecarrion** [comment]
re: The global add ons comment

It is expected in iOS, the product view only shows product add-ons(not global) which to mimics core.

**Comment by shiki** [comment]
Thank you both for confirming! I was not aware of that.

**Comment by shiki** [comment]
I created a separate issue for https://github.com/woocommerce/woocommerce-android/pull/4689#issuecomment-910618815: https://github.com/woocommerce/woocommerce-android/issues/4704

**Comment by shiki** [comment]
I finished testing for now. This is looking good!

## Tracking

- [x] Experimental feature setting
- [x] All types of fields and configurations. 
    - [x] For example, short text with number-only setting.
    - [x] Price adjustments
    - [x] And others
- [x] “Exclude add-ons” option
- [x] Ordering products with add-ons.
    - [x] Ordering with same product variation but different add-ons
    - [x] Ordering with a negative value add-on
- [x] Tested some parts of p91TBi-5JA-p2. Though I wasn't sure how to set up some of the scenarios in "Product Add-ons User Feedback". 
- [x] Refunding

## Important Issues Found

@ThomazFB I'm not sure if we want to fix these before merging this to `develop` or after. I'll leave it to you all to decide. 😁 

- https://github.com/woocommerce/woocommerce-android/issues/4704
- https://github.com/woocommerce/woocommerce-android/issues/4703
- https://github.com/woocommerce/woocommerce-android/issues/4653

## Low Priority Issues

- https://github.com/woocommerce/woocommerce-android/issues/4702: I don't think we should fix this right now. I just wanted to document it.

**Comment by ThomazFB** [comment]
@shiki I would say that it would be best for us to move the feature to beta release merging this PR, so we can benefit from overall reports and Sentry data, and meanwhile, we can go fixing each issue reported here to be merged in the release branch. Does it make sense?

What do you think about this @wzieba ?

**Comment by wzieba** [comment]
It sounds okay to me @ThomazFB !

Just to mention: the domain mapping on which I'm working right now might be helpful in #4703, #4653 and #4702 which has been issued by @shiki . It _might_ be a good idea to work on them after I finish my part but it's not hard requirement of course.

**Comment by ThomazFB** [comment]
I think your point makes sense, @wzieba! I'm working at a different bug right now, so we have sometime before starting the three issues you mentioned!

Anyway, I guess we already have our strategy set for the release, so I'll move forward with this PR and place it to be ready for review and merge!

Thanks everyone for the great work tackling this project!

**Review by wzieba — APPROVED** [review]
Looks good! :shipit:

**Pull request merged**
