### PR TITLE
[Hack week] No more pink buttons

### PR DESCRIPTION
**Pull request by hichamboushaba**
### Description
This PR updates the app's design to align with the new guidelines pecCkj-fa-p2
I had only half of a day to work on this during the Hack Week, so I may be missing some parts, but if we are satisfied with the result as a first iteration, we can then merge it and improve the other parts in other PRs.

@annchichi can you please test the changes, and see if we can merge this?

Known issue: the text links are still pink in the login screen, this needs an update to the Login library, and I don't have time to do it now.

### Images/gif
|  |  |  |  |
| - | - | - | - |
| Screenshot_20230314_120552 | Screenshot_20230314_121208 | Screenshot_20230314_120538 | Screenshot_20230314_121004 |
| Screenshot_20230314_120841 | Screenshot_20230314_120856 | Screenshot_20230314_120906 | Screenshot_20230314_120953 |
| Screenshot_20230314_120714 | Screenshot_20230314_120728 | Screenshot_20230314_120740 | Screenshot_20230314_120748 | 
| Screenshot_20230314_122730 | Screenshot_20230314_120819 | Screenshot_20230314_120825 | Screenshot_20230314_120832 |

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by annchichi** [comment]
Heya @hichamboushaba, sorry for the late reply. Overall, it's great. 👍   There are a few things I noticed:

- When you add a product, the quantity will blink in pink and then stay in pink color.
CleanShot 2023-03-21 at 14 16 28@2x

- The little megaphone icon should have the same color as the search icon. The icon in the light mode feels like black color. I can't see it clearly on my Android, so I'd love to double-check this. 
CleanShot 2023-03-21 at 14 20 26@2x

- On the Menu tab, 
1. Light mode: the store icon should be the color of the star (Woo-purple-60)
2&3. Dark mode: the store and star icons should be the same color (Woo-purple-30). Currently, the view store looks a bit 'pinky.'
CleanShot 2023-03-21 at 14 24 10@2x

Hope this helps. We can always tweak this along the way. 😊

**Comment by 0nko** [comment]
Hey @annchichi, I'm taking over this PR since @hichamboushaba is AFK. I've addressed your comments:

| | |
|---|---|
| image | image |
| image | image |
| image | image |

**Review by hafizrahman — APPROVED** [review]
Code-wise it looks good to me. Thanks both for working on this!

I think we're still waiting for Ann's response here, so I'm not merging yet.

**Comment by annchichi** [comment]
Heya @0nko 👋 , thanks for updating this. Those fixes look good to go.

**Pull request merged**
