### PR TITLE
Dark Mode: Order List Tab

### LINKED ISSUE #1579: Dark Mode: Orders List Tab
Implement light/dark mode on the My Orders tab. 

my_orders

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #1579 and applies dark/light theming on the Order List tab. The scope of this PR is limited to the main order list view. Overview of changes:
- Converted `TextView` and `Button` components to their Material counterparts. 
- Removed nested `CoordinatorLayout` and the `TabLayout` in `fragment_order_list`. 
- Added logic to programmatically create the `TabLayout` and manually add it to the `AppBarLayout` in `MainActivity`.
- Add logic to remove the tabs when `OrderListFragment` is hidden, and to add it back when it’s unhidden. 
- Had to do some magic to get the new divider designs to work with the orders list. I couldn't implement it the same way as the Top Performers card because the orders list is sectioned AND uses a `PagedListAdapter` so there is no way of knowing inside the adapter that an order item is the last item in it's section to hide the divider.

Not Included:
- [Order status tag styling](https://github.com/woocommerce/woocommerce-android/issues/1794). 
- [The Search/Filter view](https://github.com/woocommerce/woocommerce-android/issues/1793)
- [Loading skeleton](https://github.com/woocommerce/woocommerce-android/issues/1769)

## After
orders-28

orders-empty

## Recommended test areas

- Test loading light/dark on devices running API 21, 28, and 29 to verify no issues with styles across major versions.
- Test viewing orders for a store with no orders
- Verify the tabs get removed when navigating to child views, between tabs, or when entering search mode.
- Verify tabs get added back in when returning to the orders list tab.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
@Garance91540 this one is ready for a design review 👍

**Comment by Garance91540** [comment]
Hi @AmandaRiu,

Looking good, just a few notes!
- Is it possible to make all the copy in overline font uppercase (ie "Dec 3") to improve readability?
- Can we add the "#" back in front of the order numbers? It will help with readability as well
- On my phone (testing with the apk), the currency symbol appears after the numbers instead of before: 

Screenshot_20200106-104851

**Comment by AmandaRiu** [comment]
@Garance91540 Thank you for the review! 

> Is it possible to make all the copy in overline font uppercase (ie “Dec 3”) to improve readability?

Absolutely. Fixed and here’s how it looks now:

Screen Shot 2020-01-06 at 3 23 05 PM

> Can we add the “#””back in front of the order numbers? It will help with readability as well

This is how it currently looks in production and not changed by this PR (this one just deals with the light/dark mode styling). I’ve [opened a different ticket](https://github.com/woocommerce/woocommerce-android/issues/1798) to have this taken care of outside of this project. 

> On my phone (testing with the apk), the currency symbol appears after the numbers instead of before

Interesting. Is this also happening when you run the current production version of the app on that same device? I ask because I haven’t done anything to change the logic of displaying data in the app - just the styling. Please also provide the make/model/Android version of the device, as well as the device locale and timezone.

**Comment by Garance91540** [comment]
> Is it possible to make all the copy in overline font uppercase (ie “Dec 3”) to improve readability?

I'm sorry about this, I realized I gave the wrong instructions and I still think the date font is a bit weird. Looking at Kylea's original design in the Orders V2 Figma file, I'm seeing that she initially used caption and nove overline:

Screen Shot 2020-01-07 at 4 36 18 PM

Would it be ok to update this? Everything else looks 👍

> Is this also happening when you run the current production version of the app on that same device? 

Actually yes (I hadn't noticed it). My device info:
- Pixel 4 / Android 10 / time zone GMT +01:00 Central European Standard Time

**Comment by AmandaRiu** [comment]
@Garance91540 Thank you for the review!

> I'm sorry about this, I realized I gave the wrong instructions and I still think the date font is a bit weird. Looking at Kylea's original design in the Orders V2 Figma file, I'm seeing that she initially used caption and nove overline

No worries about the mixup, but I agree with your original answer. I'd prefer to stick with one design to prevent a moving target for this project and the dark mode designs all use overline. I've posted a message in Slack to get more clarification, but for now I'll leave this as-is and if it needs changing I'll do it in another PR. This way it can get code reviewed and merged. 

> Actually yes (I hadn't noticed it). My device info: Pixel 4 / Android 10 / time zone GMT +01:00 Central European Standard Time

Ok, this seems like a separate issue then. Can you open a ticket with details about your store and the formatting problem?

 Thank you! 👍

**Comment by AmandaRiu** [comment]
This one is ready for code review 👍

**Comment by AmandaRiu** [comment]
@Garance91540 Updated the font style to Caption:

**Comment by nbradbury** [comment]
This looks great but if I change the appearance and return to the order list, it crashes with this:

```
020-01-09 14:18:27.008 22705-22705/com.woocommerce.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android, PID: 22705
    kotlin.UninitializedPropertyAccessException: lateinit property ordersAdapter has not been initialized
        at com.woocommerce.android.ui.orders.list.OrderListView.setOrderStatusOptions(OrderListView.kt:58)
        at com.woocommerce.android.ui.orders.list.OrderListFragment.initializeViewModel(OrderListFragment.kt:381)
        at com.woocommerce.android.ui.orders.list.OrderListFragment.onViewCreated(OrderListFragment.kt:185)
```

**Comment by nbradbury** [comment]
I don't know how this happened, and I can't reproduce it, but at some point I ended up with the dashboard tabs above the order list. Maybe something to look into as part of #1802 ?

Screenshot_1578597666

**Comment by AmandaRiu** [comment]
@nbradbury Yeah this is a known issue. It happens whenever you switch between light/dark modes. It will be addressed in a different PR specific to fine tuning how config changes happen.

**Pull request merged**
