### PR TITLE
Connect to reader from collect payment flow

### PR DESCRIPTION
**Pull request by malinajirka**
Parent issues #3725 and #3726

This PR adds support for redirecting to connect-to-reader flow when a user tries to collect a payment and no reader is connected.

To test
- HW reader is not supported for this flow -> simulated reader will be used by default
- Testing site with WCPay installed and activated is required
1. Open detail of an order in US dollars
2. Tap on "Collect payment"
3. Notice "connect-to-reader" flow is started
4. Tap on "Connect to reader"
5. Notice when the connection flow completes, you are automatically redirected to collect payment flow
6. Finish the payment and dismiss the payment dialog
7. Tap on "Collect payment"
8. Notice you are redirected to payment flow since a reader is already connected

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by nbradbury — APPROVED** [review]
All good! :shipit:

**Comment by nbradbury** [comment]
@malinajirka Looks like I approved this too soon since there are conflicts :)

**Comment by malinajirka** [comment]
> Looks like I approved this too soon since there are conflicts :)

Yeah, sorry about that @nbradbury  -> there was another PR which touched dependency injections -> it touched all Fragments and VMs related to card reader.

Interesting, do you usually re-test PRs as reviewer after the author resolves conflicts? In WPAndroid, we'd usually ask the reviewer for a re-test only when the conflicts turned out to be complicated.

**Comment by nbradbury** [comment]
> Interesting, do you usually re-test PRs as reviewer after the author resolves conflicts? In WPAndroid, we'd usually ask the reviewer for a re-test only when the conflicts turned out to be complicated.

That's pretty much what I do as well. I don't bother with a re-test unless the changes were large.

**Comment by nbradbury** [comment]
@malinajirka ~~Looks like there's a minor lint issue that needs addressing. I'll enable auto-merge so this gets merged when that's corrected.~~ Never mind, I see you've corrected it!

**Comment by malinajirka** [comment]
Thanks, I fixed the conflicts, retested the flow and all looks good ;). Thanks for enabling the auto-merge!

**Comment by nbradbury** [comment]
@malinajirka Not sure if you already noticed, but this is failing CI.

**Pull request merged**
