### PR TITLE
[Login] Improve site discovery to support sites with multiple Link headers

### LINKED ISSUE #12079: [Login] Improve site discovery for sites with multiple Link headers
Currently, when a site returns multiple `Link` headers, the [site discovery](https://developer.wordpress.org/rest-api/using-the-rest-api/discovery/#link-header) will fail, and the app will fallback to a default URL, which could cause issues (https://github.com/woocommerce/woocommerce-android/issues/12075), while we can improve the reliability by improving our fallback URL to support sites without permalinks (https://github.com/woocommerce/woocommerce-android/issues/12043), we can also avoid having to use the fallback URL by supporting extracting the data from all the headers.

`Volley` our HTTP library already supports this https://github.com/google/volley/issues/21

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #12079 

### Description
This PR simply updates FluxC to include the changes of https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3055, the FluxC PR improves the site discovery to support sites that send multiple Link headers.

### Testing information
1. To prepare the website, please install the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin, then add the following snippet:
```PHP
function modify_pre_get_shortlink_defaults($return, $id, $context, $allow_slugs) { 
	if ($id == 0) {
		return home_url( '/' );
	}
    return $return; 
}
// Add the filter to return the `shortlink` type as the `Link` header for the home page as well
add_filter( "pre_get_shortlink", "modify_pre_get_shortlink_defaults", 10, 4 );
```
2. Open the app and sign in to the website using site credentials.
3. Confirm the sign in works without issues.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by hichamboushaba** [comment]
@JorgeMucientes since you reviewed the FluxC part, can I assume you reviewed also this one and just didn't approve it yet?

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>status: do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by JorgeMucientes — APPROVED** [review]
> @JorgeMucientes since you reviewed the FluxC part, can I assume you reviewed also this one and just didn't approve it yet?


Hey @hichamboushaba I actually did review it. However, when testing the changes using WooCommerce app I was not able to successfully log in using site credentials. 
I kept getting success for `v2/users/me/application-passwords/` but then `v2/users/me/` would fail with an error like `not a valid application password`. So I wanted to look more into it before sharing feedback. However, after coming back from lunch I'm not able to reproduce the problem anymore, so can't really share any extra insights on what was happening on my site. 
Anyway, since the problem seems to be gone and can't replicate it anymore. I'm approving the PR.

**Comment by hichamboushaba** [comment]
> I kept getting success for v2/users/me/application-passwords/ but then v2/users/me/ would fail with an error like not a valid application password

Weird, this seems like a strange failure, I hope there is a chance to reproduce it to identify the cause.
But in any case, this doesn't seem related to the changes of the PR, so I think it's safe to ship this improvement.

**Pull request merged**
