### PR TITLE
Shipping Labels: enable customs feature and update tracking

### LINKED ISSUE #4246: Shipping Labels: Add tracking for customs step and enable the feature

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes #4246, this PR contains two main changes:
1. Enables the customs feature in the shipping labels form.
2. Updates the Shipping Label tracking:
     - It removes most of the redundant button tapping events, as they are tracked by the step completion steps.
     - It adds new states to the `shipping_labels_purchase_flow` event to represent starting steps, this replaces both the "continue" and "edit" button tap events.
     - I kept the address related events, as they can't be easily tracked using the `shipping_labels_purchase_flow`, and I updated the spreadsheet to include them (https://d.pr/i/dX7Vsk)
3. Updates the "reprint shipping label" CTA text to just "print shipping label" (internal ref: p1623243768209200/1623243663.209100-slack-CGPNUU63E), I didn't want to open a separate PR just to update some text.

#### Testing
1. Create an international order in your store.
2. Open the order in the app.
3. Confirm that you can see the "create shipping label" button.
4. proceed to shipping label creation.
5. Test the customs form and confirm that it works.
6. Confirm that shipping label creation works.
7. Check the event `shipping_labels_purchase_flow` in Tracks, and confirm that it's sent for all steps.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hichamboushaba** [comment]
@anitaa1990 as discussed, I'm assigning this to you directly 🙏

**Review by anitaa1990 — APPROVED** [review]
Nice work @hichamboushaba! The events are tracked as expected!

I found a few minor issues with the flow though (that is probably unrelated to this PR). 

- When I click on the Customs Flow, it takes about 2 secs for the screen to open. I was able to reproduce that each time. This doesn't happen with the other package or rate selection flows.
. 

- It feels a bit jarring to see the suggested address screen. Do you think we can add the same slide animation we have when we click on the edit address button? 

- I think this is tracked somewhere but just to note, in case it's not 😅 . It would be good to pre select the carrier, if there was only one carrier in the list.

- I'm not sure if it makes sense for shipping labels but just to be consistent across the app, do you think it would be better to have a discard dialog when we make changes to the shipping labels flow and then click on the back button?

**Comment by hichamboushaba** [comment]
Thanks @anitaa1990 for the review.

> When I click on the Customs Flow, it takes about 2 secs for the screen to open. I was able to reproduce that each time. This doesn't happen with the other package or rate selection flows.

This is weird, I don't see any delay on my side

The only difference is that this screen is using a slide animation, while the other screens are using fade-in fade-out, I'm planning to change everything to slide-in slide-out to align with the rest of app.
Can you try changing it to fade-in fade-out and see if it makes any difference?

> It feels a bit jarring to see the suggested address screen. Do you think we can add the same slide animation we have when we click on the edit address button?

As I said, all previous screens (including the address screen) are using fade-in fade-out, it will be updated to slide-in slide-out in an upcoming PR.

> It would be good to pre select the carrier, if there was only one carrier in the list.

Noted, I added to the one issue related to this screen, that I'm planning to fix shortly before continuing M4 tasks: https://github.com/woocommerce/woocommerce-android/issues/4188#issuecomment-867473366

> I'm not sure if it makes sense for shipping labels but just to be consistent across the app, do you think it would be better to have a discard dialog when we make changes to the shipping labels flow and then click on the back button?

Me and Ondrej we decided not to use it, and IMO it's not needed for this form, as it adds a lot of friction when going back and forth.
WDYT @Garance91540 about this? should we add a discard dialog to the shipping labels screens?

**Comment by Garance91540** [comment]
> WDYT @Garance91540 about this? should we add a discard dialog to the shipping labels screens?

Given the amount of info a user could potentially have entered in this flow, and that double clicking on the back button by mistake is always a possibility, I think we should indeed show a discard confirmation dialog, but only when the user is about to exit the parent task list, not the child screens.

Screen Shot 2021-06-24 at 5 16 25 PM

**Comment by hichamboushaba** [comment]
Thanks @Garance91540, I created a task to keep track of this: https://github.com/woocommerce/woocommerce-android/issues/4257

**Pull request merged**
