### PR TITLE
Replace the deprecated package declaration of Parcelize

### PR DESCRIPTION
**Pull request by hichamboushaba**
Second part of #3824, I actually missed this part when I removed the deprecated plugin, today I noticed that all the Parcelize annotation are deprecated, and it turns out we need to update the package declaration too.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by wzieba — APPROVED** [review]
Looks good!

**Comment by hichamboushaba** [comment]
Thanks @wzieba, I'm taking a look at the lint failure now.

**Comment by hichamboushaba** [comment]
It turns out the lint issue is caused by a [bug](https://issuetracker.google.com/issues/168794947) in AGP 4.0, the "ParcelCreator" lint rule checks for the previous package only, so it fails after updating the package declaration.
I disabled the check temporarily in the commit: 291fca6, we should re-enable it after updating AGP.

**Review by wzieba — APPROVED** [review]
Got it, thanks for finding and linking the issue. I'm ok with disabling this check in lint. :shipit:

**Pull request merged**
