### PR TITLE
Free Trial: Introduce More menu header badge

### LINKED ISSUE #8842: [Free Trial] [Menu Redesign] Add store plan badge to menu header

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #8842 by introducing a badge to the More Menu view that follows the current Woo Express plan used. If there's no site plan, the badge doesn't show up. It also refactor some parts of the Site Plan to centralize the plan name acquisition logic between the Upgrades and More Menu views.

Screenshots
==========
| Light mode  | Dark mode |
| ------------- | ------------- |
| Screenshot_20230420_024811 | Screenshot_20230420_024821 |

How to Test
==========
1. Open the app with three different site types: Woo Express Free Trial, Woo Express Subscribed, Atomic Woo store
2. For the Woo Express Free Trial store, verify that the More Menu badge is `Free Trial`
3. For the Woo Express Subscribed, verify that the More menu badge is the plan name. E.g. `Performance`
4. For the Atomic Woo store, verify that the More menu badge is not visible

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
@woocommerce/mobile-ui-testing-squad I think I may need some help with some UI tests with the more menu changes again 😅. 

I'm noticing the `e2eReviewListShowsAllReviews` failure and trying to debug it, but the logs don't say much to me. It suggests a failure with the expected request URL, but this PR doesn't introduce any change to it. Looking at the test execution, I see the test exploring the Reviews, but I can't quite detect what could be wrong here. Can you folks take a quick look at this and maybe have a better understanding of what's happening?

```
expected:<
GET
/rest/v1.1/sites/161477129/stats/visits/

Query: unit = year
Query: quantity [matches] [0-9]+
Query: date [matches] (.*)
Query: stat_fields [matches] visitors
> but was:<
GET
/rest/v1.3/sites/161477129/plans/?locale=en_US
```

**Comment by pachlava** [comment]
Thanks for the ping @ThomazFB 👋 I'm taking a look

**Comment by pachlava** [comment]
> It suggests a failure with the expected request URL, but this PR doesn't introduce any change to it.

Just some initial info why this happens:
- Some of the UI tests in this repo hit the real API, some hit the mocked API (WireMock). This test does the latter.
- For the mocked API tests, we need to match every request sent by the app, and have a mocked response. Request templates/matchers are stored [here](https://github.com/woocommerce/woocommerce-android/tree/trunk/WooCommerce/src/androidTest/assets/mocks/mappings). If WireMock server can't find a mocked response for the request it intercepts, it fails the test, even if the test has not much to do with the request in question.
- **This PR adds a new request usage in the "More" screen**, I guess, by adding the `fetchCurrentPlanDetails` to `MoreMenuViewModel.kt` 
- `e2eReviewListShowsAllReviews` appears to be the only UI test that opens the `Menu`, hence it fails.

To solve this, I'll add a new mock that will match the new request (`/rest/v1.3/sites/161477129/plans`) shortly. 🙂

**Comment by ThomazFB** [comment]
Ooooh, now everything makes way more sense! Thanks for this great clarification, @pachlava! I wasn't aware of the endpoint checks and now the log message is clear! Knowing this will help me a lot with future issues! Thank you so much 🙇

**Comment by pachlava** [comment]
I'm happy to help @ThomazFB 🙂 I added a new mock file with ddecd6631221e932c26ddf5a7b69de48ea5fbaa8 and the tests are now 🟢 🎉

**Comment by wzieba** [comment]
@ThomazFB In the case of a short username and long site name, maybe we should align the badge to the right of the username?

image

**Comment by ThomazFB** [comment]
@pachlava thank you so much for tackling this and fixing the test directly! You helped me by a lot! 🙇 

>In the case of a short username and long site name, maybe we should align the badge to the right of the username?

Good catch, @wzieba! I forgot to disable the `fill` parameter in that element weight. It's fixed now: https://github.com/woocommerce/woocommerce-android/pull/8857/commits/a1643ec47d34d7d9eef6dfea36924616b197e22f

Let me know what you think!

**Review by wzieba — APPROVED** [review]
Looks good, thanks 👍 

---

When reviewing this PR I've noticed that after quick navigation back-and-forth I can end up in a state that, on top, there's a big, unwanted space.

It's not the scope of this PR but just sharing this for awareness - maybe we can fix it some day, or perhaps you know what can be the reason right away?

https://user-images.githubusercontent.com/5845095/233599371-70b01c36-020b-4d01-bef3-4379f16178c5.mp4

**Pull request merged**
