### PR TITLE
Enable Products M4 for all

### PR DESCRIPTION
**Pull request by 0nko**
- Removed `PRODUCT_RELEASE_M4 ` feature flag
- Hid beta features row in settings 
- Updated the product banner to always show the products tab top banner copy (title & info) for M4 features
- Removed conditional check for Add Product FAB visibility

## Testing

- On `develop` or any other branch, first launch the app and turn off the Products feature switch in Settings > Betal Features --> there should be no Add product FAB in the Products tab and the top banner does not mention product creation
- On PR branch, launch the app
- Go to the Products tab --> the Add product FAB should be visible even though the feature switch was turned off previously, and the top banner should mention product creation
- Go to Settings --> Beta Features row should not be visible

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by AmandaRiu — DISMISSED** [review]
Hey @0nko! Changes look good except for the text in the Products info card - it still mentions "enabling the beta feature in settings", but there is no longer a way to do that:




Also, it looks like this branch was created from the `release/5.4` branch however as it contains changes that aren't currently in `develop`.

**Comment by 0nko** [comment]
@AmandaRiu Thanks, I fixed the banner.

image

> Also, it looks like this branch was created from the release/5.4 branch however as it contains changes that aren't currently in

Yeah, I had to pull the 5.4 changes because the M4 flag is used and I wanted to remove it to prevent conflict. It's being to `develop` anyway: https://github.com/woocommerce/woocommerce-android/pull/3162. I'm not sure what the right process is in this case..

**Comment by AmandaRiu** [comment]
@0nko Updates look good! I think we just need to wait for that [other PR to be merged](https://github.com/woocommerce/woocommerce-android/pull/3162) before we can merge this one since this PR contains changes that will be included in the other PR. 👍 If this is not correct, just ping me and I'll merge it right away.

**Comment by 0nko** [comment]
Thanks @AmandaRiu. 

cc: @AliSoftware

**Comment by AliSoftware** [comment]
@0nko https://github.com/woocommerce/woocommerce-android/pull/3162 has now been merged!
I'll let you fix the conflicts and merge this one

**Review by anitaa1990 — APPROVED** [review]
:shipit:

**Pull request merged**
