### PR TITLE
Issue/13136 manage stores visibility

### LINKED ISSUE #13136: Add new screen for selecting/unselecting visible sites

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #13136 

### Description

Adds a new screen to select or unselect which stores user wants to access through site picker. 

The current PR is only UI changes. Selecting or unselecting sites won't have any impact on the displayed site picker list. 

### Testing information

1. Log into the app using WP.com credentials with an account that has multiple stores
2. Go to the site picker
3. Tap `Edit Store` button
4. Check all Woo sites are displayed and checked
5. Uncheck one site and see how the save button is enabled
6. Check again the same site and see how save is disabled

### The tests that have been performed

The above

### Images/gif

https://github.com/user-attachments/assets/c64f79be-e1f7-4151-9bdc-38aeb1e1e44d

- [X] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hafizrahman** [comment]
Not a breaking issue but I noticed the last item has a narrower tap target compared to the rest:

https://github.com/user-attachments/assets/0e29a859-06aa-4f86-876a-16cb76c35791

**Review by hafizrahman — APPROVED** [review]
Works as expected and the code looks good. I left a video showing a selection situation but that's non-blocking.

**Comment by hichamboushaba** [comment]
If I may add something, looking at the video that Hafiz shared above, IMO, the fact that the ripple effect doesn't expand to the full width of the buttons is not visually appealing. Can we move the padding to the content and not apply it to the top item?

**Comment by hafizrahman** [comment]
>  IMO, the fact that the ripple effect doesn't expand to the full width of the buttons is not visually appealing.

+1 to this, good point.

**Comment by JorgeMucientes** [comment]
Good point folks! Than you. Yeah I agree, and both UI glitches mentioned were fixed already in this subsequent PR: https://github.com/woocommerce/woocommerce-android/pull/13160


https://github.com/user-attachments/assets/d2c608f3-0dcc-41ca-93c2-2b5f4dcb8e29

**Pull request merged**
