### PR TITLE
Issue/2295 shipping label info screen

### LINKED ISSUE #2295: Shipping Labels M1 release: UI to display instructions on how to print shipping labels
As part of the M1 release, we need to add a information dialog to the order detail screen on how to print a shipping label from a device.

.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2295 by adding two info screens to the print shipping label screens.

##### Print shipping label information screen
. 

#### To test
- Click on an order from the Orders tab that has shipping labels.
- Click on the `Reprint shipping label` button.
- Click on the `See label layout and paper size options` link and notice the new screen is displayed.
- Click on the `Don't know how to print from your phone?` link and notice the new screen is displayed.

#### Notes
This PR is in draft [this print shipping label PR](https://github.com/woocommerce/woocommerce-android/pull/2909) is reviewed.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@anitaa1990 I know this is a draft, but I figured I should start a review since I assume this will come out of draft as soon as #2909 is merged. A few comments:

- "See label layout and paper size options" and "Don't know how to print with your phone" should have a ripple.
- This is really a design issue for @Garance91540, but I'm not sure of the usefulness of the label layout and paper size screen. Would it make more sense to combine this with the "Choose paper size" dialog so the user sees the sizes as they're choosing one? Or even just drop the paper size screen entirely, since label/letter/legal are standard sizes that I'd think most users are already aware of (and we give the dimensions in that dialog).
- If we do keep that screen, it needs to be updated to look better in landscape and also be scrollable (I can't scroll down to see what Label looks like). It would also be helpful if they were in the same order as they are in the "Choose paper size" dialog.

Screenshot_1601901935

- I'm also unsure of the usefulness of the "Print with your phone screen," as the method of printing may vary by device. Also, the instructions make it sound like after you tap "Print shipping label" you'll see a screen that where you choose to save the label as PDF, but in fact there's another screen that shows first (at least on my API 30 emulator). You have to choose Print from that first screen before you're taken to a screen that enables saving as PDF. And saving as a PDF doesn't make sense here since (again, on my emulator) the screen says "Select printer."

ezgif-2-2138a93405eb

**Comment by Garance91540** [comment]
Hi @nbradbury 

>This is really a design issue for @Garance91540, but I'm not sure of the usefulness of the label layout and paper size screen. Would it make more sense to combine this with the "Choose paper size" dialog so the user sees the sizes as they're choosing one? Or even just drop the paper size screen entirely, since label/letter/legal are standard sizes that I'd think most users are already aware of (and we give the dimensions in that dialog).

I spotted this feature [on Shippo](https://d.pr/i/Egd3YP), where you can even see a label preview of the label you are about to print. The goal of this page isn't to display dimensions, but rather the positioning of the labels you are about to print on the paper. This is useful because merchants are often using specific adhesive paper, sometimes preformatted, and a preview help save verify the layout before printing so there's no errors. It's also going to be implemented in core

> If we do keep that screen, it needs to be updated to look better in landscape and also be scrollable (I can't scroll down to see what Label looks like). It would also be helpful if they were in the same order as they are in the "Choose paper size" dialog.

Thanks for checking that! Can the labels be displayed on a 3 column layout so they all fit on the same page on landscape. Let's arrange the order so it matches the "Choose paper size" dialog as you suggested.

> I'm also unsure of the usefulness of the "Print with your phone screen," as the method of printing may vary by device. Also, the instructions make it sound like after you tap "Print shipping label" you'll see a screen that where you choose to save the label as PDF, but in fact there's another screen that shows first (at least on my API 30 emulator). You have to choose Print from that first screen before you're taken to a screen that enables saving as PDF. And saving as a PDF doesn't make sense here since (again, on my emulator) the screen says "Select printer."

Yep I agree that this message should be relevant for the majority of Android devices. I updated it as follow:

https://d.pr/i/FAzH6g

**Comment by anitaa1990** [comment]
Thank you for the thorough review @nbradbury!!

 > "See label layout and paper size options" and "Don't know how to print with your phone" should have a ripple.

👍 Updated in 7aa2a17

> If we do keep that screen, it needs to be updated to look better in landscape and also be scrollable (I can't scroll down to see what Label looks like). It would also be helpful if they were in the same order as they are in the "Choose paper size" dialog.
Thanks for checking that! Can the labels be displayed on a 3 column layout so they all fit on the same page on landscape. Let's arrange the order so it matches the "Choose paper size" dialog as you suggested.

That's a great catch! Thanks for testing in larger screens as well ❤️ I looked into how we could accommodate the layout to display the paper sizes horizontally if the required space is available and came across FlowLayout, which is only available in `ConstraintLayout 2.0` so I updated to the latest version. Let me know if this can be updated in another PR and I can revert the commit. This is how it looks now:

. 

> I'm also unsure of the usefulness of the "Print with your phone screen," as the method of printing may vary by device. Also, the instructions make it sound like after you tap "Print shipping label" you'll see a screen that where you choose to save the label as PDF, but in fact there's another screen that shows first (at least on my API 30 emulator). You have to choose Print from that first screen before you're taken to a screen that enables saving as PDF. And saving as a PDF doesn't make sense here since (again, on my emulator) the screen says "Select printer."
Yep I agree that this message should be relevant for the majority of Android devices. I updated it as follow:
https://d.pr/i/FAzH6g

Updated according to the designs in 89f6a13.

Ready for another round 👍

**Comment by nbradbury** [comment]
@anitaa1990 Changes look good, but I'm not sure about the alignment in landscape. @Garance91540 Should these all be aligned to the top?

Screenshot_1601997975

**Comment by anitaa1990** [comment]
Ah, that's my bad! I forgot to change the `flow_verticalAlign` to `top`. It was set to `center`. Fixed in e8bad34. 




I also noticed that the paper size options support dark mode now and I forgot to update that in this PR. So added it in 57f9b09.




Ready for another round 👍

**Review by nbradbury — APPROVED** [review]
Looks good! :shipit:

**Pull request merged**
