### PR TITLE
[Better Tablet Products] Add tracking

### LINKED ISSUE #10891: [Better Tablet Products] Add tracking. Register events

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10891 

### Description

The PR adds `horizontal_size_class` -> `compact` / `regular`to the events:
* `main_tab_products_reselected`
* `main_tab_orders_selected`
* `product_list_product_tapped`
* `product_list_add_product_button_tapped`
* `product_detail_loaded`

### Testing instructions

Open Logcat with "track" filter
* Select/reselect products tab
* Add product
* Open products details
Notice events mentioned above with the new property:

```
Tracked: main_tab_products_reselected, Properties: {"horizontal_size_class":"compact","blog_id":192152755,"is_wpcom_store":true,"was_ecommerce_trial":false,"plan_product_slug":"business-bundle","store_id":"5c2b1c40-b7f4-4e06-b5c7-65396c6b3071","is_debug":true,"site_url":"https:\/\/myusernametestsite2020151673500.in"}
Tracked: main_tab_products_reselected, Properties: {"horizontal_size_class":"regular","blog_id":192152755,"is_wpcom_store":true,"was_ecommerce_trial":false,"plan_product_slug":"business-bundle","store_id":"5c2b1c40-b7f4-4e06-b5c7-65396c6b3071","is_debug":true,"site_url":"https:\/\/myusernametestsite2020151673500.in"}
Tracked: product_list_product_tapped, Properties: {"horizontal_size_class":"compact","blog_id":192152755,"is_wpcom_store":true,"was_ecommerce_trial":false,"plan_product_slug":"business-bundle","store_id":"5c2b1c40-b7f4-4e06-b5c7-65396c6b3071","is_debug":true,"site_url":"https:\/\/myusernametestsite2020151673500.in"}
Tracked: product_list_add_product_button_tapped, Properties: {"horizontal_size_class":"compact","blog_id":192152755,"is_wpcom_store":true,"was_ecommerce_trial":false,"plan_product_slug":"business-bundle","store_id":"5c2b1c40-b7f4-4e06-b5c7-65396c6b3071","is_debug":true,"site_url":"https:\/\/myusernametestsite2020151673500.in"}
Tracked: product_detail_loaded, Properties: {"has_linked_products":false,"has_min_max_quantity_rules":false,"horizontal_size_class":"compact","blog_id":192152755,"is_wpcom_store":true,"was_ecommerce_trial":false,"plan_product_slug":"business-bundle","store_id":"5c2b1c40-b7f4-4e06-b5c7-65396c6b3071","is_debug":true,"site_url":"https:\/\/myusernametestsite2020151673500.in"}
```

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jd-alexander** [comment]
@kidinov I am actively reviewing this. I am wondering if you have seen this bug or if its a bug. Let me know what you think. 

[missing-nav.webm](https://github.com/woocommerce/woocommerce-android/assets/1509205/24d2f1bb-3133-4784-a87c-87a0f88430b9)

**Review by jd-alexander — APPROVED** [review]
I was able to verify that these events fire as expected and that the compact vs regular was being set. LGTM 🚢

**Comment by kidinov** [comment]
@jd-alexander  👋

> @kidinov I am actively reviewing this. I am wondering if you have seen this bug or if its a bug. Let me know what you think.

Do you mean the margins on the description screen? Yep, that fixed already

**Comment by jd-alexander** [comment]
> @jd-alexander 👋
> 
> > @kidinov I am actively reviewing this. I am wondering if you have seen this bug or if its a bug. Let me know what you think.
> 
> Do you mean the margins on the description screen? Yep, that fixed already

Oh sorry I didn't mention the bug haha the nav bar is disappearing when you go into the product details and come back out.

**Pull request merged**
