### PR TITLE
[Woo POS] Small updates to checkout screen per M2 Design

### LINKED ISSUE #11861: [Woo POS] Add Compose card under cart and totals as per design
Image

Currently we show totals and cart in 2 different cards on the checkout state.

Branch off of this PR:
https://github.com/woocommerce/woocommerce-android/pull/11879

Put a compose card underneath both totals and cart screens, by changing `WooPosHomeScreen`

### PR DESCRIPTION
**Pull request by backwardstruck**
### Closes: 
#11861

### Description  
<s>Adds a compose card underneath both totals and cart screens in the POS feature. Currently, totals and cart are shown as two separate cards when in the checkout state. This enhancement ensures a unified card appearance that adheres to the Figma design.</s>

Changes include modifications to `WooPosHomeScreen` to integrate the compose card that envelops both the totals and cart sections.

New Design:

Screenshot 2024-07-05 at 15 54 14

Old Design:

Screenshot 2024-07-04 at 16 58 05

### Steps to reproduce  
To test the changes made in this PR, follow the steps outlined below:

1. Navigate to the POS screen 
1. Add items to the cart and proceed to checkout.
1. Ensure the design specifications are met, focusing on layout and style consistency.

### Testing information  
- **Devices Used:** Tested on tablet emulator.
- **Alternate Workflows:** 
  - Verify edge cases where the cart has numerous items or is empty.
- **Affected Areas:** 
  - Cart screen
  - Totals screen
- **Critical Flows:** 
  - Ensure no functional regressions occur in the checkout process.

### Release Notes
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
@kidinov I think it's pretty close to the design now (although not quite). Should I try to make further changes in this PR or ticket out the remaining modifications?

**Comment by kidinov** [comment]
@backwardstruck 👋

I noticed that the margin is not correct now (weirdly that on your screenshot it's ok 🤔 ). The loading state also has an incorrect margin. The success screen lost it's margin too

Having said that, now that we are getting m2 designs, which do not contain this at all, I am wondering if it makes sense to make these changes at all, wdyt?

image


image

image

**Comment by backwardstruck** [comment]
> @backwardstruck 👋
> 
> I noticed that the margin is not correct now (weirdly that on your screenshot it's ok 🤔 ). The loading state also has an incorrect margin. The success screen lost it's margin too
> 
> Having said that, now that we are getting m2 designs, which do not contain this at all, I am wondering if it makes sense to make these changes at all, wdyt?
> 
> image image image

Ah, that screenshot is from the design, not the app. So that's why it's 100% correct. 

You're right, about the margins. 

I didn't realize the M2 designs were so different. Let me check and potentially close this PR then.

**Comment by backwardstruck** [comment]
Final decision on this pending Slack discussion:

https://a8c.slack.com/archives/C070SJRA8DP/p1720190008512919?thread_ts=1720104580.663059&cid=C070SJRA8DP

**Comment by backwardstruck** [comment]
@kidinov this is updated to simply remove the cards from cart and totals screens. I made a separate ticket to finish updating both cart and totals screens for the M2 design (e.g. replacing the Collect Card Payment button):
https://github.com/woocommerce/woocommerce-android/issues/11933

**Comment by kidinov** [comment]
@backwardstruck 👋

Looks good! I just noticed the margins may be a bit too big on the cart. And the margin between products and the cart a bit too small. Also, maybe changes from [that PR ](https://github.com/woocommerce/woocommerce-android/pull/11940) can be used to avoid merge conflicts and reuse the method that adapts margins for smaller screens. It should be merged to the trunk soon)

Screenshot 2024-07-12 at 10 08 31

image

**Comment by backwardstruck** [comment]
Thanks for the additional review @kidinov It should be closer to the design now:

*  Fixed the margins may be a bit too big on the cart. 

* Fixed the margin between products and the cart a bit too small. 

* Reused the new toAdaptivePadding method that adapts margins for smaller screens.

**Review by kidinov — APPROVED** [review]
I think start/end padding are different now on the totals and  on the cart screens, but I think it's fine to  move on with this, as we anyway will have to redo those screens as they changed in m2

image

**Pull request merged**
