### PR TITLE
feature/2889 trash project master

### LINKED ISSUE #2889: Add the ability to delete (trash) a product
Users need the ability to send a product to the trash. Note that the trash menu item should only be shown when product detail is called from the product list. Designs below.

trash

[Related FluxC issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1695)

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #2889 - This is the feature branch for deleting a product. All code has already been reviewed, but a design review is still required.

Apologies for the typo in the branch name ("**i**feature" instead of "feature").

trash

Update release notes (this is hidden behind an M5 feature flag so I haven't updated the release notes):

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by AmandaRiu — COMMENTED** [review]
@nbradbury I pulled down this branch and played around with this new feature to check all was well and it all works great. The only thing I noticed which was kind of weird is that when I open a trashed product by clicking on a product in order detail, the status configuration for that product looks like this:



I can select "Published" and update the product and it will un-trash the product which makes sense. For completeness I think it would make sense to add a "Trashed" status on this page so something is selected when the user opens this page. 

Also, there's nothing in the product detail view that makes it apparent that a product has been trashed which may lead to confusion for the user at some point. When a product is in status `Draft` we show that status in the photos area...maybe it'd make sense to have something similar for `Trashed` products? WDYT? cc: @Garance91540 

Draft | Trashed
-- | --
Screenshot_1601491010|Screenshot_1601490946

**Comment by nbradbury** [comment]
> For completeness I think it would make sense to add a "Trashed" status on this page so something is selected when the user opens this page...Also, there's nothing in the product detail view that makes it apparent that a product has been trashed which may lead to confusion for the user at some point. When a product is in status `Draft` we show that status in the photos area...maybe it'd make sense to have something similar for `Trashed` products?

Thanks for the review @AmandaRiu. I agree with you on both counts, but I think those issues are outside the scope of this PR since they already existed. This PR simply adds the ability to trash a product.

**Comment by Garance91540** [comment]
> Also, there's nothing in the product detail view that makes it apparent that a product has been trashed which may lead to confusion for the user at some point. When a product is in status Draft we show that status in the photos area...maybe it'd make sense to have something similar for Trashed products? WDYT? cc: @Garance91540

Are you saying that a Trashed product is still going to be seen in the Product list?

**Review by Garance91540 — DISMISSED** [review]
👏

**Comment by nbradbury** [comment]
> Are you saying that a Trashed product is still going to be seen in the Product list?

No, it won't. But it will still show up in order detail if someone ordered a product that has since been trashed.

**Comment by nbradbury** [comment]
@AmandaRiu This has passed design review and can be merged.

**Comment by Garance91540** [comment]
> Are you saying that a Trashed product is still going to be seen in the Product list?
No, it won't. But it will still show up in order detail if someone ordered a product that has since been trashed.

Gotcha. In that case I agree with Amanda's suggestion of adding the "Trashed" tag over the first product picture makes sense!

**Comment by nbradbury** [comment]
> Gotcha. In that case I agree with Amanda's suggestion of adding the "Trashed" tag over the first product picture makes sense!

I opened #2949 to address this.

**Comment by AmandaRiu** [comment]
@nbradbury There are some conflicts that need to be fixed before this can be merged.

**Comment by nbradbury** [comment]
> There are some conflicts that need to be fixed before this can be merged.

@AmandaRiu  Don't you love it when you're working with multiple PRs that all conflict with each other? Conflicts are resolved now.

**Review by AmandaRiu — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
