### PR TITLE
Blaze: Edit-ad screen parameters and result handlers

### PR DESCRIPTION
**Pull request by 0nko**
Part of #10519. This PR adds the data that gets passed to the edit-ad screen and allows to save the edit changes, which are reflected in the preview screen.

[Screen_recording_20240119_174709.webm](https://github.com/woocommerce/woocommerce-android/assets/1522856/6fa4b1f9-2b16-42fb-881f-d174e4471a8b)

**To test:**
1. Start the app and start the Blaze campaign creation
2. Tap on the Edit ad button
3. Notice the existing image, tagline and description are loaded in the edit-ad screen
4. Change all properties
5. Tap on the Save button
6. Notice the changes are reflected in the preview screen

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by JorgeMucientes** [comment]
Thanks for working on this @0nko. 

After testing the functionality, I noticed a couple of issues. 

One is not blocking but would be nice to get it fixed. I think when editing the tagline or description input we should save those values in the `viewState` from the viewModel, or else when opening the image selector the entered text will be lost, resulting in an annoying experience for the user. 


https://github.com/woocommerce/woocommerce-android/assets/2663464/6b0648f7-33a3-4636-9f2e-3629522d7594

About the other one, by looking at the code I wasn't able to figure out what is going on. But there seems to be a problem when trying to save the updated ad values whenever we update the image for it. If I only update the `tagline` and `descriptions` input text everything works as expected, but if I update the image when clicking `Save` it won't work: 

https://github.com/woocommerce/woocommerce-android/assets/2663464/a37eeb7d-e174-412f-a534-925e30c75864

I think the issue might be on the `Preview` logic, though. I'll try to debug it and take a look at it tomorrow.

**Comment by 0nko** [comment]
Thanks for the suggestions! I've implemented the state persistence. However, I wasn't able to reproduce the saving issue.. 

[Screen_recording_20240122_180204.webm](https://github.com/woocommerce/woocommerce-android/assets/1522856/4e8c0de7-6e69-4dac-91b7-59794f453e8e)

Looking at the video, it seems like the app silently crashes when it goes blank after going back to the preview screen... What API version did you use for testing?

**Comment by JorgeMucientes** [comment]
Hey @0nko! Thanks for applying the suggestion. 
About the other issue. I think I had `Don't keep activities` option enabled. After disabling it, it worked fine. I think this drastically reduces the issue's severity, and is none blocking now. But I still think it's worth taking a look to see what is going on. 
Btw I didn't see any crash in the logcat, so no sure the app is crashing.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by 0nko** [comment]
@JorgeMucientes Actually, that would make sense. In your video, the system image picker is opened, which opens a different activity and the WCAndroid state would be lost. I also enabled `Don't keep activities` and with the state preservation I don't see any issue, so it seems like both problems were fixed.

**Comment by JorgeMucientes** [comment]
Oh yeah, that's right! Glad we killed two birds one stone with the ViewModel state preservation. I've re-tested it enabling `Don't keep activities` and everything works well again 👍🏼 
Ready to ship @0nko

**Pull request merged**
