### PR TITLE
Dark Mode: Launcher Icon

### LINKED ISSUE #1914: Dark Mode: Update launcher icon
Create new launcher icons using Android Asset Studio and this image resource: 

App Store Icon 1024x1024@2x (1)

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #1914 by updating the launcher icons with the new color scheme. Also updated the launcher icons for the wasabi builds.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
@Garance91540 How does this look for the launcher icon?

**Comment by AmandaRiu** [comment]
This one is ready for review.

**Comment by AmandaRiu** [comment]
@anitaa1990 Thanks for the review!

> The only time the logo didn't change was in Pixel 2 XL API 21 device. I am still seeing the old logo.

This is because the minimum supported version is 23. We used to support API 21, but eventually dropped it.

**Comment by anitaa1990** [comment]
> This is because the minimum supported version is 23. We used to support API 21, but eventually dropped it.

😮TIL!!

**Comment by AmandaRiu** [comment]
> This is because the minimum supported version is 23. We used to support API 21, but eventually dropped it.

> 😮TIL!!

@anitaa1990 Aaaand....it looks like I misspoke there. Our minimum is 21 (not really sure why I thought it wasn't :/ I think it was just wishful thinking.

**Pull request merged**
