### PR TITLE
origin/issue/5962-product-detail-bottom-sheet-exception-take2

### LINKED ISSUE #5962: IndexOutOfBoundsException in ProductDetailBottomSheetAdapter
Sentry Issue: [WOOCOMMERCE-ANDROID-XW](https://sentry.io/organizations/a8c/issues/1939862035/?referrer=github_integration)

```
IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:5 androidx.recyclerview.widget.RecyclerView{e578fca VFED..... ......ID 0,130-1080,1145 #7f0a05f7 app:id/productDetailInfo_optionsList}, adapter:com.woocommerce.android.ui.products.ProductDetailBottomSheetAdapter@953f53b, layout:androidx.recyclerview.widget.LinearLayoutManager@4199458, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@e2729b1
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6364)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
...
(54 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by nbradbury**
This is the second attempt to fix #5962, a mystery crash in `ProductDetailBottomSheetAdapter`. I noticed that rather than return a unique ID in that adapter's `getItemId()`, we return `position.toLong()`. We do that in many places in WCAndroid, but ideally if an adapter has stable IDs we should provide a unique ID instead of the position.

So, this PR updates the adapter to use a unique ID for each item. I also slightly modified the way the list is populated, but that was for clarity rather than an attempt to fix this problem.

If we continue to see these crashes after this PR is in a release, I recommend the next step is to try not using unique IDs for the adapter.

To test:
 * Open product detail
 * Tap the "Add more details button"
 * Ensure the bottom sheet works as expected

### CODE REVIEW

**Comment by JorgeMucientes** [comment]
Thanks for reviewing this crash again @nbradbury. While the id generation change makes sense I don't see how is it going to have an impact on solving the crash. I'm also unsure the crash is related to the ids generation. What makes you suspect about this part of the code causing the crash? 

I like the applied refactor on how the list is `set`. Nicely done!

As a side note after reviewing this part of the code again. I'm wondering why do we need `setHasStableIds(true)` and `getItemId` function at all? Might be missing something, but my understanding is that we use `setHasStableIds(true)` to avoid a blinking effect over the recyclerView items when we apply state updates over these items while in foreground. But afaik this does not happen for the bottom sheet items. We don't apply any modifications over the items once they are shown. So, my guess is: we can get rid of this code: 
```kotlin 
init {
    setHasStableIds(true)
}

//and

override fun getItemId(position: Int) = options[position].type.ordinal.toLong()
```

Don't think that is going to fix anything but at least we remove some unnecessary code and if the crash keeps happening at least we don't have to look into that part anymore. Wdyt?

**Comment by nbradbury** [comment]
> What makes you suspect about this part of the code causing the crash?

Nothing but a hunch :) I do know that relying on `position` as the unique ID isn't a good practice and can cause problems, but I really don't know if that's the cause here.

> my understanding is that we use `setHasStableIds(true)` to avoid a blinking effect over the recyclerView items when we apply state updates over these items while in foreground. But afaik this does not happen for the bottom sheet items

A fair point. So you suggest simply getting rid of stable IDs here and see if that helps?

**Comment by JorgeMucientes** [comment]
> So you suggest simply getting rid of stable IDs here and see if that helps?

Yes I think we can get rid of `setHasStableIds(true)` and also `override fun getItemId(position: Int){ }`. Afaik `getItemId()` is only needed because we are calling `setHasStableIds(true)` in the first place. 

I doubt that will solve the crash though, I just think that getting rid of unnecessary code is good in itself, and it is also one less thing we have to worry about in case the crash keeps happening.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by nbradbury** [comment]
> Yes I think we can get rid of `setHasStableIds(true)` and also `override fun getItemId(position: Int)`

Done in [2c2c858](https://github.com/woocommerce/woocommerce-android/pull/6088/commits/2c2c8581187758352710ce7947f21bacf85c27e3)

**Comment by JorgeMucientes** [comment]
Thanks for applying the changes @nbradbury! Whether this solves the issue or not, the code has improved, so thanks for dealing with this.
Let's keep an eye on the crash and see if it gets resolved 🤞🏼  or needs another round.

**Pull request merged**
