### PR TITLE
Dark Mode: Settings About Page

### LINKED ISSUE #1584: Dark Mode: style Settings screens
Implement light/dark mode on the settings views.

Screen Shot 2020-01-14 at 3 53 37 PM

Screen Shot 2020-01-14 at 3 53 29 PM

TODO
- [x] Main settings (#1822 )
- [x] Site picker/store changer (#1824 )
- [x] Privacy Settings (#1834)
- [x] Beta features (#1838)
- [x] About (#1835)
- [x] Notification settings (for older APIs) (#1822)
- [x] Fine Tuning (#1843)

### PR DESCRIPTION
**Pull request by AmandaRiu**
Partially fixes #1584 by implementing light/dark  mode styling on the About view. 

There is no official design for these changes, and most of the components in this view don't have an exact match in the material component design specs for Woo Mobile. So, I made some guesses and applied the following styles:
- **Title** = text style: Headline 5, color: `color_on_primary_surface` (ie: white)
- **Body** = text style: Subtitle 2, color: `color_on_primary_surface` (ie: white)
- **Background** = `color_primary_surface`

Note: 
- `color_on_primary_surface` means that in light mode we use `color_on_primary`, and in dark mode we use `color_on_surface`
- `color_primary_suface` means that in light mode we use `color_primary` and in dark mode we use `color_surface`. 

The buttons don't follow any established button styles so I created a special style just for these buttons. This is not ideal as all buttons in the app should follow the same basic button types in the material component design specs for Woo Mobile.

## Screenshots

settings-about

## Recommended Testing
- Test viewing in light and dark modes
- Test on API 21 and API 29

cc: @kyleaparker @Garance91540  - please review the designs and my comments in this PR body. I have a feeling more changes are needed. Thank you!

## Update

Designs have been updated. Here are the new screenshots:

### CODE REVIEW

**Comment by AmandaRiu** [comment]
This one is ready for code review. When a new fresh design is released for this page it can be tackled at that point.

**Comment by Garance91540** [comment]
Hi Amanda, I agree with you that it would be best to use existing Material components, so I added designs for this screens using Material list items (also making this screen more consistent with what we have on iOS).

Screen Shot 2020-01-21 at 12 51 13 PM

Let me know your thoughts on this!

**Comment by nbradbury** [comment]
@AmandaRiu Code looks good and I can merge, but I'm holding off since @Garance91540 posted new designs here. If you still want to tackle that separately, let me know and I'll approve this.

**Comment by AmandaRiu** [comment]
@nbradbury Thank you for checking in. I'm going to go ahead and apply the new designs first.

**Comment by AmandaRiu** [comment]
@Garance91540 I left the following comment in the design: 

> For the rest of settings, the options are not elevated and there are no ">" symbols. For example - check out "Open source licenses" in the main settings page design. All the settings components that I build for light/dark mode follow those designs. Is it possible to have this view follow the same design?

Below are some options that foloow the baseline styles established by the main settings view. Note: I kept `automattic.com` because that's a link that leads the user to our webpage, but I can remove it if you like: 

## Variation 1
new-about-3

## Variation 2
new-about-2

## Variation 3
new-about-1


WDYT?

**Comment by AmandaRiu** [comment]
> variation #3 looks good to me! Bonus point if we can update the left padding of the text (Privacy policy and terms of service) to 16px so it doesn't look too off-centered, but we can drop it if too complicated.

Ah yea I left that in there since the material specs require settings options to be aligned with the page title.

**Comment by AmandaRiu** [comment]
this one is ready for review 👍

**Pull request merged**
