### PR TITLE
Use HTTP API calls to trigger release jobs

### PR DESCRIPTION
**Pull request by loremattei**
This PR updates our release tools to trigger any CI release job via an API call instead of relying on the automatic trigger on tags.
This way, it will be easier and cleaner to handle any failure during the release build and, moreover, it'll be possible to move more steps of the releases to CI (for example, validation and lint steps that can fail by design).

Note that in order to use the release tools, users should configure a new token for CircleCI on their local environment, following these steps:

- Go to `https://app.circleci.com/settings/user/tokens`.
- Create a Personal API Token.
- Add `CIRCLE_CI_AUTH_TOKEN=<Your Token>` to your `~/.wcandroid-env.default` (you can check out the updated `fastlane/env.example` for a template).

**To test:**
Full testing is tricky because it's tight to the release cycle. Anyway, it's possible to test the critical part of it this way:

- checkout a new `release/test` branch from this one and push it.
- add a dummy commit (the build will fail, so adding a dummy commit will avoid the failure to be reported to this PR).
- `bundle install`
- Run `bundle exec fastlane trigger_release_build branch_to_build:"release/test"`
- Verify that the release build job has been started on CircleCI. The job will fail during the upload to PlayStore because the current version is already present. This is fine.
- Delete the test branch.

**Review**
I've asked the review to @AliSoftware because he is currently the release manager of WooCommerce Android. All the code is already in production in WPiOS, so it should be fine, but there may always be some nuances with porting that I missed, so I think that understanding the changes will help if something happens during the next release.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by AliSoftware — COMMENTED** [review]
Code LGTM. Planning on actually testing (with a fake release branch and all) after lunch so I can hopefully approve it later today.

**Review by AliSoftware — APPROVED** [review]
Tested with [this triggered CI build](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/10642/workflows/13341343-88a6-4b7e-9f42-2e23239ae401/jobs/33848), worked as expected! :shipit: 

---

~While testing this, I thought it would be nice if the action could `UI.message` the URL of the CI workflow once triggered, so that we can ⌘-click on that URL from the Terminal to open the CircleCI page directly. Do you know if that would be easily possible?~

~After a quick look at the CircleCI v2 API, it seems that the API call returns a **pipeline** number and ID (e.g. `{"number":10644,"state":"pending","id":"211c6fa2-6bc1-46ef-ab0e-d70acc5092ad","created_at":"2021-04-14T13:31:12.075Z"}`) but not a workflow ID. So I'm not sure if we can easily derive a clickable URL from that without having to do an additional API call (which would not be worth it imho). Tried to build working URLs by only using the pipeline number and ID, but haven't found a valid one yet~ 😒 

[EDIT] [Found this, so I guess we're not the only one wanting this feature and seems it's not possible at the time](https://discuss.circleci.com/t/webpage-view-of-a-single-pipeline/35381) (not without an additional API call anyway). Dammit. 😒

**Comment by AliSoftware** [comment]
\cc @JavonDavis Since you're working on fixing the breaking change on release-toolkit 0.17.0 around `get_prs_list`, you might want to synchronize your fix with this PR, since this PR updates the toolkit from `0.14.x` to `0.17.1` (and thus would pick up the bug)

**Comment by JavonDavis** [comment]
Hey @AliSoftware This should be fine but at the moment there's two known issues I'm working on in this version of the release toolkit 

1. The code to get PRs seems to be broken, this will affect how contributors are populated when generating the internal P2 post
2. The .po file isn't generated when running the string translations

I'll open issues on the release toolkit repo to track these but I should have a PR up resolving these today or tomorrow. Then you'll need to update the version of the toolkit that's being targeted here. Your options can be to wait for those changes and update this branch or update it in a separate PR. I have no strong feelings towards either of these really so I'll leave that up to you and @loremattei .

**Comment by AliSoftware** [comment]
As discussed in Slack, since at least for (1), the fix that is required is in each repo's Fastfile not in the toolkit itself (because the release-toolkit introduced a braking change in the API of `get_prs_list` so we need to update the call sites to call it with new params now), having a new version of the toolkit won't be enough, and we will need a PR in woocommerce-android (on top of this #3785) to fix it.

Since merging this PR will make the API trigger (subject of that PR) work… but will make the lane crash during `get_prs_list` (due to bump to 0.17.1 with breaking change in API), and will thus break the release process overall, I suggest as said in Slack that:

 - You open a PR on top of this one (i.e. cut a branch from `update/use-api-to-trigger-release-jobs`) to fix the calls to `get_prs_list`, and make that PR target `update/use-api-to-trigger-release-jobs`.
 - Then once that other PR is approved, we can merge both PRs at once (first this 3785 – which will auto-update the target branch of the other PR – then the other PR immediately after it)

The alternative would be for you to cut your branch from `develop` directly, update the `Pluginfile` to point to the toolkit 0.17.1 and the call sites of `get_prs_lists` together, make a PR to merge this in `develop`, and then go back to this PR #3785 to fix the potential conflict (as this PR also updates the `Pluginfile` to `0.17.1` meaning same change as the one you'd have just merged into `develop`).

Whatever solution you choose (make your PR on top of this one, or make the fix separate by cutting from develop), in any case we should wait for your fix for `get_prs_list` in this repo to be submitted and approved and ready to merge first before considering merging this PR #3785.

**Comment by JavonDavis** [comment]
> As discussed in Slack, since at least for (1), the fix that is required is in each repo's Fastfile not in the toolkit itself (because the release-toolkit introduced a braking change in the API of get_prs_list so we need to update the call sites to call it with new params now),

Sorry I left off some additional context here when we chatted in Slack, when I was originally investigating even after updating the params, this did not generate the correct result in the PR list file, hence why I mentioned the need to point to a new release-toolkit version but after looking into it a bit further I think this was encountered because of the ❄️  in the milestone name and no actual change needed there in the release toolkit. That said, your suggestions make total sense and I should have the new branch in this repo and WPAndroid ready today!

**Comment by JavonDavis** [comment]
Opened the PR for the ger_prs_list issue here -> https://github.com/woocommerce/woocommerce-android/pull/3861

**Comment by AliSoftware** [comment]
@JavonDavis now that #3861 has been merged this one should be ready to be merged too… once the conflicts has been resolved.

I'm surprised that GitHub mentions a conflict for the `Gemfile.lock` and `fastlane/Pluginfile`… but not for `Fastfile`, while the `Fastfile` was changed by Jeremy to update the `get_prs_lists` call [during last code freeze – though with a typo when he updated to the new params, so the ones in this PR are the correct ones, not the ones in `develop`](https://github.com/woocommerce/woocommerce-ios/pull/3999/files#r620446871). So we might want to double-check which version `git` decided to merge during its auto-conflict-resolution on the `Fastfile` to be sure we end up with the correct one of the two in the end.

**Comment by JavonDavis** [comment]
@AliSoftware Done! I'll let you double-check this and hit the merge button 🙂

**Review by AliSoftware — APPROVED** [review]

**Pull request merged**
