### PR TITLE
Add analytics to hub settings

### LINKED ISSUE #10704: [Analytics Hub] Add tracking for layout customization
New events:

- `analytics_hub_settings_opened`
   - Triggered when the user taps on the settings icon in the Analytics Hub, to open the settings screen.
- `analytics_hub_settings_saved`
   - Custom prop `enabled_cards` with value set to a comma-separated list of all the currently enabled cards (e.g. `revenue,orders,products`)
   - Custom prop `disabled_cards` with value set to a comma-separated list of all the currently disabled cards

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: #10704 

### Why
As part of Expanded Analytics Hub milestone 2, we plan to add support for customizing the cards we display on the Analytic Hub screen.

### Description
This PR adds track events to the new Customize analytics screen.

 ### New events

 `analytics_hub_settings_opened` Registration: https://github.com/Automattic/tracks-events-registration/pull/2262
Triggered when the user taps on the settings icon in the Analytics Hub, to open the settings screen.}

`analytics_hub_settings_saved` Registration: https://github.com/Automattic/tracks-events-registration/pull/2263
Triggered when the user taps on the save menu to save the configuration
Custom prop `enabled_cards `with value set to a comma-separated list of all the currently enabled cards (e.g. revenue,orders,products)
Custom prop `disabled_cards` with value set to a comma-separated list of all the currently disabled cards
 

### Testing instructions
TC1
1. Open the app
2. Tap on See more
3. Tap on the pencil icon to navigate to the Customize Analytics screen
4. Check that the `analytics_hub_settings_opened` event is triggered

TC2
1. Open the app
2. Tap on See more
3. Tap on the pencil icon to navigate to the Customize Analytics screen
4. Edit the configuration to enable the Save button
5. Tap on Save
6. Check that the `analytics_hub_settings_saved` is triggered
7. Check that the `enabled_cards` property is part of the event, and the list of enabled cards matches the current configuration
8. Check that the `disabled_cards` property is part of the event, and the list of disabled cards matches the current configuration

### Images/gif
```
🔵 Tracked: analytics_hub_settings_opened, Properties: {"blog_id":214253715,"is_wpcom_store":true,"was_ecommerce_trial":false,"plan_product_slug":"ecommerce-bundle","store_id":"78fb3abe-869e-4280-8dcf-c4c94c9b84b6","is_debug":true,"site_url":"https:\/\/superlativecentaur.wpcomstaging.com"}

🔵 Tracked: analytics_hub_settings_saved, Properties: {"enabled_cards":"session,orders","disabled_cards":"revenue,products","blog_id":214253715,"is_wpcom_store":true,"was_ecommerce_trial":false,"plan_product_slug":"ecommerce-bundle","store_id":"78fb3abe-869e-4280-8dcf-c4c94c9b84b6","is_debug":true,"site_url":"https:\/\/superlativecentaur.wpcomstaging.com"}
```

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by rachelmcr** [comment]
@atorresveiga Instead of using an array of strings (e.g. `["products","revenue"]`) for the custom properties, could we use a single string with comma-separated values (e.g. `products,revenue`)? Sorry for being unclear in the issue — a single string is more in line with other events that save lists like this.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by atorresveiga** [comment]
> @atorresveiga Instead of using an array of strings (e.g. `["products","revenue"]`) for the custom properties, could we use a single string with comma-separated values (e.g. `products,revenue`)? Sorry for being unclear in the issue — a single string is more in line with other events that save lists like this.

Good point @rachelmcr! Fixed here: https://github.com/woocommerce/woocommerce-android/pull/10952/commits/11f09879b2b17012b7d5ba84769d2f58fddd2cd0

**Review by ThomazFB — APPROVED** [review]
Looks good!

**Pull request merged**
