### PR TITLE
Feature/7254 reduce infinite loading

### LINKED ISSUE #7254: Mitigate infinite loading experience on subsequent Jetpack timeout errors
Mitigate the infinite loading experience when Jetpack can't connect to user's site and subsequent retries are fired behind scenes resulting the following experience: 

https://user-images.githubusercontent.com/2663464/185878323-9f18c9fc-4b18-47d9-b164-29cd1878b462.mp4

More info here: pe5sF9-t6-p2

To avoid this we will: 
- Reduce the number of retries for Jetpack tunnel requests 
- Add a clear error to handle subsequent timeout errors, explaining there's a Jetpack error connecting to their site and suggesting to reach to support.

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #7254 

### Description
This PR aims to provide a better feedback and support when users experience Jetpack tunnel timeout errors when trying to verify their site. Right now this is what they experience: 

https://user-images.githubusercontent.com/2663464/187166517-f7e876f5-42c6-43b8-af88-58a00c54e6fc.mp4

With these changes applied in [FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2512) and the current changes from this PR we will display a new error dialog in SitePicker providing an option to contact support. 
  
### Testing instructions
Testing this is a bit tricky as I haven't found a way to force test sites to make them slow enough to generate timeout errors. I think the easiest way is to: 
- Enable composite build for FluxC by uncommenting `localFluxCPath = "../WordPress-FluxC-Android"` from `local-buidls.gradle` 
-  Checkout branch `feature/7254-reduce-inifinte-loading` in FluxC repo
- Go to `JetpackTunnelGsonRequestBuilder` and set `DEFAULT_JETPACK_TUNNEL_TIMEOUT_MS` to 200ms. This will ensure we get a timeout error whenever trying to verify site 
- Check the following dialog is shown:

https://user-images.githubusercontent.com/2663464/187158794-6bec3a97-e9f7-4921-94ef-0d7e86f3b04e.mp4

- Click on Contact Support and verify Help screen is open with the dialog that starts the create ticket flow. 
- Check the following events are tracked: 
`site_picker_jetpack_timeout_error_shown` 
and 
`site_picker_jetpack_timeout_contact_support_clicked`

### CODE REVIEW

**Comment by 0nko** [comment]
I think you forgot to include the testing instructions :)

**Comment by JorgeMucientes** [comment]
> I think you forgot to include the testing instructions :)

Your're right @0nko . I had this in draft but didn't notice that testing instructions were required here in order for the FluxC PR to be properly reviewed. 

Added testing instructions and missing details. Ready to be reviewed now

**Review by 0nko — APPROVED** [review]
The timeout and the dialog is working as described in the test instructions. 👍

**Comment by 0nko** [comment]
Once the FluxC reference is updated, we can merge this PR.

**Pull request merged**
