### PR TITLE
Remove redundant "No Price" banner

### LINKED ISSUE #4258: Variations: Remove redundant "No Price" banner
Could we remove the price alert banner on the Variations list screen (sorry I know this was in the original designs)? I think it’s probably enough that we show the banner on the parent product page + the “No price set” button. With the banner, the Variation list screen becomes a bit too crowded

screen-shot-2021-06-16-at-4 07 44-pm

- [ ] Move the "No price" banner to the main product page
- [ ] Remove the "No price" banner in the Variations list

---

p5T066-2p9-p2#comment-8783

### PR DESCRIPTION
**Pull request by rossanafmenezes**
Fixes #4258

## Changes

Removes the variationVisibilityWarning Warning banner for variations without prices since there is already a No Price Set tag showing in the variation. 

## Screenshots

| Before | After |
| ---- | ---- |
|  |  |
|  |  |

## Steps to reproduce

- Go to the Products screen
- Click on a variable product where at least one of the variations has no price set
- click on the Variations tab
- See the warning banner has been removed

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rossanafmenezes** [comment]
One thing that crossed my mind about this one. I wonder if removing the warning which has more information than the actual `no price set` tag (it says the product will not be visible unless you add a price) would affect the support requests. I haven't seen any in the mobile queue but supporting Woo in general I have seen customers asking for help because the product was not showing and the issue was the price missing. Probably it wouldn't affect in a relevant way (in terms of volume), but I was just wondering.

**Comment by ThomazFB** [comment]
Hey @rossanafmenezes, thanks for tackling this! I agree with your point, just removing the banner from the Variation list will probably hide info from our merchants who might not be aware of the consequences of leaving a variation with no price set! 

The thing is: the issue also describes that we should remove the banner from the Variation List and place it at the Product Details view, the reason for that is just because the banner alongside the `no price set` label at the same view info sounds redundant. Doing so would make the warning still present, but now in another view. So I believe we should also do this banner moving in this PR, WDYT?

Can you confirm if this is the intended objective of the issue @shiki? Just to be sure I'm not making a confusion here 😬

**Comment by rossanafmenezes** [comment]
Thank you for reviewing it @ThomazFB

> So I believe we should also do this banner moving in this PR, WDYT?

That would be my next question because what I understood is that we already show it on the parent product screen but I don't actually see it so I might have interpreted wrong what Jason meant. 

That said, the iOS PR just removed it as far as I can tell https://github.com/woocommerce/woocommerce-ios/pull/4532

Let's see what @shiki says 😄

**Comment by shiki** [comment]
@ThomazFB is correct. The banner is still important to remind merchants that having no price set means that the variation will not be visible on the website. The banner moving should be done at the same time. 🙂 Sorry for the confusing GitHub issue!

**Comment by rossanafmenezes** [comment]
Thank you @shiki for the clarification. I will work on this to add the banner to the parent product page then.

**Comment by rossanafmenezes** [comment]
Hi @ThomazFB 

I have added the banner to the Product Detail screen as per the screenshots below. As I mentioned, the banner does not show on a new product added from the browser because this is pulling from the local database. 

Thank you in advance for reviewing it again. 

| Variation with Price | Variation W/O price |
| ---- | ---- |
|  |  |

cc: Thank you @malinajirka for helping with this one

**Review by ThomazFB — APPROVED** [review]
Great work @rossanafmenezes! 🎉 Thanks for going through the entire path for fixing this! LGTM :shipit:

**Pull request merged**
