### PR TITLE
[Woo POS] Products UI adjustments #2

### LINKED ISSUE #12513: [Woo POS] Products UI adjustments #2
* ❓ Design. Products Screen bottom Corners too round – match to reader connection button.
* ❓ Design. Products Screen bottom Wild shadows – too strong, clipped on top and bottom, and stronger on the right.
* ❓ Design. Products Screen bottom Remove shadow on button.
* Design. Products Screen bottom Removing a product causes the weird clipping issue. It’s good that it animates the lower products up, though.
* ❓ Design. Products Screen bottom Check toolbar is vertically centered with the checkout button (without connecting checkout button position).
* ❓ Design. Products Screen bottom Margin below button should match left and right margins.

Image

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12513

### Description

* Changes the background color of the home screen as the "background" from the theme appeared to be different to the design
* Removes shadows/elevations from the buttons
* Corner radius of the "clear" button set to 4 the same as "connect to a reader"
* The checkout button is 16dp from bottom/left/right now
* Removed `animateItemPlacement` as this is buggy and there is a weird clipping issue when an item removed (When 1.7.0 is released will have to use https://developer.android.com/reference/kotlin/androidx/compose/foundation/lazy/LazyItemScope#(androidx.compose.ui.Modifier).animateItem(androidx.compose.animation.core.FiniteAnimationSpec,androidx.compose.animation.core.FiniteAnimationSpec,androidx.compose.animation.core.FiniteAnimationSpec)
* Slightly slow down the elevation animation of adding a new item to a cart

### Testing information

Check the description and validate all the changes visually

### The tests that have been performed

Validated the changes visually in both dark and light mode

### Images/gif

https://github.com/user-attachments/assets/6976d074-d40a-4e58-ba70-dde9de3747ac

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">This PR is tagged with <code>status: do not merge</code> label(s).</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @kidinov. LGTM 🚀 

I couldn't find any changes related to this from your PR description:
`The checkout button is 16dp from bottom/left/right now` Just wanted to ensure I'm not missing anything here.

**Comment by kidinov** [comment]
@AnirudhBhat thanks for the review

> I couldn't find any changes related to this from your PR description:
The checkout button is 16dp from bottom/left/right now Just wanted to ensure I'm not missing anything here.

It looks like that I fixed it there already when converted the layout to constraint

https://github.com/woocommerce/woocommerce-android/pull/12522/files#diff-fd30e2357047cd3873c2b6cf479ab48081a5165511c6abce9f2b055a14db2193R102

**Pull request merged**
