### PR TITLE
[Better Tablet Products] Infinite loading

### LINKED ISSUE #11134: [Better Tablet Products] Infinite loading
* Open Product List on Pixel 7 emulator (portrait)
* Open Detail of a product
* Press back
* Change to landscape
* Notice a two pane layout is shown but the product detail never finishes loading

Report by @malinajirka. More detail - p1711023354229269/1711023350.773419-slack-C06C3CZFHGD

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #11134

### Description

The PR:
* Renames `isTablet` class to `IsWindowClassLargeThanCompact` to convey better the meaning
* Returns divider for products back as this seems to be regression and it doesn't match the orders
* Fixes the bug when after returning back from a selected product, and changing configuration to landscape mode, no products were selected

### Testing instructions

* Follow the steps in the issues
* Notice that the first product will be selected now

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/67825950-1256-48c4-870d-faa46bb25411

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jd-alexander** [comment]
@kidinov I will review this in the morning!

**Review by jd-alexander — COMMENTED** [review]
Solutions looks good however, I was not able to reproduce the issue. I am wondering if certain network conditions are needed for reproduction or some other state is necessary. 

Something I did notice during the switch from portrait to landscape is that the up/back action changes and when the X is present it doesnt go back to the Product list, it goes to the home screen. 

X button | Back button 
--------|-------
   <kbd></kbd>  |       <kbd></kbd>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/203">18.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by kidinov** [comment]
@jd-alexander 👋

>  I am wondering if certain network conditions are needed for reproduction or some other state is necessary.

Nope, that's always reproducible, and it's not related to the network conditions. That's a video from the current trunk:

https://github.com/woocommerce/woocommerce-android/assets/4923871/76b8dfbf-8460-4f16-8c6b-e7657d82b8a6


X button is another issue and has been fixed already, and now, as I merged changes from the trunk, it should not be reproducible on this branch now

**Review by jd-alexander — APPROVED** [review]
Works as expected. 🚢

**Pull request merged**
