### PR TITLE
Issue/1801 empty states order list part2

### PR DESCRIPTION
**Pull request by nbradbury**
This is the second PR to address the order list part of #1801. In this PR, `OrderListEmptyUiState` is completely replaced by the new empty view and empty states for network errors were added. Tests have been updated to reflect these changes.

offline

error

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@AmandaRiu This one is now ready for review.

**Comment by nbradbury** [comment]
> `empty_view_secondary_image` doesn't appear to be hiding properly

Thanks for catching that. It turned out to be due to my not hiding the `empty_view_message` when there was no message. Fixed in 7c217a1.

> The "loading" empty view isn't getting hidden properly when coming back from offline

I'm not sure what you mean, as the gif doesn't match your description (the loading empty view isn't in the gif).

**Comment by AmandaRiu** [comment]
> I'm not sure what you mean, as the gif doesn't match your description (the loading empty view isn't in the gif).

Oh weird! Apparently the mp4 to gif converter I used assumed I only needed the first 5 seconds of my video. Below is the full video. This can be addressed in another PR so it won't hold up this one: 

ezgif com-video-to-gif

**Comment by AmandaRiu** [comment]
@nbradbury while testing I also found that you can duplicate the issue of the "looking up orders..." view not hiding by logging into a store for the first time.

**Comment by nbradbury** [comment]
> while testing I also found that you can duplicate the issue of the "looking up orders..." view not hiding by logging into a store for the first time.

I figured out the problem and fixed it in the feature branch in 7a81a05. The bug was due to not hiding the empty view when it's set to `null`, which it will be when the empty view should be hidden.

**Pull request merged**
