### PR TITLE
Update app illustrations.

### PR DESCRIPTION
**Pull request by hafizrahman**
This is for #3657 

## To test:

These are the screens where illustrations are updated:

| # | Case 	| Before 	| After: Light 	| After: Dark 	|
|- |-	|-	|-	|-	|
|1. | Empty Orders list: no order. Requires a test site with no order yet. Please note the string change as well. 	|  no-order-original | no-order-light | no-order-dark |
|2. | Empty Orders list: all fulfilled. Make sure the site has all orders with the "Completed" status. Probably easiest to create a new site, make one order, then set its status as "Completed". | all-order-fulfilled-original	|  all-order-fulfilled-light	|  all-order-fulfilled-dark	|
|3. | Order loading. This shows up when opening the "Orders" tab and the app is loading new Orders. | order-loading-original |  order-loading-light	|  order-loading-dark 	|
|4. | Empty search result. Use the search icon on top right of Orders screen, and enter a keyword that will have no result. |  no-result-original | no-result-light 	|  no-result-dark  	|
|5. | Empty reviews 	| empty-reviews-original  	|   empty-reviews-light |  empty-reviews-dark	|
|6. | Empty products 	|  no-products-original |  no-products-light 	| no-products-dark  	|
|7. | Jetpack required. For this, try logging in to a site with no Jetpack plugin. 	|  no-jetpack-original |  no-jetpack-light	| no-jetpack-dark |

## To test Part 2:

These are the additional updates [as mentioned here](https://github.com/woocommerce/woocommerce-android/pull/3678#issuecomment-814803444) that still needs testing:

| # | Case 	| Before 	| After: Light 	| After: Dark 	|
|- |-	|-	|-	|-	|
|1. | Empty dashboard view	|image|image|image|
|2. | Missing analytics view	|image|image	|image|
|3. | "What is Jetpack?" login fragment	|image!| image | image|
|4. | "Sign in - Need WordPress" login fragment	|image	|image | image|
|5. | "Print Shipping label Info" view	|image |image |image	|

## Known issues:

Some illustrations will generate these lint warnings:

> Limit vector icons sizes to 200×200 to keep icon drawing fast; see https://developer.android.com/studio/write/vector-asset-studio#when for more

and

> Very long vector path (xxxx characters), which is bad for performance. Considering reducing precision, removing minor details or rasterizing vector.

For now we won't optimize the illustrations yet, and will handle it in the future in case performance issues do arise. See also p91TBi-4Gb-p2

## Various items that are moved to separate issues:

These items will be resolved outside of this current PR.
- New illustrations that haven't been implemented yet, due to various reasons. They are listed in #3681
- Empty product screen's button needs updating. #3712
- Various design aspects in the app need to be updated to match the design document. #3862

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.
---

### CODE REVIEW

**Review by anitaa1990 — CHANGES_REQUESTED** [review]
Hey @hafizrahman, the changes look good. Thank you for the testing steps for each image 😄 

During testing, I found a couple of discrepancies between the design and what is implemented.
- There is a button below the `No Products` image in the `Products` tab when there ar no products in the store. This is not present in the app.

##### Design
Screenshot 2021-03-12 at 6 09 11 PM

##### App


- The button for the `Reviews` screen and the `Orders` screen looks a bit different compared to the designs. Can we make the buttons width a bit wider?

##### Designs


##### App
Screenshot 2021-03-12 at 6 18 54 PM

- It looks like the print shipping label screen illustration has not been updated. I also don't see it in the list of images that have issues. Do we want to update that in this PR as well?

Screenshot 2021-03-12 at 6 20 03 PM

@woocommerce/mobile-designers, while testing this PR, I noticed that the stats illustrations have not been updated. Is this due to the fact that we're going to be revamping the whole feature in a little while?

.

**Comment by anitaa1990** [comment]
One other thing I forgot to mention, we might want to add release notes to this PR since we're updating the UI images 😸

**Comment by hafizrahman** [comment]
> There is a button below the No Products image in the Products tab when there ar no products in the store. This is not present in the app.

Do you think it's better to create a new issue for this? Since it involves more than updating image.

> The button for the Reviews screen and the Orders screen looks a bit different compared to the designs. Can we make the buttons width a bit wider?

This is a small enough change, so I'll add it here.

> It looks like the print shipping label screen illustration has not been updated.

This is now included in #3681

**Comment by hafizrahman** [comment]
As I was about to update the button width, I found that the button we have now is shared for all kinds of empty states (products, reviews, orders, etc).

So for this question from @anitaa1990 

> The button for the Reviews screen and the Orders screen looks a bit different compared to the designs. Can we make the buttons width a bit wider?

I need to defer to @woocommerce/mobile-designers : Is it okay to make the button wider to follow design, for all the empty states?

**Comment by ghost** [comment]
> Is it okay to make the button wider to follow design, for all the empty states?

Yes, thanks @hafizrahman all empty state buttons should now have the same wider button width please.

**Comment by Garance91540** [comment]
Hi @hafizrahman , these looks so good! 

Aside for the illustrations, I noticed discrepancies for the fonts and color we used on all the empty states copy. Here's what I mean:

Screen Shot 2021-03-16 at 6 01 54 PM

I know this feedback is technically separate than illustrations, so it's totally cool to implement it in a separate PR

**Comment by Garance91540** [comment]
> @woocommerce/mobile-designers, while testing this PR, I noticed that the stats illustrations have not been updated. Is this due to the fact that we're going to be revamping the whole feature in a little while?

Great catch @anitaa1990 ! I made the illustration updates thinking we'd implement the new Analytics screens first, so here are the illustrations we should be using:

Screen Shot 2021-03-16 at 6 24 43 PM

I added notes and changes under "testing notes" in the Figma file "Woo Illustrations" > Page "Frames"

**Comment by anitaa1990** [comment]
> There is a button below the No Products image in the Products tab when there ar no products in the store. This is not present in the app.
Do you think it's better to create a new issue for this? Since it involves more than updating image.

afaik, it's a small enough change that we should be able to include it in this PR. But I'm good to update that in a separate PR if you think that makes sense. I don't see an issue created for that though 😅 ? It would be good to add that to the current release as well since it's a small enough change and would be helpful. WDYT?

> There is a button below the No Products image in the Products tab when there are no products in the store. This is not present in the app.

Thank you @Garance91540! @hafizrahman, these images would need to be updated as well.   

> It looks like the print shipping label screen illustration has not been updated. This is now included in #3681

There are two different screens for printing shipping labels. This one is already implemented in the app and corresponds to `img_print_with_phone.xml`. This needs to be updated to the correct illustration. The one in #3681 refers to the image after the shipping label is created (which is not yet live to the user).

> Updated illustrations on various places. See if you can find them all! [https://github.com/woocommerce/woocommerce-android/pull/3678]

Could we make this more specific? Maybe something like "Updated all empty state illustrations" instead? Sorry, that sounds like a nippick but it provides more context to the release note

**Comment by hafizrahman** [comment]
> it's a small enough change that we should be able to include it in this PR.

<strike>Sure, will add it here</strike>. **Update**: see next message.

> Could we make this more specific? Maybe something like "Updated all empty state illustrations" instead? Sorry, that sounds like a nippick but it provides more context to the release note

I took inspiration for the message [from this article](https://uxdesign.cc/the-art-of-writing-great-release-notes-6607e22efae1). The idea was to try to strike a balance between being informative and being more engaging to users who actually take the time to read them (especially since this update is more visual and do not change functionalities in the app). Happy to rewrite them to be more specific. **Update**: change added.

**Comment by hafizrahman** [comment]
**About adding the button on the products screen:**

> it's a small enough change that we should be able to include it in this PR.
> Sure, will add it here.

I had a go at this but it seems like it would take me some time to work on, saw some odd bugs while adding the button. For now I'm recording this on issue #3712

**Comment by hafizrahman** [comment]
> Aside for the illustrations, I noticed discrepancies for the fonts and color we used on all the empty states copy.

This is added in the "Empty state color & typography update" commit. I found that the headline already uses "Headline 6", but the rest I've updated accordingly.

**Comment by hafizrahman** [comment]
@Garance91540 This image gets added correctly (yay!):
Screen Shot 2021-03-19 at 14 45 17

Can you also please share the Dark version for it (or let me know where it is in the Figma file)?

**Comment by hafizrahman** [comment]
@woocommerce/mobile-designers 

I've updated the illustration and styling for this. Can you let me know what the navigation icon on top right is supposed to do? It's not currently available in the app. 

Screen Shot 2021-03-19 at 15 00 38

**Comment by Garance91540** [comment]
Hi @hafizrahman !

> @Garance91540 This image gets added correctly (yay!):

Victory! https://d.pr/i/Ix5DG1

> Can you also please share the Dark version for it (or let me know where it is in the Figma file)?

Yes, you should find all dark and light versions of the images in the Figma file "Woo illustrations" page "Woo Mobile" 
https://d.pr/i/Ix5DG1

> I've updated the illustration and styling for this. Can you let me know what the navigation icon on top right is supposed to do? It's not currently available in the app.

Are you referring to [those](https://d.pr/i/wWPL2Q)? These were introduced as part of the new [Home screen designs](https://woomobilep2.wordpress.com/2020/09/11/home-screen-design-i3/), and this project hasn't been implemented yet, so I think they are out of the scope of the illustration project

I noticed that the illustrations background wasn't the right color:

https://d.pr/i/wM4yGK

**Review by Garance91540 — CHANGES_REQUESTED** [review]
see comments above

**Comment by hafizrahman** [comment]
> Yes, you should find all dark and light versions of the images in the Figma file "Woo illustrations" page "Woo Mobile"

Thank you! I missed that earlier.

> Are you referring to those? These were introduced as part of the new Home screen designs, and this project hasn't been implemented yet, so I think they are out of the scope of the illustration project

Gotcha, thank you!

> I noticed that the illustrations background wasn't the right color

Nice find! This was missed because it used a separate layout element compared to the other empty view states. Fixed.

**Comment by hafizrahman** [comment]
To keep track of things, the remaining thing to do for me:
 
- [x] Use @anitaa1990 's PDF-to-SVG-to-Vector Drawable method to fix the first four images listed on #3681 and add them here.

**Comment by hafizrahman** [comment]
@anitaa1990 @Garance91540 I think I've addressed all the previous points and this is now ready to review again.

New changes added:
- Illustration on empty dashboard view
- Illustration on missing analytics view
- Illustration on "What is Jetpack" login fragment
- Illustration on "Sign In - Need WordPress" login fragment
- Illustration on "Print Shipping Label Info" view
- General typographical fixes

Not included in this PR:
- 5 remaining illustrations that's not yet checked on #3681. They're not added because the features they're related to do not exist yet.
- Update the add product button design on empty product screen view. Currently recorded in issue #3712.

**Comment by Garance91540** [comment]
Hi @hafizrahman , great! I'm not super sure where to find the new illustrations though 🤔? Am I missing them here?

If possible, can we present all the illustrations that have been updated for this project in the same table so we can review them all at once? Thank you!

**Comment by anitaa1990** [comment]
Hey @hafizrahman! Thank you for updating the remaining illustrations in the PR. As Garance mentioned, it would be good to update the PR description with the changes (or rather adding the remaining illustration screenshots for the design review). And there is also a merge conflict that needs to be fixed.

We can merge once that's done 👍

**Comment by hafizrahman** [comment]
Currently updating the initial post with screenshots of latest changes...

**Comment by Garance91540** [comment]
Hi @hafizrahman, thanks! Here are my notes:

- This applies for all light mode designs:

Screen Shot 2021-04-15 at 9 54 06 AM

The background color should be Gray 0, or the illustration kind of blend with it. 
I think there are some fonts discrepancies too

- For the "what is Jetpack"  light mode illustration specifically: 

Screen Shot 2021-04-15 at 9 59 12 AM

- "Not a WordPress site"

Screen Shot 2021-04-15 at 10 02 02 AM

- "Needs Jetpack"

Screen Shot 2021-04-15 at 10 07 47 AM

Let me know if you have any questions :)

**Comment by jkmassel** [comment]
This PR is being bumped to `6.6` because `6.5` is being frozen today.

**Comment by hafizrahman** [comment]
**Latest Update:**

Because this PR has been running pretty long, I'm doing some changes to it to keep things better organized and easier to follow.

1. Since in this PR we discovered various design elements that also need updating, not just the illustrations, I'm making a new feature branch `feature/illustration-and-design-updates` that will receive all the design + illustration changes.
2. This PR will be focused solely on the illustration change.
3. Design changes will be handled on separate PRs (that will then target the same feature branch). These are all the changes that need to be implemented:
    1.  Empty product screen's button needs updating. #3712
    2. Various design aspects in the app need to be updated to match the design document. #3862 . This contains [the latest review items](https://github.com/woocommerce/woocommerce-android/pull/3678#issuecomment-820216300) from @Garance91540.
4. There is also an issue for illustrations that are excluded in this PR: #3681. The illustrations there will be handled separately from the feature branch.

**Action items:**
1. This PR is now ready for another round of review, but this time focusing to make sure the right illustrations are shown. The list of illustrations to check are listed under "To test Part 2:" [on the original post here](https://github.com/woocommerce/woocommerce-android/pull/3678#issue-589427813). cc @anitaa1990 @Garance91540 
2. Once this PR is approved, it can be merged to the feature branch and I will then work on #3712 and #3862.

**Review by anitaa1990 — APPROVED** [review]
Looks good 👍 Thanks for the update @hafizrahman! I'll merge this PR now :shipit:

**Comment by Garance91540** [comment]
Hi @hafizrahman , just took a look at the illustrations under the "To test part 2" and I've only a few notes:

For all illustrations, can we make sure that we are using these font sizes for the titles + copy?

Screen Shot 2021-04-22 at 1 13 49 PM

Can we make sure to add some vertical padding between the illustration and the copy for the illustration below?

Screen Shot 2021-04-22 at 1 15 47 PM

Can we make sure the background color for this screen is white?
Screen Shot 2021-04-22 at 1 15 35 PM

Thanks!

**Comment by hafizrahman** [comment]
@Garance91540 Thank you for your review!

The first two items are already listed on a separate issue #3862 , with PR #3879 currently being worked on to handle them.

I'll add the white background color on the "Print with your device" screen to #3862 as well, and make sure it's handled in #3879.

**Pull request merged**
