### PR TITLE
issue/3739-status-bar-color

### LINKED ISSUE #3739: Set Status bar background to be white
The status bar’s background is black right now. 

Screen Shot 2021-03-24 at 11 24 54 from https://d.pr/i/33Zh4V

We should set it to white to unify the changes to the top nav:

Screen Shot 2021-03-24 at 11 27 10 from https://d.pr/i/SGZ586

Tested in Android 6.3 beta release. cc @woocommerce/android-developers

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #3739 - Updates the main `themes.xml` to set the status bar color, which previously was part of the versioned (v23 and v27) themes. This turned out to be unnecessary, since `android:statusBarColor` is supported from Lollipop onward, and Lollipop is our min sdk version.

Before shots below (note that it appeared correctly in dark mode):

before-light

And after shots:

after-light

Tested with AP levels 21, 23, 27, 28, 29, & 30.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by 0nko — APPROVED** [review]
:shipit:

**Comment by hichamboushaba** [comment]
Sorry guys for nitpicking here, but I noticed an issue after testing the app with this PR merged, the icons and text of status bar are not visible anymore on light theme.
We have an attribute that tells the system that the status bar has a light color, to draw its content in a darker color: https://developer.android.com/reference/android/R.attr#windowLightStatusBar, but it's supported only in Android M, so we have two solutions to address Lolipop case:
1. Keep the status bar black (I prefer this one personally).
2. Keep it white but knowing that users won't be able to see the content of the status bar.

WDYT?

**Comment by nbradbury** [comment]
@hichamboushaba Oof, that was a bad mistake on my part. I recall now that we moved the status bar colors to a v23 themes.xml to address this issue. I'll open a new PR today to resolve this.

**Comment by 0nko** [comment]
I should have caught that :(. Thanks @hichamboushaba!

**Pull request merged**
