### PR TITLE
Add Navigation Animation

### PR DESCRIPTION
**Pull request by theck13**
### Fix
Add animation to the bottom navigation menu icons when selected.  See the animations below for illustration.

<a href="https://user-images.githubusercontent.com/3827611/101291517-a074e600-37c6-11eb-8747-4fefbd50b325.gif"></a>

#### My Store
Fast|Slow
-|-
<a href="https://user-images.githubusercontent.com/3827611/101291681-ed0cf100-37c7-11eb-82cc-8d6241f53b0b.gif"></a>|<a href="https://user-images.githubusercontent.com/3827611/101291683-ee3e1e00-37c7-11eb-80a4-580f9ef34bc8.gif"></a>

#### Orders
Fast|Slow
-|-
<a href="https://user-images.githubusercontent.com/3827611/101291697-0877fc00-37c8-11eb-8ec4-32f97d3744e8.gif"></a>|<a href="https://user-images.githubusercontent.com/3827611/101291698-0a41bf80-37c8-11eb-8dfc-08c329e0910f.gif"></a>

#### Products
Fast|Slow
-|-
<a href="https://user-images.githubusercontent.com/3827611/101291701-0c0b8300-37c8-11eb-8b1d-a9df97063562.gif"></a>|<a href="https://user-images.githubusercontent.com/3827611/101291702-0dd54680-37c8-11eb-8e89-9d8cc324c15d.gif"></a>

#### Reviews
Fast|Slow
-|-
<a href="https://user-images.githubusercontent.com/3827611/101291708-13329100-37c8-11eb-8b70-adeb415e99fe.gif"></a>|<a href="https://user-images.githubusercontent.com/3827611/101291710-13cb2780-37c8-11eb-9a7f-24b5956a9d81.gif"></a>

### Test
1. Tap currently unselected item in bottom navigation menu.
2. Notice bottom navigation icon does animate.
3. Tap currently selected item in bottom navigation menu.
4. Notice bottom navigation icon does not animate.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — APPROVED** [review]
I love those!!! cc @adamzelinski  we are adding some animations in the bottom nav on Android.

**Comment by nbradbury** [comment]
This is great, @theck13 - such a nice addition to the user experience. I'm a little unsure of the product tab animation now I see it in action, though, because it seems kind of busy. Is there something more subtle we could do?

ezgif-7-8dd7bdd65516

**Review by nbradbury — APPROVED** [review]
Well,  I guess ignore my comment since this passed design review :) I'll merge after CI finishes :shipit:

**Comment by theck13** [comment]
> Is there something more subtle we could do?

That animation puts three generic shapes (i.e. triangle, square, and circle) into the box as a way represent products.  In order for the animation to finish in one second like the rest of the bottom navigation animations, those three shapes fly into the box pretty quickly.  We could remove one or two of the shapes from the animation to make the remaining shape(s) animate slower.  Would that be more subtle?

**Pull request merged**
