### PR TITLE
Issue/2844 order detail refactor

### LINKED ISSUE #2844: Hack Week: Refactor Order detail screen from MVP to MVVM
This is the master thread to track the progress of converting the Order detail screen from MVP to MVVM.

#### FluxC:
- [x] Remove redundant `WCOrderModel` when fetching order notes. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant `WCOrderModel` when fetching order shipment trackings. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when updating order status. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when adding order note. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when adding new shipment tracking. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when deleting new shipment tracking. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))

##### Order Detail Sections:
- [x] Display **Order Status Info** card. (PR: #2856 )
- [x] Display **Shipping Lines Warning** card, if order has more than 1 shipping methods. (PR: #2857 )
- [x] Display **Customer Info** card - Shipping/Billing address. (PR: #2860 )
- [x] Display **Payment Info** card. (PR: #2861 )
- [x] Display **Order notes** card. (PR: #2866 )
- [x] Display **Refunds Info** card. (PR: #2871 )
- [x] Display **Product List** card. (PR: #2872  )
- [x] Display **Shipment Tracking list** card, if WCS plugin is available. (PR: #2873  )
- [x] Display **Shipping Labels** card, if WCS plugin is available. (PR: #2874 )

##### Order Detail Actions:
- [x] Add Pull to refresh action to the Order Detail screen. (PR: #2875  )
- [x] Change Order Status (PR: #2875 )
- [x] Fulfill Order  (PR: #2878  )
- [x] Issue Refund. (Open Issue Refund screen and update the Order Detail when refund is successful).
- [x] Open Refund detail screen. (PR: #2875 )
- [x] Send email using billing email. Call/message billing phone number. (PR: #2875 )
- [x] Add new order note. (Open Add order note screen and update the Order Detail when successful). (PR: #2876  )
- [x] Request Refund for a shipping label. (PR: #2876  )
- [x] Add Shipment Tracking for an order.  (PR: #2877  )
- [x] Delete Shipment Tracking for an order.  (PR: #2877  )
- [x] Track/Copy Tracking number for an order (with WCS or Shipment Tracking plugin enabled).  (PR: #2877  )

#### Testing
- [x] Add unit tests for `OrderDetailViewModel`.  (PR: #2878  )

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2844. This is the feature branch for the order detail refactor to MVVM. All code in this PR has already been reviewed in previous PRs.

#### To Test
- Smoke testing the order detail screen to verify that the following cards display the correct information:
  - Display Order Status Info card. (PR: #2856 )
  - Display Shipping Lines Warning card, if order has more than 1 shipping methods. (PR: #2857 )
  - Display Customer Info card - Shipping/Billing address. (PR: #2860 )
  - Display Payment Info card. (PR: #2861 )
  - Display Order notes card. (PR: #2866 )
  - Display Refunds Info card. (PR: #2871 )
  - Display Product List card. (PR: #2872 )
  - Display Shipment Tracking list card, if WCS plugin is available. (PR: #2873 )
  - Display Shipping Labels card, if WCS plugin is available.  (PR: #2874 )
- Smoke the following order actions to verify that everything is working as expected.
  - Pull to refresh action on the Order Detail screen. (PR: #2875 )
  - Change Order Status (PR: #2875 )
  - Fulfill Order (PR: #2878 )
  - Issue Refund. (Open Issue Refund screen and update the Order Detail when refund is successful).
  - Open Refund detail screen. (PR: #2875 )
  - Send email using billing email. Call/message billing phone number. (PR: #2875 )
  - Add new order note. (Open Add order note screen and update the Order Detail when successful). (PR: #2876 )
  - Request Refund for a shipping label. (PR: #2876 )
  - Add Shipment Tracking for an order. (PR: #2877 )
  - Delete Shipment Tracking for an order. (PR: #2877 )
  - Track/Copy Tracking number for an order (with WCS or Shipment Tracking plugin enabled). (PR: #2877 )
- Run `OrderDetailViewModelTest`.
- Click on a new order notification to verify that it is redirecting to the Order detail screen.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
@woocommerce/android-developers this PR is ready for review 👍

**Comment by nbradbury** [comment]
If there aren't any billing details, this is still displaying the "Show billing" button, which didn't happen previously.

billing

**Comment by nbradbury** [comment]
Tapping a product in order detail doesn't open the product detail.

product

**Comment by anitaa1990** [comment]
Thanks for the review @nbradbury!!

>  Tapping a product in order detail doesn't open the product detail.

Nice catch! I had a TODO in the code for this and completely missed it 🤦‍♀️ Fixed in 566d2a4

> If there aren't any billing details, this is still displaying the "Show billing" button, which didn't happen previously.

Fixed in c8d0f87.

Ready for another round 👍

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
