### PR TITLE
Nick/default nav animations

### PR DESCRIPTION
**Pull request by nbradbury**
This PR removes most of the animations from our various navigation graphs, cutting them in size and increasing readability. Instead of duplicating the transitions in every navigation action, this PR relies on defining them in our `themes.xml`.

### CODE REVIEW

**Review by malinajirka — CHANGES_REQUESTED** [review]
Thanks @nbradbury, it's a great idea to simplify the graphs and remove the boilerplate. I always need to copy paste the animations since I don't remember how to set them up.

However, it seems the current implementation makes unintended changes. Setting the default animations in themes.xml overrides all of `enter/exit/popEnter/popExit` for all actions - those which are defining the same set of animations (which is ok) but even those which define only some of the enter/exit/popEnter/popExit => this change breaks them since they didn't have any animation before, but they do have an animation now. 
For example:

Screenshot 2021-11-30 at 7 41 50

It didn't have `exitAnim` and `popEnterAnim` animations, but it has now. This causes UI issues likes these: https://cloudup.com/cw0Iw1XcQPV

I think we'd need to 
- explicitly set the animation to null in those cases to retain the behavior 
or 
- explicitly set all `enter/exit/popEnter/popExit` on all actions which would change the behavior but probably leat to the desired behavior. 

Wdyt?

**Comment by nbradbury** [comment]
@malinajirka Oof, I should've considered this problem before I started on this task. I think that given we've been inconsistent with our animations, and given my limited bandwidth right now, we should simply close this PR. Tackling this might make a good hack week project, though :)

**Comment by malinajirka** [comment]
If you don't mind me taking over, I think I could find some time next week or during the Christmas break. Let's move this PR into a draft state and I'll see if settings all the anims on all the actions would fix the UI issues.

**Comment by nbradbury** [comment]
Sorry @malinajirka, I got your comment after I closed this PR. I'll re-open it, and feel free to take it over.

**Comment by malinajirka** [comment]
@nbradbury I updated the few remaining `actions` and it seems to work as expected. Seeing that we had to add a bunch of `@null` animations I'm not 100% convinced this is a good step tbh. I did a quick research if we could somehow create and apply animation styles so we could always define for example "default_anim_style" or "dialog_anim_style", but AFAICT it's not supported (at least through xml).
I'll leave the final decision if we should merge this up to you. It imo works as expected and is ready for review.

**Review by malinajirka — APPROVED** [review]

**Comment by nbradbury** [comment]
@malinajirka I think this is good to merge after the conflicts are resolved. It's not a perfect solution, but imo it's better than assigning the styles to every action.

Note that [we can use animations pulled from the theme](https://android-review.googlesource.com/c/platform/frameworks/support/+/1715751), but that again requires changing every navigation action.

**Pull request merged**
