### PR TITLE
Hackweek/stats widget

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes the first four steps mentioned in #2041 for this hack week. 

**Note: The intention of this PR is to get everyone to play around with the changes and tests the widgets feature thoroughly. I wouldn't recommend making this PR live until we find a way to support multiple stores and multiple store notification support in the app.**

#### Changes
- Adds a new widget to the app that displays the current day stats, if v4 stats is available for the site. 
- Provides an option to users to select a site and the color mode of the widget.
- An error message is displayed in the widget if the user is not logged in to the app.
- An error message is displayed in the widget if the store does not have WC-Admin installed or if WooCommerce 4.0 is not installed.

#### Screenshots
. . . 

. 
. 
. 
. 

#### Testing
- Run `TodayWidgetListViewModelTest` unit test.
- Add widget to a site that has WC-admin or Woo 4.0 available:
   - Login to a store that has WooCommerce 4.0 or WC-admin installed.
   - Long-press `home screen`.
   - Tap `Widgets` option.
   - Scroll to ***Woo*** widget.
   - Long press the ***Today*** widget and place on the home screen.
   - Note that the site selector screen is displayed.
   - Click on the site selector field and notice the list of sites displayed. Click on a site and verify that it is updated in the site selector field.
   - Click on the color selector field and notice a dialog is displayed with Light and Dark. Click on either and verify it is updated in the color selector field.
   - Notice the `Add Widget` button is not enabled.
   - Click on the button.
   - Notice the current day stats (visitors, order count and revenue) is displayed correctly in the widget.
- Verify that error message is displayed when user is not logged in.
   - Complete the previous test and add a widget to the app.
   - Open the app and logout of the app.
   - Close the app and notice that an error is displayed in the widget when you are logged out.
- Verify that error message is displayed when stats v4 is not available for a site:
   - Complete the first test and add a widget to the app.
   - Open the `wp-admin` of the current site you are logged into.
   - Disable WC-Admin plugin for the site and refresh the app.
   - Notice the stats reverted banner is displayed in the app.
   - Close the app and notice that the stats widget displays an error message.

#### Known issues
- I keep getting this [crash](https://gist.github.com/anitaa1990/b1e62dc14ea842209c033826bf25c007) when changing the system settings from dark mode to light mode or vice versa. I am yet to debug this crash.
- When the widget is clicked, we need to open the stats for the site assigned to the widget. The idea is to auto login the user to that site in the app. This is not yet implemented.
- Tracking events need to be added to this feature.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — CHANGES_REQUESTED** [review]
Nice to see the widget coming to life!!!

I just have a few comments on these modals:

**Padding**

Is it possible to have 24px vertical padding between text and modal borders as well as between text elements?

Is it possible to have 16px left and right padding?

Screen Shot 2020-06-12 at 3 26 35 PM

**Text widow**

To balance a bit more the copy on the modal, is it possible to add a line break as follows:
"Please log in to the WooCommerce app **[line break]** to add a widget"
"Your network is unavailable. **[line break]** Check your data or wifi connection"

**Copy**
For the widget _"Your network is unavailable. Check your data or wifi connection"_ What does "check your data" means exactly?

**Comment by anitaa1990** [comment]
Thanks for the review @Garance91540!!

>  Is it possible to have 24px vertical padding between text and modal borders as well as between text elements? Is it possible to have 16px left and right padding? To balance a bit more the copy on the modal, is it possible to add a line break as follows:

For sure! I've made the above changes! Please have a look below and let me know if it's fine! Thank you 🙇‍♀️ 

. . . . . . .

**Review by AmandaRiu — COMMENTED** [review]
@anitaa1990 I played around with the component and it works 👍 I'm wondering if that strange crash you mentioned has to do with using the navigation library for this component. I’m not 100% finished with reviewing the PR, but wanted to give you some updates just in case you were blocked. This design works but I imagine it would be annoying for users who often switch between light/dark mode on their device. For example, if I have several widgets on my home screen and they all default to the system-selected theme, then switching to dark mode would show all the other widgets dark, but our widget would still be light. The user would have to remove the widget, add it back, then select dark theme to have it match. This is probably why google’s widgets only support dark mode on Android 9+, just so the widget will automatically change. Personally I’d prefer that design, but that’s just my opinion. I did some tests and it is completely possible to just use the OS-level theme:

ezgif com-video-to-gif (2)


I accomplished this by only modifying the “dark” version of the widget to use our theme colors. [You can see those changes in this compare](https://github.com/woocommerce/woocommerce-android/compare/hackweek/stats-widget...amanda/stats-widget). 

Another thing we may want to consider is reducing the amount of padding and margins used by this widget. It’s size takes up an awkward amount of space on the home screen and doesn’t fill the three rows it’s using. For example, notice in this screenshot I have the widget sandwiched between the Messages (on the top) and Maps (on the bottom) icons and there’s a bunch of space in between. This unused space is because the widget is just barely covering over two rows forcing it to actually take up 3 (as demonstrated by the icons on placed along the right edge). Since this device allows for a maximum of 5 rows (the 6th is the main bar), this means the user can only fit one of these widgets on each screen…I think we can optimize the layout so we are taking up exactly two rows to give the user more flexibility with placing widgets:




I also left some recommendations in code comments and just want to make one more general comment that the stats xml files should be using the values from `dimens_base.xml` instead of the values from the login library.

**Review by Garance91540 — CHANGES_REQUESTED** [review]
Hi @anitaa1990 , sorry I had reviewed this PR but it seems like my comment wasn't sent? 🤔

I'm still seeing some slight issues with padding in the error message (https://d.pr/i/wVA1WY)

So I added these designs on Figma and tagged you on it. Let me know if you have any questions!

**Comment by anitaa1990** [comment]
Closing this PR since there have been a lot of changes to the app since this PR. Will open a new one with the requested changes 👍

**Pull request closed without merging**
