### PR TITLE
Load a single list in orders tab and apply any filter selection

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Work in progress: #4934 

### Description

 - Removed code for the 2 tabs from order list sections
 - Load a single list and apply any selected filters to that list ALWAYS

Known issues in this changes that have been addressed here: #5239
- Any bug related to search functionality
- Toolbar shadow appearing after opening filters and then going back to order list
- Navigate back from filter flow should display a dialog to discard changes only if filters have changed

### Testing instructions
- Open order list
- Play adding and removing filters to the list 
- Check displayed results are correct
- Kill the app and reopen and check filters are still applied

### Images/gif

https://user-images.githubusercontent.com/2663464/141773547-559c21b8-fcf8-479d-891e-f2c94c2f8fd9.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by JorgeMucientes** [comment]
Ok, for some reason when basing this PR to it's parent branch issue/4934-order-filter-tracking a ton of commits and file changes unrelated to the PR are added. So, I've based this PR on develop branch instead. So keep in mind that all tracking related code is being reviewed here: #5220
In fact, if that adds too much noise to the PR feel free to wait until #5220 is merged to proceed reviewing this. 
Sorry for the inconvenience :(

**Review by anitaa1990 — APPROVED** [review]
Nice job on this @JorgeMucientes! The changes look good 🚢 

I faced a couple of minor issues when testing that might already be fixed in another PR, but just thought I'd let you know, in case it's new.

- Could we change the text of the empty view, when there are no orders found for the selected filters? Right now, it says "Waiting for your first order", which feels incorrect.
- The discard dialog is displayed when the filter options have changed. But when I click on Discard, the selected filter is still applied to the order list. Is that expected?

Feel free to merge the PR, if the issues I mentioned above are already taken care off or will be fixed in another PR 😄

**Comment by JorgeMucientes** [comment]
Thanks for reviewing this @anitaa1990 :) 

Yes the issues you mentioned have been addressed in this PR #5239. The empty case in that last PR looks like this:



Since that empty case is specific for the case were the list has active filters selected WDYT of adding at the end of the message: "matching your filter selection" ? 

Discard dialog issues have also been addressed here #5239

**Comment by JorgeMucientes** [comment]
I will merge this and update the empty case message to: "We're sorry, we couldn't fin any orders matching your filter selection"  if we consider it a good idea, in the next PR: #5239

**Pull request merged**
