### PR TITLE
Dummy PR to test dependency diff

### PR DESCRIPTION
**Pull request by kidinov**
Dummy PR to test dependency diff

https://github.com/woocommerce/woocommerce-android/pull/5420

### CODE REVIEW

**Comment by AliSoftware** [comment]
I'm not sure I'm a fan of the working reporting this as a _violation_ — which to me suggests something is a _wrong_ and needs to be reverted or fixed — as opposed to calling it a _warning_ — as in "just wanted to highlight this and let you know, and maybe make sure you take extra care of testing that this didn't break anything"

**Comment by kidinov** [comment]
@AliSoftware totally agree

> Found 1 violations:
 
comes from `se.bjurr.violations.comments.github.plugin.gradle.ViolationCommentsToGitHubTask` and tbh I didn't find how to adjust that

**Comment by AliSoftware** [comment]
Using our [Buildkite's `comment_on_pr` action](https://github.com/Automattic/bash-cache-buildkite-plugin/blob/trunk/bin/comment_on_pr) in your sh script once we migrate — instead of this Gradle action — could allow you to customize it better there 😇 😛

**Comment by kidinov** [comment]
@AliSoftware Can it also remove a comment if it's not necessary anymore? Will it keep 1 comment per PR too?

**Comment by AliSoftware** [comment]
Ah good point. Our fastlane action (which we have [just started to use](https://github.com/wordpress-mobile/WordPress-iOS/pull/17581) on Buildkite CI) can [update an existing comment (we just have to provide the same arbitrary identifier every time we call it)](https://github.com/wordpress-mobile/release-toolkit/blob/develop/lib/fastlane/plugin/wpmreleasetoolkit/actions/common/comment_on_pr.rb), but don't currently provide the ability to delete one.

But that should be a pretty straightforward addition to implement in that action though (eg if we call the action with a reuse_identifier and a nil comment body, delete the comment instead of updating it with empty text, something like that) so that shouldn't be a blocker.

**Pull request closed without merging**
