### PR TITLE
Issue/1863 empty state fixes

### LINKED ISSUE #1863: Empty states issues
There are a few issues with empty states:

- [x] In landscape, the order list and review list empty states are cut off
- [x] The empty view isn't scrollable so on small screens there's no way to reach the buttons
- [x] On the “Orders” search screen, if you select an order status with 0 orders the empty state screen shows the message We're sorry, we couldn't find result for ""
- [x] The review list loading skeleton overlaps the empty view after rotation
- [ ]  ~~If I rotate my device to landscape while on a different tab in the app, and then open the Reviews tab, no empty state screen loads (the screen is fully blank)~~ <-- turns out this existed prior to empty states so I opened #1864 to address it.

### PR DESCRIPTION
**Pull request by nbradbury**
Fixes #1863 by correcting a few issues with the new empty states. To test, verify the following:

- [ ] In landscape, the empty views are scrollable when cut off (I recommend using an emulator with a small screen for this)
- [ ] The review list loading skeleton no longer overlaps the empty view after rotation
- [ ] On the order list, if you select an order status filter (such as "refunded") that has no matching orders, the empty view correctly shows the name of the status filter in its message (see screenshot)

Screenshot_1580323801

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
Thanks for the review, @anitaa1990! I fixed the first two issues but I'm unable to reproduce the last one. I can't think of how that would be caused by this PR, either - maybe check if it happens in `develop`?

**Comment by nbradbury** [comment]
> I am seeing the first order empty view screen when selecting Processing from the order status filter screen.

I think this is how it should work, as the logic for processing orders is to show the "All orders have been processed" empty view when all orders have been processed and other orders exist. If there are no other orders, we show the "Waiting for your first order" empty view.

In other words, selecting "Processing" from the drop down acts the same as tapping the Processing tab.

**Comment by anitaa1990** [comment]
> In other words, selecting "Processing" from the drop down acts the same as tapping the Processing tab.

Ohh, that's a good point! I didn't think about that when testing 🤦‍♀. Doesn't that mean when there are _some_  orders for the site but without any processing orders, we would be displaying the `All orders have been processed` empty view instead? 

Currently, when there is an order with status (pending payment, for example), but there are no processing orders, I am seeing this empty view for all the order statuses.

**Comment by nbradbury** [comment]
> Doesn't that mean when there are _some_ orders for the site but without any processing orders, we would be displaying the `All orders have been processed` empty view instead?

That's correct.

> Currently, when there is an order with status (pending payment, for example), but there are no processing orders, I am seeing this empty view for all the order statuses.

That should've been resolved by d3b1ca1. Did you pull the latest changes?

**Pull request merged**
