### PR TITLE
Remove order creation m1 feature flag

### LINKED ISSUE #5694: [Order Creation] Remove M1 Feature flag
In order to release the M1 deliverable to the general public, we need to remove the current Order Creation feature flag and keep the M2 one, making sure that everything is still behind the Experimental toggle for the respective feature.

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #5694 by removing the Feature flag for the Order creation M1 features, making available creating an Order with the Address, Product selection, and Payments cost summary using local price calculation.

How to Test
==========
Just do overall feature tests including verifications if the feature works as expected excluding the newly merged work around the API price calculation and still follows the Experimental toggle state to make it available.

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by shiki** [comment]
@ThomazFB While testing this, I ran into a crash when performing these steps:

1. Tap Add Product
1. Add a simple product
2. Tap Add Product
3. Choose a variable product

Here is the crash: 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.woocommerce.android.prealpha, PID: 27917
    java.util.ConcurrentModificationException
        at androidx.collection.SimpleArrayMap.put(SimpleArrayMap.java:482)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:49)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:35)
        at com.woocommerce.android.ui.orders.creation.variations.OrderCreationVariationSelectionViewModel.getNavArgs(OrderCreationVariationSelectionViewModel.kt:24)
        at com.woocommerce.android.ui.orders.creation.variations.OrderCreationVariationSelectionViewModel.access$getNavArgs(OrderCreationVariationSelectionViewModel.kt:17)
        at com.woocommerce.android.ui.orders.creation.variations.OrderCreationVariationSelectionViewModel$parentProductFlow$1$parentProduct$1.invokeSuspend(OrderCreationVariationSelectionViewModel.kt:30)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Longer version: https://gist.github.com/shiki/6957e4fa0a815f587217ded047bbf08b

**Comment by hichamboushaba** [comment]
@ThomazFB @shiki I have an idea about the cause, as this crash is not directly related to this PR, I'll try to push a fix on a separate PR.

**Comment by shiki** [comment]
@hichamboushaba @ThomazFB That disappearing products issue that I mentioned in https://github.com/woocommerce/woocommerce-android/pull/5738#issuecomment-1025798960 does not seem to be caused by #5738. 

I tested this again with M2 turned off and more often than not, some products disappear from the products list. Please see this video:

https://user-images.githubusercontent.com/198826/151834020-cccb0fb0-4d11-4706-99f7-4b7d16dcbf33.mov

Should we consider this disappearing products as a blocking issue for M1? Are you able to reproduce this? Is it just me? 😅

**Comment by ThomazFB** [comment]
@shiki I see this as a blocking issue, I'll investigate what's happening, thanks for the context.

**Comment by hichamboushaba** [comment]
> @shiki I see this as a blocking issue, I'll investigate what's happening, thanks for the context.

@ThomazFB just a FYI: https://github.com/woocommerce/woocommerce-android/pull/5738#issuecomment-1025961446, I'm talking on that comment about the same issue 🙂

**Comment by ThomazFB** [comment]
@hichamboushaba @shiki I've updated this PR with the current trunk state and hardcoded the M2 flag to false to avoid any further confusion during any testing stage of the M1 release. I believe we can restore the flag state right after the code freeze for the current version. WDYT?

**Comment by hichamboushaba** [comment]
> hardcoded the M2 flag to false to avoid any further confusion during any testing stage of the M1 release. I believe we can restore the flag state right after the code freeze for the current version. WDYT?

I agree, I think this is better.

**Review by hichamboushaba — APPROVED** [review]
Looks good to me, I won't merge until we get the final approval on releasing M1.

**Pull request merged**
