### PR TITLE
Issue/product list design review

### PR DESCRIPTION
**Pull request by nbradbury**
This PR is for the product list design review. @kyleaparker Just let me know here if anything needs adjusting!

device-2019-08-27-122654

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
> It looks like with that change we lost the border

@kyleaparker Sorry I missed that! Here it is with the border back:

Screenshot_1567099728

**Comment by kyleaparker** [comment]
Just noticed a couple more things:
- The border radius isn't being applied to the actual image, the corners within the image are square:

63962535-0b326000-ca61-11e9-83dc-16f73ee6449a png (1080×1920) 2019-08-29 14-09-15

- It looks like the list alignment isn't matching up with the design

Product details   Product list 2019-08-29 14-08-19

The specs I used are from the two line list at 72px height: https://material.io/components/lists/#specs

**Comment by nbradbury** [comment]
> * It looks like the list alignment isn't matching up with the design

@kyleaparker I can't figure out what's causing the difference. The product images are 40dp, the product name is 16sp, and the status/stock is 14sp. There's a 16dp padding on the cell, and when the product name doesn't wrap the cell is 72dp. As far as I can tell I'm following that spec exactly. Can your designer eyes see what the problem is?

**Comment by kyleaparker** [comment]
I think something is happening with the sizing of the product images, measuring from the screenshot they are 35 x 35px

**Comment by nbradbury** [comment]
> I think something is happening with the sizing of the product images, measuring from the screenshot they are 35 x 35px

What tool are you using to determine the sizing from the screenshot?

**Pull request merged**
