### PR TITLE
Issue/3556 product detail done button p2

### PR DESCRIPTION
**Pull request by nbradbury**
This is the second PR to address #3556, which removes the "Done" button from the product detail sub-screens. The purpose of this PR is to remove the "Done"  button logic from the base product fragments, and add it to the main product detail fragment.

To test, simply make changes in the sub-detail screens, ensure the "Update" button appears in product detail, and that it works correctly.

Note that the failing tests are addressed in the next PR (#3567).

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hichamboushaba** [comment]
@nbradbury I see that #3560 is merged, but I believe this PR's branch has to be rebased to include only the appropriate changes, as I see duplicate commits from the first PR.

**Comment by nbradbury** [comment]
> I believe this PR's branch has to be rebased to include only the appropriate changes, as I see duplicate commits from the first PR.

@hichamboushaba Oof, I missed that when I marked this ready for review. I'll tag this as not ready for review until I resolve that.

**Comment by nbradbury** [comment]
@hichamboushaba This is ready now.

**Review by hichamboushaba — APPROVED** [review]
Looks nice, :shipit:

**Pull request merged**
