### PR TITLE
Update navigation library

### PR DESCRIPTION
**Pull request by hichamboushaba**
This update is blocked by the pending PR https://github.com/woocommerce/woocommerce-android/pull/5755
### Description
The `beta` version of navigation had a bug that prevented restoring custom Parcelables from the saved state, which resulted in using a [workaround](https://github.com/woocommerce/woocommerce-android/pull/5307) to prevent the crash.
Now, Google has fixed the [bug](https://issuetracker.google.com/issues/207315994) we reported in the new RC version, this PR updates the navigation library, and removes the previous workaround.

### Testing instructions
Confirm the previous bug is fixed:

1. Enable "Don't keep activities" from the developer options.
2. Open Product Images screen of on the products.
3. Navigate to another app, then re-open the app.
4. Confirm that the app doesn't crash.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by wzieba** [comment]
hi @hichamboushaba 👋  I've looked at this PR wondering what's the cause of failing build. For some reason, `safeargs` bumped up Kotlin Gradle Plugin for the whole project and by this, Kotlin to version `1.6.0` as standard library is shipped with Gradle Plugin. See:

| trunk | update-navigation |
| ---- | ---- | 
| image | image |

I'm wondering if it's similar to #5490 but couldn't find a quick solution for that. I can check that in details in next week.

**Comment by hichamboushaba** [comment]
Thanks @wzieba, yes, you are right, I've spent the whole morning trying to force the kotlin plugin version, but I came up empty.
I added some code to enforce the kotlin runtime dependencies, and the build issue is easy to fix, but I still think it's a workaround, and the real fix would be to enforce our own version of the plugin.

**Comment by wzieba** [comment]
I'm still wondering what can be the issue, I've checked commit before Plugin DSL migration (28ab96e) and the issue is the same. I'm leaning toward idea that there's something wrong with `navigation-safe-args-gradle-plugin` in `rc01` but haven't had a chance to peak up the source yet.

**Comment by hichamboushaba** [comment]
Yes, I think the cause is from the `rc01`, I'm pretty sure they updated to kotlin 1.6.0, and it gets applied to us as well.
I just didn't find a way to force our version.

Next week I'll try another thing, using the non-kotlin version of the safeargs library, I don't think we need the kotlin version, since we use our own version of the `NavArgsLazy` 🤔

**Comment by hichamboushaba** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-android/pull/6093

**Pull request closed without merging**
