### PR TITLE
[Dynamic Dashboard] Coupons Card, part 1

### PR DESCRIPTION
**Pull request by hichamboushaba**
Part of: #11508 

### Description
This PR is part of the work to add the coupons card, it adds the following:
1. It builds on top of https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3012 to add the needed logic to the repository.
2. It adds the ViewModel for the card with all the business logic.
3. It adds the logic of the range selection.
4. It adds a basic UI to test the logic.
5. Renaming and moving few classes around for a better organization.

The final UI will be added separately to keep the size of the PR manageable.

### Testing instructions
1. Prepare some test data: create some coupons, and add them to some orders (you can do it from wp-admin even for old orders).
2. Open the app.
3. Enable the coupons card.
4. Confirm the coupons are loaded for the selected range.
6. Change the range and confirm the coupons are fetched for the new one.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          6 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>DashboardCouponsViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>Loaded</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>DateRangeState</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>OpenDatePicker</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>GetSelectedRangeForCoupons</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by 0nko — COMMENTED** [review]
Nice work! I've observed a couple of things while testing the PR:

- When I first selected the custom range, the range picker was shown but after specifying a range, the menu was not updated and I couldn't select the custom range after that

[Screen_recording_20240520_145056.webm](https://github.com/woocommerce/woocommerce-android/assets/1522856/b33f61d8-12aa-43e3-b98b-0a80c4439303)

- I don't see coupons that were applied manually to older orders (for any data range)

image

**Comment by hichamboushaba** [comment]
Thanks @0nko for the review

> When I first selected the custom range, the range picker was shown but after specifying a range, the menu was not updated and I couldn't select the custom range after that

I used the wrong function for setting the active tab (I'm not sure why I didn't notice this while testing, I'm quite sure I tested this scenario 😕), this now should be fixed.

> I don't see coupons that were applied manually to older orders (for any data range)

All I can think of is that maybe the analytics weren't calculated on the backend yet when you tested (they take a short amount of time), can you please re-test it now?

**Review by 0nko — APPROVED** [review]
The custom range works as expected now. I'm not sure why, but I don't see the coupons that were applied manually 🤷. Anyway, that's not really a problem.

Nice work! 🎖️

**Comment by hichamboushaba** [comment]
> The custom range works as expected now. I'm not sure why, but I don't see the coupons that were applied manually 🤷. Anyway, that's not really a problem.

Can you see them in the Analytics section of `wp-admin`?

**Comment by 0nko** [comment]
I can see it showed up now both on the web and the app 🤔, maybe I really just needed to wait..

**Pull request merged**
