### PR TITLE
Remove BoxWithConstraints from domain search

### LINKED ISSUE #10552: IllegalStateException: Event can't be processed because we do not have an active focus target.
Sentry Issue: [WOOCOMMERCE-ANDROID-92A](https://a8c.sentry.io/issues/4839515921/?referrer=github_integration)

```
IllegalStateException: Event can't be processed because we do not have an active focus target.
    at androidx.compose.ui.focus.FocusOwnerImpl.dispatchKeyEvent-ZmokQxo(FocusOwnerImpl.kt:171)
    at androidx.compose.ui.focus.FocusOwnerImpl.dispatchKeyEvent-ZmokQxo(FocusOwnerImpl.kt:171)
    at androidx.compose.ui.platform.AndroidComposeView.sendKeyEvent-ZmokQxo(AndroidComposeView.android.kt:631)
    at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:639)
    at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1988)
...
(45 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #10552.

[Screen_recording_20240205_191955.webm](https://github.com/woocommerce/woocommerce-android/assets/1522856/f21ef34f-1a17-4d0c-8892-bfa2e63dc31e)

The first crash coincides with adding of `BoxWithConstraints` in January. There is a [known issue](https://issuetracker.google.com/issues/285847708) in Compose, which may take a long time to fix, so I've removed it. There is no easy way to reproduce the issue so we'll monitor the crashes.

### CODE REVIEW

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Hey @0nko thanks for working on fixing this crash. 
I'm pre approrving the PR but there's a minor UI issue with the actual changes. The `Continue` button is not anchored anymore to the bottom of the screen. So: 
- When there are results you'll have to scroll to the end of the list to find it
- On empty case the button is right below the empty case image, which feels a bit od. 

I don't think it's a major issue as this screen doesn't have heavy use, but maybe it's worth fixing before merging. I'll let you decide.

**Comment by 0nko** [comment]
Thanks for the review, @JorgeMucientes!

> The Continue button is not anchored anymore to the bottom of the screen

That's how it was originally but it was taking too much space in landscape mode, leaving almost no space for the actual domain list. That's what the `BowWithConstraints` was supposed to solve. But just anchoring the button and not the search box would work 🤔.

**Comment by JorgeMucientes** [comment]
> That's how it was originally but it was taking too much space in landscape mode, leaving almost no space for the actual domain list. That's what the BowWithConstraints was supposed to solve. But just anchoring the button and not the search box would work 🤔.

@0nko I see. Yeah, that would work. We've had a similar problem with other screens in the app, such as the profiler screens in store creation. We solved it right as you mentioned: just anchoring the button and making the search scrollable when on landscape mode. Should be more or less straightforward change. `StoreProfilerScreen` might help as reference.

**Comment by 0nko** [comment]
@JorgeMucientes Ready for another check.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/191">17.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by JorgeMucientes** [comment]
Thanks for applying the changes @0nko. Works great now. :shipit:

**Pull request merged**
