### PR TITLE
Issue/1051-illegal-state-crash-fix

### LINKED ISSUE #1051: Fatal Exception: IllegalStateException: Can not perform this action after onSaveInstanceState
The following fatal crash has been reported on crashlytics for 2 users:

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:2080)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManagerImpl.java:851)
       at com.woocommerce.android.ui.main.MainNavigationView.clearFragmentBackStack(MainNavigationView.java:175)
       at com.woocommerce.android.ui.main.MainNavigationView.onNavigationItemReselected(MainNavigationView.java:107)
       at android.support.design.widget.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:201)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
       at android.support.design.internal.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:115)
       at android.view.View.performClick(View.java:6891)
       at android.view.View$PerformClick.run(View.java:26083)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
**App version:**  1.6, 1.3.2
**Device:** Samsung Galaxy 8 (OS version: 8.0)
**Fabric:** `5cc93721f8b88c2963b7b08f`, `5cd3d7a0f8b88c29636f461b`
**Users affected:** 2

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #1051 . 

The previous fix of using `popBackStack()` rather than `popBackStackImmediate` method has already been tried in this [commit](https://github.com/woocommerce/woocommerce-android/commit/cd0df172afcb81ca5e0c9eacad729868f67da7ff). This had no effect in fixing the crash. So modified the PR to check if the fragment state is already saved by calling `isStateSaved` before processing the request.

### CODE REVIEW

**Comment by nbradbury** [comment]
I'm not sure we should do this. We originally had `popBackStack` but changed it to `popBackStackImmediate` in [this commit](https://github.com/woocommerce/woocommerce-android/commit/cd0df172afcb81ca5e0c9eacad729868f67da7ff) in order to fix #782.

So, it appears that the crash can occur regardless of which `pop` method we call.

**Comment by anitaa1990** [comment]
Ohh 😮 did not see that we had changed it before! I wa
I will just modify this PR to `Not ready for review` till an alternate solution can be found.

**Comment by anitaa1990** [comment]
Update: not sure if it is significant that the issue is happening only in Samsung devices

**Comment by AmandaRiu** [comment]
@anitaa1990 I'd recommend just checking if the fragment state has already been saved. Something like this:
```
if (!it.isAdded || it.isStateSaved) {
      return false
}
```

**Comment by nbradbury** [comment]
Looks good! :shipit:

**Pull request merged**
