### PR TITLE
Update CONVENTION.md with naming conventions on layouts and View IDs

### PR DESCRIPTION
**Pull request by kidinov**
The naming of the layouts and views as per p91TBi-5yd-p2.

### How to test:

Just read and the CONVENTION.md file

### CODE REVIEW

**Comment by anitaa1990** [comment]
Thanks for working on this @kidinov ❤️ I failed to see when discussing in that P2 post that there is an [existing wiki page](https://github.com/woocommerce/woocommerce-android/wiki/Implementation) dedicated for naming conventions on styles, themes & drawables. 

I moved those wiki pages to a new `docs` folder, similar to what is being done in WCiOS and WordPress. The styles related file is under  `docs/theming_styling_best_practices.md`. This is the [file](https://github.com/woocommerce/woocommerce-android/pull/4456/commits/a55ee205d86fabafbd721edaae8a733987d76a51#diff-cec6e902d8e5197408865edb8019336620a0b30c7bb983eb4f55c3944ebd4df8).

 This way all the relevant documentation is consolidated under a single folder and file. Would you be ok to move the contents of this PR to that file?

**Comment by anitaa1990** [comment]
P2 post on that here: `p91TBi-5Du`

**Comment by kidinov** [comment]
@anitaa1990 Totally, having a link from the wiki on the file with code conventions is a good idea! I am just not sure that the file with best practices for styles and themes is a good place. These conventions are more about how do we code in general. Do you think, will it be good to put `CONVENTIONS.md` file inside `doc` folder? Also, I wouldn't put a link to the `CONVENTIONS.md` from wiki at the moment, because the work is super in the early stage and it might just confuse people which are not part of the team. Wdyt?

**Comment by anitaa1990** [comment]
@kidinov, I agree having a separate document for coding style in general is good! Looking at the contents of the `CONVENTIONS.md` in this PR, I noticed that we are only using layout and view id naming conventions, which is what the [docs/theming_styling_best_practices.md](https://github.com/woocommerce/woocommerce-android/pull/4456/commits/a55ee205d86fabafbd721edaae8a733987d76a51#diff-cec6e902d8e5197408865edb8019336620a0b30c7bb983eb4f55c3944ebd4df8) is all about 😄 It includes, right now, drawable, strings, styles, themes naming conventions so having layout and view id conventions in there would be a good idea. WDYT?

> Also, I wouldn't put a link to the CONVENTIONS.md from wiki at the moment, because the work is super in the early stage and it might just confuse people which are not part of the team.

Sorry about the confusion! I wasn't suggesting adding a link to the Wiki :). The wiki is going to be deprecated at any moment so we would only be using the docs folder to add any documents from now on.

**Comment by kidinov** [comment]
> Looking at the contents of the CONVENTIONS.md in this PR, I noticed that we are only using layout and view id naming conventions, which is what the docs/theming_styling_best_practices.md is all about 😄 It includes, right now, drawable, strings, styles, themes naming conventions so having layout and view id conventions in there would be a good idea. WDYT?

@anitaa1990 The file you linked states:

```
The goal of this document is to give an overview of how the material dark/light mode styling has been implemented in the WCAndroid app to act as a reference and introduction.
```

And to be honest I didn't find any naming conventions on drawables or strings in the file. It mentions how we call generic dimens (major_100 etc) and themes though

Would it make sense if during the job on the document with convention we will extract naming conventions-related info from the document you linked and move it to the CONVENTION.MD file or you see it differently?

**Comment by anitaa1990** [comment]
> Would it make sense if during the job on the document with convention we will extract naming conventions-related info from the document you linked and move it to the CONVENTION.MD file or you see it differently?

@kidinov, there are multiple documents in that PR related to naming conventions, like the [using android resources](https://github.com/woocommerce/woocommerce-android/pull/4456/files#diff-3631d78d16b76a41b0f61f190ecfa24bf2fe1a74e1e1c36ab1431ecc85c7e805) doc or the styling & theming doc. My suggestion would be to take a look at that PR and offer any improvements or wording suggestion or any feedback really to that PR 😄 I do think it makes sense to add this to existing documentation in that PR and not have one just for conventions. But after taking a look if you still feel like the existing documentation might not fit, I'm open to creating another doc just for conventions. WDYT?

**Comment by anitaa1990** [comment]
As discussed on Slack, I am merging this PR for now, since we have yet to decide how to proceed with our documentation but we can always come back and open another PR once we decide on the convention we want to follow and there is no reason to not merge this one until then.

**Review by anitaa1990 — APPROVED** [review]

**Pull request merged**
