### PR TITLE
[Coupons] Banner fix

### PR DESCRIPTION
**Pull request by 0nko**
This PR updates the banner message (doesn't mention editing) and points the survey to a prod link.

### CODE REVIEW

**Review by anitaa1990 — APPROVED** [review]
Thanks for the quick fix @0nko ❤️ LGTM :shipit:

**Comment by oguzkocer** [comment]
@anitaa1990 @0nko Whenever you merge anything to `release/xx` branch, could you please make sure to give @woocommerce/owl-team a heads up? You can also ping us for a review if that's easier.

In this particular case, since there is a string change, it's important that we merge these changes to `trunk` so that it can be translated. In other cases, there might be another reason, so it's best if you can keep us in the loop.

**Comment by anitaa1990** [comment]
> In this particular case, since there is a string change, it's important that we merge these changes to trunk so that it can be translated. In other cases, there might be another reason, so it's best if you can keep us in the loop.

Will do! I apologise for not doing so sooner! Thank you for taking care of this 🙇‍♀️

**Comment by 0nko** [comment]
Thanks @oguzkocer!

**Pull request merged**
