### PR TITLE
issue/4525-notifications-cleanup-step4

### PR DESCRIPTION
**Pull request by anitaa1990**
Step 4 of #4525. Since the changes are substantial I decided to split it into smaller PRs. **This PR is part of a work on progress so it is merged into `feature/notifications-cleanup`**

### Description
This PR takes the fourth step in cleaning up NotificationHandler. This PR includes user facing changes:
- Updated `FCMMessageService` to use `NotificationMessageHandler`.
- Updated `NotificationsProcessingService` to use the injectable `NotificationMessageHandler`.
- Added a new `MainActivityViewModel` class along with unit tests - handles click logic of notifications.
- Updated `MainActivity` to use `MainActivityViewModel`.
- The main visual change in this PR is that each notification type is displayed is it's own group. For instance, all order notifications are displayed in a separate group and all review notifications are displayed in a separate group. Also the text of both orders and review notification have been updated according to the Push Notifications for all stores designs.

### Testing instructions
I apologise in advance for the list of testing scenarios in this PR 😬 

#### Reviews
- Create a review from your test store. 
	- Verify that the notification is displayed correctly in the notification tray. 
	- Clicking on a single review notification should open the review detail screen.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 reviews from your test store (for the same product or multiple products). 
	- Verify that the notifications are displayed correctly in the notification tray. 
	- Click on one of  the review notifications and it should open the review detail screen for that specific review.
	- Click on the other review notifications when the app is open and it should open the review detail screen for that specific review.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more reviews or more from your test store (for the same product or multiple products).
	- Don't expand the notification but click on them as a group. 
	- Clicking on 2 review notifications should open the review list screen.
	- Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more reviews from your test store (for the same product or multiple products). 
	- Expand the notifications from the notification tray. 
	- Dismiss one of the notifications and verify that it is dismissed correctly.
- Create 2 or more reviews from your test store (for the same product or multiple products). 
	- Do not expand the notifications from the notification tray. 
	- Dismiss the group of notifications from the notifications tray. 
	- Verify that it is dismissed correctly. 

#### Orders
- Create an order from your test store. 
	- Verify that the notification is displayed correctly in the notification tray. 
	- Clicking on a single order notification should open the order detail screen.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 orders from your test store. 
	- Verify that the notifications are displayed correctly in the notification tray. 
	- Click on one of the order notifications and it should open the order detail screen for that specific order.
	- Click on the other order notification when the app is open and it should open the order detail screen for that specific order.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more orders or more from your test store.
	- Don't expand the notification but click on them as a group. 
	- Clicking on 2 order notifications should open the order list screen.
	- Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more orders from your test store. 
	- Expand the notifications from the notification tray. 
	- Dismiss one of the notifications and verify that it is dismissed correctly.
- Create 2 or more orders from your test store. 
	- Do not expand the notifications from the notification tray. 
	- Dismiss the group of notifications from the notifications tray. 
	- Verify that it is dismissed correctly.

#### Orders + Reviews
- Create an order and a review from your test store. 
	- Verify that the notifications is displayed correctly in the notification tray. The order and review notification should be displayed in separately.
	- Clicking on a single order notification should open the order detail screen.
	- Clicking on a single review notification should open the review detail screen.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 orders + 2 reviews from your test store. 
	- Verify that the notifications are displayed correctly in the notification tray. The order and review notification should be displayed in separately. 
	- Clicking on each of the order notifications separately should open the order detail screen.
	- Clicking on each of the review notifications separately should open the review detail screen.	
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more orders + 2 or more reviews from your test store.
	- Don't expand the notification but click on the order notifications as a group. 
	- Clicking on 2 order notifications should open the order list screen.
	- Click on the review notifications as aa group and it should open the review list screen.
	- Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more orders + 2 or more reviews from your test store. 
	- Expand the notifications from the notification tray. 
	- Dismiss one of the order notifications and verify that it is dismissed correctly.
	- Dismiss one of the review notifications and verify that it is dismissed correctly.
- Create 2 or more orders + 2 or more reviews from your test store. 
	- Do not expand the notifications from the notification tray. 
	- Dismiss the group of order notifications from the notifications tray and verify that it is dismissed correctly.
	- Dismiss the group of review notifications from the notifications tray and verify that it is dismissed correctly.	

#### Zendesk notifications
- Open a ticket from the app to Zendesk.
- Open the ticket on Zendesk and reply to it.
- Verify that the notification is displayed in the app correctly.
- Clicking on the notification should open the tickets page correctly.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
This one is ready for review @nbradbury @wzieba @hichamboushaba. Sorry in advance for the different test scenarios 🙇‍♀️ !

**Comment by wzieba** [comment]
@anitaa1990 just a heads up: I'll un-review myself from this PR as I'm sure now I won't be able to review it before my AFK. Sorry for that 🙇

**Review by ThomazFB — APPROVED** [review]
Great effort with this improvement and all tests descriptions @anitaa1990, thanks! After a good amount of tests everything looks to be working as expected, and the code looks good time. I just decided to do one additional test on my own, considering that we're changing stuff to the FCM service: I decided to run the app as an Open Source developer with no access to the actual `google-service.json`, and the app starts to throw this exception non-stop:

```
2021-08-19 23:06:38.822 7015-7333/com.woocommerce.android E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.woocommerce.android, PID: 7015
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.
        at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.1.1:8)
        at com.google.firebase.iid.FirebaseInstanceId.checkRequiredFirebaseOptions(com.google.firebase:firebase-iid@@21.0.0:52)
        at com.google.firebase.iid.FirebaseInstanceId.getInstanceId(com.google.firebase:firebase-iid@@21.0.0:73)
        at com.google.firebase.messaging.FirebaseMessaging.getToken(com.google.firebase:firebase-messaging@@21.0.0:30)
        at com.woocommerce.android.push.FCMRegistrationIntentService.onHandleWork(FCMRegistrationIntentService.kt:31)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

This may be completely unrelated to this PR as you didn't touch the `FCMRegistrationIntentService` here, so looks like it was introduced before since I also could reproduce this problem inside the `develop` branch. So maybe we should bring this to a broader forum to discuss.

Anyway, I'm approving this PR and leaving it up to you when to merge just in case you want anyone else to review it!

**Comment by anitaa1990** [comment]
Thank you for the review @ThomazFB and for the thorough testing ❤️  

> I decided to run the app as an Open Source developer with no access to the actual google-service.json, and the app starts to throw this exception non-stop:

That was reported by @hafizrahman and @nbradbury too I believe. But one workaround was to use `vanillaDebug` instead of any of the other build variants. I'll ping in platform to see what we can do about it. Thank you for reporting!

In the meantime, since that is unrelated to the changes in this PR, I'll merge this one 🤗 Thank you @ThomazFB! I really appreciate you taking the time to review thss PR!

**Pull request merged**
