### PR TITLE
Create survey product banner

### LINKED ISSUE #2642: [IAFeedback] Add “Give Feedback” and ”Dismiss” Buttons In Products Banner
image

The Give Feedback button will show a Crowdsignal survey. We should be able to reuse the component created in #2544. 

From Garance: Once users have interacted with the banner (either by sharing feedback or by clicking “Dismiss”), they’ll no longer see the banner. 

Ref p91TBi-2Ne-p2

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #2642, this PR delivers the following features:
- Add the `Give Feedback` and `Dismiss` buttons on the Product Banner
- Adapts the `FeedbackSurveyFragment` to support Products survey
- Creates the `FeedbackPrefs` to register all feedbacks actions the user may give
- Creates the `FeatureFeedbackSettings` as the main structure to register all user feedbacks requested with feature banners

Screenshots
==========
Light Mode
------------
| Click on the Product Banner to expand it | Click on the `Give Feedback` Button | Wait for the loading to finish and Interact with the survey | Verify if the expected view is presented and is fully functional | 
| ------------- | ------------- | ------------- | ------------- |
| screencap-2020-09-04T141227 197Z | screencap-2020-09-04T141137 000Z | screencap-2020-09-04T141155 224Z | screencap-2020-09-04T141126 616Z |

Dark Mode
------------
| Click on the Product Banner to expand it | Click on the `Give Feedback` Button | Wait for the loading to finish and Interact with the survey | Verify if the expected view is presented and is fully functional | 
| ------------- | ------------- | ------------- | ------------- |
| screencap-2020-09-04T122521 617Z | screencap-2020-09-04T122524 916Z | screencap-2020-09-04T141021 860Z | screencap-2020-09-04T141108 032Z |

How to Test
==========
Scenario 1 - Give Feedback
------------
1. Access the `Products` section from the Woo app
2. Verify that the Product Banner is showing up and available and click in the `Give Feedback` button
3. Verify that the survey view is called, the loading dialog is visible until the survey is completely loaded
4. Interact with the survey until the conclusion, after finishing it, verify that the custom native Feedback Completed View is called instead of letting the WebView show the default web one.
5. Once inside the Feedback Completed View, verify that each button is working as expected and described
6. After returning from the Survey, verify that the Product Banner is no longer visible

Scenario 2 - Dismiss
------------
1. Access the `Products` section from the Woo app
2. Verify that the Product Banner is showing up and available and click in the `Dismiss` button
3. Verify that the Product Banner is no longer visible and doesn't show up after reopening the app or doing any normal interaction with it

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@ThomazFB This is perhaps a question for @Garance91540, but I notice we show the "Give feedback" and "Dismiss" buttons even if the app was just installed. Do we want to ask for feedback in that situation?

**Comment by nbradbury** [comment]
@ThomazFB @Garance91540 It looks like we're using the same message on the feedback banner regardless of whether the product editing feature is enabled. Is this intentional?

**Comment by Garance91540** [comment]
> @ThomazFB This is perhaps a question for @Garance91540, but I notice we show the "Give feedback" and "Dismiss" buttons even if the app was just installed. Do we want to ask for feedback in that situation?

I think that might be ok, since the feature surveyed are supposed to be new too, you don't have to have much experience with the app to give feeback

> @ThomazFB @Garance91540 It looks like we're using the same message on the feedback banner regardless of whether the product editing feature is enabled. Is this intentional?

no! when the product editing feature is enabled, we should only show the new features that are not yet released. The banner should update accordingly to introduce these new features. I'll bring up this issue in the asynch channel

**Comment by ThomazFB** [comment]
Just a quick check @nbradbury and @Garance91540 , should this banner text sync be related to the current In-App Feedback project? I see that the banner text description is more related to a manual job of updating it as the Products project progress, is that correct? Not sure if this is a change request for this PR 🤔

**Comment by Garance91540** [comment]
> I see that the banner text description is more related to a manual job of updating it as the Products project progress, is that correct? 

yes! I think we can tackle this in a separate PR!

**Comment by ThomazFB** [comment]
Hey @nbradbury, I've just synced this branch with the `develop` and I think the Product feature message is solved now, the code changing the message from Products M2 to Products M3 looks available for the Banner here now. Let me know what you think.

**Review by nbradbury — APPROVED** [review]
@ThomazFB Looks great! In a subsequent PR we might want to show a confirmation if the user fills out the feedback form and then backs out of it, but that's a minor thing and not worth holding up this PR. :shipit:

**Pull request merged**
