### PR TITLE
[Woo POS] UI adjustments on the products screen #1

### LINKED ISSUE #12457: [Woo POS] UI changes on the products screen #1
Image

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12457

### Description

image

### Testing information

Open the products screen and notice:
* Transition from splash to products simplified to be a simple fade-in
* Changed the color of the cross to match the design
* Aligned cart with product titles
* Smaller elevation of the toolbars
* Larger font of the text on the empty cart stat
* Learn more has non-breaking space in between now

### Images/gif

https://github.com/user-attachments/assets/dee092af-f25a-4df7-9a32-0af82d8b05b1

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Review by AnirudhBhat — APPROVED** [review]
Thanks for the improvement @kidinov LGTM! Tested on Pixel tablet emulator.

**Comment by AnirudhBhat** [comment]
I noticed a slight flickering in the cart's empty state in dark mode when clearing the cart items. This might be expected behaviour, but I wanted to highlight it in case it's unintended.


https://github.com/user-attachments/assets/7f357cc1-c8da-4f01-a4e8-6e62c9ffaa62

**Comment by kidinov** [comment]
@AnirudhBhat 👋

By flickering, do you mean that the empty cart icon appears before the overlay opacity played, so it's brighter for a split second?

**Comment by AnirudhBhat** [comment]
>By flickering, do you mean that the empty cart icon appears before the overlay opacity played, so it's brighter for a split second?

Yes!

**Comment by kidinov** [comment]
@AnirudhBhat created an issue - https://github.com/woocommerce/woocommerce-android/issues/12519

**Pull request merged**
