### PR TITLE
[Simplified login] Update design for the Jetpack Installation initial screen

### LINKED ISSUE #7949: [Simplified login] Design update for the Jetpack installation initial screen
Image

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #7949 

### Description
This just updates the design of the Jetpack Installation initial screen.

### Testing instructions
1. Open site picker.
2. Click on "Add a store" then "Connect an existing store"
3. Enter site address of a non-jetpack site.
4. Confirm the screen looks as expected, and your site's favicon is loaded.

### Images/gif
| Scenario | Light | Dark |
| --- | --- | --- |
| Install | image | image |
| Connect | image | image |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by hafizrahman — APPROVED** [review]
This works nicely in my test. Code also looks good.

One thing that I feel is not a blocker but a bit different from the design is that the design removes "https://" from the site URL box:


I'm not sure if there's any prior discussion about this difference, so mentioning it just to be safe.

**Comment by hichamboushaba** [comment]
> One thing that I feel is not a blocker but a bit different from the design is that the design removes "https://" from the site URL box:

Nice catch @hafizrahman, I fixed this for the three screens in https://github.com/woocommerce/woocommerce-android/pull/7950/commits/f0def2327fb366ba838ebb6f7531095d564198e4

**Comment by hichamboushaba** [comment]
@hafizrahman I missed one change too, the connection dismiss error screen, I handled in the last commit, can you please take a second look:

| Light | Dark |
| --- | --- |
|image | image |

**Comment by hafizrahman** [comment]
Changes in dismissal screen also look and work good in my check! Let's 🚢

**Pull request merged**
