### PR TITLE
Do not revert edited Order. Do not show back navigation.

### LINKED ISSUE #6732: [Unified Order Editing] Revert Cancel Edit functionality
# Description

As discussed in p91TBi-91L-p2, in order to overcome some limitations identified for the cancel functionality, we are going to provide just a **Done** button to allow the merchant to exist the flow.

The **Done** button won't perform any network request when editing an order so we need to make sure all changes are already commited to the remote order.

# Task

- [ ] Revert cancel order functionality introduced in https://github.com/woocommerce/woocommerce-android/issues/6676

### LINKED ISSUE #6733: [Unified Order Editing] Add Done Button
# Description

As discussed in p91TBi-91L-p2, in order to overcome some limitations identified for the cancel functionality, we are going to provide just a **Done** button to allow the merchant to exist the flow.

The **Done** button won't perform any network request when editing an order so we need to make sure all changes are already commited to the remote order.

# Task

- [ ] Add a **Done** button to the top right of the navigation/app bar. This button should only be visible for the edit flow and should close/dismiss the edit view.

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #6732 
Closes: #6733 

### Description

This PR makes 3 adjustments in the scope of unified order editing:
- we no longer offer an order revert feature
- we don't show the back button (arrow) when a user edits an order
- we have the correct label for "finish" button (create/done)

### Testing instructions

TC 1 Order editing - back button
1. Click on any editable order
2. Make some changes
3. Click on perform system's back action (depends on the phone: either system's navigation bar or back geasture)
4. **Assert there's no confirmation dialog and order changes are not reverted**

TC 2 Order editing - done button
1. Click on any editable order
2. Make some changes
3. Click on the "Done" button
4. **Assert there's no confirmation dialog and order changes are not reverted**

### Images/gif

| Order Editing | Order Creation |
| --- | --- |
| Screenshot 2022-06-22 at 13 10 36 | Screenshot 2022-06-22 at 13 11 05 |

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by atorresveiga** [comment]
Great work @wzieba!  I've tested the changes, and they are working as expected. Before merging this PR, I'm curious why we removed the back-arrow navigation button in the action bar  ←  but let the merchant navigates back with the back button/action. 
Aren't those actions the same in this scenario?
Just for the record, I vote to maintain the back-arrow navigation button.
WDYT?

**Comment by wzieba** [comment]
I see your point @atorresveiga ! I respected the "navigate back button/action" (system one) to keep it in sync with rest of the app.

I'm also okay with adding a back arrow but I understand the idea behind not having it. The design was discussed here p91TBi-91L-p2#comment-10476 so I'll ping @joe-keenan - do you think we should add a back button to Toolbar or keep only `Done`?

**Comment by atorresveiga** [comment]
> do you think we should add a back button to Toolbar or keep only `Done`?

Hi @wzieba! I think if we allow the back navigation (system one), there is no reason not to add the back arrow. In the end, they are performing the same action.

**Review by atorresveiga — APPROVED** [review]
The code looks good to me, so I'll approve the PR. We can iterate on the back-arrow later

**Pull request merged**
