### PR TITLE
Dark Mode: Order Detail Order Notes Card

### LINKED ISSUE #1587: Dark Mode: style order detail screens
Implement light/dark mode on the order detail screen. 

## Todo
- [x] Order Status card (#1919)
- [x] Products card (#1922)
- [x] Payment Card (#1932)
- [x] Customer Information Card (#1933)
- [x] Notes card (#1934)
- [x] Shipping Method notice card (#1964)
- [x] Change order status dialog (#1965)
- [x] Refunded Products card (#1963)
- [x] Shipment Tracking card (#1963)

### PR DESCRIPTION
**Pull request by AmandaRiu**
Partially fixes #1587  by implementing light/dark theming on the order notes card in the order detail view. 

## Screenshots
order-detail-notes-card

### Loading skeleton
order-detail-notes-loading

PR #1933 must be merged and this branch updated with `feature/dark-mode` before this PR will be ready for review.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
@Garance91540 Thanks for the review!

> For all the cards (Payment, Customer, Order Notes), the titles are actually single line element, with a divider. Font Color is On Surface/Disabled.

I'm not sure I understand this point. Can you provide a screenshot?

> Can we use Subtitle 2 for the dates? I think it will help with readability.

I really struggled with which font types to use. Which date did you want changed? The grouped date, or the date of the order note? Just so we're on the same page, here's how the font types are currently assigned:

Screen Shot 2020-02-12 at 12 09 20 PM

> To stay consistent with the other cards, let's make the Notes time/name and copy On Surface/Medium Emphasis.

The notes time/name is already on surface medium. I'm not sure what is meant by `and copy`. Can you give me a little more detail? Sorry for the pain. 

> Regarding the notes badges, is it possible to use the new Woo Purple instead of the current one on Light mode and Woo Purple 30 on Dark Mode? Can we also use On Surface/Medium Emphasis for the grey badges?

Absolutely! Here's how it looks now with the color changes to the note icons:

note-icons

**Comment by nbradbury** [comment]
@AmandaRiu Code changes look good! Just give me a ping when this passes design review and I'll merge it.

**Comment by AmandaRiu** [comment]
@Garance91540 Updated the UI with suggestions. Here's the new screenshot:

order-notes-updated

**Comment by AmandaRiu** [comment]
@nbradbury this one is ready for final review 😄

**Pull request merged**
