### PR TITLE
Remove A/B and A/A tests code

### LINKED ISSUE #7472: [ExPlat] Remove A/A test code
The ExPlat A/A test (`woocommerceandroid_explat_aa_test_202208`, added in https://github.com/woocommerce/woocommerce-android/pull/7102) was successful so we can remove that test code. The test was only to check that there were no signs of bias in our ExPlat implementation, so there's no behavior changes to make.

Internal ref: pbxNRc-1QS-p2#comment-3773

### LINKED ISSUE #7473: [Elevate] Remove A/B test code and release banner to everyone
The linked product promo banner tested in the Elevate project A/B test (`woocommerceandroid_product_details_linked_products_banner`, added in https://github.com/woocommerce/woocommerce-android/pull/7226) was successful. We should remove that A/B test and release the treatment behavior to everyone.

Internal ref: pe5pgL-7v-p2#comment-853

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issues #7473 and #7472 by removing all direct references to the Linked Products A/B and test A/A test configured in the Experimentation Platform and leaving only the ExPlat support code.

How to Test
==========
1. Open the app and verify if the promo banner for Linked Products visibility is now only tied to not having Linked Products configured and the AppPrefs' current state.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@ThomazFB Should we remove the test from [experiments.json](https://github.com/woocommerce/woocommerce-android/blob/99d56674e146860344799634c33bbe28e721a4f5/WooCommerce/src/androidTest/assets/mocks/mappings/wpcom/experiments.json)?

**Comment by ThomazFB** [comment]
Oh, I wasn't aware of this test, thanks @nbradbury. I'm just confused about the context and where this is used, I can see it's some sort of request test, but I can't find where it's executed. Considering there's not a single experiment in the app anymore, should we delete this whole JSON file? 🤔

**Comment by nbradbury** [comment]
> Considering there's not a single experiment in the app anymore, should we delete this whole JSON file? 🤔

Probably so, but I'm not sure we should keep it since we're adding an experiment for product onboarding at some point.

**Comment by ThomazFB** [comment]
Well, in that case @nbradbury, I adjusted the file to reflect the very same state of the ExPlat configuration we have now: no parameters describing experiments. WDYT? Changes submitted here: https://github.com/woocommerce/woocommerce-android/pull/7543/commits/1685d41b5a56965408870f1fca6005936601f50a

**Review by nbradbury — APPROVED** [review]
Looks good, let's :shipit: !

**Pull request merged**
