### PR TITLE
Dark Mode v2: Magic Link Sent tweaks

### LINKED ISSUE #2326: Dark Mode v2: Magic Link Sent screen
Update the current magic link sent screen to match the designs. Since this is a shared library, will have to override the layout. 

#### Design
Screen Shot 2020-04-27 at 5 54 02 PM

#### Current Implementation
Screen Shot 2020-04-27 at 5 53 46 PM

### Updates needed
* Image 
	* Update size `280x150`
	* margin top = `90dp` 
* Text
	* override `android:textColor` in the theme to set it to `color_on_surface_high`. 
	* margin start/end to `56dp`
	* margin top/bottom to `24dp`
* Enter password instead link
	* margin top = `24dp`
	* text = `Body2`

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #2326 by overriding the layout files for `login_magic_link_sent_screen.xml` for portrait and landscape modes to better fit the designs:

### Designs
Screen Shot 2020-04-27 at 5 54 02 PM

**NOTE**: Requires design review before merge

Before | After
-- | -- 
Screenshot_1588042992|Screenshot_1588043059
Screenshot_1588043007|Screenshot_1588043052
Screenshot_1588042998|Screenshot_1588043066

### CODE REVIEW

**Review by Garance91540 — COMMENTED** [review]
Hi @AmandaRiu! 

All is looking much better, I have one question regarding the landscape view: is it possible to remove the white bottom bar with the "Open mail" and "Use password" line and rather stack them up vertically with the same styling as the other screens (no white bar)? 

We can enable scrolling if they don't fit all above the fold

**Comment by AmandaRiu** [comment]
@Garance91540 

> All is looking much better, I have one question regarding the landscape view: is it possible to remove the white bottom bar with the "Open mail" and "Use password" line and rather stack them up vertically with the same styling as the other screens (no white bar)? We can enable scrolling if they don't fit all above the fold

I've implemented those changes:

Before | After
-- | --
80442983-f98cab00-88c2-11ea-8574-9ae1d3ed2dae|Screenshot_1588097812

And since the screen has changed so drastically, I've also implemented the same level of view overrides for the magic link request screen so they now match. Note that the gravatar is smaller so that's why you can see more in this screenshot than the one above:

Before | After
-- | --
Screenshot_1588098384|Screenshot_1588098295

**Review by Garance91540 — DISMISSED** [review]
Looking great! 👏

**Comment by nbradbury** [comment]
@AmandaRiu There are merge conflicts in this. Just ping me when those are taken care of and I'll do the review.

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
