### PR TITLE
Add toolbar for PaymentsHubFragment screen

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Part of #10570 

### Description

This PR introduces individual toolbars for PaymentsHubFragment screen, replacing the shared toolbar previously used with MainActivity. This modification is essential to accommodate screens within a two-pane layout, ensuring that each screen maintains its distinct toolbar despite sharing a common parent.

### Testing instructions

Navigate to the Payment hub screen(Menu -> Payments) screen and ensure the toolbar and its action work as expected on both phone and tablet.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by jd-alexander — APPROVED** [review]
Changes are good. Tested on Samsung Galaxy 23 Ultra and Nexus 10. 

I have a question, on these toolbar related PRs I see similar logic being repeated. WDYT about a mechanism for consolidating the logic so it is shareable or did you take this approach for a particular reason? Interested in knowing more.

Please check failing checks to verify all is well before merging. Thanks!

**Comment by AnirudhBhat** [comment]
Thanks for the review @jd-alexander 
> I have a question, on these toolbar related PRs I see similar logic being repeated. WDYT about a mechanism for consolidating the logic so it is shareable or did you take this approach for a particular reason? Interested in knowing more.

I thought about extracting the logic for a while before implementing and couldn't find a reasonable solution that would avoid all the toolbar boilerplate logic. I wanted to make it work first, then make it better. I'll definitely consider this suggestion and see how we can extract this boilerplate. Thank you!

> Please check failing checks to verify all is well before merging. Thanks!

I've asked about it here: https://github.com/woocommerce/woocommerce-android/pull/10591#issuecomment-1945362636

**Pull request merged**
