### PR TITLE
[DNM] Collapsable dependency diff test

### PR DESCRIPTION
**Pull request by wzieba**
This PR tests #6215

### CODE REVIEW

**Comment by wzieba** [comment]
@kidinov 👋 do you have any idea why the comment from @wpmobilebot is not using the template changed in this PR? 🤔

**Comment by kidinov** [comment]
@wzieba have you tried to escape html symbols? If doesn't help the only way to determine is to check the source code of the plugin, I remember was doing that to figure out how to send those messages

**Comment by wzieba** [comment]
I'm wondering what's going on 🤔  I've
- added some random string in 61d96ab
- removed the previous comment just in case

and the comment still doesn't contain changes.

**Comment by wzieba** [comment]
Oh I see - in line 39 of the script we checkout to `$targetBranch`, so task from `trunk` is used while sending report!

**Pull request closed without merging**
