### PR TITLE
 #3808 change integer quantity to decimal.

### PR DESCRIPTION
**Pull request by yuliiakorabelska**
[WIP] Replaced integer quantity usage to BigDecimal.

### CODE REVIEW

**Comment by anitaa1990** [comment]
Hey @juliafedosya! Let me know once this PR is ready for review and we can get someone assigned to review it! Thank you for working on this issue 😄 Feel free to ping us here if you run into any issues!

**Comment by yuliiakorabelska** [comment]
Hi @anitaa1990 ! Thank you for offering me help! I've tried to reach you out in Slack as I seem to have an issue with CI. I could not trigger the build myself as I don't have permission, there seems to be a problem with the Installable build job. The log says  "[!] Decryption key could not be found". Could you please help me with that?
Also what would be the preferable way for you to contact regarding any issues in the future?
Thank you so much!

**Comment by anitaa1990** [comment]
> Hi @anitaa1990 ! Thank you for offering me help! I've tried to reach you out in Slack as I seem to have an issue with CI. I could not trigger the build myself as I don't have permission, there seems to be a problem with the Installable build job. The log says "[!] Decryption key could not be found". Could you please help me with that?

Hey @juliafedosya CI would fail because the PR is from a fork and does not have the necessary credentials for that. It's fine if that fails. We will open a separate PR once this is approved (from our own branch and it should work fine).

Is the PR ready for review? I ask because the PR description mentions that it's a WIP 😄 . We usually also add some more details to the PR description such as what is this PR addressing, some UI before and after screenshots, testing steps etc. You can find a template here from [our guidelines](https://github.com/woocommerce/woocommerce-android/wiki/Pull-Request-Guidelines). 

> Also what would be the preferable way for you to contact regarding any issues in the future?

Sorry, I don't think I'm on that Slack workspace yet 😬 Would you mind letting me know which workspace in Slack you tried to contact me? I don't think I'm logged into anything yet so I must have missed some messages! I apologise. I'll make sure to be available and logged in from next time 😸

**Comment by anitaa1990** [comment]
Hey @juliafedosya, would you mind if we take over this PR since we think this is an important bug that needs to be fixed? Or would you have some time to work on this this week?

**Comment by hichamboushaba** [comment]
Closing this due to inactivity

**Pull request closed without merging**
