### PR TITLE
[Migrate Simple Payments] Tracking

### LINKED ISSUE #11203: [Migrate Simple Payments] Tracking
🆕 simple_payments_migration_sheet_add_custom_amount: When tapping the Add Custom Amount CTA in the migration sheet
Then we can measure how many complete the custom amount with add_custom_amount_done_tapped/order_create_button_tapped/order_creation_success events in the funnel
🆕 simple_payments_migration_sheet_shown: When the migration sheet is shown

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #11203

### Description

The PR adds tracking of the events:
* `simple_payments_migration_sheet_add_custom_amount`
* `simple_payments_migration_sheet_shown`

### Testing instructions

Use logcat with "track" filter
* More -> Payments -> Collect Payments -> Add A custom amount 
* Notice events tracked mentioned above

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
Looks like one of the tests are failing. Not sure if your changes would have affected it though.

**Comment by kidinov** [comment]
@backwardstruck seems that the test if flaky. Restarted - now all good

**Comment by backwardstruck** [comment]
I see the correct events:


```


🔵 Tracked: orders_add_new, Properties: {"blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
🔵 Tracked: simple_payments_migration_sheet_shown, Properties: {"blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
🔵 Tracked: orders_list_loaded, Properties: {"total_duration":1.025,"status":"","total_completed_orders":0,"blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
🔵 Tracked: orders_list_loaded, Properties: {"total_duration":1.025,"status":"","total_completed_orders":0,"blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
🔵 Tracked: simple_payments_migration_sheet_add_custom_amount, Properties: {"blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
🔵 Tracked: order_creation_add_custom_amount_tapped, Properties: {"blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}



```

**Review by backwardstruck — APPROVED** [review]

**Pull request merged**
