### PR TITLE
[Scan to update inventory] Track additional analytics event

### LINKED ISSUE #10464: Start tracking `product_quick_inventory_update_bottom_sheet_shown` event

### PR DESCRIPTION
**Pull request by samiuelson**
Closes: #10464 

### Description

This PR adds additional analytics event tracking when Quick inventory update bottomsheet is opened. 
More context – pdfdoF-4k6-p2#comment-5562

### Testing instructions

Go to the Products screen and click the "Scan" icon.
Verify the following events are tracked:
1. `🔵 Tracked: product_quick_inventory_update_bottom_sheet_shown, Properties: {"item_stock_managed":true}` - in case a stock-managed product was found
2. `🔵 Tracked: product_quick_inventory_update_bottom_sheet_shown, Properties: {"item_stock_managed":false}` - in case a non stock-managed product was found

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by AnirudhBhat — APPROVED** [review]
LGTM!

Just one non-blocking question regarding the user interface and analytics tracking for non-stock managed items. When such an item is scanned, our current system displays a snackbar notification instead of a bottom sheet. However, in our analytics, this action is recorded as 'bottom sheet shown'. This discrepancy could lead to confusion in the future when reviewing our analytics data.

**Comment by samiuelson** [comment]
> LGTM!
> 
> Just one non-blocking question regarding the user interface and analytics tracking for non-stock managed items. When such an item is scanned, our current system displays a snackbar notification instead of a bottom sheet. However, in our analytics, this action is recorded as 'bottom sheet shown'. This discrepancy could lead to confusion in the future when reviewing our analytics data.

Thanks, @AnirudhBhat! I'm aware of that and we're in progress of replacing the snackbar with the bottom sheet the PR is there – https://github.com/woocommerce/woocommerce-android/pull/10467.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/187">16.9</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/187">16.9</a>. The due date for this milestone has already passed.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
