### PR TITLE
Show snackbar when there is an error syncing Inbox

### LINKED ISSUE #6279: [Home Screen updates - Inbox] Inbox error handling
Display a snackbar with the message: "Error syncing inbox" when any of the following requests fails inside Inbox screen: 
- When fetching inbox notes from API fails
- When dismissing one note fails
- When dismissing all notes fails 
- Swipe to refresh

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #6279 

### Description
Display a snackbar with the message: "Error syncing inbox" when any of the following requests fails inside Inbox screen: 
- When fetching inbox notes from API fails
- When dismissing one note fails
- When dismissing all notes fails 
- Swipe to refresh

### Testing instructions
 Remove connectivity and check snackbar with error "Error syncing Inbox" is displayed in following cases:
- Open Inbox
- Press dimiss over inbox note (if there are no inbox notes cached then enable connectivity to properly load Inbox and then retry this tests with no connectivity)
- Press dismiss all notes. Note that this has an "optimistic" approach. So local DB will be cleared even if the API requests fails. 

### Images/gif

https://user-images.githubusercontent.com/2663464/163812216-b1b88696-817a-4b37-9f72-b710afc2c8cb.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by 0nko** [comment]
@JorgeMucientes If I understand it correctly, the behavior matches the instructions. However, is this correct?

1. Turn on airplane mode
2. Go to Inbox
3. Dismiss all notes (error snackbar appears, as expected)
4. Leave the Inbox
5. Turn off the airplane mode (wait for connectivity)
6. Go back to Inbox
7. The notes are back (shouldn't the dismiss be already synced now)
8. Dismiss notes again
9. The notes get cleared but the error snackbar appears again

**Comment by JorgeMucientes** [comment]
Thanks for pointing that case out @0nko. 
"Dismiss all action" works in an "optimistic" way. When pressing that button, we remove all items from DB and in parallel we hit the API and remove the notes there too. The UI is updated "optimistically" whether the API request is successful or not, so the empty case will be shown either way.  What happens the next time you open Inbox is that DB is empty but API returns the Inbox notes we failed to delete previously. This behavior should be quite edge case but I agree is confusing even though we have displayed an error message stating that there was an issue syncing with server. 

An alternative to this would be to display skeletons while "Dismissing all" and only if all API requests succeed in removing notes then reset the DB and show the empty case. 

wdyt?

**Comment by 0nko** [comment]
> What happens the next time you open Inbox is that DB is empty but API returns the Inbox notes we failed to delete previously.

I'm not fully familiar with the optimistic action mechanism but I think the ideal scenario would be to have some sort of queue of actions, so a new one isn't performed before the previous one is finished.

Example:
1. Dismiss all
2. Notes are deleted from the DB optimistically
3. A dismiss quest is inserted into a queue with "in progress" status
4. The API is hit but the request fails 
5. The user leaves and comes back to Inbox
6. The empty message is displayed as that's the correct state the user expects
7. The reload request is put into a queue
8. The dismiss request completes
9. The reload request is performed and completes
10. New notes are loaded, if any

Again, I'm not sure how feasible this is, it's just something I'd expect as a user. If it doesn't make sense then what you suggested is better than the current behavior.

**Comment by JorgeMucientes** [comment]
Thanks for the suggestion @0nko. 

While I think queuing actions could work I think it is risky. The user might end up missing new notes. Consider this scenario: 
1. User has 3 notes 
2. Reads/Opens all of them and decides it's time to dismiss them.
3. Clicks "Dismiss all" notes. 
4. Request fails (for any reason, lets say server is down temporarily). 
5. We display an error snack bar and keep the UI as is, with the 3 notes. 
6. We enqueue the failed "Dismiss all" request to be triggered later. Now the tricky part, when should we trigger this request again? Exponential back off? Next time user opens the app? Next time they open the Inbox? Let's assume is triggered next time they open the app. 
7. Before user opens the app again the Inbox is updated with 2 new notes. 
8. User opens the app and the pending "Dismiss All" is triggered. The 2 new unread notes will be dismissed along with the 3 other notes and the user will never see them.

Imo creating a queue for this case feels overkill and I'm not sure we might be able to overcome the scenario where the user might miss new notes. I think a safer and simpler way to handle this is to show the skeleton, wait for the API result and if it fails show the snackbar error and keep the DB data. 
Going to implement that. Will ping you once it is ready as I need to make a small change in FluxC. 
Thanks for the good feedback @0nko 🙂

**Comment by JorgeMucientes** [comment]
I've added a couple changes in FluxC to improve the error handling experience for Dismiss all action. And also to avoid clearing the DB before we know that the inbox notes were deleted successfully in the server side. You can see them [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2365)

Once those FluxC changes are reviewed and merge this PR will be ready for another round.

**Comment by 0nko** [comment]
@JorgeMucientes Thanks for the response! I'll review the changes, I just wanted to comment on the scenario you mentioned (my comments in bold):

1. User has 3 notes ✔️ 
2. Reads/Opens all of them and decides it's time to dismiss them. ✔️ 
3. Clicks "Dismiss all" notes. ✔️ 
4. Request fails (for any reason, lets say server is down temporarily). ✔️ 
5. We display an error snack bar and keep the UI as is, with the 3 notes. **Why? The notes should be dismissed in the DB now, no?**
6. We enqueue the failed "Dismiss all" request to be triggered later. Now the tricky part, when should we trigger this request again? Exponential back off? Next time user opens the app? Next time they open the Inbox? Let's assume is triggered next time they open the app. **I guess that would depend on the mechanism, this shouldn't really matter, though.**
7. Before user opens the app again the Inbox is updated with 2 new notes. **That's the thing -- the 2 unread notes should be loaded _after_ the previous "dismiss all" request is completed**
8. User opens the app and the pending "Dismiss All" is triggered. The 2 new unread notes will be dismissed along with the 3 other notes and the user will never see them. **Based on what I wrote above, this shouldn't happen**

I agree that creating such queued mechanism isn't trivial. But I think it would bring a lot of benefits, such as offline support, automatic failure recovery, back-off, connectivity detection & retry. I've seen a great session on how to build this using WorkManager: https://docs.google.com/presentation/d/1c8-XG1IP8CzMwBoovuS9jpPGUK7za9PWn3IpCAS3Njk/edit#slide=id.gf92939e280_22_0

**Comment by JorgeMucientes** [comment]
Hey @0nko regarding your comment (sorry for the late reply, missed it yesterday).

> That's the thing -- the 2 unread notes should be loaded after the previous "dismiss all" request is completed

Not sure if this is feasible with the existing API for Inbox. At least not using the "dismis all" endpoint. This endpoint will delete all the notes no matter what. We can't specify which notes we want to delete, so in the previous scenario, we can't really differentiate between the 3 notes we wish to remove and the 2 new notes we don't want to. To achieve this, we would need to mark the notes as "dismissed" locally and then using work manager for example fire an independent request for each of the notes we want to dismiss. This could easily lead to firing 20-40 request to the API at the same time. Which I'd say is far from convenient, even though this scenario would be an edge case.

Also, I'm not against creating a general purpose queue mechanism for the app so we can easily retry failed requests at a different moment in time or under specific conditions. I agree, this would allow for improvements in offline support and might also improve the "slowness" perception user have of the app by allowing us to sync stuff beforehand and then loading data from DB in those places that generally feel slow. I think this could be a nice proposal to make to the team.  In any case I think that should be handled in a total different task and feels out of scope for this issue.

**Comment by 0nko** [comment]
> I think that should be handled in a total different task and feels out of scope for this issue.

Definitely 👍

**Review by 0nko — APPROVED** [review]
The fix works well. Nice work! 👍

**Pull request merged**
