### PR TITLE
Hilt Migration: Migrate Help screen.

### PR DESCRIPTION
**Pull request by hafizrahman**
Part of #3936 

Testing instructions:
1. Make sure build runs OK and tests are OK as well.
2. Run app, go to Help area and do general checking. All items should open properly.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hichamboushaba** [comment]
Thanks @hafizrahman for working on this, looks good 👍 

We just need to remove the dagger-android subcomponents and modules to finish the migration, we don't need this anymore: https://github.com/woocommerce/woocommerce-android/blob/aa65379fc7a30ea1d5776ecb7bf08c7240659a3b/WooCommerce/src/main/kotlin/com/woocommerce/android/di/ActivityBindingModule.kt#L31
and this https://github.com/woocommerce/woocommerce-android/blob/97a56df203838dadd91f5853f344d21d35f7884f/WooCommerce/src/main/kotlin/com/woocommerce/android/support/HelpModule.kt#L6

**Comment by hafizrahman** [comment]
> We just need to remove the dagger-android subcomponents and modules to finish the migration

Oh, so that's what the part in `ActivityBindingModule` was for, I was wondering but unsure whether to remove it. Wasn't sure what the empty `HelpModule` was for either, but will keep an eye on similar things on future migration steps.

**Comment by hafizrahman** [comment]
Ready for another review @hichamboushaba , thank you!

**Review by hichamboushaba — APPROVED** [review]
Nice work @hafizrahman 🥇

**Pull request merged**
