### PR TITLE
Unified Login: Not a WordPress Site error flow

### LINKED ISSUE #2942: Unified Login: Not a WordPress site screen
Create a new error screen for when the user enters a site address that does not have WordPress installed. Here is the current error:

Here is the design for the new screen:

Screen Shot 2020-09-30 at 5 16 08 PM

### PR DESCRIPTION
**Pull request by AmandaRiu**
Closes #2942. This PR adds the new "Not a WordPress site" error screen to the login by store address flow. This screen will only be show when the user enters a URL for a site that does not have WordPress installed. 

Before | After
-- | --
not-store-before|screenshot-1608068020199

### Tracks events

No new tracks events added, only new `Step` and `Flow` properties. Below are the events associated with this new view:

- Not a WordPress site error screen displayed. Set the active step to `NOT_WORDPRESS_SITE`:
`Tracked: unified_login_step, Properties: {"source":"default","flow":"login_site_address","step":"not_wordpress_site"}`

- On the new screen: User clicked on the "Help" icon:
`Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_site_address","step":"not_wordpress_site","click":"show_help"}`

- On the new screen: User clicked "Try another store":
`Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_site_address","step":"not_wordpress_site","click":"try_another_store"}`

- On the new screen: User clicked "Try another account":
`Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_site_address","step":"not_wordpress_site","click":"try_another_account"}`

### Testing
Do a fresh install of the app or clear app data, and start the login process:
1. Click **Enter your store address**. The site address form is displayed. 
2. Enter `google.com` in the store address field and click **Continue**. The "Not a WordPress site" error screen is displayed. 
3. Click the **Help** icon and verify the help screen is displayed. Verify the appropriate tracks event is fired off. 
4. Click **back** to return to the error screen.
5. Click **Try another store**. Verify the site address form is displayed and the appropriate tracks event is fired off.
6. Click **Continue** to re-display the "Not a WordPress site" error screen.
7. Click **Log in with another account**. Verify the app is directed back to the Prologue/Welcome screen and the appropriate tracks event is fired off.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by anitaa1990 — COMMENTED** [review]
The code changes look good @AmandaRiu! I just found one minor issue when testing.
The toolbar title is not displayed when the generic error screen is displayed. It's not a huge bblocker so if you feel it's fine to fix that in another PR, we can merge 👍 

Screenshot 2020-12-16 at 6 23 59 PM

**Comment by AliSoftware** [comment]
Moved to milestone 5.8 as it was not ready by the time I had to do the 5.7 code freeze.
(We can discuss re-targeting the PR to `release/5.7` if you feel it's really worth including it in 5.7)

**Review by Garance91540 — DISMISSED** [review]
👏

**Comment by AmandaRiu** [comment]
Oh thank you for f inding that Anitaa! I've updated to show the title, and I've also fixed the alignment of the image to better match the design.

Before | After
-- | --
before|after

Ready for another round!

**Review by anitaa1990 — APPROVED** [review]
LGTM :shipit: 

Just asking here in case it's missed, do you think we need to update the Login library and also make sure the listener added here is updated in the WordPress app as well?

**Pull request merged**
