### PR TITLE
Issue/2781 incorrect product type fix

### LINKED ISSUE #2781: Products: Product Type selector shows wrong options for product type
**Describe the bug**

I expect to have four options for a product type:

* Simple
* Variable
* Grouped
* External

However, right now the product type selector always shows these four options:

* Physical
* Virtual
* Grouped
* External

A few issues with this:

1. Based on the designs, Physical and Virtual should be grouped as Simple in the product type selector. I should be able to switch a simple product between physical and virtual using the virtual product option in Product Settings.
2. I never see the Variable option, so I can't change a product to variable.
3. I can see and select the current product type in that selector. I get a prompt asking me if I'm sure I want to change the product type, even though it doesn't actually change anything if I'm choosing the current product type.

**To Reproduce**

1. Go to Settings > Beta Features and enable Product Editing.
2. Go to the Products tab.
3. Open a simple product.
4. Tap on Product Type. Notice you see Physical and Virtual (instead of Simple) and Variable is not in the list.
5. Select the same product type (for example, if it's a physical product choose Physical).
6. Notice you get an "Are you sure you want to change the product type?" prompt. Select "Yes, change." Notice nothing changes.

**Screenshots**

Example of the product type selector for a simple, physical product:

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.9-rc-1

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2781. This PR fixes three issues:
- Based on the designs, Physical and Virtual should be grouped as Simple in the product type selector. I should be able to switch a simple product between physical and virtual using the virtual product option in Product Settings. The fix is to remove the Virtual product option from the product list selector.
- I never see the Variable option, so I can't change a product to variable. The fix is to include the variable option in the product list selector.
- I can see and select the current product type in that selector. I get a prompt asking me if I'm sure I want to change the product type, even though it doesn't actually change anything if I'm choosing the current product type. The fix is to ensure that the current product type is not included in the product list selector.

#### To test
- Click on a PHYSICAL product from the Products tab.
  - Click on the Product Type section.
  - Notice that the product type selection includes: "Variable", "Grouped" and "External" options only.
  - Change the product type to anything else and verify that a confirmation dialog is displayed.
  - Click on Cancel and notice that the dialog is dismissed.
  - Change the product type to anything else and verify that a confirmation dialog is displayed.
  - Click on Change and notice that the product type is changed in the Product Detail screen.
  - Notice the "UPDATE" menu button is displayed.
  - Click on the "Update" menu button and verify that the product type is updated successfully.
- Follow the above steps for a Variable, Grouped and External products.

cc @rachelmcr I added you as a reviewer since you found the original bug. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rachelmcr** [comment]
> The fix is to remove the Virtual product option from the product list selector.

I think both Physical and Virtual product options should be removed from the product list selector, and replaced with a generic Simple product option (as in core). The title/description for Simple product would be this:

> Simple product
> A unique item to sell

As in this design for selecting a product type here:

Screen Shot 2020-08-27 at 1 24 05 PM

That's the design for the product selector when adding a new product, but I was thinking it was also the expected design when editing the product type for an existing product. @Garance91540 could you confirm?

**Comment by rachelmcr** [comment]
I tested the changes in the PR and everything is working well for me, aside from my question above about using "Physical product" versus "Simple product" in the selector.

**Review by 0nko — APPROVED** [review]
Looks good and works as described 👍. Once the "Physical" is changed to "Simple" we're good to :shipit:.

**Comment by anitaa1990** [comment]
Ohh, duh! I totally missed that! Fixed in ffd0eee 👍  Thanks for the review @0nko

**Comment by Garance91540** [comment]
> @Garance91540 could you confirm? 

That's right!

**Pull request merged**
