### PR TITLE
[Woo POS] Match design for order creation failure

### LINKED ISSUE #12014: [Woo POS] Match design for order creation failure
Screenshot 2024-07-23 at 17 19 17

Screenshot 2024-07-23 at 17 21 02

```[tasklist]
### Tasks
- [x] Fonts
- [ ] Margins
- [x] Colors
- [ ] Elevation/Shadow
```

### PR DESCRIPTION
**Pull request by backwardstruck**
Closes: #12014  

### Description  

This PR updates the error screen for order creation failure to match the design specifications outlined in the linked issue.

This builds on the merged changes in https://github.com/woocommerce/woocommerce-android/pull/12119#discussion_r1691895731

### Steps to reproduce  

1. Add products in POS.
2. Trigger an order creation failure scenario (e.g., simulate a network failure by using airplane mode).
3. Go to Checkout
4. Observe the error screen that appears. Verify that the screen matches the design specifications provided in issue #12014.
5. Check the following elements:
   - Error icon is appropriately sized and positioned.
   - Error message text style matches the design.
   - "Retry" button is correctly styled (width, height, positioning) and functional.
   - Spacing between elements (icon, text, buttons) is consistent with the design.

### Testing information  

- Devices used: Android tablet emulator
- Tested scenarios
  - Order creation failure due to network issues.
 

### Images/gif  

TODO

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
@soundsokay  I think it's still not pixel perfect with the design. Mainly regarding some padding and the background color for the error state. 
Screenshot_20240725_180413

Happy to add those changes here but I can't remember if we said we were going to leave some of those changes for later.

**Comment by irfano** [comment]
I'm moving this to the 19.8 milestone.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/228">19.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — APPROVED** [review]
LGTM 🚀

**Pull request merged**
