### PR TITLE
fix: administrative area formatting for JP and TR

### LINKED ISSUE #2820: App not showing Turkish city names
**Describe the bug**

User is seeing cities' license plate code instead of the Turkish real city name in the WC app. For example

34 instead of Istanbul
06 instead of Ankara
01 instead of Adana.

This does not happen on WP-Admin

**To Reproduce**

1 - Go to a test site 

2 - select a product and proceed to checkout

3 - use a Turkish address (I used the one for the Museum of Anatolian Civilizations 
Kale, Gözcü Sk. No:2, 06240 Ulus/Altındağ/Ankara, Turkey)

4 - on the app, check the new orders and the billing and/or shipping information

**Screenshots**

This one is from the user (the entire screen is on the ticket but I cropped this part so it does not show everything)

Screenshot on 2020-09-03 at 09_11_16

This one is from my fake purchase on my test site:

IMG_20200903_093138_541

**Expected behavior**

I expected the app to show the city name just like it does on the browser as opposed to a code, which according to the user is their licence's plates codes.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
My test:
- Device: Pixel 2
- Android version: 10
- WooCommerce Android version: 4.9-rc-3

User's 👍  

- Device: xiaomi mi note 10 lite
- Android version:  Did not say, asking again
- WooCommerce Android version: 4.9-rc-2

3255763-zen

### LINKED ISSUE #5604: Order Details - state is shown incorrectly. Country is determined by Android framework.
E.g. state `Hokkaido` in `Japan` is shown as `JP01` which is location code for this state in WooCommerce Core.

Also, we format `country` based on `country code` via `java.util.Locale#displayCountry` (see: `AddressUtils`). As we have `Location` fetched from Core with its code and name, I believe we should prefer using that.

#### Core
Screenshot 2022-01-06 at 15 31 40

#### WooCommerce Android 8.1.1
Screenshot 2022-01-06 at 15 31 49

#### `WCLocation`s from Core
Screenshot 2022-01-06 at 15 32 01

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #5604
Closes: #2820

### Description

This PR fixes administrative area formatting for Japan and Turkey. Nuances and decision log is described in this internal communication post: pe5pgL-1EV-p2

#### TC1 Japan
1. Create new Order
2. Edit the customer
3. Select `Japan` as a country and any prefecture
4. Save on the customer edit screen
5. Assert that there's the English name of the prefecture in the Customer section on the Order Creation screen

#### TC2 Turkey
Repeat TC1 but with Turkey as a country.

### Images/gif

| Before | Now |
| --- | --- |
| Screenshot 2023-01-03 at 15 42 15 | Screenshot 2023-01-03 at 15 48 52 |

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
FYI: @wzieba I moved the `11.8` milestone to `11.9` in order to proceed with the code freezing. Do let me know if you still need this PR to be part of the `11.8` release.

**Comment by wzieba** [comment]
Thanks @ParaskP7 ! It's good to move it to `11.9` (but not `11.19`!!! 😄 )

**Comment by wzieba** [comment]
hi @ThomazFB 👋 do you think you could fit review of this PR today? It'd be great if it landed in `11.9` 🙂

**Comment by ThomazFB** [comment]
Oh, I completely lost the track of this PR review, sorry for that @wzieba! I'll review it right now!

**Review by ThomazFB — APPROVED** [review]
Tested in both countries and it's working just fine! Thanks for tackling this fix!

**Pull request merged**
