### PR TITLE
Navigation refactoring: result handling when navigating back 

### PR DESCRIPTION
**Pull request by hichamboushaba**
Currently, we have two ways to communicate results when navigating back:
1. Using the NavigationResult interface, and this extension: https://github.com/woocommerce/woocommerce-android/blob/2cba6e3d803067879d982ae003be100601793c57/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/ActivityExt.kt#L18-L27
2. Using the Navigation's component savedStateHandle: https://github.com/woocommerce/woocommerce-android/blob/2cba6e3d803067879d982ae003be100601793c57/WooCommerce/src/main/kotlin/com/woocommerce/android/extensions/FragmentExt.kt#L18-L21

Personally, I prefer the second way, as it doesn't have to deal with request codes, and bundles, and instead we can pass strongly typed objects. But on the other hand, we need request codes sometimes, for example when handling the AztectEditorFragment result.

In this PR, I attempt to convert some parts to the second solution, and I updated the `Fragment.navigateBackWithResult` to allow popping stack to a defined destination.
For the AztecEditorFragment result, I left it as a Bundle and added a request-code parameter to be able to handle the result appropriately in the ProductDetailFragment.

**Testing**
Test result handling when navigating back for the following scenarios:
- Products filtering
- Order refund
- Add product category
- Product description and short description
- Product variation description
- Product shipping class
- All product settings subscreens.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by 0nko** [comment]
Yes, I'm all for converting all result-handling to the 2nd solution 👍. It was actually my intention to do this eventually. The 1st approach was a workaround before the `savedState` solution existed in the Lifecycle library.

**Comment by hichamboushaba** [comment]
Thanks @0nko for the confirmation, I'll try to do convert the rest

**Comment by hichamboushaba** [comment]
@0nko I requested your review, I updated the description with all the parts that were changed and that need testing.

**Review by 0nko — APPROVED** [review]
I've tested different result-handling scenarios and everything seems to work fine. 

Really great work, @hichamboushaba! 🎖️

**Pull request merged**
