### PR TITLE
Mooore IPP: release notes

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #7142

### Description

Release notes

### Testing instructions

Check the release notes =)

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by malinajirka — COMMENTED** [review]
Thanks @kidinov, I think we might want to avoid using internal terms like `hub screen` and make the release notes more user focused. 

Perhaps we could say something like `In-Person Payments and Simple Payments have been moved to a new Payments section.`.

I believe we usually process the release notes one more time before we publish them, but if we can improve them here, why not. Wdyt?

**Comment by kidinov** [comment]
@malinajirka

Sure, I can change it, just want to make sure - I was under impression that the release notes we write should give a clear understanding of what's changed to a person who later composes them for users (Aaron before, Cesar now?), therefore I thought that these notes are for them, not for the users. 

So it's like shell we keep it more clear for them, or simple for the users? That can be 2 different types of release notes =)

**Comment by malinajirka** [comment]
My understanding is that we prepare something and they polish the details so the same language is used across all features/versions. If they want to re-word it completely, they can always open the referenced PR so I believe we don't need to try to provide all the context. 

So I'd say we don't need to spent too much time on the details, but if we can get it into a releasable state, the better. Important to note is that the person who will be polishing the details might not know whether `hub` is a user-facing term or not - they always post the proposal so we could let them know then, but feels like extra work for all parties involved. Wdyt?

**Comment by kidinov** [comment]
@malinajirka makes sense! Change here - 333aaada6eaf5cc5a1c69ab69fe64c450114972d

**Review by malinajirka — APPROVED** [review]
Thanks!

**Pull request merged**
