### PR TITLE
Fix FeedbackPrefs initialization on UI Tests

### PR DESCRIPTION
**Pull request by hichamboushaba**
### Description
This PR fixes the UI tests initialization, after we introduced Hilt to the code base, all the app's initialization has been moved to the AppInitializer class, but I missed the FeedbackPrefs init method.
I moved it to it in 09554cf, to make sure it gets called when creating tests.

Something else that I noticed, is that if I try to test a class that has multiple tests (the case of `ScreenshotTest` now) at the same time, the second test fails, this is because we try to initialize the app for each test individually using the `InitializationRule` (same behavior of Robolectric before), so this creates issues for components that don't expect to be initialized multiple times (from my testing this occurs only for ZendeskHelper). So to fix this, I moved the `mocksDemo` to its own class in 123a5a4. @designsimply if you need to have multiple tests in the same class, then we can try to find another solution, just let me know.

### Testing instructions
Run the test of MocksTest class, and confirm that you can navigate to products screen.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pachlava** [comment]
Thanks for doing this @hichamboushaba!

Since I'm not a reviewer, I'm just leaving a note that the `Products` screen now loads with no issues 👍 

A small note on the newly added file: the `mocksDemo()` test was recently created as a temporary measure to make the review of #5032 easier ([see this comment](https://github.com/woocommerce/woocommerce-android/pull/5032#discussion_r731307156)). It's not needed in the long term, and it's actually already deleted in the (still draft) #5051. So, you can freely remove the `MocksTest.kt` file (if you're fine with that) 🙂 

Thank you once again 🙇

**Comment by hichamboushaba** [comment]
> A small note on the newly added file: the mocksDemo() test was recently created as a temporary measure to make the review of #5032 easier (see this comment). It's not needed in the long term, and it's actually already deleted in the (still draft) #5051. So, you can freely remove the MocksTest.kt file (if you're fine with that) 🙂

Thanks @pachlava, I'll remove the file, and please, if you find that having a single test per file is too limiting, let me know, there are some solutions that we can try.

**Comment by pachlava** [comment]
> and please, if you find that having a single test per file is too limiting, let me know, there are some solutions that we can try.

Thank you, @hichamboushaba, so far we are not hitting this limit yet, but I'll keep this is mind and will let you know as soon as this happens 🙂

**Review by designsimply — APPROVED** [review]
Tested and confirmed the app no longer crashes when accessing the Products page while running these tests. Thank you @hichamboushaba!

**Pull request merged**
