### PR TITLE
Merge 11.1-rc-2 to trunk

### PR DESCRIPTION
**Pull request by oguzkocer**
Includes the fixes from #7756, #7763 & #7764.

---

There were 3 conflicts due to changes from #7756 & #7732:

```
Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt
	both modified:   WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
	both modified:   WooCommerce/src/main/res/navigation/nav_graph_main.xml
```

For all conflicts, I opted for the `original/trunk` version first and then removed the `source` parameter. @0nko @JorgeMucientes It looks like you have cooperated on these 2 PRs. Can I ask one of you to re-create the merge in another local branch, resolve it and compare the result to this branch? In case it's helpful, here are the commands I'd use to do this:

(**UPDATE:** I originally missed the removal of the `source` parameter in `SitePickerFragment.navigateToStoreCreation` which I addressed in fac50df300741ad638f90d2633596b77ccbfd928.)

```
git fetch
git checkout -b test-merge/11.1-rc-2-to-trunk release/11.1
git merge origin/trunk
// resolve conflicts
git diff origin/merge/11.1-rc-2-to-trunk
```

Here is the full list of conflicts:
```
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt
index 5ae5ec96cc..3d40c9124c 100644
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt
@@ -28,11 +28,15 @@ class AddStoreBottomSheetFragment : WCBottomSheetDialogFragment(R.layout.dialog_
                     AddStoreBottomSheetFragmentDirections.actionAddStoreBottomSheetFragmentToStoreCreationNativeFlow()
                 else ->
                     AddStoreBottomSheetFragmentDirections
-                        .actionAddStoreBottomSheetFragmentToWebViewStoreCreationFragment()
+                        .actionAddStoreBottomSheetFragmentToWebViewStoreCreationFragment(navArgs.source)
             }
             findNavController().navigateSafely(
+<<<<<<< HEAD
                 directions = AddStoreBottomSheetFragmentDirections
                     .actionAddStoreBottomSheetFragmentToWebViewStoreCreationFragment(),
+=======
+                directions = directions,
+>>>>>>> origin/trunk
                 navOptions = NavOptions.Builder()
                     .setPopUpTo(R.id.sitePickerFragment, false)
                     .build()
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
index d03415f827..0c8e0ff874 100644
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/SitePickerFragment.kt
@@ -269,6 +269,11 @@ class SitePickerFragment : BaseFragment(R.layout.fragment_site_picker), LoginEma
             .navigateSafely(SitePickerFragmentDirections.actionSitePickerFragmentToAddStoreBottomSheetFragment())
     }
 
+<<<<<<< HEAD
+    private fun navigateToStoreCreation() {
+        findNavController()
+            .navigateSafely(SitePickerFragmentDirections.actionSitePickerFragmentToWebViewStoreCreationFragment())
+=======
     private fun navigateToStoreCreation(source: String) {
         when {
             FeatureFlag.NATIVE_STORE_CREATION_FLOW.isEnabled() -> findNavController().navigateSafely(
@@ -276,9 +281,10 @@ class SitePickerFragment : BaseFragment(R.layout.fragment_site_picker), LoginEma
             )
             else -> findNavController()
                 .navigateSafely(
-                    SitePickerFragmentDirections.actionSitePickerFragmentToWebViewStoreCreationFragment()
+                    SitePickerFragmentDirections.actionSitePickerFragmentToWebViewStoreCreationFragment(source)
                 )
         }
+>>>>>>> origin/trunk
     }
 
     private fun navigateToHelpScreen(origin: HelpActivity.Origin) {
diff --git a/WooCommerce/src/main/res/navigation/nav_graph_main.xml b/WooCommerce/src/main/res/navigation/nav_graph_main.xml
index ca41f13b7f..fb3eddf12f 100644
--- a/WooCommerce/src/main/res/navigation/nav_graph_main.xml
+++ b/WooCommerce/src/main/res/navigation/nav_graph_main.xml
@@ -485,7 +485,13 @@
     <fragment
         android:id="@+id/webViewStoreCreationFragment"
         android:name="com.woocommerce.android.ui.login.storecreation.webview.WebViewStoreCreationFragment"
+<<<<<<< HEAD
         android:label="WebViewStoreCreationFragment" />
+=======
+        android:label="WebViewStoreCreationFragment">
+        <argument android:name="source" />
+    </fragment>
+>>>>>>> origin/trunk
     <dialog
         android:id="@+id/addStoreBottomSheetFragment"
         android:name="com.woocommerce.android.ui.sitepicker.AddStoreBottomSheetFragment"
@@ -496,8 +502,12 @@
         <action
             android:id="@+id/action_addStoreBottomSheetFragment_to_webViewStoreCreationFragment"
             app:destination="@id/webViewStoreCreationFragment" />
+<<<<<<< HEAD
+=======
         <action
             android:id="@+id/action_addStoreBottomSheetFragment_to_storeCreationNativeFlow"
             app:destination="@id/nav_graph_store_creation" />
+        <argument android:name="source" />
+>>>>>>> origin/trunk
     </dialog>
 </navigation>
```

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
There are some unit tests failures [in CI](https://buildkite.com/automattic/woocommerce-android/builds/7563#01845fb4-1761-42a4-8fbe-f0e183eecd66) with at least one related to code changed in this PR (the latter with `WebViewStoreCreationViewModel` and `appPrefsWrapper`)

```
[2022-11-10T04:16:28Z] > Task :WooCommerce:compileJalapenoDebugUnitTestKotlin FAILED
[2022-11-10T04:16:28Z] e: /var/lib/buildkite-agent/builds/ci-android-i-06b831a0c8f7f895a-1/automattic/woocommerce-android/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt: (50, 13): Type mismatch: inferred type is StoreCreationRepository but WPComWebViewAuthenticator was expected
[2022-11-10T04:16:28Z] e: /var/lib/buildkite-agent/builds/ci-android-i-06b831a0c8f7f895a-1/automattic/woocommerce-android/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt: (51, 13): Type mismatch: inferred type is WPComWebViewAuthenticator but UserAgent was expected
[2022-11-10T04:16:28Z] e: /var/lib/buildkite-agent/builds/ci-android-i-06b831a0c8f7f895a-1/automattic/woocommerce-android/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt: (52, 13): Type mismatch: inferred type is UserAgent but StoreCreationRepository was expected
[2022-11-10T04:16:28Z] e: /var/lib/buildkite-agent/builds/ci-android-i-06b831a0c8f7f895a-1/automattic/woocommerce-android/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt: (54, 9): No value passed for parameter 'appPrefsWrapper'
```

**Comment by 0nko** [comment]
This is the diff:
```
diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt
index 5ae5ec96cc..fd0059c62d 100644
--- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt
+++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/sitepicker/AddStoreBottomSheetFragment.kt
@@ -31,8 +31,7 @@ class AddStoreBottomSheetFragment : WCBottomSheetDialogFragment(R.layout.dialog_
                         .actionAddStoreBottomSheetFragmentToWebViewStoreCreationFragment()
             }
             findNavController().navigateSafely(
-                directions = AddStoreBottomSheetFragmentDirections
-                    .actionAddStoreBottomSheetFragmentToWebViewStoreCreationFragment(),
+                directions = directions,
                 navOptions = NavOptions.Builder()
                     .setPopUpTo(R.id.sitePickerFragment, false)
                     .build()
diff --git a/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt b/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt
index f31d8eb32c..4c266f94a2 100644
--- a/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt
+++ b/WooCommerce/src/test/kotlin/com/woocommerce/android/ui/login/storecreation/webview/WebViewStoreCreationViewModelTest.kt
@@ -2,6 +2,7 @@ package com.woocommerce.android.ui.login.storecreation.webview
```

I've checked the merge and it looks fine, but as @mokagio mentioned, there were some changes in the tests, too. For simplicity, I've opened a new PR with all conflicts and changes resolved: #7783.

**Comment by oguzkocer** [comment]
The failures seem to be due to the conflicting changes, rather than the git merge conflict resolution.

@0nko Thanks for looking into this. I'll leave feedback to the PR now.

**Comment by oguzkocer** [comment]
@0nko @mokagio There was a new conflict after merging #7783 in `WooCommerce/src/main/res/navigation/nav_graph_main.xml`. This is due to #7766 moving some of the contents of `nav_graph_main.xml` to `nav_graph_site_picker.xml`. I've resolved this conflict by removing the source parameter from `nav_graph_site_picker.xml` in 8ea546a8af99bd5b3ab40d6dd985a15ccda73d18.

🤞 All conflicts are resolved now.

**Comment by oguzkocer** [comment]
I addressed one more little issue from the [previous fix](https://github.com/woocommerce/woocommerce-android/pull/7778#issuecomment-1311021160) in f42110cc7f85d5d44f1f01d2d21ee5ac737a3bf0 and it's all green now.

Since this is a blocker for today's code freeze, I'll admin merge this in.

**Pull request merged**
