### PR TITLE
feature/notification-handler-cleanup

### PR DESCRIPTION
**Pull request by anitaa1990**
This PR is the result of #4624 , #4625 , #4628 , #4630 , #4633 , #4635. All the PRs have already been reviewed and fixes part of #4525 .  

### Description
The focus of this PR is to clean up `NotificationHandler` to better unit test the code and to also pave way to support push notifications for all stores project. The changes include:
- Migrate `WooChannelType` to it's own class.
- Migrate `NotificationChannelType` from `NotificationHandler` to it's own class.
- Deleted unused methods from `NotificationModelExt`.
- Deleted unused class `NotificationHelper`.
- Creating a new app model `Notification`. This is helpful in capturing all the data needed to display the notification, without having to parse fields like `site_id`, `order_id`, `comment_id` etc from `NotificationModel` every time.
- Added a new `WooNotificationBuilder` class. This includes all `NotificationCompat`, `Notification.Builder` related methods that needs a `Context`. I separated those methods so that we can unit tests most of the logic in `NotificationHandler`.
- Adding a new `NotificationMessageHandler` class - contains all the logic related to notification display.
- Adds a new `NotificationAnalyticsTracker` class - wrapper class that contains logic related to sending analytic events for notifications.
- Added helper methods to `AnalyticsTrackerWrapper`, `PreferencesWrapper`, `WooLogWrapper` and `AppPrefsWrapper`.
- Added unit tests for `NotificationMessageHandler`.
- Updated `FCMMessageService` to use `NotificationMessageHandler`.
- Updated `NotificationsProcessingService` to use the injectable `NotificationMessageHandler`.
- Added a new `MainActivityViewModel` class along with unit tests - handles click logic of notifications.
- Updated `MainActivity` to use `MainActivityViewModel`.
- Deleted a bunch of unused code :) 

### Testing instructions
I apologise in advance for the list of testing scenarios in this PR 😬 

#### Reviews
- Create a review from your test store. 
	- Verify that the notification is displayed correctly in the notification tray. 
	- Clicking on a single review notification should open the review detail screen.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 reviews from your test store (for the same product or multiple products). 
	- Verify that the notifications are displayed correctly in the notification tray. 
	- Click on one of  the review notifications and it should open the review detail screen for that specific review.
	- Click on the other review notifications when the app is open and it should open the review detail screen for that specific review.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more reviews or more from your test store (for the same product or multiple products).
	- Don't expand the notification but click on them as a group. 
	- Clicking on 2 review notifications should open the review list screen.
	- Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more reviews from your test store (for the same product or multiple products). 
	- Expand the notifications from the notification tray. 
	- Dismiss one of the notifications and verify that it is dismissed correctly.
- Create 2 or more reviews from your test store (for the same product or multiple products). 
	- Do not expand the notifications from the notification tray. 
	- Dismiss the group of notifications from the notifications tray. 
	- Verify that it is dismissed correctly. 

#### Orders
- Create an order from your test store. 
	- Verify that the notification is displayed correctly in the notification tray. 
	- Clicking on a single order notification should open the order detail screen.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 orders from your test store. 
	- Verify that the notifications are displayed correctly in the notification tray. 
	- Click on one of the order notifications and it should open the order detail screen for that specific order.
	- Click on the other order notification when the app is open and it should open the order detail screen for that specific order.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more orders or more from your test store.
	- Don't expand the notification but click on them as a group. 
	- Clicking on 2 order notifications should open the order list screen.
	- Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more orders from your test store. 
	- Expand the notifications from the notification tray. 
	- Dismiss one of the notifications and verify that it is dismissed correctly.
- Create 2 or more orders from your test store. 
	- Do not expand the notifications from the notification tray. 
	- Dismiss the group of notifications from the notifications tray. 
	- Verify that it is dismissed correctly.

#### Orders + Reviews
- Create an order and a review from your test store. 
	- Verify that the notifications is displayed correctly in the notification tray. The order and review notification should be displayed in separately.
	- Clicking on a single order notification should open the order detail screen.
	- Clicking on a single review notification should open the review detail screen.
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 orders + 2 reviews from your test store. 
	- Verify that the notifications are displayed correctly in the notification tray. The order and review notification should be displayed in separately. 
	- Clicking on each of the order notifications separately should open the order detail screen.
	- Clicking on each of the review notifications separately should open the review detail screen.	
	- Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more orders + 2 or more reviews from your test store.
	- Don't expand the notification but click on the order notifications as a group. 
	- Clicking on 2 order notifications should open the order list screen.
	- Click on the review notifications as aa group and it should open the review list screen.
	- Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more orders + 2 or more reviews from your test store. 
	- Expand the notifications from the notification tray. 
	- Dismiss one of the order notifications and verify that it is dismissed correctly.
	- Dismiss one of the review notifications and verify that it is dismissed correctly.
- Create 2 or more orders + 2 or more reviews from your test store. 
	- Do not expand the notifications from the notification tray. 
	- Dismiss the group of order notifications from the notifications tray and verify that it is dismissed correctly.
	- Dismiss the group of review notifications from the notifications tray and verify that it is dismissed correctly.	

#### Zendesk notifications
- Open a ticket from the app to Zendesk.
- Open the ticket on Zendesk and reply to it.
- Verify that the notification is displayed in the app correctly.
- Clicking on the notification should open the tickets page correctly.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hafizrahman** [comment]
@anitaa1990 Just to clarify:

> All the PRs have already been reviewed

So the code doesn't need to be checked anymore, and we just need to go through the test instructions?

**Comment by anitaa1990** [comment]
@hafizrahman, yup the test scenarios working as expected is what is key 😄

**Comment by hafizrahman** [comment]
Making a checklist: 

#### Reviews
- Create a review from your test store. 
	- [x] Verify that the notification is displayed correctly in the notification tray. 
	- [x] Clicking on a single review notification should open the review detail screen.
	- [x] Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 reviews from your test store (for the same product or multiple products). 
	- [x] Verify that the notifications are displayed correctly in the notification tray. 
	- [x] Click on one of  the review notifications and it should open the review detail screen for that specific review.
	- [x] Click on the other review notifications when the app is open and it should open the review detail screen for that specific review.
	- [x] Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more reviews or more from your test store (for the same product or multiple products).
	- [x] Don't expand the notification but click on them as a group. 
	- [x] Clicking on 2 review notifications should open the review list screen.
	- [x] Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more reviews from your test store (for the same product or multiple products). 
	- [ ] Expand the notifications from the notification tray. 
	- [ ] Dismiss one of the notifications and verify that it is dismissed correctly.
- Create 2 or more reviews from your test store (for the same product or multiple products). 
	- [ ] Do not expand the notifications from the notification tray. 
	- [ ] Dismiss the group of notifications from the notifications tray. 
	- [ ] Verify that it is dismissed correctly. 

#### Orders
- Create an order from your test store. 
	- [x] Verify that the notification is displayed correctly in the notification tray. 
	- [x] Clicking on a single order notification should open the order detail screen.
	- [x] Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 orders from your test store. 
	- [x] Verify that the notifications are displayed correctly in the notification tray. 
	- [x] Click on one of the order notifications and it should open the order detail screen for that specific order.
	- [x] Click on the other order notification when the app is open and it should open the order detail screen for that specific order.
	- [x] Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more orders or more from your test store.
	- [x] Don't expand the notification but click on them as a group. 
	- [x] Clicking on 2 order notifications should open the order list screen.
	- [x] Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more orders from your test store. 
	- [x] Expand the notifications from the notification tray. 
	- [x] Dismiss one of the notifications and verify that it is dismissed correctly.
- Create 2 or more orders from your test store. 
	- [x] Do not expand the notifications from the notification tray. 
	- [x] Dismiss the group of notifications from the notifications tray. 
	- [x] Verify that it is dismissed correctly.

#### Orders + Reviews
- Create an order and a review from your test store. 
	- [x] Verify that the notifications is displayed correctly in the notification tray. The order and review notification should be displayed in separately.
	- [x] Clicking on a single order notification should open the order detail screen.
	- [x] Clicking on a single review notification should open the review detail screen.
	- [x] Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 orders + 2 reviews from your test store. 
	- [x] Verify that the notifications are displayed correctly in the notification tray. The order and review notification should be displayed in separately. 
	- [x] Clicking on each of the order notifications separately should open the order detail screen.
	- [x] Clicking on each of the review notifications separately should open the review detail screen.	
	- [x] Verify that the correct analytics event is sent when a notification is received and clicked.
- Create 2 or more orders + 2 or more reviews from your test store.
	- [x] Don't expand the notification but click on the order notifications as a group. 
	- [x] Clicking on 2 order notifications should open the order list screen.
	- [x] Click on the review notifications as aa group and it should open the review list screen.
	- [x] Verify that the correct analytics event is sent for each of the notifications in the group.
- Create 2 or more orders + 2 or more reviews from your test store. 
	- [x] Expand the notifications from the notification tray. 
	- [x] Dismiss one of the order notifications and verify that it is dismissed correctly.
	- [x] Dismiss one of the review notifications and verify that it is dismissed correctly.
- Create 2 or more orders + 2 or more reviews from your test store. 
	- [x] Do not expand the notifications from the notification tray. 
	- [x] Dismiss the group of order notifications from the notifications tray and verify that it is dismissed correctly.
	- [x] Dismiss the group of review notifications from the notifications tray and verify that it is dismissed correctly.	

#### Zendesk notifications
- [x] Open a ticket from the app to Zendesk.
- [x] Open the ticket on Zendesk and reply to it.
- [x] Verify that the notification is displayed in the app correctly.
- [ ] Clicking on the notification should open the tickets page correctly.

**Comment by hafizrahman** [comment]
@anitaa1990 Tested everything and they all work fine aside from this last item:

>  Clicking on the notification should open the tickets page correctly.

This opens to the stats screen instead:

https://user-images.githubusercontent.com/266376/130923845-1d3f7050-b087-427e-8f36-014f8a060dd3.mp4

(also thanks to @retnonindya for helping answering the test tickets, because my ZD account can't reply to tickets anymore)

I tested in the release version and the notification does open to tickets screen properly.

**Comment by anitaa1990** [comment]
Thank you for the review @hafizrahman! Since it works in the release build, do you think it's fine to merge this PR?

**Comment by hafizrahman** [comment]
Still seeing the issue with support notification, I'm afraid.

Did a bit of debugging and here in MainActivityViewModel:
```
    fun handleIncomingNotification(localPushId: Int, notification: Notification?) {
        notification?.let {
            when (localPushId) {
                it.channelType.getGroupId() -> onGroupMessageOpened(it.channelType)
                it.noteId -> onZendeskNotificationOpened(localPushId, it.noteId.toLong())
                else -> onSingleNotificationOpened(localPushId, it)
            }
        } ?: run {
            triggerEvent(ViewMyStoreStats)
        }
    }
```
the passed notification parameter is null so it just goes to `triggerEvent(ViewMyStoreStats)`.
In my test for `viewModel.handleIncomingNotification(localPushId, notification)` in the MainActivity, the value of `localPushId` is 1999999999 while `notification` is null.

**Comment by hafizrahman** [comment]
After some discussion in Slack, we decided to go through with this PR, and will log and work on the support notification issue separately. There's incoming changes to support notification for all stores, and it might be more ideal to fix it there instead.

:shipit: for this PR, thanks for the huge amount of work here @anitaa1990!

**Review by hafizrahman — APPROVED** [review]

**Pull request merged**
