### PR TITLE
Bump stripe terminal sdk version

### LINKED ISSUE #4288: [Card Present Payments] The sdk keeps being connected to the reader when bluetooth is disabled
To reproduce go to:
* Settings
* Manager Reader 
* Connect to a reader
* Turn off Bluetooth

Notice that a connected state is presented and the disconnect button does do anything

### PR DESCRIPTION
**Pull request by malinajirka**
Fixes #4288

This PR updates Stripe Terminal SDK version from 1.0.18 to 1.0.22 (version 1.0.19-1.0.21 do not exist)

[The official release notes](https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md) for 1.0.22 mention that the only change is an update of vendor SDK (I assume card reader vendor). The new version of the vendor SDK fixes some issues - eg. onUnexpectedDisconnect wasn't being emitted when the user turned off bluetooth while connected to a reader -> the SDK remained in "connected" state.

To test:
1. Open app settings
2. Tap on "Manage Card Reader"
3. Connect to a hw reader
4. Wait until connected state is shown
5. Turn off bluetooth and notice you get automatically redirected to the "not connected" screen

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by kidinov** [comment]
I've noticed an interesting thing, which might be a separate issue though. Try:

* Click connect to the reader
* During connection turn off bluetooth
* Notice "We could not connect your reader"
* Turn on Bluetooth
* Click try again
Notice that it won't work and there is a log:

```
W/StripeTerminal: UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR: Unexpected operation in progress. Expected: class com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$DiscoverReadersOperation, found: class com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$DisconnectReaderOperation
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.adapter.Adapter.verifyOperationInProgress(Adapter.kt:109)
        at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter.cancelDiscoverReaders$terminalsdk_release(BbposBluetoothAdapter.kt:74)
        at com.stripe.stripeterminal.adapter.MasterAdapter.cancelDiscoverReaders$terminalsdk_release(MasterAdapter.kt:33)
        at com.stripe.stripeterminal.TerminalSession.connectReader(TerminalSession.kt:111)
        at com.stripe.stripeterminal.Terminal.connectReader(Terminal.kt:180)
        at com.woocommerce.android.cardreader.internal.wrappers.TerminalWrapper.connectToReader(TerminalWrapper.kt:45)
        at com.woocommerce.android.cardreader.internal.connection.ConnectionManager.connectToReader(ConnectionManager.kt:54)
        at com.woocommerce.android.cardreader.internal.CardReaderManagerImpl.connectToReader(CardReaderManagerImpl.kt:81)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel$onConnectToReaderClicked$2.invokeSuspend(CardReaderConnectViewModel.kt:242)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:349)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel.onConnectToReaderClicked(CardReaderConnectViewModel.kt:241)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel.access$onConnectToReaderClicked(CardReaderConnectViewModel.kt:56)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel$onConnectToReaderClicked$2$1.invoke(CardReaderConnectViewModel.kt:249)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectViewModel$onConnectToReaderClicked$2$1.invoke(CardReaderConnectViewModel.kt:56)
        at com.woocommerce.android.ui.prefs.cardreader.connect.CardReaderConnectFragment$observeState$1$1.onClick(CardReaderConnectFragment.kt:101)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

But it WILL work if you restart the flow (close the dialog) completely. So it looks like that we don't clean something properly when we restart the flow with "try again" button

**Review by kidinov — CHANGES_REQUESTED** [review]
Please check my comment. Probably merge this and create an issue or what do you think?

**Comment by malinajirka** [comment]
> I've noticed an interesting thing, which might be a separate issue though.

I was able to get the SDK and the OS into all kind of weird states when I turn off bluetooth during connection - I was even able to hit "retry" and connect to a reader when BT was disabled in the OS. 
Tbh I don't think we'll be able to fix these issues and most importantly I don't think it's worth our time. In my experience even different bluetooth modules behave differently - it's so weird that there are differences even in the same line of product eg. Samsung S10 has at least 3 different BT chips with inconsistent behavior.
I wouldn't worry about them unless merchants start experiencing them. If someone turns off bluetooth while connecting to a BT device I don't think they'll be surprised that they are having troubles connecting and perhaps even get the app into a weird state. Wdyt?

> But it WILL work if you restart the flow (close the dialog) completely. 

Isn't it just a matter of timing/race condition - from the log it seems the SDK is still in the process of disconnecting when you hit retry? Did you try to wait for a bit and hit retry after lets say 5 seconds? Can you reproduce the issue? I encountered a few other issues but none of them behaved as per your comment.

**Comment by malinajirka** [comment]
So I was able to replicate the log you are seeing after all, but the operation succeeded without issues - the SDK just logged this state as "unexpected" into the log. My overall opinion about these edge cases stands - imho it's not worth fixing.

**Comment by kidinov** [comment]
@malinajirka 

> Isn't it just a matter of timing/race condition - from the log it seems the SDK is still in the process of disconnecting when you hit retry? Did you try to wait for a bit and hit retry after lets say 5 seconds? Can you reproduce the issue?

That's the thing, that I can reproduce it every time, and I can wait a minute or more and click "try again" still doesn't work. At the same time closing the dialog and starting the connection flow makes it work as expected right away.
I've recorded a video to make sure that we are on the same page:

https://user-images.githubusercontent.com/4923871/123926229-5aff4c80-d994-11eb-86ba-12c7d1f6eda9.mp4

To me it looks more like a state issue somewhere in our implementation than a Bluetooth stack, otherwise why closing our dialog (and killing view model) fixes it right away? In any case, lets merge it, Ill create an issue and if it;s not a problem we will just close it

**Review by kidinov — APPROVED** [review]

**Comment by malinajirka** [comment]
@kidinov Interesting, it doesn't behave this way on my phone :) - but I agree this looks like a bug in our implementation! Thanks for creating an issue 🙇

**Comment by malinajirka** [comment]
@kidinov Actually, I might know the answer -> we are caching the Reader object for "retry" -> it apparently doesn't work on your phone. So I think the easiest fix is to start the whole connection flow from start on retry. The user will need to pick the reader again, but a good thing will be that we'll run all the bluetooth/location checks again. Wdyt?

**Comment by kidinov** [comment]
@malinajirka lets see if the issue still there with the SDK 2.0 and then come up with the solution if needed

**Pull request merged**
