### PR TITLE
UL: Merge updates from the Login Library

### PR DESCRIPTION
**Pull request by AmandaRiu**
This PR updates the login library code with [changes from WPAndroid merged in this PR](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/45). Minimum tweaks have been made to comply with the changes from WPAndroid without changing the functionality of the WCAndroid login flow so there shouldn't be any visible changes except for the one below.

While smoke testing I found the verbiage on one of the screens did not reflect the designs and since it was a small tweak I included it in this PR:

Before | After
-- | --
Screenshot_1602278918|Screenshot_1602279148

 

### To Test
Test logging in with magic link as well as with password.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@AmandaRiu The wording here seems awkward to me. How about, "Log in to WordPress.com using your email address" or "Enter the email address you use to log in to WordPress.com"?

Screenshot_1602331655

**Comment by nbradbury** [comment]
@AmandaRiu As an update on this, the text recommended by @Garance91540 in #2985 is, "Log in with your WordPress.com account email address to manage your WooCommerce stores." This PR omits the "your."

**Comment by AmandaRiu** [comment]
@nbradbury Thanks for the review! I've updated the string. Ready for another round:

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
