### PR TITLE
Correct the file locations of promo texts in screenshots.json

### PR DESCRIPTION
**Pull request by irfano**
Closes: woocommerce/woomobile-private#393

### Description

This fixes incorrect file locations for promo texts in `screenshots.json`. `bundle exec fastlane download_promo_strings` command downloads promo texts in `metadata/android/{locale}/promo_screenshot_5.txt`.

### Testing information

Follow Android Screenshots instructions (P91TBi-8Pt-p2) to test generating promo screenshots.

### The tests that have been performed

Generating promo screenshots with `bundle exec fastlane create_promo_screenshot locales:en-US`

### Images/gif

image

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by JorgeMucientes** [comment]
Hey @irfano code changes look good but I'm unable to run the screenshot command successfully. 

I get the following error all the time: 
```
[16:34:05]: Called from Fastfile at line 930
[16:34:05]: ```
[16:34:05]:     928:          UI.error(e)
[16:34:05]:     929:        end
[16:34:05]:  => 930:        screengrab(
[16:34:05]:     931:          screenshot_options.merge(
[16:34:05]:     932:            {
[16:34:05]: ```
[16:34:05]: Tests failed for locale en-US on device emulator-5560
```

Some screenshot test is broken (although if I run screenshot test from AS they run just fine) 

```
[16:32:38]: ▸ com.woocommerce.android.e2e.tests.screenshot.ScreenshotTest:s_glBindAttribLocation: bind attrib 0 name position
[16:32:38]: ▸ s_glBindAttribLocation: bind attrib 1 name color
[16:32:38]: ▸ s_glBindAttribLocation: bind attrib 2 name localCoord
[16:34:05]: ▸ Error in screenshots(com.woocommerce.android.e2e.tests.screenshot.ScreenshotTest):
[16:34:05]: ▸ java.lang.AssertionError: Unable to continue – expectation wasn't satisfied quickly enough
[16:34:05]: ▸   at org.junit.Assert.fail(Assert.java:89)
[16:34:05]: ▸   at com.woocommerce.android.e2e.helpers.util.TestIdler.idleUntilReady(TestIdler.kt:43)
[16:34:05]: ▸   at com.woocommerce.android.e2e.helpers.util.TestIdler.idleUntilReady(TestIdler.kt:33)
[16:34:05]: ▸   at com.woocommerce.android.e2e.helpers.util.Screen.waitForConditionToBeTrue(Screen.kt:475)
[16:34:05]: ▸   at com.woocommerce.android.e2e.helpers.util.Screen.waitForElementToBeDisplayed(Screen.kt:404)
[16:34:05]: ▸   at com.woocommerce.android.e2e.helpers.util.Screen.<init>(Screen.kt:66)
[16:34:05]: ▸   at com.woocommerce.android.e2e.screens.orders.SingleOrderScreen.<init>(SingleOrderScreen.kt:17)
[16:34:05]: ▸   at com.woocommerce.android.e2e.screens.orders.OrderListScreen.selectOrder(OrderListScreen.kt:19)
[16:34:05]: ▸   at com.woocommerce.android.e2e.tests.screenshot.ScreenshotTest.screenshots(ScreenshotTest.kt:127)
[16:34:05]: ▸ Time: 97.599
[16:34:05]: ▸ There was 1 failure:
[16:34:05]: ▸ 1) screenshots(com.woocommerce.android.e2e.tests.screenshot.ScreenshotTest)
[16:34:05]: ▸ java.lang.AssertionError: Unable to continue – expectation wasn't satisfied quickly enough
```

The screenShot test flow always gets stuck at the orders screens:

 


Any idea what could be going on?

**Review by JorgeMucientes — APPROVED** [review]
Don't want to block these changes because I can't run the screenshots generation on my local environment. So I'm approving 👍🏼

**Comment by irfano** [comment]
@JorgeMucientes, the issue was caused by today’s date. The changes I made:
- Order 2201 had a dynamic date of today. I updated it to use a hardcoded date like the others.
- The date headers were dynamic based on the device’s date. To resolve this, I opened the order using the orderId instead of its position.
Jorge, your issue should be resolved now.

**Comment by JorgeMucientes** [comment]
Hey @irfano thanks for making the updates. 

Just letting you know that after updating with the latest changes I'm still facing an error while running `ScreenshotTests`. The error this time seems to be different although is still happening on the order list screen for `OrderListScreen.selectOrder`: 

```
com.woocommerce.android.test/com.woocommerce.android.WooCommerceTestRunner
[07:58:55]: ▸ com.woocommerce.android.e2e.tests.screenshot.ScreenshotTest:s_glBindAttribLocation: bind attrib 0 name position
[07:58:55]: ▸ s_glBindAttribLocation: bind attrib 1 name color
[07:58:55]: ▸ s_glBindAttribLocation: bind attrib 2 name localCoord
[08:00:30]: ▸ Error in screenshots(com.woocommerce.android.e2e.tests.screenshot.ScreenshotTest):
[08:00:30]: ▸ java.lang.AssertionError: Unable to continue – expectation wasn't satisfied quickly enough
[08:00:30]: ▸   at org.junit.Assert.fail(Assert.java:89)
[08:00:30]: ▸   at com.woocommerce.android.e2e.helpers.util.TestIdler.idleUntilReady(TestIdler.kt:43)
[08:00:30]: ▸   at com.woocommerce.android.e2e.helpers.util.TestIdler.idleUntilReady(TestIdler.kt:33)
[08:00:30]: ▸   at com.woocommerce.android.e2e.helpers.util.Screen.waitForConditionToBeTrue(Screen.kt:475)
[08:00:30]: ▸   at com.woocommerce.android.e2e.helpers.util.Screen.waitForElementToBeDisplayed(Screen.kt:404)
[08:00:30]: ▸   at com.woocommerce.android.e2e.helpers.util.Screen.<init>(Screen.kt:66)
[08:00:30]: ▸   at com.woocommerce.android.e2e.screens.orders.SingleOrderScreen.<init>(SingleOrderScreen.kt:18)
[08:00:30]: ▸   at com.woocommerce.android.e2e.screens.orders.OrderListScreen.selectOrder(OrderListScreen.kt:19)
[08:00:30]: ▸   at com.woocommerce.android.e2e.tests.screenshot.ScreenshotTest.screenshots(ScreenshotTest.kt:127)
```

**Comment by irfano** [comment]
Jorge mentioned that it worked on trunk after merging this PR. The issue above might be a temporary problem on his local setup.

**Pull request merged**
