### PR TITLE
Hilt migration: migrate services

### PR DESCRIPTION
**Pull request by hichamboushaba**
Part of #3936, this PR migrates the application's services to Hilt.
I also removed `OrderFetcherModule` because it wasn't doing anything useful.

##### Test ProductImagesService
Test uploading an image from your device.

##### Test FCMRegistrationIntentService
Test push notifications from your store.

##### Test FCMRegistrationIntentService
Check logcat for the message: `Sending FCM token to our remote services` when opening the app.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by wzieba** [comment]
>  I also removed OrderFetcherModule because it wasn't doing anything useful.

+1. Just FYI, early next week I'll be moving `OrderFetcher` to `FluxC` in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2013

**Review by wzieba — APPROVED** [review]
Looks good!

**Review by wzieba — CHANGES_REQUESTED** [review]
Sorry @hichamboushaba , I've approved too early, I didn't yet test the PR. So this is just to remove the approve, I'll test the code and re-approve if I won't find any issues

**Review by wzieba — APPROVED** [review]
✅ Test FCMRegistrationIntentService
✅ Test ProductImagesService
✅ Test FCMRegistrationIntentService

all looks good.

BTW @hichamboushaba do you know the reason why we send FCM token every time we enter the app? Even if the app is only resumed from background or from the locked screen.

**Comment by hichamboushaba** [comment]
> BTW @hichamboushaba do you know the reason why we send FCM token every time we enter the app? Even if the app is only resumed from background or from the locked screen.

Sorry I don't know, this part of code is pretty old I think.
Also we need to update the implementation to remove the usage of deprecated features, there is an `onNewToken` function that delivers the new function directly to the messaging service without using `FirebaseInstanceIdService`.

**Pull request merged**
