### PR TITLE
Merge merge/release-6.0-into-develop into develop

### PR DESCRIPTION
**Pull request by AliSoftware**
Supersedes https://github.com/woocommerce/woocommerce-android/pull/3564 to fix conflicts.

The `fluxCVersion` in `release/6.0` is `1.10.1` but the one in `develop` is `183ed03893318f3d947cf9c3e094b45304ede4e1`.

I initially wrongly fixed the conflict by keeping `develop`, but then realized / decided it would make more sense to make this PR move `develop`'s FluxC to `1.10.1` (which is one commit after of the SHA1), so that `develop` also includes the hotfix after this merge.

### CODE REVIEW

**Review by jkmassel — DISMISSED** [review]
If `1.10.1` has newer changes than that hash, totally makes sense for develop to have the newer version.

LGTM!

**Comment by jkmassel** [comment]
...except for the fact that all the tests appear to be broken now 🤔

**Comment by AliSoftware** [comment]
Ok, so I am re-fixing the conflict the other way, so that we end up keeping `fluxCVersion = '183ed03893318f3d947cf9c3e094b45304ede4e1'` in `develop` after the merge, so that at least it gets fixed.

That mean that once this PR is merged, we will need a code wrangler (\cc @anitaa1990) to do a PR on `develop`, to update `develop`'s FluxC to `1.10.1` … _and_ also do the relevant fixes in the host app's code – to fix [those compilation issues we had on CI when we tried using FluxC 1.10.1 with the code from `develop`](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/9581/workflows/ab9c6426-353f-4cc2-b35f-f020b504e778) – so that those fixes from FluxC's hotfix are ultimately included in the app code and not lost in the next code freeze.

**Review by jkmassel — APPROVED** [review]

**Comment by anitaa1990** [comment]
> That mean that once this PR is merged, we will need a code wrangler (\cc @anitaa1990) to do a PR on develop, to update develop's FluxC to 1.10.1 … and also do the relevant fixes in the host app's code – to fix those compilation issues we had on CI when we tried using FluxC 1.10.1 with the code from develop – so that those fixes from FluxC's hotfix are ultimately included in the app code and not lost in the next code freeze.

I don't know that we'd want to update the fluxC hash to `1.10.1` since it doesn't include a lot of the features that the team has been working on (that is needed for the code to compile). Should we instead just update the FluxC hash to `96c59a96a69f31634198fa4a481b90a0c405ab39` which is the latest hash that includes both the hotfixes from the 1.10.1 release as well as the latest changes from `develop`.

**Comment by AliSoftware** [comment]
Yeah as long as develop is pointing to a commit that includes everything ie including the commits from hotfix 1.10.1 and all the new stuff since, that should be the way to go indeed 👍

**Pull request merged**
