### PR TITLE
[Mobile Payments] Track country and currency on payments flow collect event

### LINKED ISSUE #10527: [Mobile Payments] Track country and currency on "payments_flow_*" events
All the events that need to have country and currency tracking:

* PAYMENTS_FLOW_COLLECT
* PAYMENTS_FLOW_COMPLETED
* PAYMENTS_FLOW_CANCELED
* PAYMENTS_FLOW_FAILED

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10527

### Description

The PR:
* Moves `CardReaderTracking` to the upper payments package
* Renames it to `PaymentsFlowTracker` to reflect it's new purpose
* Moves tracking of the following events in there so it will add properties that we use for other payments-related events:
  * `PAYMENTS_FLOW_COLLECT`
  * `PAYMENTS_FLOW_COMPLETED`
  * `PAYMENTS_FLOW_CANCELED`
  * `PAYMENTS_FLOW_FAILED`

### Testing instructions

* Try both payment flows:
  * Order lists -> create order -> collect payment 
  * More -> payments -> collect payment
* Try starting (collect), completing, canceling or failing the flow
* Using logcat with a "track" filter, notice the events with `currency` and `country` properties in it  (The `canceled` event tracked only when the "back" button is clicked on the payment method selection screen during payment for the order)

```
Tracked: payments_flow_collect, Properties: {"source":"payment_method","order_id":2954,"flow":"simple_payment","payment_method":"card","card_reader_type":"external","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","blog_id":154993204,"is_wpcom_store":false,"was_ecommerce_trial":false,"plan_product_slug":"jetpack_premium","store_id":"3ee2abc7-2ac9-4e18-85ae-714aeb76377a","is_debug":true,"site_url":"https:\/\/site-for-woocommerce12a3fasdf45dfs6789.mystagingwebsite.com"}

Tracked: payments_flow_failed, Properties: {"source":"payment_method","flow":"simple_payment","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","blog_id":154993204,"is_wpcom_store":false,"was_ecommerce_trial":false,"plan_product_slug":"jetpack_premium","store_id":"3ee2abc7-2ac9-4e18-85ae-714aeb76377a","is_debug":true,"site_url":"https:\/\/site-for-woocommerce12a3fasdf45dfs6789.mystagingwebsite.com"}

Tracked: payments_flow_completed, Properties: {"flow":"simple_payment","payment_method":"cash","order_id":2954,"amount":"$1.15","amount_normalized":115,"plugin_slug":"woocommerce-payments","country":"US","currency":"USD","blog_id":154993204,"is_wpcom_store":false,"was_ecommerce_trial":false,"plan_product_slug":"jetpack_premium","store_id":"3ee2abc7-2ac9-4e18-85ae-714aeb76377a","is_debug":true,"site_url":"https:\/\/site-for-woocommerce12a3fasdf45dfs6789.mystagingwebsite.com"}

Tracked: payments_flow_canceled, Properties: {"source":"payment_method","flow":"order_payment","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","blog_id":154993204,"is_wpcom_store":false,"was_ecommerce_trial":false,"plan_product_slug":"jetpack_premium","store_id":"3ee2abc7-2ac9-4e18-85ae-714aeb76377a","is_debug":true,"site_url":"https:\/\/site-for-woocommerce12a3fasdf45dfs6789.mystagingwebsite.com"}
```

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by backwardstruck** [comment]
Finally was able to test now that I am fully set up with my site. Here is what I see:

Collect
```
2024-01-12 16:47:33.313 10436-10436 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: payments_flow_collect, Properties: {"order_id":55,"flow":"order_payment","payment_method":"card","card_reader_type":"external","milliseconds_since_order_add_new":"156667","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
``` 

Completed
```
2024-01-12 16:49:41.736 10436-10436 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: payments_flow_completed, Properties: {"flow":"order_payment","payment_method":"card","order_id":55,"amount":"$70.00","amount_normalized":7000,"plugin_slug":"woocommerce-payments","country":"US","currency":"USD","payment_method_type":"card","card_reader_model":"WISEPAD_3","card_reader_battery_level":"85 %","blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
```

Failed
```
2024-01-12 16:53:12.840 10436-10436 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: payments_flow_failed, Properties: {"source":"payment_method","flow":"simple_payment","plugin_slug":"woocommerce-payments","country":"US","currency":"USD","payment_method_type":"card","card_reader_model":"COTS_DEVICE","card_reader_battery_level":"85 %","blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
```

Cancelled:

```
2024-01-12 16:53:51.940 10436-10436 WooCommerce-UTILS       com.woocommerce.android.dev          I  🔵 Tracked: payments_flow_canceled, Properties: {"flow":"simple_payment","blog_id":227901557,"is_wpcom_store":true,"was_ecommerce_trial":true,"plan_product_slug":"wooexpress-medium-bundle-monthly","store_id":"a734d3ec-5525-43cf-b9e9-b4c015746c0e","is_debug":true,"site_url":"http:\/\/woo-totally-selfless-bear.wpcomstaging.com"}
```

I see country and currency for each, except for "Cancelled", as expected.

**Review by backwardstruck — APPROVED** [review]
I didn't find any code issues in my review.

**Comment by kidinov** [comment]
@backwardstruck 👋

Thank you for the review!

> I see country and currency for each, except for "Cancelled", as expected.

That's actually a bug you found =). The event itself is supposed to be tracked with the condition, but when tracked, the properties have to be there

> The canceled event tracked only when the "back" button is clicked on the payment method selection screen during payment for the order

I missed that the "Simple Payments" also uses the same events 🤦‍♂️ and already started to fix that, but then realised that we remove this flow soon anyway so not worth the effort 

pecCkj-1mt-p2

**Comment by backwardstruck** [comment]
Glad I could help. Thanks for the clarification.

**Pull request merged**
