### PR TITLE
Product creation using package photo: Title & description generation

### PR DESCRIPTION
**Pull request by 0nko**
This PR adds the product title and description generation using the scanned keywords from a package photo. 

**To test:**
1. Go to Products
2. Tap on + FAB
3. Select the AI option
4. Tap on Use package photo button
5. Use the media library to select a picture of a product with some text
6. Notice the image is loaded and a list of keywords from the image is displayed
7. Notice the loading state is shown and the keywords section is disabled
8. Notice that after a few moments, the product title and description is shown
9. Try unchecking all the keywords
10. Notice the Regenerate button gets disabled
11. Repeat steps 5-7 with an image that contains no text
12. Notice a message is shown that informs the user that no text was found

### CODE REVIEW

**Comment by thaheem110** [comment]
Hi!
I’m currently working on a website[ vehicle tracking company in the UAE](https://althurayauae.com/), and I’m looking for a way to implement an “Add to Cart” feature for our services and products without using WooCommerce. I want to have a simple cart system that allows users to select services or products and then proceed to checkout.
How can i do it ?

**Comment by hichamboushaba** [comment]
> Hi!
> I’m currently working on a website[ vehicle tracking company in the UAE](https://althurayauae.com/), and I’m looking for a way to implement an “Add to Cart” feature for our services and products without using WooCommerce. I want to have a simple cart system that allows users to select services or products and then proceed to checkout.
> How can i do it ?

Sorry @thaheem110, our work here is related just to the mobile app, if you have a WooCommerce question, you can ask in the [support forums](https://wordpress.org/support/plugin/woocommerce/).

**Review by hichamboushaba — APPROVED** [review]
Nice work @0nko, code looks good, and works well.

**Comment by hichamboushaba** [comment]
@0nko I'm not sure if this should be merged now, so I'll leave it to you.

**Pull request merged**
