### PR TITLE
Move secrets other than .properties outside of the repository

### PR DESCRIPTION
**Pull request by mokagio**
Counter part to https://github.com/wordpress-mobile/WordPress-Android/pull/14995.

Moves the low-hanging fruits in terms of secrets outside of the repository:

- Fastlane's `google-upload-cerdentials.json`
- The debug keystore

## To test

Checkout this branch and run `bundle exec fastlane run configure_apply`, then `ls ~/.configure/woocommerce-android/secrets`, you should see:

```
➜ ls ~/.configure/woocommerce-android/secrets

debug_a8c.keystore             google-upload-credentials.json
```

Also ensure that `debugStoreFile` in the local `gradle.properties` has been updated to the new path from `~/.configure/woocommerce-android/secrets/`.

**Individual tests**

`debug_a8c.keystore`: This file is used to sign the debug build, which is something CI does. We can verify it works locally by applying the following patch:

```diff
--- a/WooCommerce/build.gradle
+++ b/WooCommerce/build.gradle
@@ -387,7 +387,7 @@ if (["uploadStoreFile", "uploadStorePassword", "uploadKeyAlias", "uploadKeyPassw
 
 if (project.hasProperty("debugStoreFile")) {
     def sharedDebugStore = file(project.debugStoreFile.replaceFirst("^~", System.getProperty("user.home")))
-    if (sharedDebugStore.exists()) {
         android {
             signingConfigs {
                 debug {
@@ -395,7 +395,7 @@ if (project.hasProperty("debugStoreFile")) {
                 }
             }
         }
-    }
 }
 
 // Keep this at the bottom (https://stackoverflow.com/a/37565535)
```

After the patch, you should run `./gradlew configureApply` to ensure the gradle.properties local secret is updated. Then remove the keystore with `rm ~/.configure/woocommerce-android/secrets/debug_a8c.keystore`. Finally, run `./gradlew assembleDebug` this should fail because the keystore can't be found and ensure that the repo configuration reads the keystore from the new location. Run `./gradlew configureApply` to restore the secret and `./gradlew assembleDebug` should now pass.

`google-upload-credentials.json`: This file is used by the `upload_to_play_store` Fastlane action. I checked the action [documentation](https://docs.fastlane.tools/actions/upload_to_play_store/) and couldn't find a way to perform a dry-run. I saw there is a `validate_only` option, but the documentation says "Only validate changes with Google Play rather than actually publish," which doesn't make it clear to me whether data would be uploaded or not. I'm not familiar with the upload steps in this repo and would like to avoid uploading stuff accidentally.

@jkmassel let me know if you'd be up to update this PR to be against `release/7.2` to validate the changes sooner and I'll make the switch (or you can do it, if you want).

### CODE REVIEW

**Comment by AliSoftware** [comment]
> `debug_a8c.keystore`: As far as I can see, the debug keystore is only used in CI?

It's also present in `gradle.properties` (`debugStoreFile=…`), so that the developers can use it locally during development. And even though that file is ignored (and that entry is not present in `gradle.properties-example` either), changing its location will require the developers to update their own `gradle.properties`, and/or (better) run `configureApply` and expect that location in the `gradle.properties` from Mobile Secrets has the updated path too.

---

[EDIT] Oh but looking at commit `eed37c9c53eddc3993181c3f463ae5740bbd7996` (hash you used the `.configure` file of this PR) you properly took care of that too, so this should also work locally for devs doing debugging (not just on CI) 🎉 👍 

> Checkout this branch and run bundle exec fastlane run configure_apply, then ls ~/.configure/woocommerce-android/secrets, you should see:

Probably thus worth suggesting to also check that the `gradle.properties` files also got updated after `configure_apply`, to include changes to those new paths 😉

**Comment by mokagio** [comment]
> Probably thus worth suggesting to also check that the `gradle.properties` files also got updated after `configure_apply`, to include changes to those new paths 😉 

Good point. Too much copy pasta on my end. 👍 

Does this mean you're happy for the PR to be merged, @AliSoftware?

**Comment by mokagio** [comment]
> Also ensure that `debugStoreFile` in the local `gradle.properties` has been updated to the new path from `~/.configure/woocommerce-android/secrets/`.

I don't see the value in keeping this configured in a secret file, when the location is easily already specified in clear in `.configure` 🤔

I understand we might want the ability for individual developers to override the path, but that seems a different requirement than this.

@oguzkocer do you know why this is configured the way it is? Is my assessment is correct or am I missing something important? Thanks.

**Comment by AliSoftware** [comment]
> Does this mean you're happy for the PR to be merged, @AliSoftware?

Yep, looks good to me now that I've confirmed that the `gradle.properties` file was changed in mobile-secrets as expected 👍  :shipit: 

> I don't see the value in keeping this configured in a secret file, when the location is easily already specified in clear in .configure 🤔

@mokagio I agree that there's probably no point in keeping that particular key secret, it's just that it happens to be defined in the `gradle.properties` and that file has to be secret because it contains _other_ keys which do need to be kept secret.
Maybe we could split the `gradle.properties` in 2 to separate the secret values (like API keys and all) from the non-secret ones (like the debug keystore, but also others non-secret values as it's not the only one in that case), and only put in the mobile-secrets the secret ones. I'm not convinced that it's worth the trouble though.

Especially, for contributors that are outside of a8c, and who use the `gradle.properties-example` as a basis as they don't have access to mobile-secrets, they should not use the debug keystore either (which is why that one is secret too), and for those people it wouldn't make sense to have the debug keystore path set in a non-encrypted `.properties` file as they won't have the debug keystore file either. So my understanding is it's not really about keeping the _path_ to that file secret, but more about only declaring it for a12s who use mobile-secrets and use that debug keystore, but not declaring it for OSS, non-a12s contributors who don't use it (and might get an error if the path is declared while the file doesn't exist for them?)

**Review by AliSoftware — APPROVED** [review]

**Comment by mokagio** [comment]
Thanks @AliSoftware. 

> for those people [external contributors] it wouldn't make sense to have the debug keystore path set in a non-encrypted `.properties` file as they won't have the debug keystore file either.

I see your point. At the same time, `build.gradle` already performs a check to only set the keystore if the file is found:

https://github.com/woocommerce/woocommerce-android/blob/54614a69f7345d47d9c2e4de0c1b102dfbaebf7a/WooCommerce/build.gradle#L388-L399

Nothing stops a contributor from setting the `debugStoreFile` key in the `gradle.properties` (it's [currently missing](https://github.com/woocommerce/woocommerce-android/blob/54614a69f7345d47d9c2e4de0c1b102dfbaebf7a/gradle.properties-example), which I assume is intentional and makes sense in the context of the discussion we are having) to point to their own keystore. That's sort of the same as creating a keystore at the hardcoded path they would read in the configuration.

But, I might be bike shedding too much right now. Definitely a minor thing, I don't see it biting us in the future, so we can live with it till we really have a need to address it. 👍

**Comment by oguzkocer** [comment]
> @mokagio I agree that there's probably no point in keeping that particular key secret, it's just that it happens to be defined in the gradle.properties and that file has to be secret because it contains other keys which do need to be kept secret.

I haven't worked on that setup, but I agree with @AliSoftware's assessment.

> Maybe we could split the gradle.properties in 2 to separate the secret values (like API keys and all) from the non-secret ones (like the debug keystore, but also others non-secret values as it's not the only one in that case), and only put in the mobile-secrets the secret ones. I'm not convinced that it's worth the trouble though.

I am planning to post an RFC about not using `gradle.properties` for secrets, and assuming that request goes through, I think we'll make some changes to this flow. We might still want to keep it all in one file just so that we don't have to copy everything around, or maybe when the actual file is missing (all values are unmodified) we use the `-example` properties file and print out a warning for anyone who wants to update the values. In any case, it's probably best to save this discussion to the RFC post, but I figured sharing the plan would help the discussion in this PR.

**Pull request merged**
