### PR TITLE
Show onboarding error when pending requirements present

### LINKED ISSUE #7229: Make enabled "manage card readers" button when Stripe pending error comes
Currently we keep it disabled, while it possible to connect to a reader and use that

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #7229

### Description

The PR adds a specific error message when stripe pending requirements present

### Testing instructions

* if you have a site with pending requirements then skip 2 and use this site
* Change the code and return `StripeAccountPendingRequirement` from `CardReaderOnboardingChecker::getOnboardingState`
* Go to More -> Payments
* Notice error message
* Notice that all buttons are enabled and clickable
* Click on the error message and notice error screen

### Images/gif

https://user-images.githubusercontent.com/4923871/185558414-10e66c52-6662-40af-a137-56dfd4076d17.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by malinajirka — APPROVED** [review]
LGTM, thank you!

**Comment by pachlava** [comment]
@kidinov 👋 

I'm testig this change as a part of 10.1 beta test.

> Change the code and return StripeAccountPendingRequirement from CardReaderOnboardingChecker::getOnboardingState

It would really help if you could provide an example of the code change - I'm struggling to have it working the expected way. Among other things, I've tried providing `CARD_READER_ONBOARDING_PENDING to it.version` for all cases of `when` statement in `getOnboardingState`, but still don't get the `There is an issue...` banner. Thanks!

**Comment by kidinov** [comment]
> It would really help if you could provide an example of the code change - I'm struggling to have it working the expected way. Among other things, I've tried providing CARD_READER_ONBOARDING_PENDING to it.version for all cases of when statement in getOnboardingState, but still don't get the There is an issue... banner. Thanks!

@pachlava sorry, my bad. I meant to modify this method something like that:

```
    suspend fun getOnboardingState(pluginType: PluginType? = null): CardReaderOnboardingState {
        if (!networkStatus.isConnected()) return NoConnectionError

        delay(2000)
        return StripeAccountPendingRequirement(
            null,
            WOOCOMMERCE_PAYMENTS,
            null,
            "US"
        )

//        return fetchOnboardingState(pluginType)
//            .also {
//                val (status, version) = when (it) {
//                    is OnboardingCompleted -> CARD_READER_ONBOARDING_COMPLETED to it.version
//                    is StripeAccountPendingRequirement -> CARD_READER_ONBOARDING_PENDING to it.version
//                    else -> {
//                        updatePluginExplicitlySelectedFlag(false)
//                        CARD_READER_ONBOARDING_NOT_COMPLETED to null
//                    }
//                }
//                updateSharedPreferences(
//                    status,
//                    it.preferredPlugin,
//                    version
//                )
//            }
    }
```

**Comment by pachlava** [comment]
> I meant to modify this method something like that:

Thanks a lot @kidinov, this did the trick 🥳

**Pull request merged**
