### PR TITLE
[Mobile Payments] Do use full screen input for simple payments amount input

### LINKED ISSUE #8382: [Payments] - On landscape mode, amount on Take Payment screen does not show decimal point
**Describe the bug**
When a merchant takes payment in landscape mode, the number on the calculator does not show the decimal point so it looks like there are 3 extra 0s on the number.

**To Reproduce**
1. Set phone to landscape mode
2. Go to Payments > Collect Payment
3. Enter any amount
4. See that extra 0s on the calculator are making it looks like it's thousands

**Screenshots**
Screen recording:

https://user-images.githubusercontent.com/17252150/220822100-ccce8901-2638-4cc0-ae5e-891b2886f28c.mp4

**Expected behavior**
Probably the 0s can be removed from the calculator or the decimal point is displayed on the calculator.

**Mobile Environment**
Please include:
- Device: Pixel 6A
- Android version: 12 
- WooCommerce Android version: Using this branch https://github.com/woocommerce/woocommerce-android/pull/8372

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #8382 

### Description

it seems that the keyboard owns the fullscreen mode and for some reason, it doesn't show separators, so here I implemented a workaround that makes it to not use a fullscreen mode. That's not ideal though

### Testing instructions

* Start Simple Payments Flow
* On the Amount Entering screen move to landscape mode
* Notice that you can enter the amount normally

### Images/gif

screencap-2023-03-09T105640 781Z

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by samiuelson — APPROVED** [review]
LGTM! :shipit:

**Comment by jostnes** [comment]
@kidinov thanks for working on the fix! I tried this on Pixel 6a, and saw that the top is cut off when in landscape mode:

Screenshot_20230310-141050

Not sure if it would look better if the "Take Payment" screen is smaller?

**Comment by kidinov** [comment]
@jostnes Thank you for testing this

> I tried this on Pixel 6a, and saw that the top is cut off when in landscape mode:

That's the trade-off here yeah. I still think that's better than not having decimals, what do you think?

**Comment by jostnes** [comment]
> That's the trade-off here yeah. I still think that's better than not having decimals, what do you think?

Yeah I agree that this is better than not having decimals displayed but the fix introduced another UI defect. But I think for this case, I'll open a separate UI issue (https://github.com/woocommerce/woocommerce-android/issues/8539) for that since on your screenshot, it's displayed in full (so we know that the cut-off screen issue is not happening on all devices) and it is an improvement from the previous issue.

**Pull request merged**
