### PR TITLE
Payment Method Improvements] Suggested changes from previous PR

### LINKED ISSUE #11592: [Payment Method Improvements] Suggested changes from previous PR: https://github.com/woocommerce/woocommerce-android/pull/11570
Suggested changes from previous PR:

Have you considered using WCOutlinedTypedTextField the same as they do in OrderCreateEditProductDiscountScreen:https://github.com/woocommerce/woocommerce-android/pull/11570/files#r1616059600

The text color is wrong in the dark mode (it should be white). See WCColoredButton

It looks like it's not scrollable so a user can not reach the bottom of the screen if the keyboard is open

Background is not consistent with the rest of the screens
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11619
```

### LINKED ISSUE #11619: [Payment Method Improvements] Background is not consistent with the rest of the screens
See discussion here around theming:
https://a8c.slack.com/archives/C6H8C3G23/p1716936063560139

The idea would be to apply a background of `MaterialTheme.colors.surface` to the root component of the screen, instead of using `WooThemeWithBackground`

### PR DESCRIPTION
**Pull request by backwardstruck**
Closes: #11592  and #11619

### Description  

Suggested changes from previous [PR](https://github.com/woocommerce/woocommerce-android/pull/11570)

This PR addresses several improvements and fixes:

1. **WCOutlinedTypedTextField Usage:** Updated to use `WCOutlinedTypedTextField` similar to `OrderCreateEditProductDiscountScreen`.
2. **Text Color Fix in Dark Mode:** Addressed the issue where text color in dark mode was incorrect; ensured it appears white.
3. **Scrollable Screen:** Ensured that the screen is scrollable so users can reach the bottom even when the keyboard is open.
4. **Consistent Background:** Made the background consistent with the rest of the application screens.  
Ticket [here](https://github.com/woocommerce/woocommerce-android/issues/11619).

### Testing instructions  

1. Enable OTHER_PAYMENT_METHODS

1. Navigate to the payment method selection screen by selecting Cash for an order that needs to be paid.
   
1. **Verify Text Field and Dark Mode:**
   - Check the `WCOutlinedTypedTextField` functionality.
   - Ensure that the text color is white when in dark mode.
   
1. **Scroll Functionality:**
   - Open the keyboard on the payment method screen and ensure that the screen is scrollable.
   
1. **Background Consistency:** 
   - [Verify that the background of the payment method screen is consistent with other screens.](https://github.com/woocommerce/woocommerce-android/issues/11619) 

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
FYI @kidinov I created a separate ticket for the background theming (but that should now be fixed in this PR anyway):
https://github.com/woocommerce/woocommerce-android/issues/11619

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/217">18.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by kidinov — APPROVED** [review]
LGTM!

**Pull request merged**
