### PR TITLE
[Woo POS] Double check order creation failure classes for missing unit tests 

### LINKED ISSUE #12118: [Woo POS] Double check order creation failure classes for missing unit tests
The main class missing coverage is `WooPosErrorState` but in order to test that we would need to create a UI test, like `OrdersUITest`
```[tasklist]
### Tasks
- [x] Like this one: https://github.com/woocommerce/woocommerce-android/pull/6285
```

### PR DESCRIPTION
**Pull request by backwardstruck**
### Closes
Closes: #12118

### Description
This PR adds unit tests for the `WooPosErrorState` composable to ensure it behaves as expected. It's branched off of the UI changes in https://github.com/woocommerce/woocommerce-android/pull/12133

### Steps to reproduce
Run `WooPosErrorStateTest` and confirm all test passes.

### Testing information
- **Devices Used**: Tablet Emulator

### Release Notes
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Review by jostnes — COMMENTED** [review]
Thanks for adding the tests @backwardstruck! I got ping as part of the @woocommerce/mobile-ui-testing-squad. 

The test looks good, I tested it, and it works as intended, but I think it would be better suited to be out of the `/e2e/tests/ui` folder because while it's a UI test, it's not an E2E test. 

What do you think about moving it out to https://github.com/woocommerce/woocommerce-android/tree/trunk/WooCommerce/src/androidTest/kotlin/com/woocommerce/android instead? Where other non-e2e instrumented tests live, e.g. https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/androidTest/kotlin/com/woocommerce/android/WooCommerceComUTMProviderTest.kt

**Comment by backwardstruck** [comment]
> Thanks for adding the tests @backwardstruck! I got ping as part of the @woocommerce/mobile-ui-testing-squad.
> 
> The test looks good, I tested it, and it works as intended, but I think it would be better suited to be out of the `/e2e/tests/ui` folder because while it's a UI test, it's not an E2E test.
> 
> What do you think about moving it out to https://github.com/woocommerce/woocommerce-android/tree/trunk/WooCommerce/src/androidTest/kotlin/com/woocommerce/android instead? Where other non-e2e instrumented tests live, e.g. https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/androidTest/kotlin/com/woocommerce/android/WooCommerceComUTMProviderTest.kt

You're right! I'll move the code to the correct place.

**Comment by backwardstruck** [comment]
Thanks @jostnes this is updated.

**Review by jostnes — APPROVED** [review]
looks good! :shipit:

**Pull request merged**
