### PR TITLE
[Woo POS][Cash & Receipts] Reimlement the UI of the cash payment screen as per new design

### LINKED ISSUE #13121: [Woo POS][Cash & Receipts] Reimlement the UI of the cash payment screen as per new design
p1733995736575739-slack-C070SJRA8DP

Image

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #13121

### Description

Changes the UI of the cash payment screen 

### Testing information

* POS -> Add item -> Cash payments
* Notice the changed design
* Compare with the one linked

rNAclWFAdQRw7EXEcsNVai-fi-3248_13797

### The tests that have been performed

above

### Images/gif

https://github.com/user-attachments/assets/fd312470-fa82-4858-8458-76906bac5676

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/245">21.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — COMMENTED** [review]
@kidinov, the code and UI updates look good! There are two issues related to state restoring that I think are worth improving:
1. After config change cursor moves to the left:

https://github.com/user-attachments/assets/922216d7-1576-43cb-a09b-5c8928a789a0

3. After activity restart the button is disabled even though it should be enabled:

https://github.com/user-attachments/assets/ec28da0f-f456-448f-a90b-a82b80606be9

Let me know in case you want to do that in separate PRs.

**Comment by kidinov** [comment]
@samiuelson 👋

I fixed both issues:
b1269dd2f036fe8a9ae64bf2a851d5b5c07e7f05
f9021eb76ed9628f199029a2a14a9c8fec23393e

Please take a look!

**Review by samiuelson — APPROVED** [review]
LGTM!

**Pull request merged**
