### PR TITLE
Issue/2271 m2 enable reviews

### LINKED ISSUE #2271: Edit Product Release M2: enable reviews
As per designs, we need to add "Enable reviews" to the product settings screen.

Screenshot 2020-03-13 at 12 21 53 PM

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #2271 - adds an "Enable reviews" switch to the main product settings screen.

Screenshot_1587149749

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
Hey @nbradbury just wanted to point out that enabling/disabling reviews is scheduled to be part of M3 release and an issue has already been filed and added to the [Add/Edit Products release 3](https://github.com/woocommerce/woocommerce-android/projects/9) kanban board.

**Review by anitaa1990 — APPROVED** [review]
Changes look good! 
As I mentioned though, this is part of M3 release. I'm good to merge this as part of M2 as well but I think it would be good to keep the features consistent across both platforms so iOS also releases the feature at the same time. If we are keeping this as part of M3, can we add it to the M3 feature flag instead?

**Comment by nbradbury** [comment]
> can we add it to the M3 feature flag instead?

@anitaa1990 Added in d275200.

**Review by anitaa1990 — APPROVED** [review]
:shipit:

**Pull request merged**
