### PR TITLE
[Tooling] Update Dangermattic

### PR DESCRIPTION
**Pull request by iangmaia**
This PR updates Dangermattic; the main goal is to update to get a fix to the View Check validation, which reports a warning whenever there are changes to View files and the PR doesn't have screenshots / videos attached. There was a bug where it would wrongly report a warning even with a video/image already in the description. ([example](https://github.com/woocommerce/woocommerce-ios/pull/14265#issuecomment-2447562919))

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by kidinov — DISMISSED** [review]
Please ignore this comment - I am testing one GH related thing

**Comment by AliSoftware** [comment]
Opened https://github.com/woocommerce/woocommerce-android/pull/12866 to test the fix, now waiting for CI to run and detect a false negative with old Dangermattic version—after which I plan to rebase on top of this PR then run Dangermattic again and confirm the false negative disappears with the Dangermattic update…

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/243">21.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iangmaia** [comment]
@AliSoftware did you have the chance to verify it after all? 🙂

**Comment by AliSoftware** [comment]
> @AliSoftware did you have the chance to verify it after all? 🙂 

@iangmaia as mentioned in https://github.com/woocommerce/woocommerce-android/pull/12866#issuecomment-2454920224 I want able to reproduce the false positive to begin with first, so no 😞
If you hand any idea why I can't repro, I've pinged you in https://github.com/woocommerce/woocommerce-android/pull/12866

**Comment by iangmaia** [comment]
> > @AliSoftware did you have the chance to verify it after all? 🙂
> 
> @iangmaia as mentioned in [#12866 (comment)](https://github.com/woocommerce/woocommerce-android/pull/12866#issuecomment-2454920224) I want able to reproduce the false positive to begin with first, so no 😞 If you hand any idea why I can't repro, I've pinged you in #12866

Ah, my bad. I read that comment but was in the middle of something else and forgot to follow up. Will look into it now.

**Review by AliSoftware — APPROVED** [review]
Ok I say let's approve and merge this (since it's just an update to a non-breaking version bump, as per semver conventions), and solve the issue about the agent not using the right version separately (on the linter agent and its associated gem controlling what command is run)

**Pull request merged**
