### PR TITLE
Bundle configuration Talkback enhancements

### PR DESCRIPTION
**Pull request by atorresveiga**
Part of: #10499

### Why
This PR improves the talkback experience on the bundle configuration screen, considering the issues detected in the product bundles testing plan.

> Quantity is unnecessarily read out with 5 decimals when talkback focus is on the – or + buttons. 

> Checkbox is called “image content description” and doesn’t indicate that it can be interacted with

> No indication when a checkbox is disabled because the configuration is complete. (Note that this is also tough visually, but it should certainly be made very clear for low vision users)

### Description
The changes introduced in this PR will limit the value reading in the stepper to two decimal places and enhance the interaction with the configurable items, indicating whether the item is disabled or not.

#### Prerequisites:
1. In order to test this PR, you will need a store with the product bundles extension installed and a configurable bundle item with min/max settings.
2. To test this PR you must enable TalkBack in the device settings

#### Instructions
TC1
1. Open the orders screen
3. Tap on add new order
4. Tap on add product
5. Select the configurable bundle
6. Tap on the increase (+) decrease (-) buttons in the stepper control
7. Check that the quantity is read out up to two decimal places.

TC2
1. Open the orders screen
3. Tap on add new order
4. Tap on add product
5. Select the configurable bundle
6. Check that when the bundle max quantity is reached, the other configurable products are disabled
7. Check that TalkBack indicates if a configurable product is disabled.

### Images/gif
| Reading quantity  | Disabled item |
| ------------- | ------------- |
|   |   |

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by ThomazFB — APPROVED** [review]
Tested and Talkback is following the behavior detailed in the test descriptions! Great work taking care of this 😄

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
