### PR TITLE
Updating navigation library version 2.41 -> 2.5.3

### LINKED ISSUE #7210: Update navigation library to (2.5.1+) to fix warnings in the generated code
https://issuetracker.google.com/issues/237725966

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #7210

### Description

Version 2.4.1 generates code that causes kotlin compiler to complain. It's been fixed in version 2.5.1. The PR updates navigation library from 2.4.1 to 2.5.3 (the latest)

[The change list](https://developer.android.com/jetpack/androidx/releases/navigation)  looks safe. I tested all the major flows and they look fine. It would be great to test deep links because there are some changes related to this (@wzieba could you please verify that it's all ok?)

### Testing instructions

Probably checking navigation in different flows is the only way we can test something here

### CODE REVIEW

**Comment by wzieba** [comment]
Thanks for the ping @kidinov !

> [The change list](https://developer.android.com/jetpack/androidx/releases/navigation) looks safe. I tested all the major flows and they look fine. It would be great to test deep links because there are some changes related to this (@wzieba could you please verify that it's all ok?)

The deep links support we recently added doesn't use the "deep link" idea from the Navigation library. It works based on Intents and executes the same method as the one when we trigger Order Details from notifications. So if it works, deep links should work as well. But I can double-check that to be sure!

**Review by wzieba — APPROVED** [review]
Looks good to me!

https://user-images.githubusercontent.com/5845095/202130340-e5f20dd1-d8de-4e96-abc0-693ba4787d1e.mov

**Comment by hichamboushaba** [comment]
@wzieba We use the deep linking support of the navigation library for "image uploads", can you please hold on merging this PR until I test it?

**Review by hichamboushaba — APPROVED** [review]
Looks good, I tested deep links from the image upload notifications, and they work as expected.
Thanks @kidinov

**Pull request merged**
