### PR TITLE
[WOO POS] UI changes in POS Success screen

### LINKED ISSUE #12577: [WOO POS] UI changes in POS Success screen
Screenshot 2024-09-11 at 11 38 32 AM

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #12577 

### Description

Screenshot 2024-09-11 at 11 38 32 AM

This PR introduces UI updates to the POS payment success screen based on design recommendations and resolves an issue on the checkout cart screen where cart items were overlapping with the floating toolbar.

**Changes:**

Replaced the outlined button with a standard Compose-filled button.
Removed the "return home" icon from the button.
Updated the button text according to the design suggestion.
Fixed a bug causing the cart list items to overlap with the floating toolbar on the checkout cart screen.

### Question to reviewer
The design comment states that the "payment success screen background is too saturated." Joe mentioned that the green background appears more intense than in the design. However, I confirmed that we are using the exact hex code specified in the design, and on my emulator, the success background matches the design without appearing saturated. Could you please check how it looks on your device?

payment_success_screen

### Testing information

Tested this on my my tablet emulator on both dark and light mode.

Ensured cart list items are not overlapping with floating toolbar anymore.

### Images/gif

https://github.com/user-attachments/assets/7e4aa99f-25a3-478a-a442-3bea4f64bada

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [ ] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [ ] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Review by samiuelson — COMMENTED** [review]
The changes look good overall, @AnirudhBhat. There is however a small glitch on the Cart items list after transitioning from `isCheckoutButtonVisible=true` to `isCheckoutButtonVisible=false`:
<video src=https://github.com/user-attachments/assets/1f88c1e9-fc28-4ebf-8470-af9bf0ef92e8/>
Let me know if you want to merge it as is or improve further.

When it comes to the success background color it looks good to me. I'm not sure why it was looking brighter on the physical device.

**Comment by AnirudhBhat** [comment]
>There is however a small glitch on the Cart items list after transitioning from isCheckoutButtonVisible=true to isCheckoutButtonVisible=false:

Thanks for catching it @samiuelson! I've animated it and it should look fine now: https://github.com/woocommerce/woocommerce-android/pull/12591/commits/cbfefd22bdcaa8d4c3e38f5533c0fb1f4b0e377b

**Comment by kidinov** [comment]
@AnirudhBhat I used the color picker, and it looks like that in the design,. It's `ABEF86`. Having said that it's practically the same color as we use now

**Review by samiuelson — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
