### PR TITLE
Update the PR template for contributors to follow

### PR DESCRIPTION
**Pull request by mhaqs**
The PR introduces a template for contributors to follow when creating Pull Request against issues.

The template is a guide and you're not limited to follow it to the word. But it's a good idea to go through it whenever you're about to open a new Pull Request.

Update release notes:

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mhaqs** [comment]
Ah wonderful, I thought about copying the text for the wiki into the template but then made the narration about following. I'll add it 👍

**Comment by mhaqs** [comment]
Hey @shiki Thanks for the insightful and meaningful response to the template update. I had seen it but focused on finished the Trial PRs before coming back to this. I agree with the points you make, and I've thus reduced the narration of the template. 

Addressing the creativity and personality of every author is what made me feel there should be a template baseline that everyone can follow. There's multiple guides in P2s, and if everyone has their own style of writing PRs then it could get cumbersome for the reviewers to remind them that they'd like information to be presented in a certain manner.

I see the beautiful PR you've linked, and that it references blocks of code to describe the problem and solution. I've seen that referencing code does not make sense to everyone e.g. Desginers or Product Owners, and if they want to contribute feedback to the PR, they'll have to ask questions before contributing themselves. That's friction for them.

But then again, that's what we're discussing here. We could take this up in a Slack or P2 discussion, because I'm sure there will be wonderful insights from everyone. But if time doesn't permit, I think the reduced format should make sense.

**Comment by shiki** [comment]
> P2 discussion

Yup, this can be a p2 discussion.

**Comment by AmandaRiu** [comment]
Thanks for the changes @mhaqs and the very thorough review @shiki! Just one additional note from my end. This PR looks to be merging into the `feature/product-catagories` branch, and I'm wondering why that is and if it's needed since these changes aren't directly related to that branch.

**Pull request closed without merging**
