### PR TITLE
LongParameterList rule relaxation

### PR DESCRIPTION
**Pull request by kidinov**
Change to the LongParameterList rule:
```
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Inject']
```

I turned `ignoreDefaultParameters` on, which might be ok in some situations, but I'm not entirely sure that it should be like that. Wdyt?

The baseline was cleared up as well

### CODE REVIEW

**Comment by hichamboushaba** [comment]
@kidinov just a question, why not update the other rules as well? at least the `TooManyFunctions` where it seems to me everyone agrees about 🙂

**Comment by kidinov** [comment]
@hichamboushaba no specific reason - just to keep PRs small

**Comment by hichamboushaba** [comment]
OK, thanks for clarifying, even though I don't think relaxing it would make the PR bigger 🙂, as it would just result in deleting some lines from the baseline.
But it's not a big deal 🙂

**Review by hichamboushaba — APPROVED** [review]
LGTM
> I turned ignoreDefaultParameters on, which might be ok in some situations, but I'm not entirely sure that it should be like that. Wdyt?

I think it makes sense

**Pull request merged**
