### PR TITLE
Update FluxC commit to include the fix to lower max orders batch count

### PR DESCRIPTION
**Pull request by AmandaRiu**
Simple PR to update the FluxC commit hash to include the update to lower the maximum orders fetched in batch from 25 to 15. For more details, see [this PR.](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1502)

### CODE REVIEW

**Review by 0nko — APPROVED** [review]
:shipit:

**Comment by 0nko** [comment]
There is a conflict but we can merge it after it's resolved 👍.

**Comment by jkmassel** [comment]
I'm freezing `3.7`, so this is being bumped to `3.8`. If you need it to be part of the `3.7` release, please re-target `release/3.7` and merge there. Once you have, please ping me that it's been merged and I'll be happy to cut a new release candidate!

**Comment by 0nko** [comment]
@AmandaRiu Were you planning to ship it in 3.7?

**Comment by AmandaRiu** [comment]
@0nko Ready for merge. Thanks!

**Pull request merged**
