### PR TITLE
Dark Mode: Shipment Tracking configuration views

### LINKED ISSUE #1897: Dark Mode: Shipment Tracking views
Implement light/dark theming on the shipment tracking views like the dialog to add a new shipment tracking record to an order

### PR DESCRIPTION
**Pull request by AmandaRiu**
Closes #1897 by implementing light/dark material components for the various screens used to add new order tracking records to an order. This includes:

- Add new order tracking screen including custom tracking, error message display tweaks, etc.
- The "confirm discard" dialog
- Shipment tracking providers list screen
- Shipment tracking providers loading screen

**NOTE:** PR #1977 must be merged and this branch updated with the changes before this PR will be ready for merge. 

# Screenshots

### Add Tracking form changes

Before | After (light) | After (dark)
--- | --- | ---
provider-before|provider-light|provider-dark
custom-provider-before|custom-provider-light|custom-provider-dark
error-before|error-light|error-dark
confirm-discard-before|confirm-discard-light|confirm-discard-dark

### Tracking provider list changes

Before | After (light) | After (dark)
--- | --- | ---
provider-list-before|provider-list-light|provider-list-dark
provider-loading-before|provider-loading-light|provider-loading-dark

### CODE REVIEW

**Comment by nbradbury** [comment]
@AmandaRiu @Garance91540 This is unrelated to this PR but wanted to mention it: shouldn't there be a dropdown arrow on the carrier field, since tapping that opens a carrier picker dialog?

Screenshot_1582654690

**Comment by nbradbury** [comment]
@AmandaRiu This looks good, but there are conflicts that need to be resolved.

**Comment by Garance91540** [comment]
> @AmandaRiu @Garance91540 This is unrelated to this PR but wanted to mention it: shouldn't there be a dropdown arrow on the carrier field, since tapping that opens a carrier picker dialog?

Yes it should! (Similarly to iOS) Good catch :)

**Comment by AmandaRiu** [comment]
> @AmandaRiu @Garance91540 This is unrelated to this PR but wanted to mention it: shouldn't there be a dropdown arrow on the carrier field, since tapping that opens a carrier picker dialog?

> Yes it should! (Similarly to iOS) Good catch :)

Should it though? It's not like it's a drop down selector like a combo box, clicking inside the box opens a new window.

**Comment by nbradbury** [comment]
> Should it though? It's not like it's a drop down selector like a combo box, clicking inside the box opens a new window.

I'm not sure about the material guidelines, but the designs for the various add/edit products features use an arrow for every field that shows a picker.

Screenshot_1582659708

Screenshot_1582659743

Screenshot_1582659721

**Comment by nbradbury** [comment]
@AmandaRiu We can move the dropdown arrow conversation elsewhere, since that existed prior to this PR. :shipit:

**Comment by AmandaRiu** [comment]
@nbradbury Thanks for all the detail about the drop down arrow. I can look to get that added separately. Thank you!

**Pull request merged**
