### PR TITLE
build: bump Kotlin and dependent libraries

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR bumps Kotlin and other, dependent libraries. It's a next step in `ksp` migration.

### To test

Please some test the app.

### CODE REVIEW

**Comment by wzieba** [comment]
hi @hafizrahman 👋 are you fine with reviewing this PR? 🙂

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/191">17.3</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hafizrahman** [comment]
@wzieba will do!

**Review by hafizrahman — APPROVED** [review]
I smoke tested and went through the major features and everything looks good 👍🏼

**Pull request merged**
