### PR TITLE
Remove separate `RELEASE-NOTES-WEAR.txt` file for Wear app

### PR DESCRIPTION
**Pull request by AliSoftware**
And instead use a single `RELEASE-NOTES.txt` file for both

> [!NOTE]
> This is just a Draft to show what the changes in the `Fastfile` could look like if we end up deciding to go that route.

Note that if we end up going with that approach after all, we'd also need to:
 - Inform the team that p91TBi-bvq-p2 is not true anymore after all, and that every entry they add on their feature PRs will be in the same file after all
 - Update the MC ReleasesV2 scenario accordingly, to tell the Release manager to decide which bullet points to include in the ChatGPT prompt they'll use for Mobile user-friendly release notes and which one to include in the prompt for the Wear ones (with some potentially having to be included in both)

Rationale:
 - I'm ready to bet that devs will forget about `RELEASE-NOTES-WEAR.txt` and put some Wear entries in `RELEASE-NOTES.txt` instead (especially with the wear app getting releases only rarely)
 - It's not clear what to do for PRs which make changes that affect both the Mobile and the Wear app
 - The Release Manager is already the one having to feed the bullet points to ChatGPT to generate the separate user-friendly release notes for each, and might already have to make decisions on which bullet points to include based on the `[***]` priority indicator anyway

---

Here's how it'd change the process between the task triggering `start_code_freeze` and `complete_code_freeze`

### Currently

 - After `start_code_freeze`, **assuming the devs have followed the instructions from p91TBi-bvq-p2**, the dev release notes (bullet points) would have already been split between Mobile and Wear in two separate files
 - The Release Manager is supposed to copy the bullet points of `fastlane/metadata/android/en-US/changelogs/default.txt` into ChatGPT to get user-friendly release notes, and then paste them back to `fastlane/metadata/android/en-US/changelogs/default.txt`; then they would do the same with `fastlane/metadata/wear/en-US/changelogs/default.txt`.
 - This means that during development, the devs will have to remember to put their bullet point in the right `RELEASE-NOTES{-WEAR}.txt` file
 - Then at Release time the Release Manager thus supposedly doesn't have to think about how to split them. This will only work if the devs have followed the process from p91TBi-bvq-p2 during development though. In practice I anticipate that some will forget, and that it would be wise for the Release Manager to always double-check the bullet points it feeds to ChatGPT, especially check if some of those bullet points from `RELEASE-NOTES.txt` were not supposed to be only in the Wear release notes instead of the Mobile release notes.
 - It might also be unclear for the devs in which `RELEASE-NOTES{-WEAR}.txt` file to put their release notes in when they make PRs that touch both Mobile and Wear app (e.g. think an update in the DB or datamodel requiring changes in both modules)… and so they might end up only adding their entry to one and not the other

### With unified / unique `RELEASE-NOTES.txt` file (and no more `RELEASE-NOTES-WEAR.txt` file)

 - After `start_code_freeze`, the dev release notes (bullet points) would not yet been split, and will have been copied into `fastlane/metadata/android/en-US/changelogs/default.txt` only
 - The Release Manager is still supposed to copy the bullet points to ChatGPT, except this time they're the one responsible at that very step to decide how to split the bullet points. They might decide to feed 2 bullet points to ChatGPT for the user-friendly Wear release notes and the others to another ChatGPT for the user-friendly Mobile release notes. Or have some bullet points appear in both, if they apply to both.
 - **By the way, the Release Manager is already supposed to potentially do that kind of decision about what bullet points to feed ChatGPT**, based on the `[***]` priority indicators people add at the start of each entry. For example, they can already decide to remove some entries with lower `[*]` priority from the ChatGPT prompt if including them ends up making the release notes too long (or even if we tell ChatGPT to still stay under 500 chars, then the output content being too "compressed" and not detailed enough). So at that point since they already are reviewing which dev release notes to include to craft the user-friendly ones, it makes sense to me that they might as well be the ones distributing the right entries in each one (potentially including some of those in both) at that very stage too?
 - Devs can still indicate explicitly if some entries touch the Wear app by using `[WEAR]`. That being said, if they forget, since the Release Manager will still review the entries before feeding them to ChatGPT, to decide which entries goes in which release notes (Wear, Mobile, or both), such omission will still be caught, and the `[WEAR]` indicator will just be there as a hint for the Release Manager… just like the `[***]` priority indicator already is today

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iangmaia** [comment]
I like the idea 👍  It moves the "burden" of part of the process from the devs to the RM (which was already kinda there anyway), plus potentially makes our Releases v2 web tool release notes generation simpler (if it won't need to look into 2 files).

One suggestion if we move forward with this change is to announce it also on p91TBi-bvq-p2 (in a comment and/or perhaps strikethrough the original text), tagging the team, just so the full context is there and we don't run the risk of it being mistakenly used as a reference.

**Comment by AliSoftware** [comment]
@ThomazFB as someone who already experienced the process a bit for the first Wear OS release, what do you think about this proposed small change in the process?

See the PR description for the whole details about proposed change, but TL;DR is we're proposing to remove the recently-introduced `RELEASE-NOTES-WEAR.txt` after all, let devs add all their entries to `REALEASE-NOTES.txt` even the ones about Wear OS (and prefixing them with `[WEAR]`), and it'd be up to the Release Manager to decide, during code freeze, how to split the bullet points from that sprint's release notes between Wear/Mobile (or both) when feeding them to ChatGPT to create the separate user-friendly copies.

**Comment by ThomazFB** [comment]
Hey @AliSoftware, I have no issues against this strategy of a unified release notes. And given the fact that the Wear app will contain a much slower release rate and we won't be changing the Wear app unless we have a clear opportunity to do so., this makes perfect sense to me! 👍

**Review by iangmaia — APPROVED** [review]

**Comment by AliSoftware** [comment]
@iangmaia I'll let you decide when to land this PR so that you can potentially sync its landing with the update of the release scenario and announcement when all is ready

**Pull request merged**
