### PR TITLE
Show card payment option on payment methods based on cpp eligibility

### LINKED ISSUE #6640: [Mobile Payments] Show `Card` payment option on Payment Methods based on CPP eligibility
⚠⚠⚠ Under discussion. p91TBi-8P0-p2#comment-10268

> [...] provide a Collect Payment button on any unpaid order. This would then show the Take Payment option screen, allowing merchants to choose the payment method for their order after creating it.
This is also a very appropriate primary button to show to CPP ineligible stores, as it signposts the step they need to take to process the order.
>
> – p91TBi-8P0-p2#collect-payment-button

Related: pdfdoF-Hq-p2

Image

The Payment Method screen on Android always shows the Card option. We should only show this when CPP is available.  

Order-related eligibility checks:
- Not already part paid
- Currency USD/CAD
- Order status is pending, on hold, or processing
- “Payment method” from API is booking, CoD, woocommerce payments, or none
- Does not contain a subscription

Others:
- Store is in a CPP eligible country

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #6640 
Closes: #6638

### Description

1. Renames `TakePaymentFragment` to `SelectPaymentMethodFragment`
2. Show the "collect payment" button for all unpaid orders
3. Hide card payment method in `SelectPaymentMethodFragment` based on `CardReaderPaymentCollectibilityChecker`

### Testing instructions

* Try to collect payment for different orders/different statuses
* Notice that "collect payment" button visible for all unpaid orders
* Notice card payment method is visible only by the logic determined in `CardReaderPaymentCollectibilityChecker`

### Images/gif

https://user-images.githubusercontent.com/4923871/171589597-246e7ad7-2ec8-4100-bd50-568f36a68683.mp4

### CODE REVIEW

**Comment by AnirudhBhat** [comment]
Thanks for working on this @kidinov I've tested this and the card payment method is visible/gone as expected. However, I found a bug when the order status is moved to the `completed` state and then back to the `pending` state. The collect payment button gets disappeared and will not be visible anymore. Please refer to the video for a better understanding of what I mean


https://user-images.githubusercontent.com/1331230/172296372-667c32a1-2051-4fa3-8426-3558a63107c0.mp4

**Comment by AnirudhBhat** [comment]
Small update: I forgot to mention this in my earlier comment! 

In `OrderDetailPaymentInfoView`, inside `updateCollectPaymentSection` , `if (order.isOrderPaid) {` returns true even after setting the order status to `pending` back from `completed`.

**Comment by kidinov** [comment]
@AnirudhBhat that's the same as we have in the current implementation. For some reason, the order gets `datePaid` not null after we mark it as completed. It doesn't get back to null when we change it to "pending". Not sure if this is a bug or a feature. I'll ask in slack

**Comment by kidinov** [comment]
@AnirudhBhat for the reference

p1654607479841999-slack-CGPNUU63E

**Review by AnirudhBhat — APPROVED** [review]
LGTM! The issue which I mentioned seems to be there even in the production app. Let's create a ticket so that we can track it

**Pull request merged**
