### PR TITLE
[REST API] Check Woo installation

### PR DESCRIPTION
**Pull request by hichamboushaba**
Part of: #8110 

⚠️ please don't merge until #8119 is merged.

### Description
This PR adds a step to the login with site credentials to check if Woo is installed, then shows an error if it's not, with a basic installation flow (very basic for now, it's done in a Custom Tab, we don't want to spend too much time on this now).

I always feel like the error handling in the login step is too verbose:
1. The UI is almost the same for all screens, and yet we recreate the same layouts over and over.
2. We delegate showing the errors to the `LoginActivity`, which doesn't scale well, as the class size is getting out of hand.

I think we can try to solve the two issues:
1. By using a base class that handles the UI part.
2. Using `DialogFragments`: this way, showing them will be linked to the fragment that uses them, and then we don't need to delegate showing them to the parent activity.

I tried to achieve the two points using the `LoginBaseErrorDialogFragment` in this PR, which the Woo error dialog fragment uses, and I migrated some other error screens to use it in #8127, please give your thoughts about the solution (with nitpicks 🙂).
We will have another error screen for the login if the "Application Passwords" feature is disabled, and this base screen will make adding it easier too.

##### Login
1. Prepare a self-hosted site without WooCommerce.
2. Open the app, then sign in using site credentials.
3. Confirm the app shows an error screen about Woo.
4. Test the installation according to the attached video below.
5. Confirm the app logs you in.

##### Uninstalling Woo later
1. Go back to your site, then uninstall WooCommerce.
2. Force close the app, then re-open it (the task to refresh the site executes each 10 minutes and when the app is opened).
3. Confirm the app takes you to the login screen after the site is fetched.

### Images/gif
https://user-images.githubusercontent.com/1657201/211048747-87f93da8-a1bd-423a-a0e4-2a88c148479f.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ParaskP7** [comment]
FYI: @hichamboushaba I moved the `11.8` milestone to `11.9` in order to proceed with the code freezing. Do let me know if you still need this PR to be part of the `11.8` release.

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Great job @hichamboushaba. Code looks good and I think the refactor to deal with the errors using FragmentDialog works well and is flexible enough to support our login errors. Good call. The only nitpick I can see to the approach is a small flicker when navigating back from Help screen to the dialogue fragment (as the dialogue is dismissed when navigating). But tbh I think is fine and kind of corner case. 

https://user-images.githubusercontent.com/2663464/211538195-52e790c7-e560-45af-837a-74b74b8d6339.mp4

One thing I found that might be worth looking into is that after installing Woo plugin through the web flow, user is not automatically taken back to the native login flow. I saw from your screen recording that the login flow is resumed automatically,  but I was never able to reproduce this. Both times I tested the flow I was stuck on the web view, and the login flow did not resume until I closed the chrome custom tab using the "X" button. Here is a demo of the issue: 

https://user-images.githubusercontent.com/2663464/211539294-7f3b8f19-d8c4-4efa-bfb9-10712b80d974.mp4

In my first attempt I experienced the same issue, only that I landed on the Woo onboarding web flow: 

 

I think this bug is unrelated to these PR changes. Is more related to handling the resulting urls from Woo plugin installation webflow, so I'll approve the PR and leave it up to you if you want to look into this here or in a different branch :)

**Comment by hichamboushaba** [comment]
Thanks @JorgeMucientes for the review.

> One thing I found that might be worth looking into is that after installing Woo plugin through the web flow, user is not automatically taken back to the native login flow

That's expected, as it's using a Chrome custom tab, we can't detect any URL changes, so we can't close it manually, this installation flow is just an extra thing that I added, we weren't planning on having it in this iteration.
After the first iteration, we'll work on a proper flow (either native or using a WebView).

**Comment by hichamboushaba** [comment]
> The only nitpick I can see to the approach is a small flicker when navigating back from Help screen to the dialogue fragment (as the dialogue is dismissed when navigating). But tbh I think is fine and kind of corner case.

@JorgeMucientes I just noticed that I'm not getting this flicker, and it seems it happens only if "Don't keep activities" is enabled, so this won't affect the majority of the users, can you confirm if it's the same for you?

**Comment by JorgeMucientes** [comment]
@hichamboushaba hmm interesting. I do see the flicker with the "Don't keep activities" disabled too.

**Comment by hichamboushaba** [comment]
@JorgeMucientes weird, maybe device specific, normally the DialogFragment shouldn't be dismissed if the activity is kept in memory, so maybe your device is more aggressive towards clearing activities from the backstack 🤔.

Anyway, as you said, it's a minor issue.

**Pull request merged**
