### PR TITLE
Added logic to schedule sale indefinitely

### LINKED ISSUE #2098: Edit Product > Price Settings: support sale dates without a start or end date
Ref p99K0U-2iz#comment-4592

(iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/2020)

Other than supporting sale dates without a start or end date in product details, let's also support indefinite sales in the price settings:

- if a start date is not entered but an end date is entered, the start date would default to today
- if a start date is entered but not an end date (an indefinite sale), allow the end date to be unset

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2098 by adding the logic to schedule a sale without an end date.

#### To test
- Click on a product from the Products TAB.
- Click on the Pricing section of the product (click on a product without a sale scheduled).
- Toggle the Schedule Sale option.
- Notice that the start date is set to the current date and the end date is empty.
- Click on the DONE button and click on the UPDATE button in product detail screen and verify that the sale is updated successfully.

Note that this PR only handles changes to schedule a sale indefinitely. The option to remove an end date from a sale will take place in another PR.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@anitaa1990 It looks like this PR restored the bug that let users choose an end date that's before the start date.

**Comment by jkmassel** [comment]
Howdy – we're freezing `3.9` today, so this PR is being bumped to `4.0`. If needs to be released as part of `4.0`, please re-target it at the `release/4.0` branch.

**Comment by anitaa1990** [comment]
Thanks for the review @nbradbury! 

> @anitaa1990 It looks like this PR restored the bug that let users choose an end date that's before the start date.

This [PR](https://github.com/woocommerce/woocommerce-android/pull/2067) (which fixed ☝️ bug), added logic to update the start date of a sale when the selected end date is less than the start date and updates the end date of a sale when the selected start date is greater than the end date. I see the same logic is still retained in this PR and not able to reproduce an issue where the end date is less than the start date. Would you able to provide some testing steps to reproduce?

**Comment by nbradbury** [comment]
> I see the same logic is still retained in this PR and not able to reproduce an issue where the end date is less than the start date. Would you able to provide some testing steps to reproduce?

@anitaa1990 I simply selected a start date, then selected an end date that was earlier.

Screenshot_1585052001

**Comment by anitaa1990** [comment]
@nbradbury, I'm sorry I'm not able to reproduce this scenario! 

I first tried by clicking on a product without any  sale dates scheduled and selecting a start date resulted in the following crash:
```
java.lang.NullPointerException: Attempt to read from field 'sun.util.calendar.BaseCalendar$Date java.util.Date.cdate' on a null object reference
        at java.util.Date.getMillisOf(Date.java:979)
        at java.util.Date.after(Date.java:952)
        at com.woocommerce.android.ui.products.ProductPricingFragment$setupObservers$1.invoke(ProductPricingFragment.kt:110)
        at com.woocommerce.android.ui.products.ProductPricingFragment$setupObservers$1.invoke(ProductPricingFragment.kt:33)
        at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:43)
        at com.woocommerce.android.viewmodel.LiveDataDelegate$observe$1.onChanged(LiveDataDelegate.kt:22)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.SavedStateHandle$SavingStateLiveData.setValue(SavedStateHandle.java:306)
        at com.woocommerce.android.viewmodel.LiveDataDelegate.setValue(LiveDataDelegate.kt:56)
        at com.woocommerce.android.ui.products.ProductDetailViewModel.setProductPricingViewState(Unknown Source:10)
        at com.woocommerce.android.ui.products.ProductDetailViewModel.onDatePickerValueSelected(ProductDetailViewModel.kt:205)
        at com.woocommerce.android.ui.products.ProductPricingFragment$updateProductView$$inlined$with$lambda$4$1.onDateSet(ProductPricingFragment.kt:186)
        at android.app.DatePickerDialog.onClick(DatePickerDialog.java:173)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7343)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
```

I fixed that in 903b2ff

I found another bug where the date picker was not displaying the updated end date when clicking again. Fixed that in ed057f1

And trying again when selecting an end date before the start date, both dates are correctly set to the end date in the _product pricing screen_ which was the bug you had reported. But I found another scenario where clicking on the `Done` menu button or discarding the changes, the dates are incorrectly displayed in the product detail screen though. I'm looking into fixing that and will update this PR by tomorrow 👍 

But not able to reproduce the bug where the end date is before the start date _in the pricing screen text field_ 🤔 

.

**Comment by nbradbury** [comment]
> I'm sorry I'm not able to reproduce this scenario!

I just pulled your latest changes and now I can't repro this, either 🤷‍♂

**Pull request merged**
