### PR TITLE
Product variation price bulk update

### PR DESCRIPTION
**Pull request by 0nko**
This PR adds the product variation bulk update for regular price and sale price. This is the final feature branch that contains code from multiple smaller PRs that have already been reviewed:

- #6520 
- #6525 
- #6531
- #6566 
- #6647 
- #6712 

| Scenario A.  | Scenario B. |
| ------------- | ------------- |
| <video src="https://user-images.githubusercontent.com/4527432/172472919-5987461a-277e-489b-9998-df0cb8370d1d.mp4"/>  | <video src="https://user-images.githubusercontent.com/4527432/172472580-e5ada6f8-81c3-4a1f-96ee-7eb51593fd22.mp4">  |

### CODE REVIEW

**Comment by nbradbury** [comment]
This all works fine and is an impressive trial project! A few comments, none of which need to be addressed before merging:

* The bottom sheet could be simpler. No need to say "Choose a value to update" or have a "Price" header, and the dividers aren't necessary. Before and after shot below.

price

* The bulk update limit dialog could be shortened by doing away with words like "Currently" (which gives the impression that this is a short-term limit). How about  "Bulk update is supported for a max of 100 variations"?
* Related to the above, I wonder if we should have a conversation with our backend devs about a more light-weight endpoint for bulk update. It would be nice if we didn't have to send a list of variation IDs and just have the endpoint update all variations.

**Comment by nbradbury** [comment]
@0nko I'll approve this and enable auto-merge so it's merged once the CI issues are resolved.

**Review by nbradbury — APPROVED** [review]
:shipit:

**Comment by 0nko** [comment]
Thanks @nbradbury!

> The bottom sheet could be simpler. No need to say "Choose a value to update" or have a "Price" header, and the dividers aren't necessary. Before and after shot below.

This is all based on the designs in Figma. Mainly, the header is there because eventually we'll be able to change other values, as well.

> Related to the above, I wonder if we should have a conversation with our backend devs about a more light-weight endpoint for bulk update. It would be nice if we didn't have to send a list of variation IDs and just have the endpoint update all variations.

That would be quite useful!

@samiuelson There are some build issues, would you mind taking a look at those?

**Comment by samiuelson** [comment]
> @samiuelson There are some build issues, would you mind taking a look at those?

Hi @0nko & @nbradbury 👋🏼 Thanks for raising the PR and code review! I've raised a little [PR](https://github.com/woocommerce/woocommerce-android/pull/6725) fixing the issues reported by CI here, which targets this feature branch. Could you please merge it? (I can't push commits directly here)

**Pull request merged**
