### PR TITLE
[Watch App] Introduce Wear module with build and theme configurations.

### LINKED ISSUE #11333: Setup WCAndroid project with WearOS module
The current code base for the Woo mobile app can support a separate section for the Watch app code. For the Android case, we should be able to create a module inside the WCAndroid project.

The following things need to be configured for this project:

### Build configs
- Package and APK signing matching the Phone (required to allow Phone-to-Watch connection)
- Build Flavors / Variants (Vanilla and Wasabi with the same package pattern)
- ProGuard and Lint configurations
- Android Manifest configuration

###  Libraries and Dependencies
- Hilt and Dagger
- Compose
- WearOS libraries
- DataStore libraries

### Architecture support
- Dependency Injection modules configured
- Data Store declaration and injection configured
- Coroutines scope and injection configured
- Navigation through Compose

### Wear support
- Phone-to-watch Service declaration and configuration
- Watch-to-phone Service declaration and configuration
- Default complication setup
- Default tile setup

### LINKED ISSUE #11334: Configure Watch app Theme, Icons and Colors
The WearOS app should follow the same theme, icons, and colors convention as the mobile app. We should configure the Wear module with the following:

- App icon
- App splash screen w/ Icon
- Dedicated compose Theme for Wear
- Dedicated Color scheme for Wear
- Dedicated Typography for Wear

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #11333 and #11334 by introducing the `WooCommerce-Wear` module with the following:

### Build configs
- Package and APK signing matching the Phone (required to allow Phone-to-Watch connection)
- Build Flavors / Variants (Vanilla and Wasabi with the same package pattern)
- ProGuard and Lint configurations
- Android Manifest configuration

###  Libraries and Dependencies
- Hilt and Dagger
- Compose
- WearOS libraries
- DataStore libraries

### Architecture support
- Dependency Injection modules configured
- Data Store declaration and injection configured
- Coroutines scope and injection configured
- Navigation through Compose

### Wear support
- Phone-to-watch Service declaration and configuration
- Watch-to-phone Service declaration and configuration
- Default complication setup
- Default tile setup

### Theme, Icons and Strings
- Round and Square resources separation (including app icon)
- Vanilla and Wasabi resources separation (including app icon)
- Colors setup
- Theme setup
- Typography setup

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>DataStoreType</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>LoginRepository</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>LoginViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by wzieba** [comment]
hi @ThomazFB 👋 I've noticed this PR browsing other code. I'd have one request: could we introduce a new package like `wear`? So e.g. `WooCommerceWear` would be in `com.woocommerce.android.**wear**.app`? 

The reason is that later it'll be possible to introduce code mappings on Sentry. Otherwise, it'd be confusing for Sentry which package to choose. This is how it's done now for e.g. the main and `cardreader` modules:

image

If code in `cardreader` module wasn't in `cardreader` package, Sentry wouldn't know if to look for source in `WooCommerce/(...)` or `libs/cardreader/(...)`.

**Comment by ThomazFB** [comment]
Hello @wzieba, thanks for taking a look at it and worrying about it from the start! This was originally my intention, and if you check the git history, you can see that's exactly how I started the implementation. However, the connection between the phone and the watch through the Play Services **demands** that both modules possess the same package signature. I actually had a very hard time to figure it out those build and signature requirements to make the connection to work.

You can see what I'm talking about [mentioned here](https://developer.android.com/training/wearables/data/data-layer#security):

```
Both communication options, Bluetooth and Cloud Sync Service, are end-to-end encrypted.

Google Play Services enforces the following restrictions to ensure that communication between the phone and watch is secure and app-to-app.

The package name must match across devices.
The signature of the package must match across devices.
```

**Comment by wzieba** [comment]
oh I see, thank you @ThomazFB TIL ! Sorry for noise, we'll have to live with this then. Now I also understand why Pocket Casts share the same package between `app`, `wear` and `automotive` modules.

**Comment by ThomazFB** [comment]
Not noise at all, @wzieba! I truly appreciate you jumping in and asking questions about it! I actually finds very weird that the requirement is the package signature and not a config file with secrets, makes everything harder 😅

**Comment by wzieba** [comment]
Yeah, I was surprised here as well, but I guess it's something deep in AOSP. Anyway, thanks again for clarification 🙌 !

**Pull request merged**
