### PR TITLE
Issue/11321 improvements over blaze i3

### LINKED ISSUE #11321: Blaze i3 Quick Enhancements
After the user flow review session, a lot of good feedback came up. Full context here: pe5sF9-2Bb-p2

This issue summarizes a list of small changes that can be applied to the flow and that might have a significant impact. 
Bigger effort changes have been added to other GH issues and will be deferred to Blaze i4 Project. 

The small task added to this GHG issue can be tackled bit by bit while we work on other projects. We don't plan to allocate specific team effort for these as they should be 1h-2h changes at most. 

```[tasklist]
### Quick Enhancements
- [x] Intro screen small changes: Remove purple flames, explain what the $5 USD budget is (daily,weekly,total, etc)
- [x] Preview Screen: Add a new copy below the budget section: `Audience`
- [x] Preview Screen: Add a label on the ad preview specifying if the used content for the ad was generated by AI. Hide this label as soon as the user edits the content manually
- [x] Small redesign to the Blaze view inside My Store tab: Thd2rdNU8zSaLkyKZGsOSn-fi-77_29558 This will be tackled as part of the dynamic dashboard project
- [x] Align Blaze statuses in all platforms. Both iOS and Android should have the exact same statuses as the web displays.
- [x] Campaign displayed in the Blaze card is not the most recently created one.
- [x] Check Jetpack connection and hide Blaze for Jetpack CP sites
```

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Close: #11321 and: https://github.com/woocommerce/woocommerce-android/issues/11739

### Description

Don't panic about the number of file changes. Most of them are just `strings.xml` deletions in the different locales. And the rest are really simple and small changes. 

Applies a series of small improvements coming from the Blaze user flow review. 

```[tasklist]
### Changes
- [x] Intro screen small changes: Remove purple flames, explain what the $5 USD budget by adding `daily` to it) 
- [x] Preview Screen: Add a new copy below the budget section: `Audience`
- [x] Preview Screen: Add a label on the ad preview specifying if the used content for the ad was generated by AI. Hide this label as soon as the user edits the content manually
- [x] Small redesign to the Blaze view inside My Store tab: Thd2rdNU8zSaLkyKZGsOSn-fi-77_29558 This will be tackled as part of the dynamic dashboard project
- [x] Campaign displayed in the Blaze card is not the most recently created one.
- [x] Check Jetpack connection type and hide Blaze for Jetpack CP connections
- [x] Add local checks for Blaze date ranges: https://github.com/woocommerce/woocommerce-android/issues/11739
```

### Testing information
Launch Blaze campaign creation flow a review that each one of the tasks is applied

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/221">19.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hafizrahman** [comment]
Hi @JorgeMucientes ! I'm looking through the enhancement items and I have some questions

> Preview Screen: Add a new copy below the budget section: Audience

This issue mentions adding info icon. Is this supposed to be added, or not? Because in the issue the part is checked.

> Campaign displayed in the Blaze card is not the most recently created one.

If not the recently created one, what campaign should be displayed in the Blaze card?

I also see some CI build errors here (although it built fine for me locally), can you have a look?

**Comment by JorgeMucientes** [comment]
Hey @hafizrahman good questions: 

> This issue mentions adding info icon. Is this supposed to be added, or not? Because in the issue the part is checked.

Tbh, I think adding a info icon + a dialog seems overkill. I think adding the `Audience` label should be enough to make it clearer that the following fields are meant to define the audience. I haven't started a discussion for this because I don't think is that critical to involve everyone. But please let me know if you feel it makes sense to add the icon+dialog or to discuss this further with the team. 

> If not the recently created one, what campaign should be displayed in the Blaze card?

With the prior implementation, we where using `startTime` value [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3033/files#diff-7a71867a4d9f624b04bf2be1a74a476880a97484bce35b834e82d723a9c23b92L31), to get the "most recent" campaign. But `startTime` is the date when the campaign starts, not when it was created. The changes matches iOS behavior and IMHO also makes more sense, as it is how we are ordering the campaigns in the Campaign list screen. 

Sounds good? :) 

>  also see some CI build errors here (although it built fine for me locally), can you have a look?

I think those failures are because the PR is tagged with `do not merge`. As soon as [these FluxC](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3033) changes are merged I'll update the changeset and remove the do not merge tag. That should fix everything.

**Comment by hafizrahman** [comment]
> Tbh, I think adding a info icon + a dialog seems overkill. I think adding the Audience label should be enough to make it clearer that the following fields are meant to define the audience. I haven't started a discussion for this because I don't think is that critical to involve everyone. But please let me know if you feel it makes sense to add the icon+dialog or to discuss this further with the team.

Thanks for clarifying! I do not have any strong opinion on this, I was just trying to figure out what to test because the issue and PR differs. I'm OK with how it is now.

> With the prior implementation, we where using startTime value [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3033/files#diff-7a71867a4d9f624b04bf2be1a74a476880a97484bce35b834e82d723a9c23b92L31), to get the "most recent" campaign. But startTime is the date when the campaign starts, not when it was created. The changes matches iOS behavior and IMHO also makes more sense, as it is how we are ordering the campaigns in the Campaign list screen.

> I think those failures are because the PR is tagged with do not merge. As soon as https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3033 changes are merged I'll update the changeset and remove the do not merge tag. That should fix everything.

Got it! Thanks for clarifying these two points.

**Review by hafizrahman — APPROVED** [review]
Thanks for working on these, they all look good to me.

By the way, I did not know that if you remove a string, you have to also manually remove the string in different languages. I had just assumed that if a string is removed in the original strings.xml, the next translation update will remove them from the other languages file, too.

**Comment by JorgeMucientes** [comment]
Thanks for the review @hafizrahman. 

> By the way, I did not know that if you remove a string, you have to also manually remove the string in different languages. I had just assumed that if a string is removed in the original strings.xml, the next translation update will remove them from the other languages file, too.

Hmm, now that you mention it, it is most likely that way. Unused strings will get removed automatically. Or at least that was my understanding from this recent discussion: p1714744086590719-slack-C6H8C3G23

**Pull request merged**
