### PR TITLE
[Hackweek][Backend Receipts] Remove check on dev WC core version

### LINKED ISSUE #10651: [Backend Receipts] Remove check on "dev" WC Core version when the support is released

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10651

### Description

As the currently released version (8.7+) of WC core supports backend-generated receipts, we can remove support of the dev version from the code

Also, I noticed a small bug - "see receipt" button was no reenabled if the generation of a receipt fails.

### Testing instructions

* On a site with WC core 8.7.0+: Orders -> Paid Order -> see receipt visible (there is a reported bug in the backend that in some cases receipts are not generated)
* On a site with WC core 8.7.0-: Orders -> Paid Order -> see receipt not visible

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/a8fd815d-2209-4c5f-92d6-20787430bfdc

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/199">17.8</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
Will test once I am able to get receipts to show up again.

**Comment by backwardstruck** [comment]
Tested on 8.7.0.11 and "See receipt" button is visible:

Screenshot_20240321_130443

**Review by backwardstruck — APPROVED** [review]

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/202">17.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
