### PR TITLE
Add option to request for new features from the settings page

### LINKED ISSUE #590: Add Suggestions URL to the app settings
It'd be nice to give users the ability to provide new feature feedback right within the app.

Woo uses this board: http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283 for that purpose – it'd be simple enough to add a button to the Settings screen (pending approval from our friendly design folks) that would link there!

One concept for how it could look (sorry, iOS, boo hiss)
sample

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #590. This PR adds an option to the Settings page to request new features from the app. 

### Changes
- Added a new settings option called `Feature request`
- Clicking on the option opens the webview and loads the feature request page of Woo.
- Added a new event `settings_feature_request_button_tapped` to track when the button is tapped.

### Screenshots

cc @kyleaparker, could I trouble you for your thoughts here? Thank you!!

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by kyleaparker** [comment]
>If @kyleaparker is ok with the design, we would need to add an event to the click and validate it before merging this PR

Looks good, just change the wording to "Feature request" to match iOS

**Comment by anitaa1990** [comment]
Thank you @kyleaparker !!! I've modified the text. PR is ready for review 👍

**Comment by nbradbury** [comment]
@anitaa1990 Code looks good and I'll merge shortly. I needed to address a conflict i the release notes, so CI is still pending.

I'm wondering if (in a separate PR) we should take advantage of the URL preloading feature of Chrome Custom Tabs? That Ideas page takes a little while to load.

**Comment by anitaa1990** [comment]
> I'm wondering if (in a separate PR) we should take advantage of the URL preloading feature of Chrome Custom Tabs? That Ideas page takes a little while to load.

Yup, I totally agree! I'll open an issue for this today 👍

**Pull request merged**
