### PR TITLE
Activate: Reorganize the notifications code

### LINKED ISSUE #9011: Refactor existing local push notification code

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #9011, which is a subtask of #8999.

This PR doesn't change any functionality, it just refactors the packages for notifications to reduce the noise in subsequent PRs. All the notification code has been moved to the root package `notifications`, with `local` and `push` subfolders.

**To test:**
Just a simple smoke test is fine -- create a new order and make sure a notification is displayed.

### CODE REVIEW

**Comment by JorgeMucientes** [comment]
Thanks for preparing this to avoid future noise! Tested notifications and work as expected! :shipit:

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
@0nko, I've just noticed Instrumented tests are failing [due to some Hilt misconfiguration](https://console.firebase.google.com/u/0/project/api-project-108380595987/testlab/histories/bh.edfd947f2636efe3/matrices/6501882622131915769/executions/bs.c1cdb150aba40681) when it comes to injecting dependencies in instrumented tests environment.

**Comment by pachlava** [comment]
> @0nko, I've just noticed Instrumented tests are failing [due to some Hilt misconfiguration](https://console.firebase.google.com/u/0/project/api-project-108380595987/testlab/histories/bh.edfd947f2636efe3/matrices/6501882622131915769/executions/bs.c1cdb150aba40681) when it comes to injecting dependencies in instrumented tests environment.

If this helps, when reproducing this locally, I see the same issue under the condition if the app is not yet installed in the Emulator, and it's the first time I run the tests. The app gets installed during this first attempt, though, and the tests start normally on the second attempt.

**Comment by 0nko** [comment]
@pachlava Thanks for the tip. I'll have to look into it in more detail because I just moved a few classes and it's not immediately obvious to me what's wrong.

**Pull request merged**
