### PR TITLE
Fix a crash on custom fields view

### PR DESCRIPTION
**Pull request by AnirudhBhat**
### Description

This PR fixes a crash specifically on tablet devices when the custom fields screen is visited from order detail screen.

### Testing instructions

Navigate to the order detail screen for any paid order and click on "view custom fields" CTA on tablet device and ensure there is no crash.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — CHANGES_REQUESTED** [review]
@AnirudhBhat 👋🏼 This PR doesn't compile: `⚠️ Unresolved reference: openOrder`. So I'm not able to test it.

**Comment by AnirudhBhat** [comment]
@samiuelson The methods somehow got deleted while resolving merge conflicts. I've added the methods back again. Thanks for the heads up!

**Review by samiuelson — APPROVED** [review]

**Pull request merged**
