### PR TITLE
Feature/1223 order badge

### LINKED ISSUE #1223: Add badge to orders tab and drop "orders to fulfill" from the Dashboard.
As per recent designs, we should drop the "orders to fulfill" card from the Dashboard, and add a badge to the order list showing the number of unfilled orders.

bubble

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #1223 - this PR removes the unfilled orders card from the dashboard and adds a badge to the order list tab which shows the unfilled orders count.

Screenshot_1562762097

Screenshot_1562762114

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
This looks great @nbradbury, but it seems weird to have different types of notification bubbles in different colors and different alignments. @kyleaparker what are your thoughts?

**Comment by nbradbury** [comment]
> it seems weird to have different types of notification bubbles in different colors and different alignments

I wondered that myself, but that is called for by the design.

60836103-df96a600-a192-11e9-9380-d66671065f21

**Comment by kyleaparker** [comment]
I had forgotten about the notifications badge, they don't look right together. I think the design is going to need some tweaking for this. @nbradbury I noticed in your screenshot the curve on the badge doesn't quite match the design. 

It also seems odd that we would continue to show orders in the notifications tab, it would be a double up of information. Thoughts?

**Comment by nbradbury** [comment]
> @nbradbury I noticed in your screenshot the curve on the badge doesn't quite match the design.

I may need an SVG for this, then.

> It also seems odd that we would continue to show orders in the notifications tab, it would be a double up of information. Thoughts?

I'm also not wild about the duplication, but what would happen to the cha-ching if we removed order notifications? Would we keep it and take the user to the order list when they tap the order notification?

**Comment by kyleaparker** [comment]
>I'm also not wild about the duplication, but what would happen to the cha-ching if we removed order notifications? Would we keep it and take the user to the order list when they tap the order notification?

Yea I think it would be more efficient if we went directly to the order. What are your thoughts on changing the notifications tab to "Reviews". For the visual indication, I put together two options: 

Stats Improvements 2019-07-10 17-49-51

Either a count or a dot indicator on each. The dot feels less heavy, but then you don't know the exact number of new orders. Maybe it's ok since you would have received a notification for each of them.

**Comment by nbradbury** [comment]
@kyleaparker I do like the idea of only showing reviews in the last tab - especially given the backend limitation which only enables us to show one order notification - but the problem is we're not consistent about how the badging works.

We're trying to equate _unfilled_ orders with _unseen_ reviews, which are very different things. Viewing a review will remove the reviews badge, whereas viewing an order won't change the order badge. In fact, the way it works now is simply selecting the notifications tab removes the badge. We can't do that for orders.

Also, if we go with this type of approach we'd want to visually distinguish unfilled orders the same way we do unseen reviews (right now we use a vertical purple bar). Otherwise the user could switch to the orders tab and not understand what the badge means. In addition to this, perhaps in the orders list we could show the "Processing" status with the same purple background.

Thinking out loud here, but maybe it would also help if unfilled orders always appear at the top of the order list. This way users don't have to scroll around looking for the orders they need to deal with.

**Comment by kyleaparker** [comment]
>We're trying to equate unfilled orders with unseen reviews, which are very different things. Viewing a review will remove the reviews badge, whereas viewing an order won't change the order badge. In fact, the way it works now is simply selecting the notifications tab removes the badge. We can't do that for orders.

An alternative is to keep the dot badge for reviews and just make sure the colour is the same and they align at the top:

Stats Improvements 2019-07-11 07-53-07

>Also, if we go with this type of approach we'd want to visually distinguish unfilled orders the same way we do unseen reviews (right now we use a vertical purple bar). Otherwise the user could switch to the orders tab and not understand what the badge means. In addition to this, perhaps in the orders list we could show the "Processing" status with the same purple background.

This task is in progress for this sprint 👍

**Comment by nbradbury** [comment]
> An alternative is to keep the dot badge for reviews and just make sure the colour is the same and they align at the top

Works for me :)

> This task is in progress for this sprint

Great, I'll get to work on this and hopefully be done in time for the cutoff.

**Comment by nbradbury** [comment]
> Great, I'll get to work on this and hopefully be done in time for the cutoff.

I take that back. There's a significant amount of work involved in only showing reviews in the last tab, including FluxC work. We'll have to move this to the next sprint.

cc @astralbodies @AmandaRiu

**Comment by AmandaRiu** [comment]
@nbradbury I haven't finished a full review yet, but looking at the UI changes I feel like we have an overload of purple going on and this makes it so the indicator doesn't really stand out anymore. 



I have some recommendations:
- What if we used the original highlight color?
- I noticed the bar that shows that an order hasn't been seen doesn't disappear when you view an order. Can we fix that? Having two different UX around this bar between the two tabs feels clunky and confusing. If so, we should also add a "mark all as seen" option in the toolbar of the orders tab just like we do in the reviews tab. 

cc: @kyleaparker

**Comment by kyleaparker** [comment]
There is a separate design task for the orders list changes that is currently in progress. It was my understanding that this change was only going to add the orders badge for now. 

The badge itself is going to need some tweaks to the size, font size, and margins and it might be best if we review the Figma file together next week.

**Comment by nbradbury** [comment]
> There is a separate design task for the orders list changes that is currently in progress. It was my understanding that this change was only going to add the orders badge for now.

That was how it started but feedback on this PR suggested replacing "Notifications" with "Reviews" so I assumed that was something to tackle in this PR. If that's incorrect I can revert the changes.

> The badge itself is going to need some tweaks to the size, font size, and margins and it might be best if we review the Figma file together next week.

That would be fine. If the badge is anything other than a simple circle/oval, I will likely need an SVG for it.

**Comment by nbradbury** [comment]
I'm closing this in favor of #1245, since this PR got too ambitious with changes.

**Pull request closed without merging**
