### PR TITLE
build: move included build configuration to fix Dependabot

### LINKED ISSUE #7768: Fix Dependabot
**Describe the bug**
Dependabot configuration is broken, resulting with such error:

Screenshot 2022-11-09 at 10 29 26

And on PRs with messages like this: https://github.com/woocommerce/woocommerce-android/pull/7306#issuecomment-1299765694

Also, Dependabot stopped creating any new PRs.

**To Reproduce**
1. Go to https://github.com/woocommerce/woocommerce-android/network/updates 
1. Click on the "last checked (...)" label
2. Click on "Check for updates"

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #7768

### Description

This PR moves the configuration of included builds to a separate file, `config/gradle/include_builds.gradle`.

The reason for moving this code to a separate class is to fix Dependabot.

Proof of fix is available on my fork: https://github.com/wzieba/woocommerce-android

#### How does it fix Dependabot?

Dependabot resolves Gradle files [statically](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem). It doesn't understand the content but instead looks for known schemas of version declaration. Contrary to what the linked documentation says, it looks for both `build.gradle` and `settings.gradle` files.

When it finds our `seetings.gradle` file, it tries to evaluate `includeBuild(ext.localFluxCPath)` (or rather: navigate to included build's `build.gradle`) as it doesn't understand it's inside `if` statement and also cannot understand the `ext` value. Hence, the crash.

### Testing instructions

Try to include builds with this new configuration. For me it all worked correctly.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
👋 @wzieba !

The changes LGTM, thank you so much for addressing this! 💯 

Since @oguzkocer setup the composite builds solution back then, I think it is better if we also get another 👍 from him as well.

Question (❓): How come dependabot stopped working all of a sudden, but was working fine before. To my knowledge this composite build configuration was there for some time know and dependabot was fine with it, right? 🤔

PS: To be honest, you know me, no matter if that fixes dependabot, or if we can get another solution to fix that instead, I do like to have such configuration extracted to separate files like you did (see `jacoco.gradle` as well), so a double 👍 on it. But, an quick FYI, going to Gradle Kotlin DSL, if we ever go there, that would be a problem as it doesn't allows for such implicit setup. No matter, we can deal with that when the time comes.

**Comment by wzieba** [comment]
> Since @oguzkocer setup the composite builds solution back then, I think it is better if we also get another 👍 from him as well.

Sure 👍 

> Question (❓): How come dependabot stopped working all of a sudden, but was working fine before. To my knowledge this composite build configuration was there for some time know and dependabot was fine with it, right? 🤔

Yes. I think it was just an update to Dependabot that broke our setup. Recently, they've e.g. added support for `buildSrc` defined dependencies declarations. Maybe traversing for `includeBuild`s is a useful feature in some cases. For us, it's not 😅 .

> No matter, we can deal with that when the time comes.

I'm sure we'll find some neat solution to that! 🙌

**Comment by ParaskP7** [comment]
> Yes. I think it was just an update to Dependabot that broke our setup. Recently, they've e.g. added support for buildSrc defined dependencies declarations. Maybe traversing for includeBuilds is a useful feature in some cases. For us, it's not 😅 .

Ooo, nice, didn't know that they did that recently, now that everyone goes away from `buildSrc` then want to support that... 😅 

> I'm sure we'll find some neat solution to that! 🙌

💯

**Review by oguzkocer — APPROVED** [review]
I reviewed and tested this PR yesterday and forgot to approve it 🤦‍♂️

It looks great @wzieba, thank you for the fix!

**Pull request merged**
