### PR TITLE
[Better Tablet Products] Fix for moving to trash on tablet. Empty state for the case when product is not selected

### LINKED ISSUE #11013: [Better Tablet Products] If the store has 0 products, we get a forever loading sidebar

### LINKED ISSUE #11014: [Better Tablet Products] Move to trash doesn’t appear to work at all

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #11014
Closes: #11013

### Description

The PR:
* Fixes the issue when trash a product doesn't work on tablets
* Adds "error" state when product details opened with product that is not available anymore (the same used for "empty" state so we can show that when nothing is selected on 2 pane mode, e.g. when there are no products)

### Testing instructions

Do both on a tablet and a phone
* Open products
* Trash a product -> notice that it works now on a tablet
* Either trash all products you have or use a store with no products
* Notice that a meaningful message is shown in this case now instead of indefinitely loading screen

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/4923871/24566c80-f1c3-4aa1-9a66-56a47c5f7661

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>TrashProduct</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>ProductsCommunicationViewModel</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>CommunicationEvent</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/197">17.7</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
Looks like there are a few conflicts that should be resolved before I test.

**Comment by kidinov** [comment]
@backwardstruck done

**Comment by malinajirka** [comment]
Andrei asked me to take over the review of this PR to ensure it's reviewed before the code freeze this week, I hope you don't mind @backwardstruck .

@kidinov great job, the code looks good to me and the app behaves as expected. I found two small issues, but I don't think either of them should block this PR or this feature.

# Issue 1 - Up navigation is missing when I create a product using the AI flow 
1. Open Empty product list on tablet in two-apps mode (see screenshot).
2. Tap on Add product
3. Select 'Create a product with AI'
4. Finish the flow
5. Notice the UP navigation is missing on the product detail screen. (The back button works)
Screenshot_1709806784


# Issue 2 - Resizing the apps space in two-apps mode shows 'No products selected screen' (imho not worth fixing)
1. Open empty product list on tablet in two-apps mode (see video)
2. Shrink the space for the Woo app
3. Notice the product detail with 'No product selected' is shown
[Screen_recording_20240307_112626.webm](https://github.com/woocommerce/woocommerce-android/assets/2261188/e2a545f2-907e-4898-a0f7-7613c43c0bbf)

**Review by malinajirka — APPROVED** [review]

**Comment by kidinov** [comment]
@malinajirka thanks!

>  Up navigation is missing when I create a product using the AI flow

~~Yep, the same goes for the manual flow. I have a ticket already on that.~~ I have to fix it by EOD

> Resizing the apps space in two-apps mode shows 'No products selected screen' (imho not worth fixing)

Frankly whole 2 pane -> 1 pane and back is not working properly. This is a little bit better on the orders, but pretty much the same. I have a ticket on that but I agree that at least it's not blocking the release

**Pull request merged**
