### PR TITLE
Feature/product detail done button master

### LINKED ISSUE #3556: Change "Done" button logic
Currently all the product detail sub-screens have a "Done" button to save changes to the product draft, and they all show a discard dialog if you hit the back button. Per [a discussion on Slack](https://a8c.slack.com/archives/CGPNUU63E/p1612977972011800), we've decided to only have a "Done" button on product detail. Changes in sub-screens are automatically saved to the draft, and a discard dialog only shows if you exit the main detail screen without saving changes.

### PR DESCRIPTION
**Pull request by nbradbury**
Closes #3556 - This is the master feature branch for dropping the Done button from the product detail flow. All code has been reviewed already in #3560, #3565, and  #3567.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@Garance91540 I wasn't sure whether you wanted to do a design review of this. If so, me posting screenshots probably isn't enough, so you'll likely want to [download the APK](https://30051-105889163-gh.circle-artifacts.com/0/Artifacts/WooCommerce-pr-3598-build-30051.apk).

**Comment by Garance91540** [comment]
Hi @nbradbury , I trust you  for that one, @adamzelinski and I will test during the code freeze release!

**Comment by nbradbury** [comment]
> I trust you for that one

@Garance91540 Famous last words ;)

**Review by ThomazFB — APPROVED** [review]
Working just fine, LGTM :shipit:

**Pull request merged**
