### PR TITLE
Task/enable blaze i3

### PR DESCRIPTION
**Pull request by JorgeMucientes**
### Description

Enables Blaze i3 in production

### Testing instructions

Smoke test Blaze campaign creation flow by creating a few campaigns with different budget, durations, or targeting options. 

**Note:** Since these changes are going to be applied to `release/17.9` I'm minimizing the changes required to enable the feature. All the code clean-up changes are handled here: https://github.com/woocommerce/woocommerce-android/pull/10932 

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/202">17.9 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR contains changes to <code>RELEASE-NOTES.txt</code>.<br />
Note that these changes won't affect the final version of the release notes as this version is in code freeze.<br />
Please, get in touch with a release manager if you want to update the final release notes.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by hichamboushaba** [comment]
@JorgeMucientes I noticed this is going to `17.9`, but the other PR https://github.com/woocommerce/woocommerce-android/pull/11163 is not, I already merged it before noticing this, but should we cherry-pick its changes to the release branch too?

**Comment by JorgeMucientes** [comment]
Hey @hichamboushaba. I don't think that is a problem and that was my original intention. I wanted keep the changes of this PR strictly to just enable Blaze feature flag. 
The changes from https://github.com/woocommerce/woocommerce-android/pull/11163 are just a small fix that is not critical or anything, so IMHO, it is completely fine to release it in the next version.

**Comment by hichamboushaba** [comment]
> The changes from https://github.com/woocommerce/woocommerce-android/pull/11163 are just a small fix that is not critical or anything, so IMHO, it is completely fine to release it in the next version.

Ok, thanks for the clarification @JorgeMucientes, but did we confirm the API accepts the current day when creating the campaign?

**Comment by JorgeMucientes** [comment]
The API does allow you to create a new campaign for the current date @hichamboushaba. However, the campaign will transition to `Cancel` right away as soon as is created. I would've expected for the API to fail. 
By default, the app will set start date to the current date +1 day. So, in the unlikely case where the user edits that and changes it to "today," then they'll face the situation of the campaign getting canceled. 
I still think it's quite corner case and will happen only for a few days before the fix is released. But I'm fine with cherry-picking the fix if you believe it is critical enough. Let me know and I'll add it to this PR.

**Review by 0nko — APPROVED** [review]
Everything looking good! 🎉

**Pull request merged**
