### PR TITLE
Merge 8.4.1 into trunk

### PR DESCRIPTION
**Pull request by jkmassel**
Merges the `8.4.1` hotfix release into `trunk`.

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
The only things I expect from an Android hotfix are the `versionName` and `versionCode` changes, and of course the diff for the fix. We don't have release notes for hotfixes.

I'm surprised by the @wpmobilebot / Peril [message](https://github.com/woocommerce/woocommerce-android/pull/5831/#issuecomment-1033144558) about dependency changes. However, I saw it was there [also in the fix PR](https://github.com/woocommerce/woocommerce-android/pull/5826) which was obviously merged. So, I don't think it should block the merge but I'd like to know more about it 🤔

**Comment by jkmassel** [comment]
@mokagio, I suspect the bot is mistaken about this, because there were no dependency changes in either PR 🤔 

/cc @kidinov?

**Comment by kidinov** [comment]
@jkmassel there are newer changes in the Trunk itself, that's why dependency list actually has changed  (e.g. c47f08f8b82f8ead363dd8ec2f4511e1df4b92aa). I'll think how to improve that 🤔

**Comment by kidinov** [comment]
@jkmassel it's actually improved already. This branch is old and doesn't contain changes I made lately. The most important is merging the target branch into the current one before comparison, so it's alright

**Pull request merged**
