### PR TITLE
issue/3673-product-status-crash-fix

### LINKED ISSUE #3673: Custom product status crash
Sentry Issue: [WOOCOMMERCE-ANDROID-19P](https://sentry.io/organizations/a8c/issues/2191501102/?referrer=github_integration)

```
IllegalArgumentException: None
    at com.woocommerce.android.ui.products.settings.ProductStatusFragment.getStatusForButtonId(ProductStatusFragment.kt:114)
    at com.woocommerce.android.ui.products.settings.ProductStatusFragment.onClick(ProductStatusFragment.kt:79)
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3673. I wasn't able to reproduce this crash. It looks like the button id is null and we throw an `IllegalArgumentException` [here](https://github.com/woocommerce/woocommerce-android/commit/d0bbb7d33bf3162e725803d96a19d274bf86416b). 

But for the fix, I removed the exception [from here](https://github.com/woocommerce/woocommerce-android/commit/d0bbb7d33bf3162e725803d96a19d274bf86416b) and added the default status. 

So that if we are not able to find the status by the button id, the worst case scenario is the user would have to select again as opposed to the app crashing and the user having to open the app again, click on the product again and then change the status. I'm not sure if this is the best approach we could so I'm open to suggestions 😅 Maybe we could also add a logger to Sentry to track why this is happening.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by hichamboushaba — CHANGES_REQUESTED** [review]
@anitaa1990 I added the exception because I prefer to fail early than have a wrong status, and this actually caught a bug in our implementation, we use the id `btnPrivate` for the check here: https://github.com/woocommerce/woocommerce-android/blob/3da0dbfc061b917db0c77949592fa11b4282207a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/products/settings/ProductStatusFragment.kt#L112
while the actual button uses the id `btnPublishedPrivately`https://github.com/woocommerce/woocommerce-android/blob/3da0dbfc061b917db0c77949592fa11b4282207a/WooCommerce/src/main/res/layout/fragment_product_status.xml#L12

**Comment by anitaa1990** [comment]
Thanks for the review @hichamboushaba! I was able to reproduce the crash by:
- Marking the visiblity of the product as `Private`, 
- Changing the status to anything other than `Privately published`. 
- Clicking on `Privately published` again. 

The bug you mentioned was the reason for the crash and changing it fixed the issue! Thanks so much ❤️

**Review by hichamboushaba — APPROVED** [review]
LGTM, thanks for working on this :shipit:

**Comment by nbradbury** [comment]
Can I suggest updating the exception to `throw IllegalArgumentException("Unknown buttonId $buttonId")`? I see this PR fixes the issue, but it would be helpful if we included that to begin with. I can take of this, just wanted to get your input.

**Pull request merged**
