### PR TITLE
Integrate cash on delivery API into the View Model

### PR DESCRIPTION
**Pull request by AnirudhBhat**
### NOTE: Please make sure to review and merge [this](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2503) PR before reviewing this one. Update the fluxc hash in this PR to point to the latest trunk and remove the "do not merge" label before merging this PR.

Closes: #7146 

### Description

This PR integrates the [Cash on Delivery API](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2501) into the onboarding error screen. 

Basically, this PR adds the ability to enable COD from the onboarding COD disabled error screen. 

## COD enabling successfully
1. Make sure COD is disabled on your store
2. Navigate to the IPP settings
3. Ensure you see COD disabled error screen while onboarding
4. Click on "enable cash on delivery" CTA
5. Ensure that the operation is successful and the onboarding moves to next screen
6. Visit the wp-admin page and make sure the COD is enabled

## COD enabling failure
1. Make sure COD is disabled on your store
2. Navigate to the IPP settings
3. Ensure you see COD disabled error screen while onboarding
4. Turn off the internet so that enabling COD fails
5. Click on "enable cash on delivery" CTA
6. Ensure that the operation fails and you see a toast message on the screen

### Images/gif

https://user-images.githubusercontent.com/1331230/185067092-66517c64-7c1d-4cd3-8a37-b5cf5fd6b1ac.mp4

https://user-images.githubusercontent.com/1331230/185067619-6b248b6e-cb35-41d0-8bc7-4c2e0344d4e1.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pachlava** [comment]
@AnirudhBhat 👋 ! Just cross-checking if I understand this right: I should wait for wordpress-mobile/WordPress-FluxC-Android/pull/2503 merge before reviewing the current PR?

**Comment by AnirudhBhat** [comment]
@pachlava 
>Just cross-checking if I understand this right: I should wait for https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2503 merge before reviewing the current PR?

Ideally, you can review the functionality of the app by downloading the build by scanning the QR code. Since there seems to be an issue in the build (In some other part of the codebase unrelated to this PR). Installable build QR code is not generated. I'll look into this and keep you posted.

**Comment by pachlava** [comment]
> Since there seems to be an issue in the build (In some other part of the codebase unrelated to this PR). Installable build QR code is not generated. I'll look into this and keep you posted.

Oh yes, this is true, and thanks for keeping me posted!

Maybe my question was not written in the best way, it was not related to the fact of app being buildable or not at this moment. I was curious whether I should wait for the [FluxC PR](wordpress-mobile/WordPress-FluxC-Android/pull/2503) to be merged first, before taking a look into current PR. Thanks! 🙂

**Comment by AnirudhBhat** [comment]
>I was curious whether I should wait for the [FluxC PR](https://github.com/woocommerce/woocommerce-android/pull/wordpress-mobile/WordPress-FluxC-Android/pull/2503) to be merged first, before taking a look into current PR.

Sorry for the confusion. You can still review this PR. But in order to merge this PR, the fluxc PR needs to be merged first since this PR depends on the [fluxC commit](https://github.com/woocommerce/woocommerce-android/pull/7205/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7)

**Comment by pachlava** [comment]
> since this PR depends on the [fluxC commit](https://github.com/woocommerce/woocommerce-android/pull/7205/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7)

Now it's clear! Thanks, @AnirudhBhat!

**Review by pachlava — APPROVED** [review]
I tested the PR as a part of #7212 - everything worked as described (I was using an Emulator, though). Enabling the COD worked, and the change was reflected in the wp-admin, as well as the failure to enable COD (because of the lost connection) was handled properly. Good to go from my side 🚀

**Review by rossanafmenezes — APPROVED** [review]
LGT

Works like a charm. 

Screen Shot 2022-08-17 at 9 16 01 AM
M

**Pull request merged**
