### PR TITLE
Collect payment button while creating a new order navigates to the Order list instead of Select payment method

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #10773 

### Description

This PR addresses an issue where clicking the 'Collect Payment' button during the creation of a new order incorrectly redirected users to the Order List. With this fix, users will now be properly navigated to the Select Payment Method screen, streamlining the payment collection process for both phone and tablet devices.

### Testing instructions

1. Create new order, add product or custom amount
2. Tap Collect Payment
3. **Ensure you see payment options** - Test the behaviour on both tablet and on phone

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/1331230/67282ce2-3fd2-4ceb-85cc-b6d9398f0809

https://github.com/woocommerce/woocommerce-android/assets/1331230/987acbbc-325d-42c7-867e-06a0ad45eb50

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please ensure the PR has the <code>Tracks</code> label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>Tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — COMMENTED** [review]
💡 I think after collecting a payment (e.g. mark as paid) it would be good to redirect to the `OrderDetailsFragment`. Currently after completing the order we still stay at the payment method selection screen which may be confusing and suggests the payment was not successful.

Can we change that, @AnirudhBhat ?

**Comment by AnirudhBhat** [comment]
>  I think after collecting a payment (e.g. mark as paid) it would be good to redirect to the OrderDetailsFragment. Currently after completing the order we still stay at the payment method selection screen which may be confusing and suggests the payment was not successful.
Can we change that, @AnirudhBhat ?

I've changed as per suggestion: https://github.com/woocommerce/woocommerce-android/pull/10774/commits/0cfbf20559cbb8946ec45b1604d7a34f569c884a

**Comment by AnirudhBhat** [comment]
@samiuelson I'll be merging this to the feature branch. Please feel free to add any comment here and I will fix it on the feature branch.

**Pull request merged**
