### PR TITLE
[Backend Receipts] Abstract old stripe and the new way of retriving receipts based on WC version

### LINKED ISSUE #10612: [Backend Receipts] Abstract old (stripe) and the new way of retriving receipts based on WC version

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #10612

### Description

The PR adds fetching of backend-generated receipts starting from a specific version (the exact version is still unknown and will be changed in the following PRs) of the WC plugin. The backend-generated receipts are available for **all paid** receipts, not only the ones paid with the card on the current device in our current implementation

### Testing instructions

To test backend-generated receipts (notice that the receipts itself are not final yet) use the shared site
* Open any paid order and notice the "see receipt" button -> click and take a look at the receipt
* Create order and make card payment -> Notice that at the end of the flow, a new backend-generated receipt can be viewed

To test that there is no regression:
* Use any site with the release version of WC
* Notice that receipts only paid with a card from the given device will be provided

### Images/gif

With the support of the backend-generated receipts

https://github.com/woocommerce/woocommerce-android/assets/4923871/b4d125c1-5004-4beb-82b8-83bf58ef32a9

Without the support of the backend-generated receipts

https://github.com/woocommerce/woocommerce-android/assets/4923871/3ff0ac40-a693-4364-a859-fe819f16e961

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by backwardstruck** [comment]
To test backend-generated receipts (notice that the receipts itself are not final yet) use the shared site:

Here I'm having trouble logging in. I will ping you.


To test that there is no regression:




Screenshot_20240130_154853

Screenshot_20240130_154925

**Comment by backwardstruck** [comment]
I think I did this right:

```
To test backend-generated receipts (notice that the receipts itself are not final yet) use the shared site:
```

Screenshot_20240131_155114

**Review by backwardstruck — APPROVED** [review]
Tested and code changes look good.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/190">17.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
