### PR TITLE
Login crash fix

### LINKED ISSUE #3618: LoginJetpackRequiredFragment epilogueButtonBar → KotlinNullPointerException
Sentry Issue: [WOOCOMMERCE-ANDROID-1BT](https://sentry.io/organizations/a8c/issues/2228697188/?referrer=github_integration)

```
KotlinNullPointerException: None
    at com.woocommerce.android.ui.login.LoginJetpackRequiredFragment.onViewCreated(LoginJetpackRequiredFragment.kt:52)
...
(20 additional frame(s) were not displayed)
```

Created by @shiki

---

This seems to be coming from: https://github.com/woocommerce/woocommerce-android/blob/f8c3512ecae7cc69514bccd06887c31708b36abc/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/login/LoginJetpackRequiredFragment.kt#L52

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #3618.

**To test:**
1. Create a site without Jetpack (using jurrasic.ninja, for example)
2. Start the login process by entering the site address
3. When the Jetpack-required screen is opened, rotate the screen
4. Notice the app doesn't crash

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by nbradbury — APPROVED** [review]
Looks good!

**Comment by AliSoftware** [comment]
Hello @0nko 👋 

FYI, note that, as the Peril warning above says, the entry in the Release Notes you added in that PR won't be taken into account, as we already sent the Release Notes draft to Editorial for them to craft a nice copy.

It's a little bit unfortunate, because I see that this PR was apparently created only very soon after we created the post on EditorialP2; so if I knew about this PR earlier, I would have had time to mention that new entry to Cheri in time for them to include it in her editorial copy. 🤷 

That's not that big a deal this time around, especially since the copy we are gonna go with for this release mention a generic "bug fixes" wording that this fix can easily fall into 😜. But for the next time around, don't hesitate to follow the instructions in the Peril warning and communicate and ping me about any PR done on the `release/*` branch 😉  – so that can see if we can work with Editorial about any new entry to `RELEASE-NOTES.txt` added after code-freeze (or decide to skip it and not change the `RELEASE-NOTES.txt` file in the PR at all); and also, so that I'm aware that I should consider doing a new beta with that new fix at some point.

Thanks 🙇

**Comment by 0nko** [comment]
Hi @AliSoftware 👋 

> FYI, note that, as the Peril warning above says, the entry in the Release Notes you added in that PR won't be taken into account, as we already sent the Release Notes draft to Editorial for them to craft a nice copy.

Oh ok, I didn't know about this rule. It's been a while since I added a change to release notes in the frozen branch. 

> It's a little bit unfortunate, because I see that this PR was apparently created only very soon after we created the post on EditorialP2; so if I knew about this PR earlier, I would have had time to mention that new entry to Cheri in time for them to include it in her editorial copy. 🤷

I only targeted the `6.2` branch because I saw an easy fix and thought I'd just get it released asap. But it's a rare bug and there is no need to cut a beta just for this. Since I didn't really plan it, I didn't think to tell you. I guess I should have just targeted `develop`.

**Comment by AliSoftware** [comment]
> Oh ok, I didn't know about this rule. It's been a while since I added a change to release notes in the frozen branch.

No worries 🙂  That's what the Peril bot and warning is here for 😉 

> I only targeted the `6.2` branch because I saw an easy fix and thought I'd just get it released asap. But it's a rare bug and there is no need to cut a beta just for this. Since I didn't really plan it, I didn't think to tell you. I guess I should have just targeted `develop`.

Makes sense 👍  No problem, wont do a beta just for this one, it will just be included within the next beta whenever one happens 🙂 (and the fix will soon land in `develop` too anyway, via #3676)

**Pull request merged**
