### PR TITLE
Unified Login: No WPcom found error screen

### LINKED ISSUE #2815: Unified Login: No matching WPcom account
Show a new error screen if the email address the user attempted to login with doesn't match a WordPress.com account. 

Current behavior:

New design:

Screen Shot 2020-09-02 at 4 24 54 PM

### PR DESCRIPTION
**Pull request by AmandaRiu**
Closes #2815. During the WordPress.com login flow, if the user enters an email address that is not associated with a WPcom account, then this new error screen is shown:

Before | After (light) | After (dark)
-- | -- | --
Screenshot_1601505407_framed|Screenshot_1601580317_framed|Screenshot_1601580341_framed

### Tracks events
The following `Flow`, `Step` and `Click` tracks events were added:
- Step: `no_wpcom_account_found` - tracked as soon as this screen is shown
- Click: `help_finding_connected_email` - when clicking on the link to get help finding connected email
- Click: `try_another_account` - when clicking try another account
- Click: `login_with_site_address` - when clicking the option to login with site address

Track event samples:
```
Tracked: unified_login_step, Properties: {"source":"default","flow":"google_login","step":"no_wpcom_account_found"}
Tracked: unified_login_interaction, Properties: {"source":"default","flow":"google_login","step":"no_wpcom_account_found","click":"help_finding_connected_email"}
Tracked: unified_login_interaction, Properties: {"source":"default","flow":"login_site_address","step":"no_wpcom_account_found","click":"try_another_account"}
Tracked: unified_login_interaction, Properties: {"source":"default","flow":"google_login","step":"no_wpcom_account_found","click":"login_with_site_address"}
```

### To Test
1. Launch the app to login
2. Click on **Continue with WordPress.com**
3. Enter an email address not associated with a WordPress.com account - verify new error screen is displayed
4. Click each button on screen to verify action and track event.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by AmandaRiu** [comment]
@Garance91540 This requires a design review:
- Since this error screen happens after entering an email address, I changed the error message to “It looks like <email> isn’t associated with a WordPress.com account”. Please let me know if this is okay. 
- The image asset had some errors when I tried to import it into Android Studio so the "WordPress" logo is missing. The error was `The stroke-dasharray attribute is not supported.` Maybe you can tweak the asset? Please let me know how to proceed.
- I also need a dark version of this image asset. 

Many thanks!!

**Comment by Garance91540** [comment]
Hi Amanda! Everythink looks good, except I notice some fonts seem to not be right (we can tackle this in a separate PR):

- CTAs: https://d.pr/i/aRDLGM

The font for these should be: Roboto Medium 14

- "Need help finding the connected email?" should be Body 1 https://d.pr/i/kGG64z

Thanks!

**Comment by AmandaRiu** [comment]
Updated with recommendations from @Garance91540 and updated screenshots. This one is ready for review 👍

**Comment by nbradbury** [comment]
@AmandaRiu If I enter a non-WP email address and choose "Log in with another account" from the No WPcom found error screen, after I return to the prologue screen tapping "Continue with WordPress.com" does nothing.

Also, unrelated but wanted to mention it: there's no ripple on the "Continue with WordPress.com" button.

**Comment by AmandaRiu** [comment]
@nbradbury Great catches! Fixed and ready for another round!

**Review by nbradbury — APPROVED** [review]
Nice work! :shipit:

**Comment by Garance91540** [comment]
Hi @AmandaRiu , you mentioned you updated the screenshots but I'm not sure? The buttons fonts needs to be Roboto Medium 14 https://d.pr/i/aRDLGM

**Pull request merged**
