### PR TITLE
Remove Stats V3 Code

### LINKED ISSUE #2068: Stats 4.0: changes required to stop support for the old v3 stats UI
After we retire the old stats (date to be confirmed as to when this will take place), if site version is <4.0 or WC admin manually disabled, we would need to display an empty screen to the user:

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fixes issue #2886 and #2068. Since now only the Stats V4 API is supported through the My Store group of views, this PR is a major code cut removing everything related to the old Dashboard group of views with the Stats V3 API integration.

Since this is mostly a code removal, the main point of this PR is to make sure that all Stats V4 still works as it should and prompts errors when the user login with a Stats V3 site.

How to Test
==========
Scenario 1
-----------

1. Login with a valid Stats V4 site
2. Verify that both Revenue and Top Performers fields are working properly as expected
3. Verify that the Top Performers offline features are working as expected
4. Verify that clicking any Top Performers properly opens the Product Details view

Scenario 2
-----------

1. Login with a Stats V3 site
2. Verify that a view is loaded prompting that `We can't display your store's analytics`

Screenshots
==========
| Light Mode  | Dark Mode |
| ------------- | ------------- |
| screenshot-1603868577241 | screenshot-1603868556781 |

Update release notes:

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by 0nko — COMMENTED** [review]
So much code deleted 😍.

When I tested the 1st scenario in airplane mode and I switched tabs I noticed that an error is shown even though we know we're offline. I don't think that's necessary.

image

**Comment by 0nko** [comment]
For scenario 2, this is what I see when I switched to v3 stats:

image

Is this expected or should there be a more specific error message?

**Comment by ThomazFB** [comment]
Hey @0nko! Thank you so much for your review! I'll take a look at this offline problem you mentioned and push the fix. 

But about your second point for the loading error, my understanding was that since we're warning for a long time that the app will not support the V3 anymore we could only display the loading error, but I'm not sure about that.

@Garance91540, there's any guideline for this scenario? Now that we're leaving behind all Stats V3 implementation, should we warn the user that we no longer support the current site version through any kind of banner or just leave the error there?

**Comment by Garance91540** [comment]
> @Garance91540, there's any guideline for this scenario? Now that we're leaving behind all Stats V3 implementation, should we warn the user that we no longer support the current site version through any kind of banner or just leave the error there?

Hi @ThomazFB ! I've designed a screen for that case in the Figma file "My Store - Stats Improvements": 

Screen Shot 2020-10-20 at 3 37 30 PM

**Comment by ThomazFB** [comment]
Hey @0nko and @Garance91540, thanks again for your inputs, took me a while to fix this one but I've submitted all changes as requested. Now this PR also fixes the issue #2068 and includes the fix for the Snackbar showing up when the device is offline. I think this PR is now ready for another round.

**Comment by Garance91540** [comment]
Hi @ThomazFB , where can I find the updated screenshots to review?

**Comment by 0nko** [comment]
@Garance91540 

image

image

**Review by 0nko — COMMENTED** [review]
Thanks @ThomazFB! The changes look good. 

I just noticed that when I'm on a site with v3 stats and I turn on the flight mode, the stats tabs are shown (see the screenshot above).

**Comment by ThomazFB** [comment]
Hey @0nko, Thank you again for your review! I've submitted new changes fixing those issues with the TabLayout for Stats and some UI and test improvements. The PR is ready for another round!

@Garance91540, I've just uploaded to the PR description the current UI for the Stats V3 error view, sorry for not uploading it before, Let me know what you think! And thanks once again for your time!

**Review by 0nko — APPROVED** [review]
Thanks for the changes @ThomazFB, it looks great! 🎖️

**Comment by Garance91540** [comment]
Thank you, looking great!

**Pull request merged**
