### PR TITLE
issue/3880-virtual-products-ui-update

### LINKED ISSUE #3880: Products: Provide option to create a virtual product
There have been some feedback from users not able to find the option to create a virtual product from the app. The option is currently hidden in the Product Settings screen.

We need to include that option in the product type selection screen, when creating a new product.
Screen Shot 2021-04-20 at 15 54 58

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #3880 by adding the virtual product switch to the Product Detail screen. 

Ref: `slack-mobile-woo-async-mtg-CGPNUU63E/p1618915586287300`

### Changes
- Removed the virtual switch from the product settings screen.
- Added a new product type called `virtual` which will be displayed when adding a new product and when changing the product type.

#### Editing a product
. 

#### Adding a product
. 

#### Add a product
- Click on the `+` icon from the Products tab.
- Notice the virtual product type added to the list.
- Click on the virtual product type and notice the product type set to `virtual product`.
- Verify that you are able to publish the product and view the product page when clicking on the `View product on Store`. 

#### Edit a product
- Click on an existing product from the products tab.
- Click on the `Product type` section and change the product type to `Virtual`.
- Verify that the confirmation dialog is displayed and once clicked, the product type displayed is `Virtual`.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by nbradbury — APPROVED** [review]
Changes look good! :shipit:

**Comment by Garance91540** [comment]
Hi there, 

Is there a reason why the "creating product" and "editing product" bottom sheet have different content?

Ideally, this should be the copy for both of them:
https://d.pr/i/6BOvYl

**Comment by nbradbury** [comment]
@Garance91540 I opened #3905 to address the wording differences.

**Comment by Garance91540** [comment]
perfect, thanks @nbradbury

**Pull request merged**
