### PR TITLE
[Meetup project] Support filtering orders using a customer or a product

### PR DESCRIPTION
**Pull request by JorgeMucientes**
### Description

This PR adds support for filtering orders by product or y customer. 

Some notes on the implementation:
1. We made some changes to Address handling to avoid depending on shared view models in #10876 
2. The Customer picker supports two arguments that dictates its behavior:
    i. `allowCustomerCreation` which is used to hide the Customer creation FAB.
    ii. `allowGuests` is used to decide where guests can be picker or not.
3. Since the order filtering screens were changed to be `DialogFragments` recently, and navigation from a `DialogFragment` to a `Fragment` causes the dismissing on the dialog, we had to create equivalent `DialogFragments` for the product and customer pickers, we still share the same `ViewModels` and `Compose` UIs, please check f4e00ff and 4154804.

##### Filtering
1. Open orders section
4. Click on Filters
5. Select a customer from the list
6. Select a product from the product list 
7. Check order results are filtered for selected customers and products. 

##### Non-regression
Smoke test the address editing flow of order creation and editing.

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">View files have been modified, but no screenshot or video is included in the pull request. Consider adding some for clarity.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by JorgeMucientes** [comment]
Hey @hichamboushaba, I noticed 2 issues with the current implementation. I'll try to fix them and push the solution. Just letting you know about them now to avoid both of us working on the same thing at the same time. The following are the issues I found:

1. Can't pick product from product picker


https://github.com/woocommerce/woocommerce-android/assets/2663464/c5c8b744-803c-425c-8605-022b072a9f3c


2. Filters tag does not reflect the status of a selected filter when specific customer or products are selected as filters. 

https://github.com/woocommerce/woocommerce-android/assets/2663464/ad1fb840-5046-404b-99e3-a721a5bbbfc3

**Comment by hichamboushaba** [comment]
OK, thanks @JorgeMucientes for letting me know.

> Can't pick product from product picker

Regarding this, it seems weird the `arrow` is shown for those products, I think this could be related to the issue that you previously mentioned to me about the picker in the Blaze campaign creation flow where the tapping variable products opens the variation picker.
On my side, I can't reproduce any of those issues.

> Filters tag does not reflect the status of a selected filter when specific customer or products are selected as filters.

Nice find, I think this impacts only customers, at least on my side.

Please let me know if I can help with the troubleshooting or fixing on any of the above issues.

**Comment by JorgeMucientes** [comment]
Both problems mentioned above: https://github.com/woocommerce/woocommerce-android/pull/10927#issuecomment-1966843670 have been addressed. Ready for the final round of review.

1. Can't pick the product from product picker when the products have variations and are displayed as `recentProducts` or `popularProducts`: https://github.com/woocommerce/woocommerce-android/pull/10927/commits/068ecd1ab16606602b7cf86b3781106e216db591 cc: @samiuelson @AnirudhBhat in case you might want to review that commit 🙂
2. Filters tag does not reflect the status of a selected filter when specific customer is selected in the filters: https://github.com/woocommerce/woocommerce-android/pull/10927/commits/9f0350cf02ee7aa3df67999d2b2dbd42b496d3aa

> Regarding this, it seems weird the arrow is shown for those products, I think this could be related to the issue that you previously mentioned to me about the picker in the Blaze campaign creation flow where the tapping variable products opens the variation picker.

Yes is the same issue I was experiencing with Blaze campaign creation @hichamboushaba . Glad it's fixed!

**Comment by JorgeMucientes** [comment]
I can't approve this PR since I was the one to open it, but this was a collective effort from @hichamboushaba @0nko and me. 

The code looks good, and the feature works as expected. So please feel free to approve and merge after any of you finish reviewing 👍🏼 .

**Comment by hichamboushaba** [comment]
Great, thanks @JorgeMucientes, I'll do one final testing round and I'll approve the PR after.

**Review by hichamboushaba — APPROVED** [review]
Thanks @JorgeMucientes for the last changes, I found one additional issue while testing this:

https://github.com/woocommerce/woocommerce-android/assets/1657201/eb150cf0-f35b-46f4-a733-4cccd1883481

The product selection was cleared when the filters screen is opened twice, I fixed the issue in the last commit f5be5eb26b6ed252c107c6372fd19f17556cdd67, and I'm pre-approving this now, but I won't merge it until you have a chance to revisit it.

**Comment by JorgeMucientes** [comment]
Works great! :shipit:

**Pull request merged**
