### PR TITLE
Save Order list/Order detail navigation state when the fragment recreates

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #10576 

### Description

This PR addresses the management of Order list/Order detail navigation state during configuration changes and dynamically adjusts to variations in app window size, such as when entering split view or resizing the window. It ensures consistent navigation behaviour across these scenarios.

### Testing instructions

Ensure the Order list/ Order detail screen states are maintained in the following scenarios
1. On configuration change such as screen rotation
2. When the app enters into split view and the app window is resized

**Note:** There's a known issue for which I've created a ticket here: https://github.com/woocommerce/woocommerce-android/issues/10700

### Images/gif

https://github.com/woocommerce/woocommerce-android/assets/1331230/241e88a4-7445-4089-b1ac-d1906eafa7be

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please ensure the PR has the <code>Tracks</code> label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>Tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — APPROVED** [review]
Works good overall 👍🏼 

One issue I can see is the layout in the split mode. I think we should make the left pane wider and get rid of the margins on the right:
Screenshot_20240212_172716

**Comment by AnirudhBhat** [comment]
Thanks for the review @samiuelson 
> One issue I can see is the layout in the split mode. I think we should make the left pane wider and get rid of the margins on the right:

I'll take this in a separate PR. Thank you!

**Pull request merged**
