### PR TITLE
[Woo POS] Error screens UI updates

### LINKED ISSUE #12223: [Woo POS] Fix error state as now it doesn't match the design
Now it has a background that doesn't work, for instance, for products.

Also, there is a divider which must be optional. And it's called `WooPosErrorState` - shell it be "screen" or "component"?

Image

Image

### PR DESCRIPTION
**Pull request by samiuelson**
## Woo POS Error screens UI updates

Closes: #12223 

### Description

This PR intends to update the generic Error component as per latest design specs. 
* Refer to Figma: TfaZ4LUkEwEGrxfnEFzvJj-fi-2530_13218

### Steps to reproduce

Produce errors in different screens of the POS and verify they visually match designs.

### Testing information

Verify that the error states are rendered correctly – in the products screen and in the totals screen. You can simulate no-network situation to trigger errors.

### Images/gif

Screenshot_20240809_163541
Screenshot_20240809_163501

- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by AnirudhBhat — COMMENTED** [review]
@samiuelson Thanks for working on this. It seems that the primary action button on both the product and totals error screens doesn't align with the design. Please let me know if I'm not referencing the most recent version.

Screenshot 2024-08-13 at 1 37 26 PM
Screenshot 2024-08-13 at 1 39 00 PM

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/230">20.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by samiuelson** [comment]
> @samiuelson Thanks for working on this. It seems that the primary action button on both the product and totals error screens doesn't align with the design. Please let me know if I'm not referencing the most recent version.

Good catch, @AnirudhBhat 👍🏼 Fixed in [5b782b3](https://github.com/woocommerce/woocommerce-android/pull/12271/commits/5b782b345de1b9d89c7c2ec3ff646053419e5ba8):


Screenshot_20240814_190750
Screenshot_20240814_190652

**Comment by AnirudhBhat** [comment]
Thanks for the improvement, @samiuelson. I noticed a couple of minor design inconsistencies with the Figma design:

1. On the products screen error, in the Figma design, the entire error screen is centered. However, in the code changes, the "Retry" button appears at the bottom of the screen.
2. On the totals screen error, the "Retry" button in the Figma design has less padding at the bottom, while in the implementation, the padding appears to be more.

What do you think? Let me know if you want to merge this PR before the release branch cut off and we could merge this PR as is and create a separate PR for the design fixes 👍

**Comment by samiuelson** [comment]
> Thanks for the improvement, @samiuelson. I noticed a couple of minor design inconsistencies with the Figma design:
> 
> 1. On the products screen error, in the Figma design, the entire error screen is centered. However, in the code changes, the "Retry" button appears at the bottom of the screen.
> 2. On the totals screen error, the "Retry" button in the Figma design has less padding at the bottom, while in the implementation, the padding appears to be more.
> 
> What do you think? Let me know if you want to merge this PR before the release branch cut off and we could merge this PR as is and create a separate PR for the design fixes 👍

Thanks, @AnirudhBhat! I believe this is matching Figma designs now:
Screenshot_20240816_210315
Screenshot_20240816_210356

**Review by AnirudhBhat — APPROVED** [review]
LGTM 🚀

**Pull request merged**
