### PR TITLE
[Woo POS] M2: Clear cart when products are reloaded

### LINKED ISSUE #11981: [Woo POS] M2: Make sure that product passed to the totals is in the database
As pull to refresh clears the DB, we may, in some cases, end up with the products being deleted from the DB

Convo on this topic, with one potential solution

https://github.com/woocommerce/woocommerce-android/pull/11923#discussion_r1672048696

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #11981

### Description

To fix 2 possible scenarios:
* Product added to a cart -> pull to refresh -> product removed from the DB -> order can not be created
* Product added to a cart -> pull to refresh -> Checkout started -> Reload failed -> User comes back to the products -> Error is displayed

Or maybe others when there is disparity between products and products in the cart 

### Testing information

Try pull to refresh, retry after error  -> notice that the cart being cleaned

### Images/gif

- [x] I have considered adding unit tests for this change. If I decided not to add them, I have provided a brief explanation below (optional):
- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by samiuelson — COMMENTED** [review]
Looks good overall @kidinov! I'd like to do a final round of testing when you update the branch.

**Comment by kidinov** [comment]
@samiuelson I've just resolved the conflicts, pleaes take a look

**Comment by samiuelson** [comment]
> @samiuelson I've just resolved the conflicts, pleaes take a look

Thanks @kidinov for resolving the conflicts! It seems the Home screen is not restoring its state correctly after Home activity dies – the cart is cleared. Take a look:

|Don't keep activities ON|Don't keep activities OFF|
|---|---|
|<video src=https://github.com/user-attachments/assets/29e70bcd-1622-4e2b-bd37-b7621dbd2e50/>|<video src=https://github.com/user-attachments/assets/e645e958-4814-4afd-b73a-7b7c2230a581/>|

The problem is that the "products loading" event is triggered now whenever Products screen is recreated. I think we should keep the restored Cart state, and don't override it when recreating the activity. 

For the context, here's the last PR fixing state recreation: https://github.com/woocommerce/woocommerce-android/pull/12190/files

**Comment by kidinov** [comment]
@samiuelson  👋

Good catch! But thinking about that, I am leaning more towards keeping it as it is. My thinking is based on the assumption that, in most cases, activity is killed if it is not in use for quite some time. So, in this case:
* The cart that was created some time ago is most probably not an actual one. It's POS, so an assumption here is that the merchant works face-to-face with a customer, which makes the cart something that is short-lived
* We are still sure that the products in the cart will be more likely to be in sync with the actual products on the site. So this kinda kills the idea behind this PR of `newly loaded products -> new cart` 

On the other hand, if, for instance, the activity dies when a merchant switches to a calculator and then the cart is lost, it's certainly problematic. I'm not sure how likely this scenario is, though 🤔

Wdyt?

**Comment by samiuelson** [comment]
> @samiuelson 👋
> 
> Good catch! But thinking about that, I am leaning more towards keeping it as it is. My thinking is based on the assumption that, in most cases, activity is killed if it is not in use for quite some time. So, in this case:
> 
> * The cart that was created some time ago is most probably not an actual one. It's POS, so an assumption here is that the merchant works face-to-face with a customer, which makes the cart something that is short-lived
> * We are still sure that the products in the cart will be more likely to be in sync with the actual products on the site. So this kinda kills the idea behind this PR of `newly loaded products -> new cart`
> 
> On the other hand, if, for instance, the activity dies when a merchant switches to a calculator and then the cart is lost, it's certainly problematic. I'm not sure how likely this scenario is, though 🤔
> 
> Wdyt?

👋🏼 @kidinov, I think we can get away with clearing the cart. If we decide to do so, let's remove Cart's view state serialization and storing it into Budle.

However, there is another scenario that I think we should not allow, resulting in a state mismatch. See below:
Screenshot_20240813_201915
The Cart pane is in the wrong state (showing the back button, and missing "Clear all" button).

Steps to repro:
1. Don't keep activities ON
2. Add products and click Checkout
3. Go home and back to the app
4. The cart is empty, however after adding new item the state mismatch occurs.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/230">20.0</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by kidinov** [comment]
We discussed that this not neccesary now 

p1723641605617179-slack-C025A8VV728

**Pull request closed without merging**
