### PR TITLE
Update order analytics for metadata

### LINKED ISSUE #6939: [Order Meta Data] Update Analytics
We need to update our analytics events to support order metadata:

* Update the `*_order_open` event to include new custom properties:
  * `custom_fields_count: $total-metadata-count`
  * `custom_fields_size: $metadata-size-in-bytes`
* Add a new event `*_order_view_custom_fields_tapped` that is fired when the user taps the "View custom fields" button in Order Details.

Internal ref: pe5pgL-61-p2

### PR DESCRIPTION
**Pull request by ThomazFB**
Summary
==========
Fix issue #6939 by adjusting the `ORDER_OPEN` event in the Order list view to set additional info to the track event:

- custom_fields_count: describing the amount of the metadata available in that order
- custom_fields_size: describing the total size in bytes of all metadata value fields combined

How to Test
==========
1. Simply select an Order in the Order List view that contains metadata on it, and verify in the logs that the `ORDER_OPEN` track event includes the expected new fields 

```id I/WooCommerce-UTILS: 🔵 Tracked: order_open, Properties: {"id":118,"status":"pending","custom_fields_count":2937,"custom_fields_size":19,"blog_id":204071362,"is_wpcom_store":true,"is_debug":true}```

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by nbradbury — APPROVED** [review]
@ThomazFB Code looks good but there's a failing test. I'll approve this and enable auto-merge for when that's resolved.

**Comment by rachelmcr** [comment]
> `"custom_fields_count":2937,"custom_fields_size":19`

@ThomazFB @nbradbury Are these two properties reversed? I think the count in this example should be 19 and the size should be 2937 bytes, right? (I just happened to peek at this, so let me know if I'm mistaken here.)

**Comment by ThomazFB** [comment]
@nbradbury thank you for the review! I'll fix the failing test right now! 

@rachelmcr you're correct, I reversed them 🤦 Let me fix that right now! Thanks!

**Comment by nbradbury** [comment]
> @ThomazFB @nbradbury Are these two properties reversed?

@rachelmcr Thanks for catching that, I totally missed it!

**Pull request merged**
