### PR TITLE
Update mediapicker dependency to be fetched from S3 and enable composite build for it

### PR DESCRIPTION
**Pull request by oguzkocer**
### Description

https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/pull/52 starts publishing the `WordPress-MediaPicker-Android` library to our S3 Maven and this PR updates the project so these dependencies will be fetched from the S3 Maven. It also adds composite build support to make it easier to work with the library.

_Note that https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/pull/52 is not reviewed yet. I'll make it available for review once this PR is approved. It's unlikely that any change in that PR will impact this integration._

### Testing instructions

I am not familiar with the media picker, but a smoke test of the library should be enough. It'd be great if it can also be tested with composite build which can be enabled by:
* Copy the `local-builds.gradle-example` file as `local-builds.gradle`
* Uncomment & update the path of the `localMediaPickerPath` to your local `WordPress-MediaPicker-Android`
* Gradle sync & verify that Android Studio shows the `Media Picker` project
* Smoke test the media picker
* Make a change in the media picker library and verify that you can use it immediately in the app

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
Local build worked as expected 👍 

image


Screen Shot 2021-11-10 at 10 39 10 am

I'm not able to launch the app, but that's in both build configuration (i.e. with or without the line in `local-build.gradle`) so I doubt it has to do with this PR. This is the error I'm getting:

```
> Task :WooCommerce:kaptJalapenoDebugKotlin FAILED

Execution failed for task ':WooCommerce:kaptJalapenoDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

I run with `--info` and `--stacktrace` but didn't get any more useful information.

I noticed that [lint on CI failed, too.](https://app.circleci.com/pipelines/github/woocommerce/woocommerce-android/15565/workflows/9020d49d-16fc-4707-ad09-77acceee503f/jobs/53313). The stacktrace looks similar to mine, but I'm not sure whether the issues are due to the same cause.

**Comment by oguzkocer** [comment]
@mokagio The app is working for me locally. The installable build also seems to be working. There isn't much information in the error you've shared, so not sure what's going on with your local build. Could you try removing `gradle.properties` and applying the configuration again just in case that's related? You can also do a clean build with `./gradlew clean` and then running the app.

**Comment by oguzkocer** [comment]
@0nko I tried resolving the conflict, but it looks like the commit hash that's used in the `feature/media-picker-library` branch for the media picker is not yet merged to `trunk` in `WordPress-MediaPicker-Android`.

**Comment by 0nko** [comment]
@mokagio @oguzkocer I've been seeing similar errors on Jitpack. I managed to figure one out by removing a `@Suppress` annotation that didn't cause any problems my local machine. I thought it had something to do with Jitpack and I was hoping migrating to S3 would address this. That's why the `feature/media-picker-library` branch is pointing to a different library branch, which removes the sample app module (it was failing on the error above). So you can resolve the conflict simply by using your commit hash.

**Comment by oguzkocer** [comment]
@0nko If I merge `feature/media-picker-library` into this branch and resolve the conflict by keeping the `mediapickerVersion` as `52-a841b734d79f561e698d1f90c13892d610b12dec` it results in the following error:

```
> Task :WooCommerce:kaptVanillaDebugKotlin
Note: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.volley.VolleyLibraryGlideModule]
/woocommerce-android/WooCommerce/build/tmp/kapt3/stubs/vanillaDebug/com/woocommerce/android/mediapicker/MediaPickerModule.java:16: error: @Binds methods' parameter type must be assignable to the return type
    public abstract error.NonExistentClass provideMediaPickerLogger$WooCommerce_vanillaDebug(@org.jetbrains.annotations.NotNull()
                                           ^
/woocommerce-android/WooCommerce/build/tmp/kapt3/stubs/vanillaDebug/com/woocommerce/android/mediapicker/MediaPickerModule.java:31: error: @Binds methods' parameter type must be assignable to the return type
    public abstract error.NonExistentClass bindTracker(@org.jetbrains.annotations.NotNull()
```

Is that the error you're referring to - because this one looks like a valid error to me, or were you referring to the issue @mokagio is having? If it's the latter, @malinajirka shared this today on Slack which I think is the issue @mokagio is having:

> When you encounter the following error during build
> ```
> Execution failed for task ':WooCommerce:kaptWasabiDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
>```
>Make sure JDK for Gradle is set to the correct version - Java 11 for  WPAndroid/WCAndroid => press cmd+shift+A => type “gradle jvm” => change JDK version to 11.

**Comment by 0nko** [comment]
@oguzkocer Oh I see now. The S3 branch in MP library was behind the trunk by a couple of commits. I've merged the trunk and the new build should hopefully fix this.

**Comment by mokagio** [comment]
@oguzkocer I can confirm the fix you and @malinajirka suggested worked for me. I guess we just have to sort out that lint task then we can merge 👍

**Comment by oguzkocer** [comment]
@0nko @wzieba @woocommerce/owl-team I've fixed the merge conflict and this is now ready to review/merge.

**Review by 0nko — APPROVED** [review]
Works great! Let's merge it. :shipit:

**Pull request merged**
