### PR TITLE
[Payment Method Improvements] Gray out button until payment amount is greater or equal to amount due

### LINKED ISSUE #11604: [Payment Method Improvements] Gray out button until payment amount is greater or equal to amount due

### PR DESCRIPTION
**Pull request by backwardstruck**
Closes: #11604

This PR is branched off of https://github.com/woocommerce/woocommerce-android/pull/11594

### Description

**Gray out "Mark order as complete" button:**
   - The "Mark order as complete" button is disabled if the amount of cash received is less than the amount due. This prevents users from completing the order without receiving sufficient payment.

**Display correct currency symbol in change due field:**
   - The change due field now correctly displays the currency symbol, aligning with the currency used for the transaction.

### Testing instructions

0. Enable `OTHER_PAYMENT_METHODS`

1. **Gray out button test:**
   - Navigate to an order that needs to be paid with cash.
   - Enter a cash received amount that is less than the amount due.
   - Verify that the "Mark order as complete" button is grayed out and disabled.
   - Enter a cash received amount that is equal to or greater than the amount due.
   - Verify that the "Mark order as complete" button is enabled.

2. **Currency symbol in change due field test:**
   - Verify that the change due field displays the correct currency symbol as defined by the app's currency settings.

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

---

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/217">18.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by kidinov — APPROVED** [review]
I've done some changes to the code (moved the state into state object and some other stuff)

Please feel free to revert them if they don't make much sense

**Comment by backwardstruck** [comment]
> I've done some changes to the code (moved the state into state object and some other stuff)
> 
> Please feel free to revert them if they don't make much sense

Thanks a lot. I see `Moved ui state flags to the UI state`, which I definitely should have done to simplify things.

**Pull request merged**
