### PR TITLE
Added logic to display bottom sheet button if some product info is not available

### LINKED ISSUE #2669: Edit Products: Shipping section not displayed if it is not available
The shipping section for a product is not displayed in the Product detail screen if there is no shipping information available. This is possibly related to the changes in [this PR](https://github.com/woocommerce/woocommerce-android/pull/2617) when the bottom sheet was introduced. But since the bottom sheet is enabled only for products M3, the shipping section is no longer displayed.

Possible solutions could be to:
- enable the bottom sheet for all users since iOS is also doing the same thing.
- ensure that the option to add shipping is displayed when there is no shipping section.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #2669. The bottom sheet button was initially only displayed for M3 release. But this meant if there was no shipping or short description available for a product, there was no option to add those details. This PR adds logic to display the "Add more details" button if some product info for M1 and M2 release is not available.

#### Screenshots
. 

#### To test
- Click on a Physical product with no shipping info.
- Notice the **Add More details** button is visible.
- Click on the button and notice Shipping section.
- Click on the Shipping section and update some details.
- Notice now that the bottom sheet button is no longer visible and a new shipping section is displayed in the Product Detail screen.

**Please be sure to test this change in a release version as well since the M3 features should not be visible in the release version.** 

This is a hotfix and warrants a new beta release since users would no longer be able to add shipping info for a product in the 4.7 beta. cc @oguzkocer and @loremattei 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hey @anitaa1990, nice fix! Changes are working just fine here, tests are passing and the M3 feature flag is just fine on my tests too. LGMT :shipit:

**Comment by oguzkocer** [comment]
Thanks for the ping @anitaa1990! This PR doesn't seem to be targeting the release branch, I'll cherry-pick it this time. However, in the future, could you please make sure beta fixes are targeting the current release branch? cc @ThomazFB This is good to verify during PR review as well.

> This is a hotfix and warrants a new beta release

Just a minor nitpick. This is technically not a `hotfix` as we reserve that term for fixing current production.

**Comment by ThomazFB** [comment]
Oh, sorry about that and thank you for pointing it out @oguzkocer, I'll look to be more aware next time.

**Comment by anitaa1990** [comment]
> This PR doesn't seem to be targeting the release branch, I'll cherry-pick it this time. However, in the future, could you please make sure beta fixes are targeting the current release branch? 

My bad!! Thanks for taking care of it @oguzkocer! I apologise! I meant to target the release branch but missed it. Will be careful in the future to target the release branch. 

> Just a minor nitpick. This is technically not a hotfix as we reserve that term for fixing current production.

Sounds good 👍

**Pull request merged**
