### PR TITLE
Dark Mode v2: No stores error view

### LINKED ISSUE #2328: Dark Mode v2: No Woo Stores
Tweak the login epilogue view to match designs. 

Design
Screen Shot 2020-04-27 at 6 14 56 PM

Updates needed:
* Users name should be `Body1` onSurfaceHigh
* Username should be `Body2` onSurfaceMedium
* Need help finding connected email link should be `16sp`
* “Try Another Account” should be on top, and “View Connected Stores” on the bottom.

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #2328. Implements some tweaks to the no stores view:
- Update the `Woo.Button.Secondary` style to use `Body2` instead of `Caption` as that was too small. This style is only used by the login library and matches the designs. 
- Fixed the padding around the drawable to add more space between the image and the body text. 
- Updated the User Name text to match designs
- Updated the username text to match designs

**NOTE:** Requires design review before merge

@Garance91540 The "View Connected Stores" and the "Try another account" buttons are linked to a ton of logic used in this screen for determining when to show/hide buttons and the "Try Another Account" button is always an action available for this view and all the other error views, but "View Connected Stores" will only be shown if there are stores connected to the account the user logged in with. Because of that I did not swap these buttons to keep the code easy to follow and reduce the possibility of bugs. WDYT?

### Designs

Screen Shot 2020-04-27 at 6 14 56 PM

### Implementation

Before | After
-- | --
Screenshot_1588044264|Screenshot_1588044215
Screenshot_1588044258|Screenshot_1588044220

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by Garance91540 — APPROVED** [review]
Hi @AmandaRiu , 
Sounds good about keeping "Try another account" Primary!

Long overdue, I changed the styling of the Secondary buttons for light and dark mode by making them filled (respectively with white and elevation/04dp). Additionally, I also removed the white background of the bottom bar on this screen.
I know these were late additions so feel free to disregard these changes for now, and we can add them in a "later improvement" P2.

https://d.pr/i/ju1VAB

**Comment by AmandaRiu** [comment]
This one is ready for review/merge 🥳

**Comment by AmandaRiu** [comment]
@Garance91540 

> Long overdue, I changed the styling of the Secondary buttons for light and dark mode by making them filled (respectively with white and elevation/04dp). Additionally, I also removed the white background of the bottom bar on this screen. I know these were late additions so feel free to disregard these changes for now, and we can add them in a "later improvement" P2.

Thanks. I've opened [a new ticket for this request](https://github.com/woocommerce/woocommerce-android/issues/2342) and added a question for you there since there is more to this change than just this view.

**Comment by AmandaRiu** [comment]
This PR is ready for review + merge 🥳

**Review by nbradbury — APPROVED** [review]
:shipit:

**Pull request merged**
