### PR TITLE
Issue/4797 image upload progress

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #

### Description
This PR attempts to show upload progress, by restoring what was done before in ProductImageService, but it turned out that the upload reporting is broken from FluxC, if the file is small, we get just one initial progress info, then we don't get anything until the file is uploaded, and when uploading large files, the bar goes almost full instantly, then stays for a long time waiting for the upload to occur.
I tried to investigate this a bit, but I wasn't able to find a solution, the [StackOverFlow answer](http://stackoverflow.com/questions/35528751/okhttp-3-tracking-multipart-upload-progress) that has the solution we use in FluxC has so many people complaining that it doesn't work well, and some explain why it doesn't, I tried some of the alternative solutions (define a socketFactory, or perform the counting in the base body...), but none of them made any difference, I can't spend more time on this right now, maybe later.

https://user-images.githubusercontent.com/1657201/133782009-70191a6d-270e-4632-bae9-6c110ede1daf.mp4

https://user-images.githubusercontent.com/1657201/133782018-81db8b34-241b-4c6c-a69b-2d7f6d5880ae.mp4

I don't know if we should merge this as is, as it restores the exact behavior we had before, then troubleshoot the FluxC's issue separately, or wait until we find a solution, WDYT @woocommerce/android-developers?

### Testing instructions

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by 0nko** [comment]
I'd say let's merge it. Even though it's not fixing the underlying issue, the code is much cleaner and it uses flows! 👍

**Comment by hichamboushaba** [comment]
Thanks @0nko, that's my opinion too, I'll try to fix the lint issues, and make the PR ready for review in the coming days.

**Review by 0nko — COMMENTED** [review]
This is probably not related, but I just wanted to double check since you've merged from `develop` -- after pulling your changes and running the app, I'm getting a DB migration exception:
```
java.lang.RuntimeException: Unable to create application com.woocommerce.android.WooCommerceDebug: android.database.sqlite.SQLiteException: duplicate column name: ORDER_KEY (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE WCOrderModel ADD ORDER_KEY TEXT
```

**Comment by hichamboushaba** [comment]
> This is probably not related, but I just wanted to double check since you've merged from `develop` -- after pulling your changes and running the app, I'm getting a DB migration exception:
> 
> ```
> java.lang.RuntimeException: Unable to create application com.woocommerce.android.WooCommerceDebug: android.database.sqlite.SQLiteException: duplicate column name: ORDER_KEY (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE WCOrderModel ADD ORDER_KEY TEXT
> ```

I think this is normal after the PR #4953, since you before pulling the new changes, you were in a scenario similar to what's explained on the P2: p91TBi-61j-p2 (old version of fluxC core, with new version of fluxC's plugin WooCommerce), which means the DB uses an old version `160`, but still has the columns from the new version. After you pulled the changes, the app will try to migrate from `160` to the last version, but since the columns already exist, the app crashed.

**Review by 0nko — APPROVED** [review]
Thanks for the updates, @hichamboushaba! :shipit:

**Pull request merged**
