### PR TITLE
Edit product categories

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Part of: #11061

This PR relies on https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2974 that need to be merged before. 

### Description

Adds new functionality to edit existing product categories from the product detail screen. 
There are some UI improvements in the upcoming PR for dealing with the loading states and success messages. So need to worry about those in this PR. 

### Testing instructions

1. Open the product detail screen
2. Select the category section
3. Make sure you have existing categories. If not, add a few of them.
4. Tap on any of the existing categories. Do not tap on the checkbox, tap on the list item
5. This will open the category "detail" 
6. Edit the category values
7. Click "Done"
8. Notice the category is updated successfully.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 300 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Class <code>CategoryUpdateResult</code> is missing tests, but <code>unit-tests-exemption</code> label was set to ignore this.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by 0nko — CHANGES_REQUESTED** [review]
Nice work, @JorgeMucientes! The edit functionality works well, however, I've encountered some strange behavior:

[Screen_recording_20240318_160516.webm](https://github.com/woocommerce/woocommerce-android/assets/1522856/46148a00-57ec-47a6-a656-7f5049351352)

- Notice that after I change the title, the checked state is cleared when I scroll away from the changed category and come back
- When I change the category title back to the original title and save the changes, the product detail lists 2 categories now (old and new name)

**Comment by JorgeMucientes** [comment]
Thank you for the review @0nko! 
Great catch! It took me a while to figure out what the heck was going on. Oh boy, the good old `recyclerview` issues 😓, I'm so glad we don't have to use it anymore. This time the problem was with `categoryCheckbox.setOnCheckedChangeListener`, which was getting called whenever the view holder was getting recycled, generating all sorts of random behaviors with the `checked` status, upon scrolling in long lists of items
Fixed in here:https://github.com/woocommerce/woocommerce-android/pull/11077/commits/e6fed7d3a180b404bf9273ac376a01e3ba5f286b  by just using a clickListener that is only invoked when the user interacts with the checkbox. 

Ready for another round

**Comment by 0nko** [comment]
Thanks for the changes, @JorgeMucientes. The list issue is now fixed but I still see the problem with the phantom categories in the product details 😕

https://github.com/woocommerce/woocommerce-android/assets/1522856/4ee3e801-2077-4d59-b275-ec71f240bf1a

**Comment by JorgeMucientes** [comment]
Ouch, sorry I missed that bug you reported @0nko. Good catch.
Ok, fixing that required some extra refactorign, plus that bug also affected the category `deletion` feature. So I have fixed the issue in this commit: https://github.com/woocommerce/woocommerce-android/pull/11085/commits/ff2cbe1dd3e61c71626ab9d6931b59d6759ae2e8, but you'll have to test it and review it in the delete category PR: https://github.com/woocommerce/woocommerce-android/pull/11085

Before merging this PR I will make sure to merge the PR: https://github.com/woocommerce/woocommerce-android/pull/11085 into this, so the feature is integrated as a whole and everything works as expected.

**Review by 0nko — APPROVED** [review]
Adding and removing of categories works well now, nice job @JorgeMucientes! 🏅

**Pull request merged**
