### PR TITLE
Free Trial: Upgrades screen UI

### LINKED ISSUE #8450: [Free Trial] Add "Subscription" tile in Menu
### Description (changed on 9th Mar 2023, check!)

This task is about adding a new tile on the "Menu" screen. See internal communication for the icon and details: pe5pgL-2mT-p2#comment-1956

We should probably show it only for WPCOM sites.

Image

### LINKED ISSUE #8451: [Free Trial] Add "Subscription" view with needed UI
### Description

Create the "Subscription" screen UI. Bonus points for using Compose.

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #8450 

Closes: #8451

### Description

This PR adds UI for "Upgrades" screen.

### Testing instructions

Not needed but you can open the `UpgradesScreen` class and render Compose previews to see UI details of each state.

### Images/gif

image
image

https://user-images.githubusercontent.com/5845095/224367290-83505321-0daa-4edc-b8e2-ce238c3491af.mp4

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by atorresveiga** [comment]
I will share with you some ideas about the current design implementation. Please let me know what you think.




1. The `Current`  in the subscription status was the first thing that caught my eye.



Do we plan to show a different status than the current status? Otherwise, I believe we can safely remove that word from the status description.

2. I'm not loving the idea of having the troubleshooting card. It is a card with a title for just one button. I think that we can explore a different approach here and merge both cards and use labels and a divider to emphasize the content differences. 

3. The subscribe now button will be shown only when the subscription status is trial. On any other states, I think the button should be hidden/changed to cancel. With this in mind, I think it is worth exploring moving the button to the same line as the subscription status.

4. What do you think if we change all the `buttons` to `text buttons` on this screen? Similar to the iOS design. I kind of liked that approach more.

**Comment by wzieba** [comment]
Hi @atorresveiga !

Thank you for the review and suggestions. As discussed internally, I've applied only some suggestions but I think they already made the screen look better.

> On any other states, I think the button should be hidden/changed to cancel.

Please see `UpgradesScreen` class, I've updated the code to preview all possible states (also in dark mode) so it should be also resolved now.

The "cancel" button will be implemented later, in iteration 4.

Ready for re-review!

**Comment by atorresveiga** [comment]
The code is looking good and working as expected.
I have one tiny suggestion. On the Loading state, it would be great to show something indicating the screen is working. 

In this patch, I added a SkeletonView on the Loading state. WDYT?

<details>
  <summary>Patch</summary>

```
  Index: WooCommerce/src/main/kotlin/com/woocommerce/android/ui/upgrades/UpgradesScreen.kt
  IDEA additional info:
  Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
  <+>UTF-8
  ===================================================================
  diff --git a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/upgrades/UpgradesScreen.kt b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/upgrades/UpgradesScreen.kt
  --- a/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/upgrades/UpgradesScreen.kt	(revision 556755133729e240317e27f21e27096d4b93c26c)
  +++ b/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/upgrades/UpgradesScreen.kt	(date 1678898457792)
  @@ -17,6 +17,7 @@
   import androidx.compose.ui.tooling.preview.Preview
   import androidx.compose.ui.unit.dp
   import com.woocommerce.android.R
  +import com.woocommerce.android.ui.compose.animations.SkeletonView
   import com.woocommerce.android.ui.compose.component.WCOutlinedButton
   import com.woocommerce.android.ui.compose.theme.WooThemeWithBackground
   import com.woocommerce.android.ui.upgrades.UpgradesViewModel.UpgradesViewState
  @@ -74,6 +75,9 @@
                               Text(stringResource(R.string.upgrades_upgrade_now))
                           }
                       }
  +                    if (state is Loading) {
  +                        SkeletonView(width = 132.dp, height = 24.dp)
  +                    }
                       Text(
                           style = MaterialTheme.typography.caption,
                           text = when (state) {
```

</details>

**Review by atorresveiga — APPROVED** [review]
LGTM! :shipit:

**Comment by wzieba** [comment]
> On the Loading state, it would be great to show something indicating the screen is working.

Looks really nice, thanks!

**Pull request merged**
