### PR TITLE
Support product review reply

### LINKED ISSUE #8038: Support replying to product reviews
## Description

This task is about support for replying to customer reviews. It's currently implemented in iOS: https://github.com/woocommerce/woocommerce-ios/issues/7777

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #8038 

Please review and merge FluxC PR first: 

https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2599

### Description

This PR adds a feature of replying to user reviews.

#### TC 1 Success case
1. Open review details
2. Tap on "reply"
3. Write a reply message
4. Press "Done"
5. After a while, see a snack bar with a success message
6. Validate that the response has been sent in wp-admin

#### TC 2 Failure case
1. Open review details
2. Tap on "reply"
3. Write a reply message
4. Turn off the internet connection
5. Press "Done"
6. See a snack bar with a failure message

### Images/gif

https://user-images.githubusercontent.com/5845095/208421965-39f4fdfd-96d7-4c15-a165-9988c00c7a17.mp4

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Review by ThomazFB — APPROVED** [review]
Tested and it's working nicely! I just noticed that the card UI is a bit different from the capture you placed in the PR description:



Would that be expected? It seems there's enough room for the buttons to span across a single horizontal row.

Also, one question that's more related to user experience but not necessarily something that should be tackled: Is it possible to mark the review as `replied`? This could make it easier for a merchant to keep track of replies in a long list of reviews.

**Comment by wzieba** [comment]
Thanks for the review!

> Would that be expected? It seems there's enough room for the buttons to span across a single horizontal row.

I agree, I'll work on that.

> Is it possible to mark the review as replied?

Unfortunately, it's challenging (internal: pe5pgL-Qm-p2). I followed iOS implementation and I think if we want to provide a good UX for this feature, we have to include some changes into Core endpoints (to include replies in Review Details).

**Comment by wzieba** [comment]
I just realized I forgot to address your comment @ThomazFB 🤦 sorry. I'll do this in a separate PR!

**Comment by wzieba** [comment]
hi @ThomazFB 👋 I was experimenting with this and I am thinking about leaving the view as it is.

I agree there's some space for making the buttons in one line, but a smaller screen size will also move buttons to the second line. I'll move to other priorities to not spend time on this, but generally this screen could use some UI rework - iOS looks better here. Maybe next HACK Week?

**Comment by ThomazFB** [comment]
@wzieba Yeah! This is not a priority at all! But thank you a lot for taking a look at it! We can leave it for a future HACK week! 😄

**Pull request merged**
