### PR TITLE
[REST API] Remove the need for cookie+nonce authentication for Jetpack activation process in REST API login flow.

### LINKED ISSUE #8749: [REST API] Improve connection phase without needing cookie nonce
This is to implement the solution outlined in pe5sF9-1le-p2#comment-1942

### PR DESCRIPTION
**Pull request by hafizrahman**
Closes: #8749 

> **Warning**
>  Please do not merge before the FluxC PR wordpress-mobile/WordPress-FluxC-Android#2707 is merged, and the FluxC version here is updated to match.

---

### Description

After adding the REST API login flow, we are exploring the possibility of exclusively using webview to generate application passwords for logging in, without any native login components that we currently use. In this scenario, the app no longer receives site credentials, so we cannot make API calls requiring cookie+nonce authentication.

This PR does two things to achieve that:

#### 1. Change Jetpack-related API calls that previously used cookie+nonce, to use application pasword.

At present, the Jetpack activation feature in the REST API login flow contains some functions involving cookie+nonce API calls:
1. Fetching the Jetpack connection URL,
2. Fetching the Jetpack user (through Jetpack connection data).

This PR, along with FluxC PR [wordpress-mobile/WordPress-FluxC-Android#2707](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2707), ensures that these two calls use application passwords instead. 

> **Note**
> Please note that the removal of cookie+nonce is only needed for REST API login flow. Fetching that uses cookie+nonce is still possible, to make sure [Jetpack installation in WPCom login flow](https://github.com/woocommerce/woocommerce-android/pull/7889) is still supported.

#### 2. Update the Jetpack Connection phase using an alternative solution that doesn't require cookie+nonce authentication.

The Jetpack Connection phase is updated in this PR to account for the removal of cookie+nonce authentication usage.

<details><summary>Read more for technical details.</summary>

The Jetpack activation flow consists of several hybrid steps:
1. Installation (native) ->
2. Activation (native) ->
3. Connection (webview, as native support is unavailable).

The Jetpack connection process must becompleted using a webview with a URL obtained from the fetch Jetpack connection URL call. In the past, as mentioned in [this issue](https://github.com/woocommerce/woocommerce-android/issues/7525) and [this PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2538), the method varied depending on whether the site already had a Jetpack site-connection or if Jetpack wasn't installed yet. If the site already had Jetpack, the retrieved URL could be used directly; otherwise, the app would register the site to Jetpack behind the scenes (using cookie+nonce authentication) to obtain a usable connection URL.

In the current PR, since cookie+nonce authentication is no longer desired, the approach for handling cases without Jetpack installed is adjusted. Instead of registering first (which is no longer possible), an alternative URL is used in the following format: `https://wordpress.com/jetpack/connect?url=[site_url]&mobile_redirect=woocommerce://jetpack-connected&from=mobile` This URL can be used without cookie+nonce authentication to support the connection process until completion. The connection is completed through a "mobile redirect," which the webview captures and returns the result to the app for further action. This alternative method is discussed internally in pe5sF9-1le-p2#comment-1942.

</details> 

---

### Testing instructions

1. Have a test .org site with WooCommerce, but no Jetpack installed,
2. Start app, login using site address,
3. Once logged in, on the My Store screen, tap the Jetpack benefits banner at the bottom,
4. On the Jetpack benefits screen, tap the "Log In to Continue" screen,
5. Ensure the WordPress.com email login screen is shown, enter email,
6. Ensure the password field is shown, enter the password there,
7. Ensure that the Jetpack Activation screen is shown, with the "Installing Jetpack" heading at the top,
8. Wait and ensure "Installing Jetpack" step completes,
9. Wait and ensure "Activating" step completes,
10. Wait and ensure "Connect store to Jetpack" opens a webview,
11. Follow the steps on the webview until connection is completed,
12. Ensure that the webview automatically closes,
13. Ensure that "Connect store to Jetpack" now says "Validating", wait until it completes,
14. Ensure that "All done" is checked afterward.
15. Ensure "Go to Store" button shows up,
16. Tap the button, ensure that you're now logged back in to the app. Now the app should be in the Jetpack/WordPress.com login state, so all functionalities should be available and the Jetpack banner on My Store is not shown anymore.

### Demo video

https://user-images.githubusercontent.com/266376/231725659-69e31a91-54d1-45e8-881f-58c5d16cffbd.mov

- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by hafizrahman** [comment]
The broken unit tests are unrelated to this PR, and already has fixes aimed for 13.2 ([this PR](https://github.com/woocommerce/woocommerce-android/pull/8703)).  **UPDATE**: this is no longer relevant.

**Review by 0nko — COMMENTED** [review]
d

**Review by 0nko — COMMENTED** [review]
I followed the instructions, however, I couldn't fully complete the activation. I'd get back to the login screen:

[activation.webm](https://user-images.githubusercontent.com/1522856/233182373-1958787d-db73-4dfe-a733-ddf1fba05605.webm)

The logcat showed this:
```
NetworkUtility.shouldRetryException: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1/devices/new/?device_token=doZXPDNSSQGYfd_-gvTaUX%3AAPA91bEYE_NRtl15H2qqzNWjbnWgLZ0vCJxkESb-5mwlocCP0L0Kto1w-C2TVk-oLQKozt_CJfwzExGgSZRFmriu2WPrYrwYh6bhvquQ9DkMNKmNbjqX1IKgBubXNID7xXcrsoxPXSnB&device_family=android&app_secret_key=com.woocommerce.android&device_name=Google%20sdk_gphone64_arm64&device_model=Google%20sdk_gphone64_arm64&app_version=13.1-rc-2&version_code=402&os_version=13&device_uuid=72d3d03d-6487-4af5-a278-01968434d6e8&locale=en_US
Volley error on https://public-api.wordpress.com/rest/v1/devices/new/?device_token=doZXPDNSSQGYfd_-gvTaUX%3AAPA91bEYE_NRtl15H2qqzNWjbnWgLZ0vCJxkESb-5mwlocCP0L0Kto1w-C2TVk-oLQKozt_CJfwzExGgSZRFmriu2WPrYrwYh6bhvquQ9DkMNKmNbjqX1IKgBubXNID7xXcrsoxPXSnB&device_family=android&app_secret_key=com.woocommerce.android&device_name=Google%20sdk_gphone64_arm64&device_model=Google%20sdk_gphone64_arm64&app_version=13.1-rc-2&version_code=402&os_version=13&device_uuid=72d3d03d-6487-4af5-a278-01968434d6e8&locale=en_US Status Code: 400

Error trying to register device: GENERIC_ERROR - Invalid request input
[118] NetworkUtility.shouldRetryException: Unexpected response code 404 for https://yummy-dove.jurassic.ninja/wp-json/wp/v2/plugins/jetpack/jetpack
Volley error on https://yummy-dove.jurassic.ninja/wp-json/wp/v2/plugins/jetpack/jetpack Status Code: 404
```

After I tried it again (after disconnecting Jetpack and deleting the plugin on the web), the app was in a bad state and I had to clear the cache to make it work like before.

[connected_before.webm](https://user-images.githubusercontent.com/1522856/233179918-d549781d-db2f-4d80-8050-86a859b3beff.webm)

**Comment by hafizrahman** [comment]
@0nko thank you for the review!

That's interesting. From the video between 0:27 to 0:28 I see that it first opens the Jetpack connect screen on webview (this is the `https://wordpress.com/jetpack/connect?url=<site_url>&mobile_redirect=woocommerce://jetpack-connected&from=mobile`):

Screenshot 2023-04-20 at 19 11 33

then it switches to the Jetpack plans page before the webview is dismissed:

Screenshot 2023-04-20 at 19 12 10

The Jetpack plans page is shown on the webview only when the connection process is completed, thus it's used as a success state where the app should close the webview and return to the install flow screen.

I'm curious why it's missing some steps on the video; for example, the webview doesn't ask you to enter your site credentials and to approve the connection manually, like on 1:03 on my demo video. 🤔  This might be a behavior on the `wordpress.com/jetpack/connect` page that I hadn't realized before. 

I did see that the webview might be behaving unexpectedly (sometimes redirecting to `woocommerce://` and sometimes to the plans page upon connection success), and this is why I added [cache clearing functionality](https://github.com/woocommerce/woocommerce-android/pull/8802/files#diff-565fabcc70406226a57849b454f5ba5154dc9629b373fc0e7fc3b42eb993d08fR127-R138) to hopefully make it be more consistent. But the behavior on the video is new to me.

As for the error messages:

```
Volley error on https://public-api.wordpress.com/rest/v1/devices/new/?device_token=doZXPDNSSQGYfd_-gvTaUX%3AAPA91bEYE_NRtl15H2qqzNWjbnWgLZ0vCJxkESb-5mwlocCP0L0Kto1w-C2TVk-oLQKozt_CJfwzExGgSZRFmriu2WPrYrwYh6bhvquQ9DkMNKmNbjqX1IKgBubXNID7xXcrsoxPXSnB&device_family=android&app_secret_key=com.woocommerce.android&device_name=Google%20sdk_gphone64_arm64&device_model=Google%20sdk_gphone64_arm64&app_version=13.1-rc-2&version_code=402&os_version=13&device_uuid=72d3d03d-6487-4af5-a278-01968434d6e8&locale=en_US Status Code: 400
Error trying to register device: GENERIC_ERROR - Invalid request input
```

I checked this on FluxC and this is only called by `NotificationRestClient`, so quite probably unrelated to this PR.

```
NetworkUtility.shouldRetryException: Unexpected response code 404 for https://yummy-dove.jurassic.ninja/wp-json/wp/v2/plugins/jetpack/jetpack
Volley error on https://yummy-dove.jurassic.ninja/wp-json/wp/v2/plugins/jetpack/jetpack Status Code: 404
```

This is related to `pluginRepository.installPlugin()` that's called in `startJetpackInstallation()` in JetpackActivationViewModel. The install process tries to fetch plugin info from that endpoint and somehow got 404 (maybe the site was temporarily down at the moment?) In any case, in the event of failure, the app will [proceed to install the plugin anyway](https://github.com/woocommerce/woocommerce-android/blob/e93ff7810368300596dc7fd1686c40f5a008dc1d/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/common/PluginRepository.kt#L95), which I could see also happen on your video around 0:23.

---

So at this point I think the only issue here is the webview behavior. I'm not super sure why this is the case, do you mind retrying with a fresh new site and let me know how it goes? If it also still breaks, can you also share the app log so I can figure things out further? Thank you!

**Comment by 0nko** [comment]
Yeah, it's weird. I tried it again with a fresh jurassic ninja installation with the same result:

[jetpack.webm](https://user-images.githubusercontent.com/1522856/233507300-769157db-9d9d-429b-b398-76c27f95d2ca.webm)

Log:
```
[Apr-20 19:55 WP d] DB Updating site: https://miniature-otter.jurassic.ninja
[Apr-20 19:55 PLUGINS d] Plugin jetpack installed successfully
[Apr-20 19:55 PLUGINS d] Plugin jetpack activated successfully
[Apr-20 19:55 LOGIN d] Jetpack Activation: handle step: Connection
[Apr-20 19:55 LOGIN d] Jetpack Activation: start Jetpack Connection
[Apr-20 19:55 LOGIN d] Fetching Jetpack Connection URL
[Apr-20 19:55 WP d] API JetpackStore: fetchJetpackConnectionUrl
[Apr-20 19:56 LOGIN d] Jetpack connection URL fetched successfully
[Apr-20 19:56 UTILS i] 🔵 Tracked: back_pressed, Properties: {"context":"MainActivity","is_debug":true}
[Apr-20 19:56 UTILS i] 🔵 Tracked: jetpack_setup_login_flow, Properties: {"step":"password","tap":"submit","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:56 LOGIN i] Signing in using WPCom email or username: oruttkay@gmail.com
[Apr-20 19:56 WP d] API Dispatching action: AuthenticationAction-AUTHENTICATE
[Apr-20 19:56 WP d] API Dispatching action: AccountAction-FETCH_ACCOUNT
[Apr-20 19:56 LOGIN i] Authentication Succeeded for user null
[Apr-20 19:56 WP d] API Dispatching action: AccountAction-FETCH_ACCOUNT
[Apr-20 19:56 WP d] API Dispatching action: AccountAction-FETCHED_ACCOUNT
[Apr-20 19:56 WP d] API Dispatching action: AccountAction-FETCHED_ACCOUNT
[Apr-20 19:56 UTILS d] Current FCM token: cnY7GSd0QyyTKoJvQmh5BT:APA91bE9YqOgcoG1_TxHJe_H7ze8jU8ldHaxn9E6y5ibmPlNeUE9ftkdKOW-DpIsZixKlO1yb8FYU22ASx5lzscFOECEQCj1bqOBoh4Y1TdtArKKdP4xNIO2xhYhks7zfIvumJn8bLey
[Apr-20 19:56 UTILS i] 🔵 Tracked: jetpack_setup_login_completed, Properties: {"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:56 LOGIN d] Jetpack Activation: handle step: Installation
[Apr-20 19:56 LOGIN d] Jetpack Activation: start Jetpack Installation
[Apr-20 19:56 UTILS d] Current FCM token: cnY7GSd0QyyTKoJvQmh5BT:APA91bE9YqOgcoG1_TxHJe_H7ze8jU8ldHaxn9E6y5ibmPlNeUE9ftkdKOW-DpIsZixKlO1yb8FYU22ASx5lzscFOECEQCj1bqOBoh4Y1TdtArKKdP4xNIO2xhYhks7zfIvumJn8bLey
[Apr-20 19:56 PLUGINS d] Installing plugin Slug: jetpack, Name: jetpack/jetpack
[Apr-20 19:56 PLUGINS d] Fetching plugin jetpack/jetpack
[Apr-20 19:56 WP d] API Dispatching action: PluginAction-FETCH_SITE_PLUGIN
[Apr-20 19:56 WP d] PLUGINS PluginCoroutineStore: Fetching WPAPI plugin
[Apr-20 19:56 PLUGINS d] Fetching plugin succeeded, plugin is:Installed
[Apr-20 19:56 PLUGINS d] Plugin jetpack is already installed and activated
[Apr-20 19:56 LOGIN d] Jetpack Activation: handle step: Connection
[Apr-20 19:56 LOGIN d] Jetpack Activation: start Jetpack Connection
[Apr-20 19:56 LOGIN d] Fetching Jetpack Connection URL
[Apr-20 19:56 WP d] API JetpackStore: fetchJetpackConnectionUrl
[Apr-20 19:56 LOGIN d] Jetpack connection URL fetched successfully
[Apr-20 19:57 UTILS i] 🔵 Tracked: jetpack_setup_login_flow, Properties: {"step":"password","tap":"submit","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 LOGIN i] Signing in using WPCom email or username: oruttkay@gmail.com
[Apr-20 19:57 WP d] API Dispatching action: AuthenticationAction-AUTHENTICATE
[Apr-20 19:57 WP d] API Dispatching action: AccountAction-FETCH_ACCOUNT
[Apr-20 19:57 LOGIN i] Authentication Succeeded for user null
[Apr-20 19:57 WP d] API Dispatching action: AccountAction-FETCH_ACCOUNT
[Apr-20 19:57 WP d] API Dispatching action: AccountAction-FETCHED_ACCOUNT
[Apr-20 19:57 WP d] API Dispatching action: AccountAction-FETCHED_ACCOUNT
[Apr-20 19:57 UTILS d] Current FCM token: cnY7GSd0QyyTKoJvQmh5BT:APA91bE9YqOgcoG1_TxHJe_H7ze8jU8ldHaxn9E6y5ibmPlNeUE9ftkdKOW-DpIsZixKlO1yb8FYU22ASx5lzscFOECEQCj1bqOBoh4Y1TdtArKKdP4xNIO2xhYhks7zfIvumJn8bLey
[Apr-20 19:57 UTILS i] 🔵 Tracked: jetpack_setup_login_completed, Properties: {"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 LOGIN d] Jetpack Activation: handle step: Installation
[Apr-20 19:57 LOGIN d] Jetpack Activation: start Jetpack Installation
[Apr-20 19:57 UTILS d] Current FCM token: cnY7GSd0QyyTKoJvQmh5BT:APA91bE9YqOgcoG1_TxHJe_H7ze8jU8ldHaxn9E6y5ibmPlNeUE9ftkdKOW-DpIsZixKlO1yb8FYU22ASx5lzscFOECEQCj1bqOBoh4Y1TdtArKKdP4xNIO2xhYhks7zfIvumJn8bLey
[Apr-20 19:57 PLUGINS d] Installing plugin Slug: jetpack, Name: jetpack/jetpack
[Apr-20 19:57 PLUGINS d] Fetching plugin jetpack/jetpack
[Apr-20 19:57 WP d] API Dispatching action: PluginAction-FETCH_SITE_PLUGIN
[Apr-20 19:57 WP d] PLUGINS PluginCoroutineStore: Fetching WPAPI plugin
[Apr-20 19:57 PLUGINS d] Fetching plugin succeeded, plugin is:Installed
[Apr-20 19:57 PLUGINS d] Plugin jetpack is already installed and activated
[Apr-20 19:57 LOGIN d] Jetpack Activation: handle step: Connection
[Apr-20 19:57 LOGIN d] Jetpack Activation: start Jetpack Connection
[Apr-20 19:57 LOGIN d] Fetching Jetpack Connection URL
[Apr-20 19:57 WP d] API JetpackStore: fetchJetpackConnectionUrl
[Apr-20 19:57 LOGIN d] Jetpack connection URL fetched successfully
[Apr-20 19:57 UTILS i] 🔵 Tracked: jetpack_setup_login_flow, Properties: {"step":"password","tap":"dismiss","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 UTILS i] 🔵 Tracked: jetpack_setup_login_flow, Properties: {"step":"email_address","tap":"dismiss","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 WP d] API JitmStore: jitm
[Apr-20 19:57 UTILS i] 🔵 Tracked: dashboard_main_stats_date, Properties: {"range":"days","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 UTILS i] 🔵 Tracked: dashboard_top_performers_date, Properties: {"range":"days","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 UTILS i] 🔵 Tracked: feature_jetpack_benefits_banner, Properties: {"action":"shown","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 UTILS i] 🔵 Tracked: store_onboarding_shown, Properties: {"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"MyStoreFragment","is_debug":true}
[Apr-20 19:57 ONBOARDING d] Fetching onboarding tasks
[Apr-20 19:57 WP d] API OnboardingStore: fetchOnboardingTasks
[Apr-20 19:57 ONBOARDING d] Success fetching onboarding tasks
[Apr-20 19:57 UTILS i] 🔵 Tracked: jitm_fetch_success, Properties: {"source":"my_store","jitm":"null","count":0,"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 JITM i] No JITM Campaign in progress
[Apr-20 19:57 UTILS i] 🔵 Tracked: dashboard_pulled_to_refresh, Properties: {"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 WP d] API WCStatsStore: fetchRevenueStats
[Apr-20 19:57 WP d] API WCOrderStore: fetchHasOrders
[Apr-20 19:57 ONBOARDING d] Fetching onboarding tasks
[Apr-20 19:57 WP d] API OnboardingStore: fetchOnboardingTasks
[Apr-20 19:57 WP d] API JitmStore: jitm
[Apr-20 19:57 WP d] API WCLeaderboardsStore: fetchLeaderboards
[Apr-20 19:57 UTILS i] 🔵 Tracked: dashboard_main_stats_loaded, Properties: {"range":"days","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 UTILS i] 🔵 Tracked: dashboard_top_performers_loaded, Properties: {"range":"days","blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 ONBOARDING d] Success fetching onboarding tasks
[Apr-20 19:57 UTILS i] 🔵 Tracked: jitm_fetch_success, Properties: {"source":"my_store","jitm":"null","count":0,"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 JITM i] No JITM Campaign in progress
[Apr-20 19:57 UTILS i] 🔵 Tracked: main_tab_hub_menu_selected, Properties: {"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 UTILS d] Reduced image disk cache to 62,337MB (193,662MB smaller)
[Apr-20 19:57 UTILS i] 🔵 Tracked: hub_menu_settings_tapped, Properties: {"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:57 WP d] API WhatsNewStore: fetchWhatsNew
[Apr-20 19:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"AppSettingsActivity","is_debug":true}
[Apr-20 19:57 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"MainSettingsFragment","is_debug":true}
[Apr-20 19:57 WP d] API WhatsNewStore: fetchWhatsNew
[Apr-20 19:58 UTILS i] 🔵 Tracked: main_menu_contact_support_tapped, Properties: {"blog_id":0,"is_wpcom_store":false,"is_debug":true}
[Apr-20 19:58 SUPPORT i] Fetching SSR
[Apr-20 19:58 WP d] API WooCommerceStore: fetchSSR
[Apr-20 19:58 UTILS i] 🔵 Tracked: view_shown, Properties: {"name":"HelpActivity","is_debug":true}
[Apr-20 19:58 WP e] API Volley error on https://miniature-otter.jurassic.ninja/wp-json/wc/v3/system_status/?_fields=environment%2Cdatabase%2Cactive_plugins%2Ctheme%2Csettings%2Csecurity%2Cpages Status Code: 503 - exception: null
[Apr-20 19:58 WP e] API StackTrace: com.android.volley.ServerError
	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:201)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

[Apr-20 19:58 WP w] API org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
[Apr-20 19:58 SUPPORT e] Error fetching SSR
[Apr-20 19:58 UTILS i] 🔵 Tracked: support_application_log_viewed, Properties: {"is_debug":true}
[Apr-20 19:58 DEVICE w] OS: 13
DeviceName: Google sdk_gphone64_arm64
Language: English
```

I'll add you to the site.

**Comment by 0nko** [comment]
@hafizrahman I found what the issue was -- after the site connection is successful, the WebView triggers the exit event multiple times. So not only is the WebView closed, also the Jetpack installation screen is exited so it can't finish the setup. I added a flag to check for this and it works correctly now.

**Review by 0nko — APPROVED** [review]
:shipit:

**Pull request merged**
