### PR TITLE
Unified Login: Jetpack not connected error screens

### LINKED ISSUE #2657: Unified Login: Jetpack not connected screen
The following error screens will need to be updated to match the new themes and styling:

- Jetpack not connected

Screen Shot 2020-09-02 at 5 04 10 PM

### PR DESCRIPTION
**Pull request by AmandaRiu**
Closes #2657 by implementing new designs and button options on the "Jetpack not connected" screen:

Light | Dark
-- | --
Screenshot_1599080606|Screenshot_1599080612

## To Test
1. Tap **Enter your store address**
2. Enter a store address where Jetpack is either not installed or not active/connected.
3. Verify the Jetpack Required screen is displayed (see screenshot above)
4. Verify store address populates in the message.
5. Click **What is Jetpack** and verify the "What is jetpack" dialog appears. Close dialog.
6. Tap **Learn how to install and connect Jetpack** and verify help page loaded successfully
7. Tap to go back to Jetpack required screen.
8. Tap **Log in with another account** - verify routed back to the login prologue screen

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ThomazFB** [comment]
Hey @AmandaRiu, awesome work here! The code is looking good, functionality, UI and Dark Mode looks just fine too! I've just noticed one problem with the `Jetpack required` screen:

screencap-2020-09-04T054707 690Z

When using in the landscape mode, the main text goes to the limits of the screen and seen to not follow the same margin of the back arrow and the bottom buttons. 

Also, just to confirm, I've noticed that the center image and the image for the `What is Jetpack?` Dialog doesn't appear in landscape mode, I suppose this is intentional for best UI fit?

screencap-2020-09-04T055332 015Z

**Comment by AmandaRiu** [comment]
@ThomazFB Thanks for the review and awesome catch! I've fixed this issue in 8b6ed10194187436476540b68390cf14b2375096

> Also, just to confirm, I've noticed that the center image and the image for the What is Jetpack? Dialog doesn't appear in landscape mode, I suppose this is intentional for best UI fit?

Yup, the images are purposely left out in landscape view. 👍 

Ready for another round!

**Comment by loremattei** [comment]
Hi there! I'm moving this to 5.1 because 5.0 has been cut. If you want this to make it to 5.0, please feel free to ping me.

**Comment by ThomazFB** [comment]
Hey @AmandaRiu, thanks for that change! Everything is working just fine now! LGTM :shipit:

**Pull request merged**
