### PR TITLE
Track errors when failing to load suggestions in Blaze campaign creation

### LINKED ISSUE #12878: Track errors when failing to load content from Blaze dsp
We noticed when there are Jetpack sync issues, Blaze feature is impacted and the campaign creation flow will fail. Request such loading ad `/suggestions` will return errors like: 

```json
{"message":"Unexpected Server Error","errorMessage":"Request failed with status code 404","stack":["AxiosError: Request failed with status code 404","    at settle (\/app\/dsp\/node_modules\/axios\/lib\/core\/settle.js:19:12)","    at BrotliDecompress.handleStreamEnd (\/app\/dsp\/node_modules\/axios\/lib\/adapters\/http.js:585:11)","    at BrotliDecompress.emit (node:events:529:35)","    at endReadableNT (node:internal\/streams\/readable:1400:12)","    at processTicksAndRejections (node:internal\/process\/task_queues:82:21)"]}
```

Add tracking to this type of errors to monitor how often they happen. Currently we are on the dark with this. We had a couple discussion but could not figure out what caused the sync issues, so let's try to figure out if this is something users are experiencing or if its only devs on their test sites experiencing this.

New Event: `_blaze_suggestions_loading_failed`
Property: `error_type` | $errorMessageValue

Equivalent issue on iOS: https://github.com/woocommerce/woocommerce-ios/issues/14337

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Closes: #12878

### Description

This PR adds tracking to errors when fetching suggestion for a Blaze ad. 

### Steps to reproduce
To reproduce the error where fetching suggestions fail to load, you have to create a scenario where Jetpack sync issues happen. I followed the next steps to create a Jetpack Sync issues: 
1. Create jurassic ninja site with WooCommerce and Jetapack
2. Connect Jetpack
3. dd a few products (I used smooth generator) 
4. Disconnect Jetpack from your account. Jetpack > My Jetpack > scroll down and click `Manage` > Disconnect Jetpack
5. Add some more products to your site (remember which are the new products you are adding in this step) 
6. Connect Jetpack again to the same account you connected it before
7. Attempt to create a Blaze campaign for one of the products you added in step 5
8. Loading the suggestions will fail with the following error: 
```json
{"message":"Unexpected Server Error","errorMessage":"Request failed with status code 404","stack":["AxiosError: Request failed with status code 404","    at settle (\/app\/dsp\/node_modules\/axios\/lib\/core\/settle.js:19:12)","    at BrotliDecompress.handleStreamEnd (\/app\/dsp\/node_modules\/axios\/lib\/adapters\/http.js:585:11)","    at BrotliDecompress.emit (node:events:529:35)","    at endReadableNT (node:internal\/streams\/readable:1400:12)","    at processTicksAndRejections (node:internal\/process\/task_queues:82:21)"]}
```

If you can't reproduce this error or don't want to follow these steps ping me and I'll invite you to `https://traditional-sable-finfoot.jurassic.ninja/` which is already experiencing the Jetpack sync issue.

### Testing information
1. Follow the steps above
2. Attempt to create a Blaze campaign for a product that is not synced (step 5 products)
3. When suggestions fail to load check logcat to verify the following event is tracked: 
```
🔵 Tracked: blaze_suggestions_loading_failed, Properties: {"error":"Unexpected Server Error",
```

### The tests that have been performed

The above

https://github.com/user-attachments/assets/8e1c0324-475c-44e5-9d61-ad31d1663563

This is an internal tracking change no need to add anything to release notes. 

- [X] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/244">21.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false"><p>This PR contains changes to Tracks-related logic. Please ensure (<strong>author and reviewer</strong>) the following are completed:</p>

<ul>
  <li>The tracks events must be validated in the Tracks system.</li>
  <li>Verify the internal Tracks spreadsheet has also been updated.</li>
  <li>Please consider registering any new events.</li>
  <li>The PR must be assigned the <strong>category: tracks</strong> label.</li>
</ul></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by irfano — APPROVED** [review]
LGTM! 👍🏻 I’m approving, but I have a few questions:
- Do you know why I can't see `woocommerceandroid_blaze_suggestions_loading_failed` in the Tracks Live View or Events? 
- The auto-message suggested that “The tracks events must be validated in the Tracks system.” Should we validate all newly added events?

**Comment by JorgeMucientes** [comment]
Hey @irfano great questions! Thanks for bringing those up.

> Do you know why I can't see woocommerceandroid_blaze_suggestions_loading_failed in the Tracks Live View or Events?

Hmm, that's interesting. Afaik the live view should show the tracked events even if the app is `DEBUG` build. I did notice that the live view takes around 5-10 mins to display the events tracked. Did you wait that long? Although when I looked for `woocommerceandroid_blaze_suggestions_loading_failed` in the events section, there are no results showing there, which is weird since the events we fired for testing should show there. I wonder if the event is only `is_debug: true` it doesn't show up in the events panel? But I think that'd be really strange because I checked other events and is showing results for both debug and production builds. 

> The auto-message suggested that “The tracks events must be validated in the Tracks system.” Should we validate all newly added events?

I think we should. Good reminder. I tried starting the event validation process, but since there aren't any tracked instances of it I don't think I can complete it. I'll look into this to figure out why `woocommerceandroid_blaze_suggestions_loading_failed` is not showing up on tracks

**Comment by irfano** [comment]
> Did you wait that long?

Yes, I did. Thank you for investigating this further.
For further discussion: p1731584513235259-slack-C03L1NF1EA3

**Pull request merged**
