### PR TITLE
Merge 8.0 code freeze into develop

### PR DESCRIPTION
**Pull request by jkmassel**
Merges the `8.0` code freeze into `develop`, including:
- Using production dependencies
- Version bumps
- Translation Additions

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
- [x] New version header in `RELEASE-NOTE.txt` 
- [x] Version updates in `build.gradle`
- [x] `release_notes.txt` updated with notes from `RELEASE-NOTE.txt` for current version 
- [x] `strings.xml` updates via automation merging values from libraries
- [x] Switched `ext` versions to production

**Comment by mokagio** [comment]
I approved this PR before noticing the CI failures 😳 🤔 

I restarted the build, just in case, let's see...

**Comment by mokagio** [comment]
My rebuild failed. I won't dismiss my review because, even though it's an approval, we can't merge till CI is green.

**Comment by mokagio** [comment]
More info: The app builds fine locally for me on this branch, but when I run the tests I get the following error:

```
e:
  /Users/gio/Developer/a8c/wcandroid/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/tracking/
    OrderShipmentProvidersRepository.kt: (60, 54):
      Unresolved reference: newFetchOrderShipmentProvidersAction
```

**Comment by jkmassel** [comment]
Waiting on #5224

**Comment by mokagio** [comment]
@jkmassel should we ask for that PR to point to the release branch, or do you plan on cherry-picking?

**Pull request merged**
