### PR TITLE
Fixes disappearance of the "collect payment" button on the Order detail screen

### LINKED ISSUE #5048: If a card present payment fails with any error. The option to collect payment is removed when we refresh Order detail screen
**To Reproduce**

1. Create a situation where payment will fail (i.e. a [decimal stock quantity](https://wordpress.org/plugins/wpc-product-quantity/) is used). You can install and activate a plugin that supports decimal quantities, such as WPC Product Quantity for WooCommerce. To use this plugin as an example, go to WP Admin > WPClever > Product Quantity, change Decimal Quantities to Yes, add 0.5 for Minimum, Step, and Default.
2. On the web, submit an order containing a product with a decimal stock quantity.
3. In the app, open the order.
4. Tap the "Collect Payment" button and tap the test card to the reader.
5. Observe the error message
6. Pull-to-refresh on the order details screen.
7. Try to collect the payment again.

**Result:** when a payment fails with the unexpected error, the "Collect Payment" button turns back into an "Issue Refund" button and you become stuck awaiting payment but there is no longer an option to collect payment

### PR DESCRIPTION
**Pull request by AnirudhBhat**
Closes: #5048 

### Description

This PR fixes the disappearance of the "collect payment" button on the Order detail screen when the payment fails for any reason

Here is what was happening before this PR
1. Make the payment fail. For example, create any order with decimal quantity (#5048 has more detail on how to do this)
2. Try to collect payment from the order detail screen
3. Payment fails
4. Now, try to refresh the order detail screen
5. Collect payment button was disappearing

Because backend sends paymentMethod as "woocommerce_payments" after payment failure. `CardReaderPaymentCollectibilityChecker.kt` does not know how to handle this payment method and thus, it makes this order in-eligible for IPP.  Thus, it hides the collect payment button

This PR fixes it

### Simulating the Card reader
1. Go to the app's `build.gradle` file
2. Replace `project.hasProperty("useSimulatedReader").toString()` with `true`

### Criteria for a store and an order to be eligible for IPP
1. Store must have WCPay plugin installed 
2. Store's default address has to be a USA address
3. The order has to be COD

PdfdoF-V-p2 Here is an In-person payments FAQ that has more info on setting up the store and everything related to IPP. 

If you have any questions. Hit me up!

### Testing instructions

1. Create any order with decimal quantity
2. Try to collect payment from the order detail screen
3. Payment fails
4. Now, try to refresh the order detail screen
5. Make sure that the Collect payment button is showing

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by JorgeMucientes** [comment]
@AnirudhBhat Code changes look good 👍🏼 , but I was not able to reproduce the bug or test the fix. I followed instructions from #5048, set up the store to US and placed an order with decimal quantity and COD. But I never saw the pay button in the order details: 
image

Maybe a second pair of eyes with IPP properly set up could be good to test the fix

**Review by JorgeMucientes — APPROVED** [review]

**Comment by AnirudhBhat** [comment]
Thank you for the review @JorgeMucientes! Regarding the "Collect payment" button not being visible for you. Just to double confirm, have you got the WCPay plugin installed for your store?

**Comment by JorgeMucientes** [comment]
Yes I do have WcPay enabled on my store. I have the test mode enabled though. I don't know if that may have any effect. 
Also, I'm not sure I comply with this first option:
Screenshot 2021-10-22 at 15 13 32

Do I have to set up anything special?

**Comment by AnirudhBhat** [comment]
@JorgeMucientes Since we have launched IPP to all the US merchants. If your store address is in the US, you will automatically be eligible for IPP. (In `FeatureFlag.kt` file, we return `true` for card reader feature)
If you navigate to settings from `My store`. I believe you are not seeing any In-Person-payments related option there as well. Correct?

You can set a debug pointer in `CardReaderPaymentCollectibilityChecker` and navigate to Order Detail Screen and see why exactly is it failing for you.

Ahh, I believe your store's currency is the problem here. Can you please set it to USD and see if it works?

**Comment by JorgeMucientes** [comment]
Hi @AnirudhBhat I think the problem is my test store location is not being updated after applying changes to the store address from woo-admin. I've set a USA address for my store as well as $ currency and saved the changes. The $ currency update is properly reflected, but the app still considers my shop is in Spain. My guess is that it considers it a spanish merchant because it's using my payment details from WcPay -> Stripe. So basically the error for the store is that is not a US merchant

https://user-images.githubusercontent.com/2663464/138655576-605b8505-e417-4cc8-b4b1-ce603b499594.mp4

This is my shop address configuration: 

Screenshot 2021-10-25 at 09 49 10

But as suggested, I think for IPP is not taking into account those adress details, but the ones used in Stripe when setting up WooCommerce Payments.

What I did is create a new account, setting everything from sratch like I was a US merchant. But I'm stuck. I first got this error: 



Then I disabled test mode and got this other error: 



I suspect is because my details when setting Wcpay using Stripe are not properly validated, which is to be expected as I used fake data as input since I don't have a US identity. 

Screenshot 2021-10-25 at 10 30 18

I click edit details and go over to Stripe setup, where my social security number can't be validated and that is probably why WcPayments are restricted. 

Screenshot 2021-10-25 at 10 30 30


So I'm kind of stuck here. I don't know if there is a way to setup WcPay as a US merchant to test this.

**Comment by malinajirka** [comment]
@JorgeMucientes Hi there 👋, thanks for going far and beyond setting up your store and investigating why it doesn't work as expected! You are on the right track, both Stripe and Store address needs to be set to a valid US address. I'll dm you an instructions guide on how to set up a store even when you don't have a US address - the main trick is to use [WCPay dev plugin](https://github.com/Automattic/woocommerce-payments-dev-tools). More details in the dm :).

**Comment by JorgeMucientes** [comment]
@AnirudhBhat I was finally able to test it 🥳  Works fine! Thanks for the help in setting it up @AnirudhBhat and @malinajirka 

:shipit:

**Pull request merged**
