### PR TITLE
[Mobile Payments] Not possible to fix some onboarding errors via authenticated webview as stripe embedded window is not opening

### LINKED ISSUE #12907: [Mobile Payments] Not possible to fix some onboarding errors via authenticated WebView
It looks like some time ago, the Stripe site started to open in a pop-up in a browser, and our authenticated web view doesn't support it on Android, so a user ends up in an endless loading state. Check the video for a better understanding.

https://github.com/user-attachments/assets/440885c9-7bb4-4cd0-b7d8-fd1bad84cf15

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #12907

### Description

It looks like some time ago, the stripe site started to open in a pop-up in a browser (I validated that in a desktop browser), and our authenticated web view doesn’t support it on Android, so a user ends up in an endless loading state.

The PR replaces authenticated web view with chrome tabs, which means that if a user is not logged in in a browser, then they will need to enter their credentials. I could not make it work with webview

### Steps to reproduce

On the web wp-admin:
* Payments -> Overview -> reset account to simulate "WC_PAY_NOT_SETUP" error

In The app:
* More -> Payments -> Click on the error at the bottom -> Try to finish onboarding on the web
* Notice that at some point, nothing happens as stripe web page could not be open

### The tests that have been performed

The steps from the steps to reproduce

### Images/gif

https://github.com/user-attachments/assets/dea433fe-edc3-4987-a935-47532498141a

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [x] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/244">21.2</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by AnirudhBhat** [comment]
Thanks for working on this @kidinov 

I tried the steps to reproduce on `trunk` and I could see the onboarding screens. If I understand correctly, the onboarding on web view from `trunk` should be broken right? Let me know if I'm doing something wrong.

https://github.com/user-attachments/assets/3380ef40-fe28-441b-844c-65113b55c47b


I also tried to run this change on tablet device (Emulator) from this branch and the onboarding on web view very slow and didn't load the screens properly. On the phone, it worked just fine

https://github.com/user-attachments/assets/589aa13d-cb20-4337-8b70-26a069dce35f

**Comment by kidinov** [comment]
@AnirudhBhat 👋

It looks like that you use not wpcom site that's why chrome tab used instead of webview and therefore that worked fine

https://github.com/woocommerce/woocommerce-android/pull/12917/files#diff-d0d7f8bc957e25d0d4eb0980bfeda1d2de0d4a6ad7853ce4d46426cbe616d9bfL91

**Comment by AnirudhBhat** [comment]
>It looks like that you use not wpcom site that's why chrome tab used instead of webview and therefore that worked fine

Ah. Got it 👍 

> also tried to run this change on tablet device (Emulator) from this branch and the onboarding on web view very slow and didn't load the screens properly. On the phone, it worked just fine

Is the change from this PR working fine on tablet (emulator) for you? It works fine on phone whereas on tablet, it throws some error as seen in the video.

**Review by AnirudhBhat — APPROVED** [review]
Thanks for working on this @kidinov. The changes looks good to me. It works as expected on phone whereas on tablet (emulator), the onboarding page throws some error.

I'll be AFK today. Tagging @samiuelson so that he can look if there are any further changes done to this PR. Thanks!

**Comment by kidinov** [comment]
@AnirudhBhat 

> the onboarding page throws some error.

The web page throws an error? What error?

**Comment by AnirudhBhat** [comment]
>The web page throws an error? What error?


You can see it [here](https://github.com/woocommerce/woocommerce-android/pull/12917#issuecomment-2473220443) (second video from tablet). 

"Data layer message channel was not initialised within 1000ms"

**Comment by kidinov** [comment]
@AnirudhBhat, Oh, I see. it looks like that tablet has some issues with the connection

**Comment by kidinov** [comment]
@AnirudhBhat could you please go through the checklist?

**Pull request merged**
