### PR TITLE
Fix FluxC room injection module

### LINKED ISSUE #4591: [Product Add-ons] [FluxC] Refactor single Product addons storage to match Global addons table structure
Currently, we're storing addons as a JSON string inside FluxC `WCProductModel` class and we serialize it to an object when the property gets called:
https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/5c420b05cfff5b44e66d1b538ded7a11c5642188/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/model/WCProductModel.kt#L113

Our objective here is that once #4410 is complete, we want to stop doing the JSON string strategy and store all Product addon data at the same table of Global addons, normalizing how every addon info is fetched at database level.

image

### PR DESCRIPTION
**Pull request by ThomazFB**
#Summary

This PR is just an adjustment for the code introduced at FluxC on this PR: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2102. Tests require just that the app builds as expected, Nothing else.

⚠️ This PR must be merged right after the mentioned above, so if possible I would like to ask to just approve this one and I can merge both at the right moment. Thanks!

- [X] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@ThomazFB I'm seeing this error when I try to build the app. I've invalidated caches and restarted but that didn't help. Am I missing something in the configuration?

Screen Shot 2021-08-24 at 2 55 27 PM

**Comment by ThomazFB** [comment]
Hey @nbradbury, thanks so much for taking this PR right away! 

> I'm seeing this error when I try to build the app. I've invalidated caches and restarted but that didn't help. Am I missing something in the configuration?

This is weird 🤔, I can inspect the `RoomDatabase` inside my Woo project here, and CI seems to find everything with no issues. 

image


I decided to check if the fluxc `build.gradle` file contains the correct dependencies and looks fine too as you can see here:

https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/fd19515fd6de758f9b922495592b3b7b5d147834/fluxc/build.gradle#L88

Maybe your project is still pointing to the incorrect FluxC artifact? Could you try to run `gradle cleanBuildCache` to see if the FluxC version is updated?

**Comment by nbradbury** [comment]
> Could you try to run `gradle cleanBuildCache` to see if the FluxC version is updated?

Unfortunately, that didn't fix it. So it builds fine for you?

**Comment by nbradbury** [comment]
@ThomazFB I added the Room dependencies to WCAndroid's `build.gradle` and now the app builds fine. 🤷

**Comment by ThomazFB** [comment]
@nbradbury this is so weird 😰, I'm trying to clear everything in order to see if I also reproduce this problem, but Room gets imported as transitive dependency from FluxC, it should work for you too 🤔

@shiki since you're around, could you also try to build this branch and see if something happens?

**Comment by shiki** [comment]
@ThomazFB I'm getting the same error as Nick: 

image

**Comment by ThomazFB** [comment]
OK, after some investigation I found some possible culprits, but I still can't reproduce this Room dependency problem in my machine and I am not sure about what's really happening. I see that the card reader lib already imports the commons lib from Room, so it could be a conflict issue, but since I can't test if it solves the problem or not. 

Considering this, I would like to ask for more people from our @woocommerce/android-developers team to help with possible solutions on what could be causing this, and if someone who can reproduce the issue could verify if there's indeed a library conflict happening here.

**Comment by hichamboushaba** [comment]
I tried to build the application from this branch on my machine, and it worked without issues.
But StackOverflow has some questions of people facing the same issue as @nbradbury and @shiki, and the suggestion is to either use `api` in the Room declaration in FluxC, or add Room as a dependency to the app itself (https://stackoverflow.com/questions/63557547/dao-injection-problem-roomdatabase-not-found-with-hilt-android)

I think re-cloning the project from scratch would confirm if the issue is related to something specific to the machine or not 🤔

**Comment by shiki** [comment]
Thanks, @hichamboushaba. 

I used the [the commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2102/commits/b3bf064883f4dcfa9fba2a69dea288727980d1af) that uses `api` and it looks like the build is successful. I had to invalidate the cache in Android Studio first though. 

```
git diff
diff --git a/build.gradle b/build.gradle
index ac36d15ed..b30930b70 100644
--- a/build.gradle
+++ b/build.gradle
@@ -94,7 +94,7 @@ tasks.register("installGitHooks", Copy) {
 }
 
 ext {
-    fluxCVersion = '2102-47f5ab4f3a57b9c8e455db9379fed45f26338bde'
+    fluxCVersion = '2102-b3bf064883f4dcfa9fba2a69dea288727980d1af'
     glideVersion = '4.12.0'
     testRunnerVersion = '1.0.1'
     espressoVersion = '3.3.0'
```

**Comment by ThomazFB** [comment]
I can thank enough you both, @hichamboushaba and @shiki! Life savers! 🙇

**Review by shiki — APPROVED** [review]
I retested this with the recent commit (b865a41de32ea57660414bcd64357a092343f5c4). I invalidate the cache and rebuilt. Still working fine. 

Thank you, everyone, for the help!

**Pull request merged**
