### PR TITLE
Refund detail screen

### LINKED ISSUE #1264: New Refund Details screen
A new Refund Details contains the amount and reason for a refund. It can be accessed by tapping the **View details** in the Order details, under the Refunded section.

image

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #1264. The order detail screen lists all issued refunds and allows to see the details of a particular refund. If the refunds can't be loaded, the refund total is displayed instead.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by nbradbury** [comment]
@0nko The first time I ran this I got a "no such table" crash. Clearing storage fixed it, but I wanted to mention this in case it points to a real problem.

```
Process: com.woocommerce.android, PID: 17436
    android.database.sqlite.SQLiteException: no such table: Refunds (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM Refunds WHERE (LOCAL_SITE_ID = ? AND ORDER_ID = ?)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
``

**Comment by 0nko** [comment]
@nbradbury Thanks for the report. I found the problem and I fixed it in the [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1381/commits/3d40a6260fe54aa09d361db3efb002bb6e0a46eb). 

I assumed that that table is automatically created if it doesn't exits, which it is, but only when the app is run for the first time when the DB is created.

**Comment by 0nko** [comment]
I agree, but that's what the API is returning for the method - `Credit Card (Stripe)`.

**Comment by nbradbury** [comment]
> I agree, but that's what the API is returning for the method - `Credit Card (Stripe)`.

Ah, in that case perhaps we should summon @kyleaparker and ask if we should get rid of the other parens (maybe just separate "View details" with a dash)?

**Comment by 0nko** [comment]
I've discovered that the missing `WCRefunds` table crash was caused by a bug in one of the older FluxC migration scripts: wordpress-mobile/WordPress-FluxC-Android#1393

**Comment by kyleaparker** [comment]
>Ah, in that case perhaps we should summon @kyleaparker and ask if we should get rid of the other parens (maybe just separate "View details" with a dash)?

**Comment by 0nko** [comment]
The updated layout:
image

@kyleaparker The date is being formatted based on the phone's language settings.

**Pull request merged**
