### PR TITLE
Remove price rounding

### LINKED ISSUE #4448: Investigate price's rounding impact and how to solve it
We introduced previously some rounding around prices in the app (https://github.com/woocommerce/woocommerce-android/pull/1629), but this is causing some unwanted side effects, for example a part of the issue #4442 is caused by this change, as the rounding then re-calculation of `totalPrice` lead to some precision loss.
The PR #4446 attempts to fix this urgently by avoiding the re-calculation, but to fix the root cause, we would need to revisit the rounding.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: #4448

#### Context
As explained on the issue, some rounding was added to prices at the level of the model mappers. This was done to fix an issue that resulted in displaying the button "Issue refund" even though the order was refunded.

Later, it was found that this is causing some discrepancies since the rounding can result in information loss, one of the issues that were reported is #4442, and I was able to reproduce another bug by changing my Store's settings to use 3 decimal digits (p1641485892015100/1641479883.008200-slack-C02KUCFCSFP).

Before removing the rounding, I wanted to understand what caused the original issue about displaying the "refund" button even though the order was refunded, especially since the API returns the values already rounded according to the store's settings. And I tracked it to these [lines](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/21f7b079b7fd265bd217a41dddf23138eb94a491/plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderRestClient.kt#L890-L893) in FluxC, on those lines we parse the individual refunds as `Double`, and we sum them, which resulted in the precision loss.

Removing the rounding now won't cause the same bug as before, since because we don't support refunding by value anymore, we check the number of non-refunded products too instead of just comparing `refundTotal` and the order's `total`:  
https://github.com/woocommerce/woocommerce-android/blob/fdfe2e43f2c56a0857a9a23fbaabf810bb5bca48/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt#L191-L192

But still, we can check if the calculation is correct or not:
| Before | After |
| ---- | ----- |
| Screen Shot 2022-01-10 at 13 31 19 | Screen Shot 2022-01-10 at 13 39 17 |

And we can then confirm that `isRefundAvailable` calculation is correct even without rounding:
| When `refundTotal` is double (without rounding) | When `refundTotal` is BigDecimal (without rounding) |
| ---- | ----- |
| Screen Shot 2022-01-07 at 14 56 34 | Screen Shot 2022-01-07 at 17 31 23 |

#### Changes
1. Import the changes of the FluxC's [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2240) that make the `refundTotal` as BigDecimal, same as the sum of the refunds.
2. Remove the rounding from the models' mapping.

### Testing instructions
For the tests, please change your store's settings to have three decimals (if you have WCPay, please disable it, since it's multi-currencies feature messes with the decimals settings, I didn't investigate this extensively since it's not related to this)

#### TC to confirm we don't bring the original bug back
1. Create an order with two items, and set their prices to 1.058 and 1.053 (a tip: you can update the total directly to apply discounts, instead of changing the item's prices).
2. Open the app.
3. Confirm that you can see the correct prices (before this change, a situation similar to the screenshots I shared here p1641485892015100/1641479883.008200-slack-C02KUCFCSFP would occur)
4. Make a refund for the products, it has to be for each product individually.
5. Connect debugger to the app and put a breakpoint on this [line](https://github.com/woocommerce/woocommerce-android/blob/fdfe2e43f2c56a0857a9a23fbaabf810bb5bca48/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/details/views/OrderDetailPaymentInfoView.kt#L192).
6. Confirm that `order.isRefundAvailable` is false.

#### Non-regressions tests
I can't really think of any scenario that can be broken by this change, since the prices were already rounded to the correct value by the backend, so just smoke testing orders and variations should be enough.

#### Upgrade path
Please test the database migration by updating from an older version.

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by shiki** [comment]
> I can't really think of any scenario that can be broken by this change, since the prices were already rounded to the correct value by the backend, so just smoke testing orders and variations should be enough.

@hichamboushaba I saw a migration in the FluxC PR. Do you think that's worth it to mention for Call for Testing? Maybe test upgrading from an older version? Is there even a risk there? I don't understand the migration code so I have absolutely no opinion here. 😄 

FYI I'm just testing this but will leave the review to everyone who's assigned. 😅

**Comment by hichamboushaba** [comment]
> I saw a migration in the FluxC PR. Do you think that's worth it to mention for Call for Testing?

That's a valid test case, thanks for mentioning it @shiki, I'll add it to the PR description

**Comment by shiki** [comment]
This is looking good. Thank you for recognizing that we need to fix this, @hichamboushaba. I tested upgrading from `trunk` and have also tested creating an order. I only used one product though since I read the PR description late. 

### Using trunk

When using `trunk`, the total is clearly wrong. Please note that my site's decimal symbol is using **comma**. 

This is the order that I created on the site:

tax

And this is what shows up in `trunk`:



The tax was incorrectly rounded and the order total is wrong. 

### Using this PR

Using this PR, I can see that the taxes and order total is the same as Core:



When refunding, I can also refund everything with the correct subtotal and tax amounts:



After the refund, the order is marked as "Refunded" and you can't refund it anymore. 

---

I'll let everyone else test and review the code. 😊 🙇

**Review by wzieba — APPROVED** [review]
> we parse the individual refunds as Double, and we sum them, which resulted in the precision loss.

Nice finding! I checked it in debugger to better understand issue:

### With `Double`

image

### With `BigDecimal`

image

Code looks all good 👍 I see @shiki did exhaustive testing (thank you!) so I decided to not go into e2e testing. But if it's preferable to gain even more certainty in this solution, please feel free to ping me.

**Comment by hichamboushaba** [comment]
Thank you @shiki and @wzieba, I'm going to merge this now, we can always adjust anything if an issue came up from testing later on.
PS: I added one additional commit to add a release-notes' entry cc11959

**Pull request merged**
