### PR TITLE
[Dashboard] Add corruption handlers to Data Stores using Protocol Buffer schemas.

### PR DESCRIPTION
**Pull request by ThomazFB**
Note: [This change was originally implemented here, but we recreated it since we decided to branch it off a release branch. Adding it here for reference, since the original PR contains discussions. ](https://github.com/woocommerce/woocommerce-android/pull/13045#issuecomment-2515522573)

Summary
==========
This is a follow-up to https://github.com/woocommerce/woocommerce-android/pull/12891, where reverting the Data Store library upgrade didn't clear the corrupted files to some users. We verified that the corruption exception we're getting is very likely to be connected with a parsing failure of the Protocol Buffer schemas we have in the app, affecting two Data Stores: `Dashboard` and `CustomDateRange`. 

This PR adds a corruption handler to the DataStore creation, which simply restarts the DataStore with the default instance of each schema.

Additionally, this PR also updates all the Preferences DataStores used through the app to recover automatically and report the corruption event to Sentry. 

Steps to Reproduce
==========
Copy [this file](https://cloudup.com/c6YYEbOIyyj) to your device in `/data/data/com.woocommerce.android.dev/files/datastore`.
1. Open Dashboard
2. Edit the custom range for `Most active coupons` card
3. Tap on Save and verify the crash

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

## Reviewer (or Author, in the case of optional code reviews):

Please make sure these conditions are met before approving the PR, or request changes if the PR needs improvement:

- [x] The PR is small and has a clear, single focus, or a valid explanation is provided in the description. If needed, please request to split it into smaller PRs.
- [x] Ensure Adequate Unit Test Coverage: The changes are reasonably covered by unit tests or an explanation is provided in the PR description.
- [ ] Manual Testing: The author listed all the tests they ran, including smoke tests when needed (e.g., for refactorings). The reviewer confirmed that the PR works as expected on big (tablet) and small (phone) in case of UI changes, and no regressions are added.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/244">21.2 ❄️</a>. The due date for this milestone has already passed.<br />
Please assign it to a milestone with a later deadline or check whether the release for this milestone has already been finished.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ThomazFB** [comment]
@malinajirka Regarding the hotfix procedures for this PR, given we're mid week already and a few days away from the Play Store submission, I'm considering avoiding a beta cut and letting go of the release right away instead. WDYT?

**Comment by ThomazFB** [comment]
Also, to follow up on what we discussed in peaMlT-XN#comment-2680, I verified the Crash Logging injection instance during the app startup, and it's working as expected. We shouldn't see any issues, just as you predicted.

**Review by malinajirka — APPROVED** [review]
Thanks for working on this @ThomazFB !

I've tested the following flows:
- Corrupted - /data/data/com.woocommerce.android.dev/files/datastore/custom_date_range_configuration.preferences_pb
- Corrupted - /data/data/com.woocommerce.android.dev/files/datastore/dashboard_configuration_275
- Corrupted - /data/data/com.woocommerce.android.dev/files/datastore/dashboard_coupons_custom_date_range_configuration.preferences_pb
- Corrupted - /data/data/com.woocommerce.android.dev/files/datastore/tracker.preferences_pb
- Login on clear app installation

All of them worked as expected, even those which are loaded on startup seem to have Sentry initialized. Having said that, I haven't tested the events get actually sent to Sentry - I'm having troubles enabling Sentry on a debuggable build and I can't corrupt the files on a production build.

I think it would be good to include flows that you tested in the description. Feel free to check the `Manual Testing: The author listed all the...` checkbox after you update the description. Thanks!

> Regarding the hotfix procedures for this PR, given we're mid week already and a few days away from the Play Store submission, I'm considering avoiding a beta cut and letting go of the release right away instead. WDYT?

Considering the next release is on Monday, which is still several days away and more importantly, this change might potentially result in crashes on startup, I'd definitely suggest releasing a new beta. @toupper let us know in case you'd have a different opinion.

**Comment by irfano** [comment]
A new beta, including this fix, has been published with `21.2-rc-3`.

**Pull request merged**
