### PR TITLE
Adds support to display Blaze push notfication status updates correctly

### LINKED ISSUE #12191: Address the issue in which Blaze notifications are displayed as "Help & Support" notifications in Woo Android.

### PR DESCRIPTION
**Pull request by JorgeMucientes**
Important we need to merge this before `20.1.` code freeze. 

Closes: #12191 
Requires FluxC changes: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/3071

### Description

Adds new notification types to display  Blaze push notifications correctly. Initially, these push notifications were being displayed as Help & Support notifications, that is the reason the backend will only trigger this notifications for versions `20.1` onwards. 

This first iteration only fixes that notifications are not displayed as `Help & Support` notifications. Tapping on the notification will simply open the app. 

### Testing information
The Blaze push notification status updates have been enabled from App version > `20.0`. 

**Notifications disabled below v20.1 scenario**
1. Compile the app and create a Blaze campaign 
2. After successfully creating the campaign, open the campaign detail webview and click on Stop the campaign. 
3. The campaign will be canceled but you won't receive any notification.

**Notifications enabled scenario**
Clear application data (this is needed to generate a new Firebase token that will register the app with the updated version) 
Apply this patch: 
```diff
Subject: [PATCH] Update app version
---
Index: version.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/version.properties b/version.properties
--- a/version.properties	(revision a1461dddaf609db6972f48585d826ee123ff9429)
+++ b/version.properties	(date 1724162328853)
@@ -1,2 +1,2 @@
-versionName=19.9-rc-1
-versionCode=588
\ No newline at end of file
+versionName=20.1
+versionCode=588

```

1. Create a Blaze campaign 
2. Follow the instructions on the screenshot below to approve the campaign. You should receive a push for campaign `approved`. Tapping on it will open the app. 
3. Open campaign detail and stop the Blaze campaign. This should triggered a `canceled` notification. 
4. Repeat steps 1 and 2, but this time instead of approving the notification, click on `reject`. You should receive a push for campaign `rejected`

BlazeInstructions

To test the 4th notification type `performed` you'll have to trust me that I tested it. It is cumbersome to manually trigger this notification. This will be triggered naturally when the Blaze campaign comes to an end. I tested it here with the help of Sebastian Barbosa: p1724167294148939/1723478091.588909-slack-C069RG07W6S

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/232">20.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by irfano — APPROVED** [review]
The code looks good! Thanks for documenting how to test. I tested the canceled, rejected, and approved notification types, and I believe the ~~approved~~"performed" type should work like the other types. 

> Clear application data (this is needed to generate a new Firebase token that will register the app with the updated version)

My only comment is regarding this: when the user updates the app from the Play Store, the token won't be updated. I think we should open another PR to ensure the token is updated if the app version changes. WDYT?

**Comment by JorgeMucientes** [comment]
Hey @irfano thank you for the feedback. Good points!

>  I believe the approved type should work like the other types.

~~I'll ask the Blaze team why the "approved" action was not considered when adding the notifications support for Blaze.~~
EDIT: Sorry I initially missread. What do you mean by that? How is the behavior different from the others?

> My only comment is regarding this: when the user updates the app from the Play Store, the token won't be updated. I think we should open another PR to ensure the token is updated if the app version changes. WDYT?

Imho that shouldn't be necessary. The `FCMRefreshWorker` (which refreshes the FCM token) is fired every 7 days, which is pretty much the time elapsed between one release and the next. It's true that users updating the app won't get the push notifications enabled right away, but I don't think that is a problem because, in the worst-case scenario, they'll get the notifications enabled 7 days after upgrading to version `20.1`. 

Let me know if you still think we should address this somehow.

**Comment by irfano** [comment]
> EDIT: Sorry I initially missread. What do you mean by that? How is the behavior different from the others?

Sorry, I would say "performed". I mean I haven't tested the "performed" type but I believe it should work like others.

**Comment by irfano** [comment]
> The FCMRefreshWorker (which refreshes the FCM token) is fired every 7 days

I didn't notice this. So it seems fine. 👍🏻

**Pull request merged**
