### PR TITLE
Remove `checkstyle` plugin

### PR DESCRIPTION
**Pull request by wzieba**
I'd like to propose removing `Empty line not allowed before brace` rule from our checkstyle. My arguments are:

1. It's nothing bad to have an empty line before brace
2. If there are conflicts about having/not having this line - they're resolved automatically.
3. It slows me by breaking builds in CI ([example](https://buildkite.com/automattic/woocommerce-android/builds/5041#0182686b-ffa0-4435-b56f-917b458f101c/186-208))

Screenshot 2022-08-04 at 12 45 11

It happened to be so many times that I thought we might want to remove it.
If it was a rule from Detekt, I wouldn't mind so much (because I use `--auto-correct`) but this `checkstyle` rule forces me to find class, find line, add space and then commit.

@woocommerce/android-developers do you have some thoughts on that?
cc: @ParaskP7

### CODE REVIEW

**Comment by ParaskP7** [comment]
👋 @wzieba and thank you for raising this question! 💯 

I am also thinking about this restriction at times and I too find it unnecessary, so, from my side it is a 👍 !

Suggestion (💡): I actually want to take this opportunity and suggest something else, why not having [CheckStyle](https://checkstyle.sourceforge.io/) removed from WCAndroid as a whole. This static analysis tool is mainly for Java, give-or-take some custom rules that we have like that one we are discussing. Since WCAndroid is 100% on Kotlin, why not remove it and start depending solely on Detekt. Wdyt, maybe worth a P2 post? 🤔 

```
Checkstyle is a development tool to help programmers write Java code that adheres to a coding standard.
It automates the process of checking Java code to spare humans of this boring (but important) task.
This makes it ideal for projects that want to enforce a coding standard.
```

PS: I know that people are confused at times about CheckStyle being applicable to Kotlin too, but this is not true, this tool if solely (or at least primarily) for Java codebases, again, give-or-take the custom rules (that run on a file system or abstract level, like braces) that some projects might have configured (like ours). 🤔

**Comment by wzieba** [comment]
Thanks @ParaskP7 for your arguments!

> I actually want to take this opportunity and suggest something else, why not having [CheckStyle](https://checkstyle.sourceforge.io/) removed from WCAndroid as a whole.

Yes, I think it'd be a good direction. I think I was just too shy to suggest it right away 🫣.

> Wdyt, maybe worth a P2 post? 🤔

I think it's okay to take the decision here, in PR discussion with ping to all @woocommerce/android-developers . It's also ok to have P2 post, but I can't commit to preparing it this week.

**Comment by nbradbury** [comment]
> I actually want to take this opportunity and suggest something else, why not having [CheckStyle](https://checkstyle.sourceforge.io/) removed from WCAndroid as a whole.

Agreed!

**Comment by JorgeMucientes** [comment]
I agree with  removing `checkstyle`. I think the value it provides is minimal and I often waste some time with the same issue shared by @wzieba in this PR. We do have some custom rules I wanted to ask about, and to double check if It's safe to get rid of them: 

Why is this needed? 
```xml
    <module name="RegexpSingleline">
        <property name="format" value="^(?!.*\bimport\b).*Store\.[A-Z][A-Za-z0-9]*[ );]"/>
        <property name="message" value="Specific imports should be used for FluxC Store inner classes"/>
        <property name="severity" value="error"/>
    </module>
```

Can we add this to the codestyle? 
```xml
    <module name="RegexpSingleline">
        <property name="format" value="[^\S\r\n]@[\S]*(\([{]?\&quot;.*\&quot;[}]?\)++|\([^\&quot;]*\)++)[^ \t]"/>
        <property name="message" value="In-line annotations must be followed by one whitespace"/>
        <property name="severity" value="error"/>
    </module>
```

I think we'll be ok without these 2
```xml
    <module name="RegexpMultiline">
        <property name="format" value="@Inject(\n|\r\n).*[^{,(]$"/>
        <property name="message" value="Inject annotation should be in-line with the annotated field or property"/>
    </module>

    <module name="RegexpSingleline">
        <property name="format" value="^(?!.*\bclass\b).*\S.*@Inject"/>
        <property name="message" value="In-line inject annotation should precede the rest of the declaration"/>
    </module>
```

Imo look ok to live without those rules. +1 to getting rid of it.

**Comment by kidinov** [comment]
> I actually want to take this opportunity and suggest something else, why not having [CheckStyle](https://checkstyle.sourceforge.io/) removed from WCAndroid as a whole.

That's something I proposed a year ago, so 100% for this. From my research the whole thing was copy-pasted from WP android project when Woo started and was there while we don't have any java code

**Comment by wzieba** [comment]
Following the discussion we have, I've pushed ac8a6e7 commit, which removes `checkstyle` plugin completely.

As we don't have the majority of voices, I believe we could wait a few more days - I'd say until Tuesday (9th August), to give a chance to everyone who might have arguments for keeping `checkstyle`. Sounds good?

**Comment by hichamboushaba** [comment]
Agreed with all of you, let's get rid of `Checkstyle`, one analysis tool is enough.

**Comment by 0nko** [comment]
I agree with the rest of you, 🗑️ it!

**Comment by wzieba** [comment]
I think we have 6 of 12 Woo Android developers now + @ParaskP7 so let's consider it voted out 😄.

I've just removed `checkstyle` from `required` steps. Can I ask anyone to approve this PR?

**Comment by ParaskP7** [comment]
> I think we have 6 of 12 Woo Android developers now + @ParaskP7 so let's consider it voted out 😄.

😄 🎉 

> I've just removed checkstyle from required steps. Can I ask anyone to approve this PR?

I can review it today, consider it done and thank you @wzieba ! 💯

**Review by ParaskP7 — APPROVED** [review]
👋 @wzieba !

I have reviewed the removal of [CheckStyle](https://checkstyle.sourceforge.io/) from this repo, everything LGTM, good job on cleaning-up everything related to that, including `git ignore`, `docs`, `ci`, etc! 🥇 ❤️ 🙇

**Pull request merged**
