### PR TITLE
Update FluxC and Login libraries

### PR DESCRIPTION
**Pull request by hichamboushaba**
### Description
This PR just updates FluxC and Login libraries to bring change of the following PRs while making there is no regression:
1. https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/76
2. https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/78
3. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2280
4. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2263 (this was is already merged in FluxC, so its changes are already present in Woo)

I tested the app locally with all the above PRs, and there is no regression at all.
@develric as agreed, please go ahead and merge all the above PRs, then I'll be able to update the FluxC and Login hashes with latest trunk commits, to bring all changes.

##### Jetpack CP
Confirm that connection to Jetpack CP sites works as expected for both WPCom credentials flow and site address flow.

##### XMLRPC changes
Check the testing steps on the WPAndroid [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15919), and try them with the Woo app, and confirm there is no regression.
For information, the result will be different for all cases after entering the site credentials, since we [show](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/blob/bc6e1dc665af6188a99c2f64af3e5f331358828e/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java#L604-L610) a "discovery error" screen in WCAndroid:
Screen Shot 2022-02-16 at 13 36 19

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by develric** [comment]
hey @hichamboushaba 👋 ! Thanks so much for helping with this 🙇 ! I'll ping you as we progress into it. 
btw, you were mentioning to expect ci failures since the linked libs are not in trunk yet, but just to double check is [this](https://github.com/woocommerce/woocommerce-android/pull/5868#issuecomment-1041452652) what you were expecting, thanks 🙇

**Comment by hichamboushaba** [comment]
> but just to double check is https://github.com/woocommerce/woocommerce-android/pull/5868#issuecomment-1041452652[](https://github.com/hichamboushaba) what you were expecting, thanks 🙇

No, not this comment, but actually a compile failure that should be triggered on the CI, locally I had to merge `trunk` from FluxC to be able to compile the app, and this is because the branch of the FluxC [PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2280) lacks some changes that were added recently and that WCAndroid expects, everything should be OK once we update the hash to a `trunk` commit though.

**Comment by develric** [comment]
Thanks for clarifying 🙇

**Review by malinajirka — APPROVED** [review]
I only smoke tested the changes and LGTM, thank you!

**Pull request merged**
