### PR TITLE
Compile SDK version to 33

### LINKED ISSUE #6764: Update compile SDK version to 33
As per proposal - paqN3M-qL-p2

### PR DESCRIPTION
**Pull request by kidinov**
Closes: #6764 

### Description

* Extracts SDK versions to reuse them across the modules
* Updated compile SDK version to 33
*  Fixed compilation errors

### Testing instructions

* Run a smoke test of the main flows

### CODE REVIEW

**Comment by kidinov** [comment]
Buildkite failing because the SDK 33 is not there. I asked Core team - p1655372617011789-slack-C030U03RC8Y

**Review by malinajirka — APPROVED** [review]
Thanks @kidinov!

LGTM :) 🚢

**Comment by oguzkocer** [comment]
> Updated compile SDK version to 33

There is a warning about AGP `7.2.1` is only being tested up to `32`. Do we need to update to `33` at this time?

> WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33
> This Android Gradle plugin (7.2.1) was tested up to compileSdk = 32

**Comment by kidinov** [comment]
@oguzkocer 

> There is a warning about AGP 7.2.1 is only being tested up to 32. Do we need to update to 33 at this time?

Yeah, the new android is actually around the corner and we still didn't update even compile SDK version. I see that we are already on the supported Gradle version but AGP is a bit behind. We either can ignore this warning for now and merge it hoping that it won't bring any trouble or we have to update AGP, but it should be done in the following weeks. Wdyt?

Here is the plan regarding this process, if you are interested  - paqN3M-qL-p2

**Comment by oguzkocer** [comment]
@kidinov We can't update AGP any time soon, not unless we have to. So, I guess we should just test it as best as we can and ignore the warning. 🤷

**Pull request merged**
