### PR TITLE
Added push notification support for Zendesk

### LINKED ISSUE #621: ZenDesk: Hook up push notifications
Wire things up to show push notifications when a reply is received via Zendesk.

### PR DESCRIPTION
**Pull request by anitaa1990**
Fixes #621 by adding push notification implementation to Zendesk tickets.

### Changes
- Register the `fcm_token` with Zendesk stored locally after user logs in to the app and verifies their contact email address.
- Added modifications to `FCMMessageService` to check if the incoming notification is from Zendesk. 
- Added logic to `MainActivity` to open `My tickets` page when a zendesk notification is clicked.

### Known issues:
- If the push notifications are not properly enabled before creating a ticket, the user doesn't seem to get push notifications for them even if push notifications are enabled after the ticket creation.
- If the user opens a ticket, change the email (which will reset their identity and remove all their tickets), they'll still get push notifications for the previous ticket even though they can not actually access it. So clicking on this ticket notification redirects them to the Help page. 

For both cases, I _think_ this is because the push notification tokens are attached to tickets and not to Zendesk identities 🤷‍♀ 

### Testing:
- [x] Start with a fresh install and login to the app. Open a new ticket. Close the app and reply to the ticket via Zendesk. Verify that notification is received and clicking on it, redirects to the `My tickets` page.
- [x] Open the app and click on the previously opened ticket. Reply to the ticket via Zendesk dashboard. Verify that no notification is displayed and the screen is automatically refreshed with the reply.
- [x] Open the app and change the support email address. Open a new ticket from the app. Close the app and reply to the ticket via Zendesk. Verify that notification is received and clicking on it, redirects to the `My tickets` page.
- [x] Logout of the app. Open a new ticket from the login page. Reply to the ticket. Verify that notification is NOT received since user is not logged in. Check "My Tickets" section and verify that your ticket is there with a reply. This test doesn't accomplish much except to validate the point that this feature is still pending 🤷‍♀
- [x] Login to the app again. Reply to the previously opened ticket (from login screen). Close the app. Reply to the ticket via Zendesk dashboard. Verify that no notification is received. Check "My Tickets" section and verify that your ticket is there with a reply.
- [x] Login to a different account and verify that we are not able to receive notifications for previously opened tickets. I believe this is due to how notifications are sent from our back-end as the WordPress.com user changes in this scenario. Again, this test doesn't accomplish much except to validate the point that this feature is still pending  🤷‍♀
- [x] Create a new order and verify that the new order notification is displayed and clicking on it, opens the Order detail page.
- [x] Write a product review for a test site and verify that the product review notification is displayed and clicking on it, opens the product review detail page.

### CODE REVIEW

**Comment by nbradbury** [comment]
@anitaa1990 The code looks good but something seems to be going wrong.

To test, I opened the app and before I logged in I submitted a help request and closed the app. I replied to it on Zendesk and waited ten minutes, but I didn't receive a notification.

I then completed login and visited help & support, and the reply appeared after a second. Next I replied to the Zendesk response and minimized the app, but after waiting five minutes no notification appeared. I re-opened the app and returned to help & support and the reply showed up.

Note that I tested on both an emulator and a real device.

**Comment by anitaa1990** [comment]
Hey @nbradbury , thanks for the quick review!

> To test, I opened the app and before I logged in I submitted a help request and closed the app. I replied to it on Zendesk and waited ten minutes, but I didn't receive a notification. I then completed login and visited help & support, and the reply appeared after a second. Next I replied to the Zendesk response and minimized the app, but after waiting five minutes no notification appeared. I re-opened the app and returned to help & support and the reply showed up.

Yup, this is a known limitation 🤦‍♀. We are not registering a user for push notifications before they are logged in. A user cannot be registered for any push notifications until they have authenticated. This is because our wpcom endpoint for registering push notifications requires the device token, push application ID, application version, and default Store ID.

And if the push notifications are not properly enabled before creating a ticket, the user doesn't seem to get push notifications for them even if push notifications are enabled after the ticket creation. I think this is because the push notification tokens are attached to tickets and not to Zendesk identities 🤷‍♀ 

I should have mentioned that we are only enabled notifications for authenticated users in this PR.

**Comment by nbradbury** [comment]
> We are not registering a user for push notifications before they are logged in

My bad, you did mention this in your description but I misread it. However, I still don't receive a notification when I _am_ logged in and the app is minimized. The only time I see a notification is if I force close the app.

**Comment by anitaa1990** [comment]
> The only time I see a notification is if I force close the app. Shouldn't the notification also be seen if the app is minimized?

Ohh, yup we should definitely get the notifications even if app is minimised or if it is forced closed. I'm not able to reproduce this 🤔 I logged into the app, opened a ticket and minimised the app and replied to the ticket from Zendesk. Unfortunately, we won't be able to get notifications for tickets already created before the notifications are enabled. So we would need to open another ticket 🤦‍♀

**Comment by nbradbury** [comment]
> Unfortunately, we won't be able to get notifications for tickets already created before the notifications are enabled

Ah, I think that's what happened! I just tried again with a new ticket and it worked just fine. So functionality-wise this looks good. I'll dig deeper into the code in a bit, but could I ask you to merge `develop` into this branch? Right now it's requiring me to uninstall and re-login whenever I switch to this branch.

**Comment by anitaa1990** [comment]
Thanks @nbradbury!! Merged into develop 👍

**Pull request merged**
