### PR TITLE
Dark Mode: Bottom bar

### LINKED ISSUE #1745: Dark Mode: Bottom Navigation Bar
Style the bottom navigation bar for light and dark modes. 

## Light Mode
Screen Shot 2019-12-19 at 1 28 07 AM

## Dark Mode
Screen Shot 2019-12-19 at 1 27 58 AM

## Related Links
- [BottomNavigationView Component](https://material.io/develop/android/components/bottom-navigation-view/)
- [Material Design: Bottom Navigation](https://material.io/components/bottom-navigation/)

### PR DESCRIPTION
**Pull request by AmandaRiu**
Fixes #1745 by styling the bottom navigation bar to the latest material dark/light designs. 

## Implementation Comments
* Supporting APIs 21 + 22 required a bunch of workarounds to how theming is done since API 23 introduced a bunch of theme and style optimizations. I didn’t realize this until I started testing on a device running API 21. Because of this, I had to back out of a bunch of styling options and manually define some colors with alpha since < API 23 doesn’t allow theme-level attributes to be used in resource files, and the color resource file `alpha` property isn’t supported until API 23. 
* **Badge coloring** - the border of the badge is supposed to match the bottom bar background color, but in dark theme the background color is the `colorSurface` value plus an alpha caused by elevation. Since adding an alpha in this scenario doesn’t work as intended I had to “fake” the color by creating an equivalent without the alpha. Depending on the device, this may lead to the border being slightly more noticeable. We should eventually update the logic for drawing badges to use `BadgeUtils` with `BadgeDrawable`. I didn’t do it during these changes because [according to google](https://github.com/material-components/material-components-android/issues/657) the API is not finalized. I played around with it for a bit and indeed, the API is a mess and not ready for production.

## Other
- [This PR](https://github.com/woocommerce/woocommerce-android/pull/1755) must be approved and merged before this one can be. 

## Designs

Screen Shot 2019-12-26 at 11 48 40 PM
Screen Shot 2019-12-26 at 11 48 22 PM

### Zoomed In

Screen Shot 2019-12-27 at 1 40 28 AM
Screen Shot 2019-12-27 at 1 40 35 AM

## Zoomed in 

(note the orange navbar is due to battery saver mode being enabled):
Screen Shot 2019-12-27 at 1 42 28 AM
Screen Shot 2019-12-27 at 1 42 35 AM

cc: @kyleaparker for design review

### CODE REVIEW

**Comment by AmandaRiu** [comment]
This one is ready for review :)

**Comment by Garance91540** [comment]
Hi @AmandaRiu, looking good! The only thing I noticed is the font color of the order notification bubble: it should be "On Primary / Medium Emphasis" but it's currently white.
Screenshot: https://d.pr/i/Qr6Esj
Design: https://d.pr/i/FsHVqO

**Comment by AmandaRiu** [comment]
@Garance91540 I've updated the badge coloring:

Screen Shot 2020-01-02 at 12 16 51 PM

Screen Shot 2020-01-02 at 12 16 38 PM

**Comment by Garance91540** [comment]
looks good on my end!

**Comment by AmandaRiu** [comment]
Designs approved. I'm going to go ahead and merge this one since it's already been approved so I can get the next draft PR in line ready for review. Thanks @anitaa1990 !

**Pull request merged**
