### PR TITLE
Payment Flow - tracking

### PR DESCRIPTION
**Pull request by malinajirka**
Parent issue #3726 

card_present_collect_payment_tapped: The user tapped on the Collect Payment button to collect a card payment.
card_present_collect_payment_failed: The payment process failed.
card_present_collect_payment_success: The payment was completed successfully.

Note
We also track `card_present_collect_payment_canceled: The user canceled the payment process.` event on iOS - however, I can't think of an easy maintainable way how to implement this without making some vital changes to how the flow works. Moreover, I don't think that events is necessary, as if the flow doesn't result in either success or failure, we know user canceled it. Wdyt?

To test
Test the the events are being recorded. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by kidinov** [comment]
JFYI I updated from develop, otherwise the diff were bigger than it should be

**Comment by kidinov** [comment]
> We also track card_present_collect_payment_canceled: The user canceled the payment process. event on iOS - however, I can't think of an easy maintainable way how to implement this without making some vital changes to how the flow works. Moreover, I don't think that events is necessary, as if the flow doesn't result in either success or failure, we know user canceled it. Wdyt?

Are we sure that failed flow always the result of the user's actions? I thought that the flow can fail due to other reasons as well

**Review by kidinov — APPROVED** [review]
The events you implemented look good. Let's just think if we can/should implement `card_present_collect_payment_canceled: The user canceled the payment process` in another PR

**Comment by malinajirka** [comment]
> Are we sure that failed flow always the result of the user's actions? I thought that the flow can fail due to other reasons as well

I'm not sure I follow @kidinov - there are two events "card_present_collect_payment_failed" and "card_present_collect_payment_canceled". `_failed` is scenarios when the flow fails without the user interaction and `_cancel` is for scenarios when the user manually cancels the flow. However, manual cancelation is a bit tricky to implement imo.

**Comment by kidinov** [comment]
@malinajirka you were asking:

>  I don't think that events is necessary, as if the flow doesn't result in either success or failure, we know user canceled it. Wdyt?

So, what I was saying that user cancelation is not the same as failure or success.

**Comment by malinajirka** [comment]
> So, what I was saying that user cancelation is not the same as failure or success.

@kidinov I completely agree, but when the user cancels we don't track either - my reasoning is that if the user cancels the flow neither success nor failure will be recorded -> we'll know that they canceled the flow. So I don't think tracking cancel is necessary as we can come to the same conclusions even when we don't track it. Considering the effort I don't think it's worth implementing this event in another PR - but perhaps I'm missing something and it's easy to implement.

**Pull request merged**
