### PR TITLE
Merge 10.4 code freeze to trunk

### PR DESCRIPTION
**Pull request by oguzkocer**

### CODE REVIEW

**Comment by oguzkocer** [comment]
Per usual, I am admin merging this PR so that the strings are ready to be sent for translation on Monday morning.

**Review by AliSoftware — APPROVED** [review]
- [x] New empty entry created in `RELEASE-NOTES.txt` for next iteration.
- [x] `release_notes.txt` extracted and injected in `.pot`.
- [x] Internal dependencies bumped to a new stable version in `build.gradle` if necessary.
- [x] New strings frozen/copied into `fastlane/resources/values/strings.xml`.
- [x] Version bumped in `WooCommerce/build.gradle`

:shipit:

**Comment by oguzkocer** [comment]
@AliSoftware Isn't it Saturday morning over there?! 😅

**Comment by AliSoftware** [comment]
> @AliSoftware Isn't it Saturday morning over there?! 😅

😄  It is, but I had to shift my working hours yesterday and today, so I was working a bit on odd hours to compensate and to finish some things up before I forget over the weekend 😅  (but I just finished writing all my notes, so off I go now!)

**Pull request merged**
