### PR TITLE
[WooExpress Removal] Remove site upgrade options

### PR DESCRIPTION
**Pull request by hichamboushaba**
Part of: #11115

⚠️ Please don't merge yet.

### Description
This PR handles the second part of #11115, which is removing the ability to upgrade sites from the app:
1. Renames the "Upgrades" entry in the more menu screen to "Subscriptions"
2. Hides the "Subscriptions" entry for free trial sites.
3. Remove the "Upgrade now" button from the free trial banner and from the "Subscriptions" screen.

**Same as the previous PR, this doesn't include any code cleanup, it just hides the different items, code cleanup will be handled separately**

### Testing instructions
1. Sign in using WordPress.com.
2. Choose a WooExpress website.
3. Confirm that the "Upgrades" button was renamed to "Subscriptions"
5. Click on it and confirm the functionality still works.
6. Choose a free trial website (create one on the web if needed)
7. Confirm the "Upgrade Now" button of the free trial website has been removed.
8. Confirm the "Subscriptions" entry in the more menu is not shown.
9. Confirm the Onboarding tasks don't include neither "Launch your Store" nor "Name your Store".

### Images/gif

- [x] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by JorgeMucientes — APPROVED** [review]

**Comment by JorgeMucientes** [comment]
Hey @hichamboushaba code looks good and works as described. Approving!
I do have some doubts though about why removing the `Upgrade` options for free trial sites? What is the reasoning behind it? I mean, once we remove WooExpress store creation flow, there won't be any more free trial sites, but why prevent users that are already on free trial from upgrading their existing store?

**Comment by hichamboushaba** [comment]
> I do have some doubts though about why removing the Upgrade options for free trial sites? What is the reasoning behind it? I mean, once we remove WooExpress store creation flow, there won't be any more free trial sites, but why prevent users that are already on free trial from upgrading their existing store?

This is what we agreed on (pe5sF9-2w9-p2#comment-3495) because we are seeking to make the app more aligned with the "Help the Hosts" strategy, and not offer an advantage for WooExpress as a platform.
I'll hold on merging this PR, if we want to re-discuss this, let's start a new discussion on the linked P2.

**Comment by JorgeMucientes** [comment]
Hey @hichamboushaba there's no need to defer the merging of this, if it was already agreed. 

> because we are seeking to make the app more aligned with the "Help the Hosts" strategy, and not offer an advantage for WooExpress as a platform.

I understand this new strategy. However, users that are in a `Free trial` are users already hosted on WP.com. So, it's not that we favor our hosting solution over the others because they are already hosted with us. Removing the upgrade option will remove user's capacity to transition their free trial store to a real store. 
In any case, I don't want to overcomplicate things or loose more time into discussions. Because removing the upgrading option for existing free trial is something that will impact very few users and only for the next 15 days after this is released. 

Let's keep things as they were agreed.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/202">17.9</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
