### PR TITLE
Issue/3725 more readers found UI

### PR DESCRIPTION
**Pull request by malinajirka**
Parent issue #3725 

Merge instructions
~~1. Make sure https://github.com/woocommerce/woocommerce-android/pull/4211 is merged first~~
~~2. Remove "do not merge" label~~
3. Merge this PR

This PR adds Ui for the logic implemented in https://github.com/woocommerce/woocommerce-android/pull/4211.

Designs:
- it seems the line height used in designs is custom -> I used the default line height defined in the OS. Let me know if you'd prefer me to introduce a custom definition of line height.

| Design | Light (gif + static) | Dark (gif + static) |
|---|---|---|
| light |  | dark |
|  | light static | dark static |

To test:
1. Open detail of an unpaid order in US dollars
2. Notice a single reader is found and UI for a single reader is shown
-----------------------------------
Prerequisite: Unfortunately, I'm not aware of an easy way how to simulate that StripeTerminalSDK found multiple readers. I manually edited [this line](https://github.com/woocommerce/woocommerce-android/blob/2d8146f946b3f54e781982ffa53d25bd5024e650/libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/connection/ConnectionManager.kt#L44) to return multiple readers.
1. Open detail of an unpaid order in US dollars
2. Tap on "Collect Payment"
3. Connection flow automatically starts and displays a list of found readers after a few seconds
4. Notice the "Scanning for readers" progress icon is animated
4. Tap on "Cancel" and notice the dialogs is dismissed
5. Tap on "Collect Payment"
6. Tap on one of the found readers
7. Notice the app connects to it and continues with the payment flow

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Update:
Issues that need to be addressed:
- [ ] Update error message on timeout - https://github.com/woocommerce/woocommerce-android/pull/4212#issuecomment-862574979

### CODE REVIEW

**Comment by nbradbury** [comment]
@malinajirka I'm reviewing this first because it helps me test #4211, but I'll be sure to merge #4211 before this one.

**Comment by nbradbury** [comment]
@malinajirka I'm wondering why the serial number is limited to the last eight digits when it could show the entire thing?

Screenshot_20210616-100131

Also, would it make sense to show the device type under the serial number? I would guess merchants with several readers have the same type, but for others maybe it would help them identify the correct reader?

Screen Shot 2021-06-16 at 10 01 03 AM

**Comment by nbradbury** [comment]
If there are more readers than can fit on-screen, the "Scanning for readers" progress message is off-screen. This is especially noticeable in landscape.

progress

**Comment by malinajirka** [comment]
> I'm wondering why the serial number is limited to the last eight digits when it could show the entire thing?

Good question, the ids are usually very long so they'd get cut off (depends on screensize of course). Technically, if we use `ellipsize=end` it's not a big deal, but I think using last 8 digits should be enough for the user to identify the reader anyway -> the benefit is that the UI looks better when the ID isn't that long. Related discussion p1623704220233300-slack. Wdyt?

> the device type under the serial number? 

We currently support only a single reader type, so we'd be showing just a constant. But I think it's a good idea for future (cc @Garance91540 )

> If there are more readers than can fit on-screen, the "Scanning for readers" progress message is off-screen.

I noticed that as well, but I thought it's fine since the user can scroll down. Moreover, I think the user doesn't need to know that the scan is still in progress until they check all the found readers and the one they are looking for is not there -> so showing it at the end make sense to me. Wdyt @nbradbury @Garance91540 ?

**Comment by nbradbury** [comment]
> Wdyt @nbradbury @Garance91540 ?

I like the way Android handles this for bluetooth devices, by showing the scanning message above the list of devices.

bt

**Comment by nbradbury** [comment]
If I leave the "Several readers found" dialog showing without selecting a device, after a minute or so that dialog goes away and the "Connecting to reader failed" dialog appears. Is that by design?

Screenshot_20210616-101601

**Comment by malinajirka** [comment]
> If I leave the "Several readers found" dialog showing without selecting a device, after a minute or so that dialog goes away and the "Connecting to reader failed" dialog appears. Is that by design?

Yes, that is expected behavior. The "scanning" job automatically finishes after 1 minute - we can change this delay [here](https://github.com/woocommerce/woocommerce-android/blob/b64f8c13fd1103fd78fcfa12c83479f2187f2c13/libs/cardreader/src/debug/java/com/woocommerce/android/cardreader/internal/connection/actions/DiscoverReadersAction.kt#L21) if needed. But during my testing the reader is discovered within the first 1s after the scanning starts, so I think 1 minutes should be more than enough. The user can click on "retry" to restart the scanning if needed. Do you have any concerns?

**Comment by nbradbury** [comment]
> The user can click on "retry" to restart the scanning if needed. Do you have any concerns?

Just that it shows a list of readers, then times out and says "We couldn't find any readers." That message should be something like "Want to keep looking for readers?" or "Timed out looking for readers."

**Comment by nbradbury** [comment]
@malinajirka I raised a few design issues, but otherwise this looks & works great. Do you want to wait for the design issues to be addressed before I merge this, or is it better for you if it merge it as-is?

**Comment by malinajirka** [comment]
> Just that it shows a list of readers, then times out and says "We couldn't find any readers." That message should be something like "Want to keep looking for readers?" or "Timed out looking for readers."

Ahh, I see what you mean now. Yeah the message is confusing, I agree -> I'll update it along with the other design issue.

> I raised a few design issues, but otherwise this looks & works great. Do you want to wait for the design issues to be addressed before I merge this, or is it better for you if it merge it as-is?

Thanks so much for the review!! ;) Let's wait one or two days if someone from the design team finds time to provide some feedback - if they don't I'll merge it and address any issues later.

**Comment by Garance91540** [comment]
Hi there, 

> We currently support only a single reader type, so we'd be showing just a constant. But I think it's a good idea for future (cc @Garance91540 )

I agree! I'll add this in the designs

> so showing it at the end make sense to me. Wdyt @nbradbury @Garance91540 ?

Agreed!

**Comment by malinajirka** [comment]
@nbradbury I updated the error message and the rest seems to be approved. Could you please double-check the change, thanks!

**Review by kidinov — APPROVED** [review]
I checked the last commit - looks good. Approving to keep moving

**Pull request merged**
