### PR TITLE
feat: include `cardreader` module when uploading source context

### PR DESCRIPTION
**Pull request by wzieba**
### Description

This PR is about including `cardreader` module when uploading source context to Sentry, so we can browse benefit from this feature in this module as well.

Additionally, I've introduced a code mapping so Sentry will be able to match `cardreader` package to the correct source:
image

### Testing instructions

1. Run `WooCommerce:sentryCollectSourcesVanillaRelease`
2. Navigate to `WooCommerce/build/intermediates/sentry/vanillaRelease/source-to-bundle`
3. Assert there is a `cardreader` package

### Images/gif

- [ ] I have considered if this change warrants release notes and have added them to `RELEASE-NOTES.txt` if necessary. Use the "[Internal]" label for non-user-facing changes.

### CODE REVIEW

**Comment by hafizrahman** [comment]
I did:

1. `./gradlew WooCommerce:sentryCollectSourcesVanillaRelease`
2. Build finished completely
3. The directory you mentioned does not have the "cardreader" package:
Screenshot 2024-04-03 at 10 02 15

Did I miss a step somewhere?

<details>
  <summary>Here's the terminal log in case it's useful:</summary>

```
hafiz woocommerce-android (sentry_include_cardreader_module) >> ./gradlew WooCommerce:sentryCollectSourcesVanillaRelease

> Configure project :WooCommerce
WARNING: You're using the example google-services.json file. Google login will fail.
WARNING: You're using the example google-services.json file. Google login will fail.
WARNING: We recommend using a newer Android Gradle plugin to use compileSdk = 34

This Android Gradle plugin (8.1.0) was tested up to compileSdk = 33 (and compileSdkPreview = "UpsideDownCakePrivacySandbox").

You are strongly encouraged to update your project to use a newer
Android Gradle plugin that has been tested with compileSdk = 34.

If you are already using the latest version of the Android Gradle plugin,
you may need to wait until a newer version with support for compileSdk = 34 is available.

To suppress this warning, add/update
    android.suppressUnsupportedCompileSdk=34
to this project's gradle.properties.

> Task :WooCommerce:processVanillaReleaseMainManifest
/Users/hafiz/Desktop/woocommerce-android/WooCommerce/src/release/AndroidManifest.xml:26:5-28:31 Warning:
        uses-permission#com.android.vending.BILLING was tagged at AndroidManifest.xml:26 to remove other declarations but no other declaration present
/Users/hafiz/Desktop/woocommerce-android/WooCommerce/src/release/AndroidManifest.xml:15:9-17:35 Warning:
        meta-data#com.google.android.play.billingclient.version was tagged at AndroidManifest.xml:15 to remove other declarations but no other declaration present
/Users/hafiz/Desktop/woocommerce-android/WooCommerce/src/release/AndroidManifest.xml:19:9-22:35 Warning:
        activity#com.android.billingclient.api.ProxyBillingActivity was tagged at AndroidManifest.xml:19 to remove other declarations but no other declaration present
warn: removing resource com.woocommerce.android:string/free_trial_survey_screen_title without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_one_day_after_free_trial_expires_description without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_one_day_after_free_trial_expires_title without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_one_day_before_free_trial_expires_description without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_one_day_before_free_trial_expires_title without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_still_exploring_description without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_still_exploring_title without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_store_creation_complete_description without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_store_creation_complete_title without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_survey_after_24_hours_description without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_survey_after_24_hours_title without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_upgrade_to_paid_plan_after_6_hours_description without required default value.
warn: removing resource com.woocommerce.android:string/local_notification_upgrade_to_paid_plan_after_6_hours_title without required default value.
warn: removing resource com.woocommerce.android:string/more_menu_button_w___admin without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_check_error_existing_subscription without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_check_error_not_available_for_country without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_check_error_title without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_check_generic_error without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_existing_purchase_not_acknowledged without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_loading_subtitle without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_loading_title without required default value.
warn: removing resource com.woocommerce.android:string/store_creation_iap_eligibility_network_error without required default value.


BUILD SUCCESSFUL in 35s
42 actionable tasks: 42 executed

Publishing build scan...

🐢 5 slowest tasks were: 
Duration        % of build      Task
19s             54%             :WooCommerce:kspVanillaReleaseKotlin
5s              16%             :WooCommerce:mergeVanillaReleaseResources
5s              15%             :libs:cardreader:compileReleaseKotlin
2s              6%              :WooCommerce:packageVanillaReleaseResources
2s              6%              :WooCommerce:processVanillaReleaseResources

No authToken provided. Skipping reporting.
https://gradle.com/s/dljgvs65lonts

hafiz woocommerce-android (sentry_include_cardreader_module) >> 
```

</details>

**Comment by wzieba** [comment]
Could you please check further in the file hierarchy? It should be in `com/woocommerce/android`, like it's in `cardreader` Gradle module.

**Review by hafizrahman — APPROVED** [review]
Oh yup! Find it, thanks for the clue @wzieba 

I'm approving 👍🏼  The buildkite errors seem unrelated to this PR, but please double check and merge afterward.

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/woocommerce/woocommerce-android/milestone/204">18.1</a>. This milestone is due in less than 2 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
