### PR TITLE
Issue/2117 step2 filter products

### LINKED ISSUE #2117: Products M2 release: provide option to filter products
As per design specifications, we want to provide the option to filter products. 
- [ ] I want to filter products by stock status
- [ ] I want to filter products by product status
- [ ] I want to filter products by product type

. . .

### PR DESCRIPTION
**Pull request by anitaa1990**
Step 2 of filtering products feature and fixes #2117 by adding filtering by stock status, product type and product status. 

#### Points to note
- Since the `ProductListFragment` is one of the top level fragments and not part of the navigation component, I could not implemented a SharedViewModel to pass the filter data from the `ProductFilterListFragment` back to the `ProductListFragment`. To overcome that, I implemented a similar solution to our `navigationBackWithResult` function where we pass a bundle with a request code to our destination fragment. Instead of using the navigation destination to pass the bundle, I used `getActiveTopLevelFragment` from `MainActivity`. 
- Note that this PR is to be merged into a feature branch and is only available for debug users.
- I have also added logic to display the filter, sort card only if:
  - M2 feature flag is enabled. (currently for debug builds).
  - There are products available (with no filters). If filters are activated, however, the filter button is displayed even when there are no products.

#### Screenshots
. 

. 

. 

. 

. 

. 

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by anitaa1990** [comment]
@nbradbury and @0nko, I have added both of you as reviewers since you have both worked with the navigation component and would like to get the 👌 from you before pulling this PR out of draft

**Comment by nbradbury** [comment]
@anitaa1990 I'm guessing you'll address this in another PR, but just so it's mentioned, the message you get when there are no products matching the filter should be updated.

Screenshot_1587736336

**Comment by nbradbury** [comment]
@anitaa1990 I think relying on `navigatebackwithresult()` here works just fine 👍

**Comment by anitaa1990** [comment]
Thanks for the review @nbradbury!

**Pull request merged**
